### ISSUE TITLE
Style problem with html text align

### ISSUE THREAD

**Issue by skipness** [daohoangson/flutter_widget_from_html#10]
Here is the html：
```html 
<em><span style="color: red;"><div style="text-align: right;">testing</div></span></em>
```
The widget can position the text but didn't apply other style(red color, italic) to it.
![](https://i.ibb.co/LYR0jFC/Simulator-Screen-Shot-i-Phone-XS-2019-03-05-at-14-05-44.png)

But if i put one tag(used `<h1>` tag as example) inside the `<div>` tag, all the style can be applied.
![](https://i.ibb.co/3k0r4Jr/Simulator-Screen-Shot-i-Phone-XS-2019-03-05-at-14-13-13.png)

**Comment by daohoangson** [comment]
Okie, this is weird. And somehow I didn't receive email notification for this issue before the version bump 😠 

Nice catch btw.

**Comment by skipness** [comment]
haha that’s fine
Actually it’s a quite fast response👍🏻

**Comment by daohoangson** [comment]
v0.1.3 has been released with the fix for this. Please take some time to upgrade and verify the fix. Thank you.

**Comment by skipness** [comment]
Works now👍🏻

**Comment by skipness** [comment]
One more thing
Are you planning to write any document about this package?
For example how to implement `WidgetFactory`,  what `onProcess ` and other method in `WidgetFactory` do.

**Comment by daohoangson** [comment]
I do. Things are still changing so I haven't committed to writing document yet.

**Comment by skipness** [comment]
Nice👍🏻
