### ISSUE TITLE
onTapUrl: cannot customize URL behavior

### ISSUE THREAD

**Issue by s3819660** [daohoangson/flutter_widget_from_html#1006]
I would like to open a WebView instead of launching the URL from the browser. To do that, I want to catch the URL then navigate to another screen with WebView.
I read your issue #28 and if I understand correctly, onTapUrl should have enabled customization of URL tap behavior?
I wrote the following code to catch and print the Url instead of launching it from the browser. However, it always opened the browser.

My import:
`import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';`

HtmlWidget:
`
child: HtmlWidget(
  html,
  onTapUrl: (url) => _hello(url),
),
`

Callback:
`
  _hello(String url) async {
    print(url);
    return true;
  }
`

I placed a debugger at the print(url); line yet the debugger catches nothing.
Did I make a mistake somewhere? 
Thank you so much for your contribution and support!

**Comment by daohoangson** [comment]
What is your HTML? Did you tap the link?

**Comment by s3819660** [comment]
ah I just realized the issue was on my part.
I sincerely apologize for the false alarm.
This package rocks! And thank you so much for being so supportive!

**Comment by s3819660** [comment]
ah I just realized the issue was on my part.
I sincerely apologize for the false alarm.
This package rocks! And thank you so much for being so supportive!
