### ISSUE TITLE
Large HTML block doesn't work in release mode

### ISSUE THREAD

**Issue by evergreenapps23** [daohoangson/flutter_widget_from_html#1007]
## Steps to Reproduce

Use this plugin with a very large block of HTML (I'm sitting at 7000 lines when formatted). In debug mode, the page renders perfectly. In release mode on a mobile browser it works perfectly but not on a desktop browser. On the desktop browser, it freezes when trying to load the widget.

UPDATE
I have rolled back Flutter to 3.10.6. Everything works perfectly. So this bug comes from an incompatibility between Flutter 3.13.x and flutter_widget_from_html. Not sure what the issue could be as for shorter HTML blocks there seems to be no issue.

<details>
  <summary>HTML</summary>

I'm going to leave out the HTML as it is a sensitive document. I can assure you that the HTML is correct as it works perfectly in debug mode, as well as when saved as an HTML document and opened by a browser.
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget(
        htmlData, //saved as a string
      );
```
</details>

<details>
  <summary>Tesing environment</summary>

```
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2134], locale en-AU)
    • Flutter version 3.13.1 on channel stable at C:\Users\green\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (5 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\green\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\green\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.54

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

## Expected results

Page to load with HTML

## Actual results

White page and unresponsive browser window (including navigation buttons and close button)

**Comment by scolnet** [comment]
Hello Team,

I'm having a similar problem with flutter 3.13.1 only in **release** mode and with **canvakit** renderer (I don't understand why but debug mode is ok)
Compiled on mac m1 and chrome.
Not need a large html : 
A simple html text with formatted text like `<p>Hello <b>everybody</b></p>` freeze the renderer without any error log. => need to kill the process chrome, reload page is not enough. (I have the problem with html tags b strong or i)
 
The widget is well displayed but few seconds later when I try to navigate or scroll, the screen freeze. (Maybe it's when the widget is disposed?)
A simple method to reproduce is to display HtmlWidget in AlertDialog => close dialog and try to navigate in your app.

I use flutter_html_core only, for 2 years without any problem.
When I rollback to flutter 3.10.6, it's ok.

if someone has an idea ?

**Comment by mstich-mcmservices** [comment]
I'm experience the same problem as scolnet.  The html is not rendered and the browser page completely locks up.

The html I am using is: 
`<p><b>This is a sample description</b></p><p></p><ol><li><b>First item</b></li><li><b>Second item </b></li><li><b>Third item</b></li></ol><p></p>`

**Comment by lesonlhld** [comment]
I had the same problem last week with Flutter 3.13.1 in release mode. It works fine if I go back to the old Flutter 3.10.6

To reproduce the problem, just show HTML with tag `<b>Some String</b>`

**Comment by daohoangson** [comment]
This appears to be a widespread issue. I'm triaging with simple HTML in Flutter 3.13.1, release mode, canvaskit renderer.

**Comment by daohoangson** [comment]
`v0.10.4` has been released with the workaround for this.

For context: a custom `TextStyle` was needed to properly support `line-height: normal` inline style. After Flutter 3.13, it is no longer a big issue so that feature has been simplified. See #1009

**Comment by scolnet** [comment]
First tests are ok with flutter 3.13.1 +web  release mode + canvaskit
Thanks for your responsiveness.

**Comment by mstich-mcmservices** [comment]
v0.10.4 work for me as well.  Same setup - flutter 3.13.1 +web release mode + canvaskit.

**Comment by evergreenapps23** [comment]
Tested my implementation just now. Works flawlessly. Thanks for being so responsive and quick on the update. Really strong work.
