### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by SinanKanmaz** [daohoangson/flutter_widget_from_html#101]
Hello! I started to get bugs with the latest Flutter update. How can I solve this error?
This Error:
Compiler message:
/C:/flutter_src/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/cached_network_image_provider.dart:53:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/flutter_src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
/C:/flutter_src/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/scaled_file_image.dart:45:24: Error: The method 'ScaledFileImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ScaledFileImage key) {
                       ^
/C:/flutter_src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by daohoangson** [comment]
Looks like one of our dependencies (`cached_network_image`) does not work well with your current version of Flutter. Can you share the output of `flutter doctor -v`?

If you are running Flutter 1.10.15, it is a known issue and requires a major upgrade for `cached_network_image` (see https://pub.dev/packages/cached_network_image/versions/2.0.0-rc). It's not recommended to build your app on non-stable Flutter channel.

**Comment by SinanKanmaz** [comment]
this is my flutter doctor -v:
[√] Flutter (Channel master, v1.10.15-pre.186, on Microsoft Windows [Version 10.0.18362.418], locale tr-TR)
    • Flutter version 1.10.15-pre.186 at C:\flutter_src\flutter
    • Framework revision 1c535de7e0 (2 days ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Zeynep\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\Zeynep\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (3 available)
    • KFAUWI     • G0W0MA0772451FT7 • android-arm    • Android 5.1.1 (API 22)
    • Chrome     • chrome           • web-javascript • Google Chrome 77.0.3865.120
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

**Comment by SinanKanmaz** [comment]
I get this error when I import the html widget.

**Comment by daohoangson** [comment]
Hah, so you are on Flutter master channel. As I said earlier:

> If you are running Flutter 1.10.15, it is a known issue and requires a major upgrade for cached_network_image (see https://pub.dev/packages/cached_network_image/versions/2.0.0-rc). It's not recommended to build your app on non-stable Flutter channel.

Can you switch to stable channel?

**Comment by rguntha** [comment]
I have faced the same issue.
I switched to master channel to try the web version.

**Comment by daohoangson** [comment]
> I switched to master channel to try the web version.

If you are trying to run this on web, try the core package. It has no dependency https://pub.dev/packages/flutter_widget_from_html_core

**Comment by daohoangson** [comment]
@SinanKanmaz @rguntha I have just released `flutter_widget_from_html@0.3.0-rc` with updated dependency for Flutter 1.10.15 (master channel). Please try upgrading and let me know if it works for your use case.
