### ISSUE TITLE
ERROR: fwfh_chewie: ^0.7.1+2 (last) use chewie-1.0.0 and it's have some error. 

### ISSUE THREAD

**Issue by vqthanh1412489** [daohoangson/flutter_widget_from_html#1011]
## Steps to Reproduce

<p>Use flutter_widget_from_html: ^0.10.4 (have a dependency <a title="^0.7.1+2" href="https://pub.dev/packages/fwfh_chewie">fwfh_chewie</a>). But <a title="^0.7.1+2" href="https://pub.dev/packages/fwfh_chewie">fwfh_chewie</a> is using chewie-1.0.0 and it gets this error.</p>

<div class="log-line"><code>Running Gradle task 'assembleDevRelease'...</code></div>
<div class="log-line"><code>../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.</code></div>
<div class="log-line"><code>SystemChrome.setEnabledSystemUIOverlays(</code></div>
<div class="log-line"><code>^^^^^^^^^^^^^^^^^^^^^^^^^^</code></div>
<div class="log-line"><code>../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:157:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.</code></div>
<div class="log-line"><code>SystemChrome.setEnabledSystemUIOverlays(</code></div>
<div class="log-line"><code>^^^^^^^^^^^^^^^^^^^^^^^^^^</code></div>
<div class="log-line"><code>../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:161:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.</code></div>
<div class="log-line"><code>SystemChrome.setEnabledSystemUIOverlays([]);</code></div>
<div class="log-line"><code>^^^^^^^^^^^^^^^^^^^^^^^^^^</code></div>
<div class="log-line"><code>../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/material_controls.dart:441:50: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.</code></div>
<div class="log-line"><code>- 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../programs/flutter/packages/flutter/lib/src/material/theme_data.dart').</code></div>
<div class="log-line"><code>Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.</code></div>
<div class="log-line"><code>playedColor: Theme.of(context).accentColor,</code></div>
<div class="log-line"><code>^^^^^^^^^^^</code></div>
<div class="log-line"><code>../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/material_controls.dart:442:50: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.</code></div>
<div class="log-line"><code>- 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../programs/flutter/packages/flutter/lib/src/material/theme_data.dart').</code></div>
<div class="log-line"><code>Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.</code></div>
<div class="log-line"><code>handleColor: Theme.of(context).accentColor,</code></div>
<div class="log-line"><code>^^^^^^^^^^^</code></div>

<p>When I use chewie-1.5.0 it's working&nbsp;</p>
<div class="ddict_div" style="top: 86.8906px; max-width: 150px; left: 5px;"><img class="ddict_audio" src="chrome-extension://bpggmmljdiliancllaapiggllnkbjocb/img/audio.png">
</div>

<details>
  <summary>`HtmlWidget` configuration</summary>
<div class="log-line"><code>HtmlWidget(</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _htmlContent,</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; onLoadingBuilder: (context, element, loadingProgress) =&gt; Container(</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; padding: EdgeInsets.only(top: ScreenUtil().screenHeight / 4),</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color: Colors.red,</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ),</code><br><code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; )</code></div>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>
<a href="https://imgur.com/EQB4cZS"><img src="https://i.imgur.com/EQB4cZS.png" title="source: imgur.com" /></a>

```
```
</details>

## Expected results

Don't get this error for the lastest version.

## Actual results

I still get this error with the lastest version.

**Comment by daohoangson** [comment]
Have you tried specifying a recent version of the chewie package directly in your app's pubspec? E.g. `chewie: ^1.7.0`?

**Comment by vqthanh1412489** [comment]
> Have you tried specifying a recent version of the chewie package directly in your app's pubspec? E.g. `chewie: ^1.7.0`?

Thank you!
