### ISSUE TITLE
Amazon affiliate  iframe dont work

### ISSUE THREAD

**Issue by kama-tech** [daohoangson/flutter_widget_from_html#1015]
Hello, I have tried to add an amazon affiliate iframe in a webapp, but it does not show anything, however I have tried other iframes, for example from YouTube and other websites, and if it works, any suggestions?
<img width="1202" alt="Screenshot 2023-09-05 at 5 28 42 PM" src="https://github.com/daohoangson/flutter_widget_from_html/assets/17535459/e99672d5-53c0-4e2f-9dfd-2099b024527e">

**Comment by daohoangson** [comment]
What is your HTML?

**Comment by kama-tech** [comment]
simple html 


HtmlWidget(
  '<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=mobilea04cffb-20&language=en_US&marketplace=amazon&region=US&placement=B09F3DJNGF&asins=B09F3DJNGF&linkId=8810db11548943f6b991b940d2cc04b4&show_border=true&link_opens_in_new_window=true"></iframe>',

);

**Comment by daohoangson** [comment]
Probably a bug with the protocol relative URL. Can you try this HTML in your app?

```html
<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=mobilea04cffb-20&language=en_US&marketplace=amazon®ion=US&placement=B09F3DJNGF&asins=B09F3DJNGF&linkId=8810db11548943f6b991b940d2cc04b4&show_border=true&link_opens_in_new_window=true"></iframe>
```

**Comment by kama-tech** [comment]
> Probably a bug with the protocol relative URL. Can you try this HTML in your app?
> 
> ```
> <iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=mobilea04cffb-20&language=en_US&marketplace=amazon®ion=US&placement=B09F3DJNGF&asins=B09F3DJNGF&linkId=8810db11548943f6b991b940d2cc04b4&show_border=true&link_opens_in_new_window=true"></iframe>
> ```

Its work.

**Comment by daohoangson** [comment]
That's good to hear. Let me investigate the bug further then.

**Comment by kama-tech** [comment]
> That's good to hear. Let me investigate the bug further then.

ok thanks

**Comment by daohoangson** [comment]
`v0.10.5` has been released with the fix for this, it should render your original HTML, the one without https, correctly. Please try upgrading and let me know if it works for you.

**Comment by kama-tech** [comment]
> `v0.10.5` has been released with the fix for this, it should render your original HTML, the one without https, correctly. Please try upgrading and let me know if it works for you.

Work perfect thanks
