### ISSUE TITLE
Texts should be selectable

### ISSUE THREAD

**Issue by umutoney** [daohoangson/flutter_widget_from_html#102]
https://master-api.flutter.dev/flutter/material/SelectableText-class.html

**Comment by daohoangson** [comment]
Selectable text is very useful but unfortunately it cannot be done with `SelectableText.rich` because it does not support non-`TextSpan` children which is used by this plugin to render inline image.

https://api.flutter.dev/flutter/material/SelectableText/SelectableText.rich.html

> The textSpan parameter must not be null and only contain TextSpan in textSpan.children. Other type of InlineSpan is not allowed.

**Comment by daohoangson** [comment]
Reconsider `SelectableText` support when this issue is closed: https://github.com/flutter/flutter/issues/38474

**Comment by ModernChocolate** [comment]
You could use https://github.com/fluttercandies/extended_text

**Comment by daohoangson** [comment]
It works!

<img src="https://user-images.githubusercontent.com/239336/122192192-a0644a00-cebd-11eb-9299-a31a275c15cc.png" width="300" />

**Comment by ModernChocolate** [comment]
Does this mean that we'll have selectable text on flutter_html_widget ? 🤩

**Comment by daohoangson** [comment]
> Does this mean that we'll have selectable text on flutter_html_widget ? 🤩

Yes 🚀

**Comment by DFelten** [comment]
Great to hear that this feature will be possible in the future. Can you give an estimation how well it works? :) 

Currently we have to create an own div tag for coupons to make them copyable.

**Comment by daohoangson** [comment]
Current it works with simple test cases and doesn't with HTML that has deep nested stylings. I ran a few quick tests so I didn't dig any further. Once the bugs are ironed out, I think it should be fairly stable.

**Comment by rajeshzmoke** [comment]
@daohoangson  Any update on this?

**Comment by daohoangson** [comment]
The reference commits haven't reached stable yet. They are in beta though, that's some progress.

**Comment by daohoangson** [comment]
Flutter 2.5 has been released with support for `WidgetSpan` in `SelectableText`. Expect a new version soon.

**Comment by daohoangson** [comment]
It works on stable but Flutter source code modification is still required. The assertion should be removed sometime soon (I hope). Will keep a close eye on this.

**Comment by bksubhuti** [comment]
This is very important to me.  I'm glad to hear about the progress.  Is there special code to write to make this happen.  I'm confused when a different widget (SelectableText.rich)  is mentioned, unless that is used internally in wrapped code.?

**Comment by daohoangson** [comment]
Very simple tests have been done to verify selectable widget but it's not usable yet. We will have to wait.

**Comment by bksubhuti** [comment]
What is the approximate time projection for this feature?

**Comment by daohoangson** [comment]
It depends entirely on the Flutter team, I'm asking at `https://github.com/flutter/flutter/issues/38474#issuecomment-932849890`.

**Comment by JesseBlackman** [comment]
> The Flutter team has removed the restriction on master channel, it should make it way to dev channel in a few days.

hi, still waiting for support

**Comment by lrorpilla** [comment]
I am also pretty excited to finally be able to have this -- I tried passing paragraphs to use `SelectableText` and while I can't select separate paragraphs, it's really promising to just see this finally work on master. Is there a fork of the package with the text already set up to have `SelectableText` I can try out?

**Comment by daohoangson** [comment]
Looks like it's available in the 2.8.0 beta 3 days ago https://github.com/flutter/flutter/releases/tag/2.8.0-3.1.pre, let me release a new version with this real quick.

**Comment by daohoangson** [comment]
`v0.8.3-beta.1` has been released. The new parameter works like this:

```dart
HtmlWidget(
  html,
  isSelectable: true, // default is false
)
```

There is a live demo link available in the PR: https://github.com/daohoangson/flutter_widget_from_html/pull/631. There are still issues like selecting across multiple paragraphs etc.

**Comment by DFelten** [comment]
Thanks for this! I will test this tomorrow. Which version or branch of Flutter do we need for this?

**Comment by daohoangson** [comment]
You need at least 2.7, currently in beta channel.

**Comment by bksubhuti** [comment]
Is there a way to have the popup disabled and also a callback when there is a selection?
and _special wish_ is to have a callback on word click (as if every word were a url).

Our webview project does this.. https://play.google.com/store/apps/details?id=com.paauk.tipitakapalireader
We want to migrate out of webview and into this package so we can do desktop.

**Comment by daohoangson** [comment]
You want to disable the selectable popup? Err, you can disable selectable mode for that I guess.

Technically you can register all sort of gesture recognizer on the widgets and texts. But doing so for everything may hurt performance 🤔 Please open a separate discussion for this if you want to discuss further.

**Comment by daohoangson** [comment]
`v0.8.3+1` has been released with support for `isSelectable` in the `flutter_widget_from_html` package. The core package is not updated at this time to avoid bumping the minimum required Flutter version. v2.8 stable is pretty new.

I'm closing this two-year-old issue right now, please open new issue if you encounter bugs related to this feature.

**Comment by Vluf** [comment]
Can this be augmented with the newly released [SelectionArea](https://api.flutter.dev/flutter/material/SelectionArea-class.html) in Flutter 3.3? Makes selecting multiple paragraphs possible!

**Comment by daohoangson** [comment]
Should be. I'm working on it here https://github.com/daohoangson/flutter_widget_from_html/pull/821. Ideally `HtmlWidget` should work automatically if it is built within a selection area.

**Comment by bksubhuti** [comment]
okay.. sadhu x 3 (appreciated).  Because of you, we moved forward to 5 OS.
