### ISSUE TITLE
I'm not getting the styles in the content that i want to render.

### ISSUE THREAD

**Issue by kessler428** [daohoangson/flutter_widget_from_html#1023]
Well basically i want to render an html that i'm getting for the back end, like this is the code html:

![Screenshot 2023-09-09 at 2 42 33 PM](https://github.com/daohoangson/flutter_widget_from_html/assets/84168483/18a22986-fb93-460f-be44-97603eab67c2)

But the styles are not working when i render mi aplication:
This is the code: HtmlWidget(state.listOfTocs[indexOfToc].html),

<img width="1124" alt="Screenshot 2023-09-09 at 2 45 04 PM" src="https://github.com/daohoangson/flutter_widget_from_html/assets/84168483/c1c47993-53c9-40a4-b5b4-3fc5d80bff3f">

And these are the results that im expecting:

</details>
![Screenshot 2023-09-09 at 2 46 13 PM (2)](https://github.com/daohoangson/flutter_widget_from_html/assets/84168483/6414b767-b345-472d-83cf-5eddf18ef709)

**Comment by daohoangson** [comment]
This appeared to be working as expected. This package supports inline styling via STYLE attribute only. The STYLE tag and remote stylesheet with LINK tag are not supported.
