### ISSUE TITLE
How to control the max lines?

### ISSUE THREAD

**Issue by Erchil66** [daohoangson/flutter_widget_from_html#1025]
Hi, i have a question about max lines, it only work when only text and doesn't include or with ul/il or p inside.

e.g.

```
'<div style="max-lines: 2"><p>sample Text to know maxlines :<br /><br /><br /></p>
      <ul>
      <li>kamatis</li>
      <li>buongon</li>
      <li>atis</li>
      <li>bayabas</li>
      </ul></div>'
```
from above inpute html tags doenst work at all it still view the whole thing.

**Comment by daohoangson** [comment]
This is the expected behavior. The current implementation use [RichText.maxLines](https://api.flutter.dev/flutter/widgets/RichText/maxLines.html) to control the lines so it won't work if the HTML contains other block elements like UL, LI. Similar line clamp CSS won't work in browser either IIRC.
