### ISSUE TITLE
SUB and SUP tag is not working

### ISSUE THREAD

**Issue by pashupatisah112** [daohoangson/flutter_widget_from_html#1031]
I am using flutter   
sdk: ">=2.17.3 <3.0.0"
flutter_widget_from_html: ^ 0.10.5+3
Dart version: 2.19.6

**Comment by daohoangson** [comment]
What is your HTML? You are using Flutter 3.3?

**Comment by pashupatisah112** [comment]
Flutter 3.7.10
My HTML has square and base ..consists of mathematical formulae.

**Comment by daohoangson** [comment]
Without specific HTML to troubleshoot, it's hard to figure out the problem and fix it. Can you share your HTML?

**Comment by pashupatisah112** [comment]
This is my HTML. I noticed its a little different from actual 'sub' tag. It has been generated as <msub> instead of <sub>. It works on browser. Is there any custom way to handle the situation?

<p>There are <strong>4 types </strong>of chemical reaction mainly. They are as follows:</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="3:1-3:96"><strong>1)</strong> <strong>Addition or combination reaction:</strong> Two or more reactants combine to form a single product.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="5:1-5:13">Examples:</p>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="7:1-7:56">
<li style="margin-bottom: 10px;" data-sourcepos="7:1-7:56">Sodium combines with chlorine to form sodium chloride:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">2Na + Cl2 &rarr; 2NaCl
</code></pre>
</div>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="11:1-11:73">
<li style="margin-bottom: 10px;" data-sourcepos="11:1-11:73">When iron fillings are heated with sulfur, ferrous sulfide is produced:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">Fe + S &rarr; FeS
</code></pre>
</div>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="16:1-16:103"><strong>2) Decomposition or dissociation reaction</strong>: A single reactant breaks down into two or more products.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="18:1-18:13">Examples:</p>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="20:1-20:64">
<li style="margin-bottom: 10px;" data-sourcepos="20:1-20:64">When lead oxide is heated, it decomposes into lead and oxygen:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">2PbO &rarr; 2Pb + <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>o</mi><mn>2</mn></msub></math>
</code></pre>
</div>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="24:1-24:91">
<li style="margin-bottom: 10px;" data-sourcepos="24:1-24:91">When sodium chloride is electrolyzed at a high temperature, it forms sodium and chlorine:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">2NaCl &rarr; 2Na + <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>c</mi><msub><mi>l</mi><mn>2</mn></msub></math>
</code></pre>
</div>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="29:1-29:101"><strong>3) Displacement reaction:</strong> One element or ion in a compound is replaced by another element or ion.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="31:1-31:102"><strong>Single displacement:</strong> A single element replaces a similar element of an adjacent reactant compound.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="33:1-33:12">Example:</p>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="35:1-35:83">
<li style="margin-bottom: 10px;" data-sourcepos="35:1-35:83">Zinc displaces hydrogen from sulfuric acid to form zinc sulfate and hydrogen gas:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>Z</mi><mi>n</mi></math> + <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub></math>S<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>O</mi><mn>4</mn></msub></math> &rarr; <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>Z</mi><mi>n</mi><mi>S</mi><msub><mi>O</mi><mn>4</mn></msub></math> + <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub></math>
</code></pre>
</div>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="40:1-40:94"><strong>Double displacement:</strong> Two ionic compounds exchange ions, producing two new ionic compounds.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="42:1-42:12">Example:</p>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="44:1-44:86">
<li style="margin-bottom: 10px;" data-sourcepos="44:1-44:86">Silver nitrate and sodium chloride react to form silver chloride and sodium nitrate:</li>
</ul>
<div class="code-block ng-star-inserted">
<pre style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">AgN<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>o</mi><mn>3</mn></msub></math> + NaCl &rarr; AgCl + NaN<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>o</mi><mn>3</mn></msub></math>
</code></pre>
</div>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="49:1-49:95"><strong>4) Neutralization or acid-base reaction:</strong> An acid and a base react to form a salt and water.</p>
<p style="margin: 24px 0px; white-space-collapse: preserve; word-break: break-word; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="51:1-51:13">Examples:</p>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="53:1-53:109">
<li style="margin-bottom: 10px;" data-sourcepos="53:1-53:109">Sodium hydroxide (NaOH) reacts with hydrochloric acid (HCl) to form sodium chloride (NaCl) and water (<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub></math>O):</li>
</ul>
<div class="code-block ng-star-inserted">
<p style="margin-top: 0px; margin-bottom: 0px;"><code class="code-container no-decoration-radius" style="font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-stretch: normal; font-size: 0.875rem; line-height: 1.125rem; font-family: 'Google Sans Mono', monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text">NaOH + HCl &rarr; NaCl + <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub></math>O
</code></p>
</div>
<ul style="margin: 4px 0px; padding-inline-start: 36px; color: #1f1f1f; font-family: 'Google Sans', 'Helvetica Neue', sans-serif; font-size: 16px; background-color: #ffffff;" data-sourcepos="57:1-57:105">
<li style="margin-bottom: 10px;" data-sourcepos="57:1-57:105">Copper oxide (CuO) reacts with hydrochloric acid (HCl) to form copper chloride (Cu<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>C</mi><msub><mi>l</mi><mn>2</mn></msub></math>) and water (<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub></math>O):</li>
</ul>
<p>&nbsp;</p>
<div class="code-block ng-star-inserted">
<p style="margin: 0px;"><code class="code-container no-decoration-radius" style="font: 400 0.875rem / 1.125rem 'Google Sans Mono', monospace; letter-spacing: normal; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-code-block-background); border-radius: 16px; padding: 16px; display: block; overflow-x: auto; direction: ltr;" role="text"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>C</mi><mi>u</mi><mi>O</mi></math> + <math xmlns="http://www.w3.org/1998/Math/MathML"><mn>2</mn><mi>H</mi><mi>C</mi><mi>l</mi></math> &rarr; <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>C</mi><mi>u</mi></math><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>C</mi><msub><mi>l</mi><mn>2</mn></msub></math> + <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>H</mi><mn>2</mn></msub><mi>O</mi></math></code></p>
</div>

**Comment by daohoangson** [comment]
Your HTML is using MathML to render, support for that is still in progress. See #471

**Comment by pashupatisah112** [comment]
Thank you for your support
