### ISSUE TITLE
Unable to run in v0.10.5+3 : "setInspectable" not found in "WebKitWebViewController" for iOS.

### ISSUE THREAD

**Issue by aliasgar4558** [daohoangson/flutter_widget_from_html#1032]
Facing below error when running application with **version 0.10.5+3**.

**`Error (Xcode): ../../../.pub-cache/hosted/pub.dev/fwfh_webview-0.9.0+2/lib/src/web_view/io.dart:84:28: Error: The method 'setInspectable' isn't defined for the class 'WebKitWebViewController'.`**

It seems like something is breaking in the latest changes/package update.

**Comment by daohoangson** [comment]
The latest version requires the latest Xcode. You can stay at `v0.10.5` until Xcode is updated.
