### ISSUE TITLE
iframe  iOS

### ISSUE THREAD

**Issue by xiechunjiang** [daohoangson/flutter_widget_from_html#1034]
Using an iframe to nest a link is no problem in Android, but in iOS it will automatically jump to the Safari browser.

  var html = '''
 

<iframe width="560" height="315" src="https://player.bilibili.com/player.html?aid=363695358&amp;bvid=BV1W94y1p7vB&amp;cid=1274668196&amp;p=1"></iframe>

 ''';     HtmlWidget(
                html,
                buildAsync: true,
       )

**Comment by daohoangson** [comment]
I'm afraid this is a behavior of the website. It can detect its environment and behave differently.
