### ISSUE TITLE
Font usage

### ISSUE THREAD

**Issue by SayaGames** [daohoangson/flutter_widget_from_html#104]
Hi, 
How to use custom fonts from flutter's "fonts" folder or some other locations?
How to change app's fontname with HtmlWidget plugin?

Best regards?

**Comment by daohoangson** [comment]
You can set the `textStyle` when you create a new `HtmlWidget` like this:

```dart
    HtmlWidget(
        kHtml,
        textStyle: TextStyle(fontFamily: 'Roboto'),
    )
```

Or you can put the `HtmlWidget` inside a `DefaultTextStyle` like this:

```dart
    DefaultTextStyle(
        style: DefaultTextStyle.of(context)
            .style
            .copyWith(fontFamily: 'Roboto'),
        child: HtmlWidget(kHtml),
    )
```

**Comment by SayaGames** [comment]
Thank you very much

**Comment by daohoangson** [comment]
Hey @SayaGames, as the issue has been resolved, I'm closing it now. Cheers.
