### ISSUE TITLE
Bad State: No element issue occurs again.

### ISSUE THREAD

**Issue by kunaldas1997** [daohoangson/flutter_widget_from_html#105]
I previously mentioned about this issue, and again, it occurs. This occurs when you changed the context in the main website, but the app cannot read and render it

**Comment by kunaldas1997** [comment]
In simple, the app cannot read the data from the website when modified.

**Comment by daohoangson** [comment]
Your issue is similar to the one you posted earlier? https://github.com/daohoangson/flutter_widget_from_html/issues/68

Do you have a simple app that I can build and reproduce it? I have two fairly complex apps using this plugin and render data from the web without issue.

https://github.com/daohoangson/flutter-blogspot_reader/blob/16f81c7fb5748e81334bdabe78036680f9220521/lib/blogspot/entry.dart#L27

https://github.com/daohoangson/flutter-tinhte_demo/blob/be01f1f50420094bdef77619bc09938374bc214d/lib/src/widgets/html.dart#L49

**Comment by kunaldas1997** [comment]
As I already mentioned, the app shows this particular issue, when you all of a sudden change the data on the server, and the app doesn't get the data all of a sudden. Nope, no simple app :/

**Comment by daohoangson** [comment]
Can you capture the html before the change (that `HtmlWidget` renders okie).

And the html after the change (that `HtmlWidget` cannot render).

I'm trying to reproduce the issue on my device.

**Comment by daohoangson** [comment]
Oh, and which Flutter version is being used to build the app? `flutter doctor` output should be useful here.

**Comment by kunaldas1997** [comment]
Yes. I could capture the HTML code that renders fine, as well as the one that doesn't render.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.19018.1], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] Connected device //ignore from here
    ! No devices available

! Doctor found issues in 1 category.

**Comment by daohoangson** [comment]
> Yes. I could capture the HTML code that renders fine, as well as the one that doesn't render.

This would be great. Thanks!.

**Comment by daohoangson** [comment]
Hey @kunaldas1997, do you have the html contents yet?

**Comment by kunaldas1997** [comment]
you can check the content from this -> https://onetechstop.net/wp-json/wp/v2/posts

I use this.

**Comment by daohoangson** [comment]
I know this is an old issue but I have just tried with the latest HTML from the WP api and it seemed to work fine. Feel free to reopen or better yet, open a new issue if you are still having problems.
