### ISSUE TITLE
support  font tag?

### ISSUE THREAD

**Issue by OHeroJ** [daohoangson/flutter_widget_from_html#106]

**Comment by daohoangson** [comment]
Adding support for FONT tag is fairly simple, I can add it in the next release. It should allows usage of `color`, `face` and `size` attributes.

**Comment by daohoangson** [comment]
`v0.2.4` has been released with support for FONT tag. Please update and let me know if it works for you @OHeroJ

**Comment by ControlAdad** [comment]
Can we use fonts loaded from **link** tag? For example Google Fonts?

**Comment by daohoangson** [comment]
Nope.
