### ISSUE TITLE
Amazon affiliate iframe dont open on android after click

### ISSUE THREAD

**Issue by devuserPP** [daohoangson/flutter_widget_from_html#1069]
Hello, I have tried to add an amazon affiliate iframe inside android app. Problem is, when I click on iframe, in the console give error '**E/FrameEvents( 7785): updateAcquireFence: Did not find frame.**' For web is working without problem.
flutter_widget_from_html_core: ^0.14.3
fwfh_webview: ^0.14.2
here is the code 
```
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import 'package:fwfh_webview/fwfh_webview.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'fwfh_webview',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('WebViewFactory Demo'),
        ),
        body: Center(
          child: HtmlWidget(
            '<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=6546546312107-20&language=en_US&marketplace=amazon&region=US&placement=B0C5ZYKYP4&asins=B0C5ZYKYP4&linkId=a6258cbb6a15b8b910b9c1eda68c09c2&show_border=true&link_opens_in_new_window=true"></iframe>',
            factoryBuilder: () => MyWidgetFactory(),
          ),
        ),
      ),
    );
  }
}

class MyWidgetFactory extends WidgetFactory with WebViewFactory {}

```

**Comment by daohoangson** [comment]
What do you expect would happen when you click the link? If you want to launch browser, you need to use https://pub.dev/packages/fwfh_url_launcher or implement your own `onTapUrl`.

**Comment by devuserPP** [comment]
@daohoangson Sorry but I do not understand you. I expect the same behavior as running the code for web browsers and the same on Android. That means when clicking inside the iframe launch a new window in a web browser and open the URL. In case of using onTapUrl or fwfh_url_launcher, how I can get URL from iframe?

**Comment by devuserPP** [comment]
@daohoangson thank you so much for the example. Now it's clear to me, working great.
