### ISSUE TITLE
Horizontal center non-full width table

### ISSUE THREAD

**Issue by AnhLT-Nexle** [daohoangson/flutter_widget_from_html#1071]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```

<figure class=\"table\"  style=\"margin-left:auto;margin-right:auto;width:55.65%;\">
   <table class=\"ck-table-resized\">
      <colgroup>
         <col style=\"width:70.47%;\">
         <col style=\"width:29.53%;\">
      </colgroup>
      <tbody>
         <tr>
            <td style=\"border-style:solid;border-width:1px;\">1</td>
            <td style=\"border-style:solid;border-width:1px;\">2</td>
         </tr>
         <tr>
            <td style=\"border-style:solid;border-width:1px;\">3</td>
            <td style=\"border-style:solid;border-width:1px;\">4</td>
         </tr>
      </tbody>
   </table>
</figure>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

version 0.14.3

```
```
</details>

## Expected results
The second table
<img width="763" alt="Screenshot 2023-10-20 at 16 21 48" src="https://github.com/daohoangson/flutter_widget_from_html/assets/96031601/8ef66ed1-7079-4a1b-86c5-e90e139bad14">

## Actual results
The second table
![Screenshot 2023-10-20 at 16 21 19](https://github.com/daohoangson/flutter_widget_from_html/assets/96031601/eba91e09-3681-497b-8207-dba94b5a8b7a)

**Comment by daohoangson** [comment]
Yeah, `margin-left:auto;margin-right:auto;` is not supported yet.

**Comment by daohoangson** [comment]
`v0.14.5` has been released with support for `auto` margins but your HTML won't work as it is right now. Because `COLGROUP` is not supported yet (follow #531 for that).

**Comment by AnhLT-Nexle** [comment]
Thank you for your quick support.
