### ISSUE TITLE
Error with version flutter_widget_from_html: ^0.14.6

### ISSUE THREAD

**Issue by suhail600** [daohoangson/flutter_widget_from_html#1087]
Issue Description:

Upgraded Package Version: **0.14.6** (Error)

Problem:

 I encountered a build issue with the following error:

```
D:\development\aryn\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:94: error: cannot find symbol
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());
                                                                              ^
  symbol:   class PackageInfoPlugin
  location: package dev.fluttercommunity.plus.packageinfo
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Additional Information:

This issue occurs after using  version **0.14.6** of the flutter_widget_from_html package. 

The error seems to be related to a missing or conflicting dependency (PackageInfoPlugin from dev.fluttercommunity.plus.packageinfo).
Removing the flutter_widget_from_html package allows the app to build without errors.
Flutter Environment:

**_Flutter doctor has no issues related._**

Flutter version:  **3.10.5**
Dart version: **3.0.5**
Operating System: **windows**

**Steps to Reproduce:**

Add the **flutter_widget_from_html** package in a Flutter project to version **0.14.6**.
Attempt to build the project, and the error described above is encountered.
Please provide guidance on resolving this issue and ensuring compatibility with the latest version of the **flutter_widget_from_html** package.

**Comment by daohoangson** [comment]
The `package_info_plus` package is needed for `wakelock_plus` which is needed for `chewie` since v1.6.0, previous versions use `wakelock` instead. There are a few things we can try here:

- `flutter clean` and install dependencies again
- Pin `chewie: 1.5.0` in your pubspec
- Switch from `flutter_widget_from_html` to `flutter_widget_from_html_core` if your HTML doesn't need VIDEO tag support

**Comment by suhail600** [comment]
thanks for the solution , its woking fine now. i have used flutter_widget_from_html_core as there is no video rendered.
