### ISSUE TITLE
Compatibility Issue with CachedNetworkImage 3.2.3 due to Deprecated DecoderCallback

### ISSUE THREAD

**Issue by AndriiReverchuk** [daohoangson/flutter_widget_from_html#1099]
## Issue Description
While building my Flutter project, I encountered an error related to the `cached_network_image` package. The error is as follows:

"./../../../.pub-cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Помилка: тип «DecoderCallback» не знайдено . image_provider.CachedNetworkImageProvider ключ, декодування DecoderCallback) { ^^^^^^^^^^^^^^^^"

This seems to be due to the `DecoderCallback` type being deprecated in Flutter's recent updates (reference: [Flutter API Docs](https://api.flutter.dev/flutter/painting/DecoderCallback.html)).

## Package Information
The issue arises when using the `flutter_widget_from_html` package, which internally relies on `fwfh_cached_network_image`. The `cached_network_image` version causing the issue is `3.2.3`.

## Suggested Solution
Updating the `cached_network_image` dependency within `fwfh_cached_network_image` from version `3.2.3` to `3.3.0` or later seems to be a potential solution to this compatibility issue.

## Additional Information
- Flutter version: 3.16.0
- `flutter_widget_from_html` version: 0.14.6
- `cached_network_image` version: 3.2.3 (causing the issue)

I'm attaching a screenshot of the error for further reference.

<img width="1624" alt="screnshot" src="https://github.com/daohoangson/flutter_widget_from_html/assets/66751960/f68528a3-7299-4e8d-8117-c1134f5103e7">

Looking forward to a resolution or guidance on how to proceed with this. Thank you for your time and efforts in maintaining this package.

**Comment by daohoangson** [comment]
Can you try running `flutter pub upgrade cached_network_image`? It should bump that package to 3.3.0 without fix from us.

**Comment by daohoangson** [comment]
Ah the `flutter_blurhash` package, which you're currently using, is not yet compatible with Flutter version 3.16. You have two options: either downgrade Flutter to v3.13, or remove the that package from your project. This is no longer related to the `flutter_widget_from_html` package.
