### ISSUE TITLE
Problem with custom tag handling

### ISSUE THREAD

**Issue by skipness** [daohoangson/flutter_widget_from_html#11]
I try to use the following code to handle `<blockquote>` tag:
```dart
case 'blockquote':
    meta = lazySet(meta,
    color: theme.hintColor,
    buildOp: BuildOp(
          isBlockElement: true,
          onWidgets: (widgets) {
            return <Widget>[Blockquote(child: this.buildColumn(widgets))];
          },
        ));
break;
```
The `Blockquote` widget is a container with left board and I have set a default text color to it.
When rendering the following html code:
```html
<blockquote>some text before span <span style="color: red;">testing</span> text after span</blockquote>
```
I expect the the text "tesing" is in red color and the remaining text color is the one I have set in `parseElement` method. However, the text color of text "text after span" is not the one I set.
![](https://i.ibb.co/Q6WcGw2/Simulator-Screen-Shot-i-Phone-XS-2019-03-05-at-14-56-04.png)

I am not sure if I implement the custom widget in the right place or is it a bug, please advise.

**Comment by daohoangson** [comment]
I think it's a bug. Let me check.

**Comment by daohoangson** [comment]
I have just realized that the library doesn't support `color` in inline styling. Did you implement that yourself?

**Comment by skipness** [comment]
> I have just realized that the library doesn't support `color` in inline styling. Did you implement that yourself?

Yes, I did it this way:
```dart
 @override
  NodeMetadata parseElementStyle(NodeMetadata meta, String key, String value) {
    meta = super.parseElementStyle(meta, key, value);
    switch (key) {
      case 'font-size':
        meta = lazySet(meta,
            fontSize:
                this.defaultTextStyle.fontSize + _supportedFotSize[value]);
        break;
      case 'color':
        meta = lazySet(meta, color: _supportedColorStyle[value]);
        break;
    }
    return meta;
  }
```

**Comment by daohoangson** [comment]
Nice, I did something similar and found the bug. Let me try and fix it real quick.

**Comment by daohoangson** [comment]
I have just released v0.1.2 with the fix, please try upgrading and let me know if it works for you.

**Comment by skipness** [comment]
Will test on tomorrow
Thanks👍🏻

**Comment by skipness** [comment]
Works now👍🏻
