### ISSUE TITLE
Disabling logging the parser process

### ISSUE THREAD

**Issue by darkstarx** [daohoangson/flutter_widget_from_html#1119]
Hello! Thanks for the great package.

I would like to disable logging of the parser. It's very long process and there are many messages generated by the widget during parsing an html. This log is much larger than my application's log, so it becomes annoying to find my logs between huge amount of useless information.

<img width="687" alt="image" src="https://github.com/daohoangson/flutter_widget_from_html/assets/3534966/7f520f39-e63a-4c70-8cd5-c76b11a13ffd">

**Comment by daohoangson** [comment]
By default, the log records are silent, you must have configured some printer for those? The ones in the screenshot have the "finest" level, which is very verbose. You can either increase the global level:

```dart
Logger.root.level = Level.FINE;
```

Or adjust your printer to ignore a log record by `loggerName` or similar.

**Comment by darkstarx** [comment]
No, I don't use `print`, it's not recommended. Instead, I use `log` from `dart:developer` for logging the messages from the `Logger`. Indeed, I can filter messages by the logger name, thank you for you advice!

**Comment by rawthriver** [comment]
Hi! There must be a way to disable logging. It is wrong that developer must write a patch to package to be sound and convenient (in fact yout do not know, how others using logger).
Besides that, spawning loggers this way `logger = Logger('fwfh.HtmlTable${loggers++}'),` is not good. Consider using this index inside message.
Anyway, thanks for such a useful package!
