### ISSUE TITLE
How can I justify all the content?

### ISSUE THREAD

**Issue by hortigado** [daohoangson/flutter_widget_from_html#1124]
Hi in the package Html() i can do the following
` Html(
   style: {
     'html': Style(textAlign: TextAlign.justify),
    },
 )`
Thanks

**Comment by daohoangson** [comment]
Assuming your HTML has the `P` tag. You can use `customStylesBuilder` to specify the text alignment. Something like this:

```dart
    HtmlWidget(
      html,
      customStylesBuilder: (e) {
        if (e.localName == 'p') {
          return {'text-align': 'justify'};
        }

        return null;
      },
    );
```

**Comment by hortigado** [comment]
@daohoangson Thanks and if the html not have a tag and it is only text. I am reading a database where different values are returned, some just text and others in html text with tags.

**Comment by daohoangson** [comment]
If you have no control then it's probably easiest to just wrap it inside a div to apply some global style.

```dart
final withStyle = '<div style="text-align: justify">$html</div>';
```

**Comment by hortigado** [comment]
Thank you, its working good.
