### ISSUE TITLE
font-family usage

### ISSUE THREAD

**Issue by peterjonesdyedurham** [daohoangson/flutter_widget_from_html#1126]
I'm looking for a way to use 'font-family' but can't find anything here. Is it possible to use 'font-family' in an inline style in my HTML in 'HtmlWidget"?
Thanks in advance.

**Comment by daohoangson** [comment]
Yes, `font-family` is supported. It is listed in the README and pub.dev too:

<img width="418" alt="Screenshot 2023-12-07 at 09 09 38" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/31884224-0f30-46fb-bd4c-0d2de847b29c">

**Comment by peterjonesdyedurham** [comment]
Thank you for your quick response. Can you point me to an example as to how to use `font-family within `const String htmlContent`? I haven't been able to make it work yet. Thank you.

**Comment by daohoangson** [comment]
Something simple like `Hello, <span style="font-family: Lato">Google Fonts</span>.` should work. Given that you include the font in your pubspec.

**Comment by peterjonesdyedurham** [comment]
Thanks Dao.
