### ISSUE TITLE
Improve `WebView` auto resize logic

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#1139]
We are using timers to perform size evaluations and resize the web view. For slow web pages, it is not reliable / slow to react. It would be better if we can use JavaScript channel and listen to the window `resize` event.

Should wait for #1138 to stabilize the test executions before attempting this.

See:
- https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
- https://github.com/aker99/social_embed_webview/blob/2f6b6cf/lib/social_embed_webview.dart

**Comment by DFelten** [comment]
We already use something like this in our controller. Maybe that will help.

```dart
static const String _javaScriptChannel = 'ContentHeight';

static const String _sizeReportingJavaScript = '''
const resizeObserver = new ResizeObserver(entries => 
  $_javaScriptChannel.postMessage(entries[0].target.scrollHeight)
)

resizeObserver.observe(document.documentElement)
''';
```

```dart
controller.addJavaScriptChannel(
  _javaScriptChannel,
  onMessageReceived: _setContentHeight,
);

```

**Comment by daohoangson** [comment]
Thank you for the suggestion, @DFelten. I think the implementation will look very similar to that.

**Comment by daohoangson** [comment]
Just FYI, the latest version (`v0.15.1`) has been released with the new auto resize logic.
