### ISSUE TITLE
Add support for RTL

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#115]
- [x] attribute `dir`
- [x] inline style `direction`
- [x] inline style `margin-(block|inline)-(start|end)` (with legacy support)
- [x] inline style `padding-(left|right)` for LI

**Comment by JohnMusleh** [comment]
dir="rtl" still does not work right?, any plans on implementing this?

**Comment by daohoangson** [comment]
Yes, it's not yet supported. I plan to add support for it though.

For now, you can use the `Directionality` widget to force a text direction.
