### ISSUE TITLE
Widget Max Lines

### ISSUE THREAD

**Issue by ahmdmau** [daohoangson/flutter_widget_from_html#1155]
Hello!

Could you please provide an example of using "max-lines" and "text-overflow"?

Thanks in advance!

**Comment by daohoangson** [comment]
You can do something like this https://github.com/daohoangson/flutter_widget_from_html/issues/706#issuecomment-1022784038

```html
<div style="max-lines: 3; text-overflow: ellipsis">text goes here</div>
```

**Comment by ahmdmau** [comment]
Thanks for reply!

I mean the maximum number of lines for the widget. On some pages, I don't want to display the full content; I just want to show around three lines.

**Comment by daohoangson** [comment]
You need to use both the CSS (as above) and something like a `SizedBox+ClipRect` to control this because the HTML may contain unexpected contents which is impossible to measure in "lines of text", for example an IFRAME of embedded YouTube video.

**Comment by ahmdmau** [comment]
Like wrapping the HTML Widget with SizedBox right?

**Comment by ahmdmau** [comment]
`return SizedBox(
      height: 48,
      child: ClipRect(
        child: HtmlWidget(
          '<div style="max-lines: 3; text-overflow: ellipsis">${content.escapedString()}</div>',
        ),
      ),
    )`
    
    With this code, i got bottom overflowed

**Comment by ahmdmau** [comment]
```
return SizedBox(
      height: 48,
      child: ClipRect(
        child: HtmlWidget(
          '<div style="max-lines: 3; text-overflow: ellipsis">${content.escapedString()}</div>',
        ),
      ),
    )
```

with this code, i got bottom overflow

**Comment by tylertzeyang** [comment]
@ahmdmau Hi, may I know how do you solve it?
