### ISSUE TITLE
Running setState() does not update content

### ISSUE THREAD

**Issue by edisonpagtakhan** [daohoangson/flutter_widget_from_html#118]
Calling setState() after changing the html string passed to `HtmlWidget` does not update the content

**Comment by daohoangson** [comment]
You need to update the key if you change any props of the `HtmlWidget`. Something like this should work:

```dart
HtmlWidget(
    html,
    key: ValueKey(html),
)
```

This is required because `HtmlWidget` is a `StatefulWidget`.

**Comment by daohoangson** [comment]
Duplicated of https://github.com/daohoangson/flutter_widget_from_html/issues/100.

**Comment by edisonpagtakhan** [comment]
It worked! Thank you :) Closing this issue now.
