### ISSUE TITLE
It render zero width space to normal space

### ISSUE THREAD

**Issue by Lykeosovandara** [daohoangson/flutter_widget_from_html#119]
When i add zero width space and it render it to space

**Comment by daohoangson** [comment]
Can you share your html?

**Comment by Lykeosovandara** [comment]
Yes here it is
~~~html
<p>I​Like​Playing​football​​game</p>
~~~
There is a zero white space in each word

**Comment by daohoangson** [comment]
I have just released `v0.2.4+4` with a fix for this. Can you upgrade and try again? Sorry for the inconvenience.

**Comment by Lykeosovandara** [comment]
Ok Thank You
