### ISSUE TITLE
Full screen Button hidden/not working for Embedded Vimeo video (iFrame) on Android Device only.

### ISSUE THREAD

**Issue by brt-manishp** [daohoangson/flutter_widget_from_html#120]
Following is the github link to demo project
https://github.com/brt-manishp/flutter_demo_video.git

dependencies:
  flutter_widget_from_html: ^0.2.4+4

I have integrated above library in project and I am not able to switch to full screen for videos embedded in iframe.

I have tested in Nexus 5, samsung j7, etc but not working on any of the devices

Please have a look at it and help with with issue

Thank you in advance and regards

**Comment by daohoangson** [comment]
This is a duplicated of #35.

> I'm aware of this issue. Unfortunately, this seems to be the case with all implementations of this kind. e.g. if you use React Native and render a Web View of YouTube, it won't be able to go fullscreen.

**Comment by brt-manishp** [comment]
Okay.. Can you help me with any work around. Twiking internal library code would help ?

Thank you.

**Comment by brt-manishp** [comment]
> This is a duplicated of #35.
> 
> > I'm aware of this issue. Unfortunately, this seems to be the case with all implementations of this kind. e.g. if you use React Native and render a Web View of YouTube, it won't be able to go fullscreen.

Okay.. Can you help me with any work around. Twiking internal library code would help ?

Thank you.

**Comment by daohoangson** [comment]
I don't think there is any way to work around this issue at this moment. Sorry.

**Comment by brt-manishp** [comment]
above library also have its own Video Player. so does it have quality controller like switching between (1080p, 720p, 350p) considering separate links

**Comment by daohoangson** [comment]
Which "above library" were you talking about?

**Comment by brt-manishp** [comment]
> Which "above library" were you talking about?
flutter_widget_from_html: ^0.2.4+4

**Comment by daohoangson** [comment]
Yes, if you use html5 `VIDEO` tag, it will render video player. However, it's impossible to do that for YouTube iframe since the metadata is not available at the time of rendering.
