### ISSUE TITLE
Big God, hello, there is a serious problem here, please read

### ISSUE THREAD

**Issue by WangYiOS** [daohoangson/flutter_widget_from_html#1200]
God, hello, the question is as follows:
flutter version is 3.16.0, install flutter_widget_from_html 0.14.11, iOS will not run, please know, if there is time, fix it, because flutter 3.16.0 will be used by more and more people, thank you, thank you for reading

======

大神，你好，问题如下： 
flutter版本是3.16.0，安装flutter_widget_from_html 0.14.11，iOS无法运行起来，请知晓，有时间的话，修复下，因为flutter 3.16.0使用的人会越来越多，谢谢，感谢阅读

**Comment by WangYiOS** [comment]
Big boss, I found the problem, it is my side of the problem, need to change the iOS and Andorid configuration, as shown in the following picture, just change!
=========
大佬，找到问题了，是我这边的问题，需要更改iOS和Andorid的配置，如下图所示，更改即可！

![Snip20240301_9](https://github.com/daohoangson/flutter_widget_from_html/assets/17872114/d32e4239-448f-4e29-8cbb-6a5775ed8244)


![Snip20240301_10](https://github.com/daohoangson/flutter_widget_from_html/assets/17872114/f8fcbfee-ce9a-4dff-a1b2-a943814eabd0)

**Comment by RobotJohns** [comment]
666

**Comment by daohoangson** [comment]
This looks like the issue has been resolved. I'm closing now.
