### ISSUE TITLE
Replacing the font typeface

### ISSUE THREAD

**Issue by MariyaVik** [daohoangson/flutter_widget_from_html#1202]
I want to replace the font typeface, but my code doesn't work

```
    HtmlWidget(
        program.programData.description,
        customStylesBuilder: (element) {
          if (element.attributes.containsKey('style')) {
            {
              print(element.attributes['style'].runtimeType);
              if (element.attributes['style']!.contains('font-family')) {
                return {
                  'font-family': 'Montserrat',
                };
              }
            }
          }
          return null;
        },
      );
```

How can I change an existing text style?

<details> 
    <summary>Flutter doctor -v</summary>
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.19045.4046], locale ru-RU)
• Flutter version 3.19.1 on channel stable at C:\flutter
 • Upstream repository https://github.com/flutter/flutter.git
 • Framework revision abb292a07e (13 days ago), 2024-02-20 14:35:05 -0800
 • Engine revision 04817c99c9
 • Dart version 3.3.0
 • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\1\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.87.0)
    • VS Code at C:\Users\1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 122.0.2365.66

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
    </details>

**Comment by daohoangson** [comment]
The inline style has higher priority than `customStylesBuilder` so changing `font-family` in that callback won't work. If you want to ignore inline font or replace it to some other font, you need a custom `WidgetFactory` and override the `parseStyle` method. Something like this:

```dart
class MyWidgetFactory extends WidgetFactory {
  @override
  void parseStyle(BuildTree tree, css.Declaration style) {
    if (style.property == 'font-family') {
      // ignore
      return;
    }

    return super.parseStyle(tree, style);
  }
}
```
