### ISSUE TITLE
copy bug

### ISSUE THREAD

**Issue by SinglTown** [daohoangson/flutter_widget_from_html#1224]
When the `renderMode` of `HtmlWidget` is set to `ListViewMode`, and the `customWidgetBuilder` returns `HtmlWidget` as well, the content of the `HtmlWidget` cannot be copied simultaneously with the content of the `HtmlWidget` within `customWidgetBuilder`. There's a screencast available for reference.

```dart
      return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: SelectionArea(
          child: HtmlWidget(
            content,
            customStylesBuilder: (dom.Element element){
              return {};
            },
            renderMode: const ListViewMode(
                shrinkWrap: true,
                physics: NeverScrollableScrollPhysics(),
            ),
            customWidgetBuilder: (element){
              if(element.localName == 'span'){
                return const HtmlWidget(
                  '测试用的HtmlWidget组件',
                );
              }
              return null;
            },
          ),
        )
    );
```

https://github.com/daohoangson/flutter_widget_from_html/assets/20661818/74b14680-f527-4d11-b9cd-85377936effc

**Comment by daohoangson** [comment]
It appears that the inner text has a `_ScrollableSelectionContainerDelegate` as the selection registrar. Which is different from the `_SelectableRegionContainerDelegate` from outside. So they cannot be selected together...

I'll take a closer look.

**Comment by daohoangson** [comment]
The latest version has a fix for this, please try upgrading and let me know whether it works for you.

**Comment by SinglTown** [comment]
It works, Thank you.

**Comment by daohoangson** [comment]
That's great to hear. I'm closing this issue now.
