### ISSUE TITLE
iOS build issue on Flutter 3.19.6

### ISSUE THREAD

**Issue by alexgularte** [daohoangson/flutter_widget_from_html#1228]
I'm facing the following issue when building for iOS:

Running pod install...
Running Xcode build...
Xcode build done.                                           291.0s
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.

Could not build the application for the simulator.
Error launching application on iPad Air (5th generation).

Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (8 days ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

**Comment by daohoangson** [comment]
Try adding `chewie: ^1.8.0` as a dependency. Your app probably has some conflict with chewie latest version so it couldn't be used.

Alternatively, switch from `flutter_widget_from_html` to `flutter_widget_from_html_core` if you don't need VIDEO tag support.

**Comment by alexgularte** [comment]
Great, I replaced to flutter_widget_from_html_core and it worked perfectly.

Thank you!!!
