### ISSUE TITLE
v0.2.4+4 broken build?

### ISSUE THREAD

**Issue by mikeCalvir** [daohoangson/flutter_widget_from_html#123]
I have resolved this by specifying 0.2.4+3 in my pubspec file, but previously I was getting several compile errors within this package (from memory the first was complaining about unknown symbol "bodyPadding").

I had previously tried 
- flutter clean
- Removed all dependencies, flutter pub get, put them back then flutter pub get again

But the only thing that has solved the issue has been to go back to the previous version.

However, perhaps this was some kind of problem with a local corruption, I do not know, but I thought I'd mention the issue I had here in case it becomes useful to somebody.

**Comment by daohoangson** [comment]
Hmm, what is your Flutter version / channel? Output of `flutter doctor -v` should be useful here. 

Can you create a new app, just include the package and build it? I tried that and it built fine.

**Comment by mikeCalvir** [comment]
Thanks for this response @daohoangson, I will definitely try this and get back to you (probably early next week sometime).
Hopefully it was a temporary corruption issue but it was odd that "flutter clean" didn't resolve it.

**Comment by daohoangson** [comment]
Make sure you don't use Flutter 1.12, the latest version of this package doesn't work with it yet. Use the 0.3 rc maybe.

**Comment by xalabax** [comment]
Flutter version 1.12.13+hotfix.5, 
flutter_widget_from_html: ^0.2.4+4
Not build too.

Compiler message:
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by xalabax** [comment]
How to add 0.3 rc to pubspec.yaml?

**Comment by daohoangson** [comment]
Just put something like `flutter_widget_from_html: ^0.3.0-rc` and it should work. @xalabax

**Comment by daohoangson** [comment]
Have you figured it out @mikeCalvir?

**Comment by mikeCalvir** [comment]
Hi, sorry I didn't get straight back!
It was resolved at the time, looking at the project now it has:
```
  flutter_widget_from_html: 
  flutter_widget_from_html_core: 
```
Flutter is 1.12.13 hotfix 5, and all looks fine.
