### ISSUE TITLE
Set `style.height` to any appropriate value to stop this message.

### ISSUE THREAD

**Issue by AnkitFlutterDev** [daohoangson/flutter_widget_from_html#1245]
i am creating admin panel using flutter web,
whenever i applied this html content : '''<p>Get started at <a href="https://flutter.dev">https://flutter.dev</a> today.</p>

<p>Flutter is Google's mobile UI framework for crafting high-quality native interfaces on iOS and Android in record time. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.</p>

<iframe src="https://www.youtube.com/embed/qU2d9kZMIr4" ></iframe>
</p>

'''

i got this warning : 
Height of Platform View type: [WebViewState#409a5(lifecycle state: created)#888408485] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [WebViewState#409a5(lifecycle state: created)#888408485] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

if i removed this <iframe src="https://www.youtube.com/embed/qU2d9kZMIr4" ></iframe> no warning

plz help me as soon as possible

**Comment by At738343** [comment]
this will fixed in next release? or @daohoangson you suggesting me change something in my code?i can't undesrstand ur suggestion 
https://github.com/daohoangson/flutter_widget_from_html/commit/abd4b020674e0dc1f06f78206c882c29a5e0d46e

**Comment by daohoangson** [comment]
This will be fixed in the next release.

**Comment by At738343** [comment]
thanks man for ur fast reply

**Comment by daohoangson** [comment]
The latest version (`v0.15.1`) has been released with the fix for this. Please try upgrading and let me know whether it works for you.

**Comment by AnkitFlutterDev** [comment]
it's working fine now, Thanks.

**Comment by daohoangson** [comment]
That's great to hear. I'm closing this issue now.
