### ISSUE TITLE
Can't handle zero size image. Causing errors and html widget cannot scroll.

### ISSUE THREAD

**Issue by freesignapp** [daohoangson/flutter_widget_from_html#1260]
## Steps to Reproduce
For an image with 0 size:
<img style='width:0;height:0' ...>

It causes errors and html widget cannot scroll down.

<details>
  <summary>HTML</summary>

```html
<table cellpadding='0' cellspacing='0' border='0' width='100%'>
            <tbody>
               <tr>
                  <td align='center' style='overflow:hidden;font-size:0;padding:0;margin:0;line-height:0'>

<img style='width:0;height:0' alt='' src='https://ci5.googleusercontent.com/proxy/fStXuzC736py7f0D_e3__AANXKXbA2K2zwrrSt-SqPO13cuGRcBx7yxAbganlRXAlP7rBKu1_jSPWdvER0HiaRtl5xymLNmBEZY28dD-WJUYG-OB5VMAuyDkec7x-USq7w-jmPok_PuPnt6cDgY0LNgT8HY367HhqkuAO96giyMZyhPKNufhQMjgioJdtUgDkd1PDIb3IAG3ysloRpdbR-LAd4WybN4YbJzIcv7c1xr2-GawvU4XgIJ1WPLnQ5EZ8AMT4SBlatav3rbe-APvaloXVKlkiL9_4FPycxhrXrc7d8aaC8JstGH0-a9vXgWDaOwnBCQqk4inOrZ21aN2fUSMQF-rssVbKlCmYCrXLwwql5bVuP3XnVC84sc8g6whNDjfFp5Q1W1lOmJyPxy-zlSiAoDSdeF6M32Dr-JMXeSvvL95fE-y7XV3iQxfsyFziy6AOV6uCiXadwHVP1ih_djCxbc2bZp7Xs_OLOYv-oeeR64145XMAfRaxpLYwL1Hup4ZyFb8_NmBOPBbFnAxRBR8TV8MqfvVbTRf0_nYnNQfyndBT23Dzwud-TxNjZZ1QBBnhgy2bKLjW4bDnDOmWJBslKecqSxmD-MybqIz0QOpRBbl_FA8xlrbSbtHDwD-tI10FKpF1ldNg-_0RvoIiNxrQ1UF-MTjQLjTprCyShH-yT1YtLHRlPLpbCPg9Fpa8EQo3NwWgrmX0noX24pyEPSr7WKLUDdjFtlnE3uS0mroDTkwoB8VwNhyGtoRqjqpwL0NcTujbOv7NHZW=s0-d-e1-ft#https://etrack01.com/track/open/eyJtYWlsbGlzdF9pZCI6IDMwOTg0NzcsICJ0YXNrX2lkIjogIjQ1MTQ1MjgiLCAiZW1haWxfaWQiOiAiMTY2MTMzNjY2NzIwMl8xMDQ0NDNfNTUwMDBfODQzLnNjLTEwXzlfNDBfMTY0LWluYm91bmQzNiR4bXl4a2pAZ21haWwuY29tIiwgInNpZ24iOiAiZGFiNTM2MWNhNmE0YmRkZjU0NmM1NjJiMTg3YTEwMWYiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIyMjU3MzM0MCIsICJ0cmFja19kb21haW4iOiAiZXRyYWNrMDEuY29tIiwgInJlYWxfdHlwZSI6ICIiLCAibmV0ZWFzZSI6ICJmYWxzZSIsICJvdXRfaXAiOiAiMTA2Ljc1LjExNS4yMzEiLCAiY29udGVudF90eXBlIjogMywgInVzZXJfaWQiOiAxMDQ0NDMsICJvdmVyc2VhcyI6ICJmYWxzZSIsICJjYXRlZ29yeV9pZCI6IDE3OTcxOH0=.gif'></td>
               </tr>
            </tbody>
         </table>            
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

## Actual results

`
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
BoxConstraints has NaN values in minWidth and maxWidth.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, h=0.0; NOT NORMALIZED)

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

The following RenderObject was being processed when the exception was fired: _RenderCssSizing#e5ae5 relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: CssSizing ← WidgetPlaceholder ← _AutoScaleInlineWidget ← Semantics ← _WidgetSpanParentData
    ← RichText ← Builder ← Center ← Align ← WidgetPlaceholder ← HtmlTableCell ← HtmlTable ← ⋯
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=1095.0, 0.0<=h<=Infinity)
  size: MISSING
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderSemanticsAnnotations#e3044 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderImage#58e75 NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: file:///opt/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12
Another exception was thrown: Assertion failed: file:///opt/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12
Another exception was thrown: Assertion failed: file:///opt/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12
Another exception was thrown: Assertion failed: file:///opt/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12
Another exception was thrown: Assertion failed: file:///opt/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12

`

**Comment by daohoangson** [comment]
Are these images for tracking purposes? There may be a logic that calculates ratio using width and height values and caused this error I think.

**Comment by freesignapp** [comment]
Yes. The zero size image is widely used in marketing emails for tracking purpose. So it's a must for an html view to handle it, otherwise lots of marketing emails cannot be viewed. Please fix it at your earliest convenience. Thank you!

**Comment by andreymosin** [comment]
Also can't handle zero size iframes

**Comment by daohoangson** [comment]
The latest version (`v0.15.1`) has been released with the fix for this. Please try upgrading and let me know whether it works for you.

**Comment by freesignapp** [comment]
I tested the latest build (v0.15.1) and found the problem has been fixed. Thank you!

**Comment by daohoangson** [comment]
Glad to hear that, I'm closing this now.
