### ISSUE TITLE
WebAssembly Compilation Error due to dart:html Import in wakelock_web

### ISSUE THREAD

**Issue by bivu029** [daohoangson/flutter_widget_from_html#1264]
### I'm encountering an issue when building my Flutter project for the web using WebAssembly (Wasm). The build fails due to the wakelock_web package, which imports dart:html. This import is not compatible with the Wasm target.

**Steps to Reproduce:**

Create a new Flutter project.
Add the flutter_widget_from_html package to pubspec.yaml.
Attempt to build the project for the web using the command: flutter build web --wasm.
Expected Behavior:
The project should build successfully for the web with Wasm.
Actual Behavior:
The build fails with the following errors:
`Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^

.....
.....

Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^
`
Flutter Doctor Output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4412], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
**Additional Context:**
The issue appears to be due to the wakelock_web package, which is imported in flutter_widget_from_html. This package imports dart:html, which is not compatible with the Wasm compilation target.

Dart has shifted to new interop solutions for WebAssembly:

package:web replaces dart:html and other web libraries.
**Suggested Solution:**
To make the flutter_widget_from_html package compatible with Wasm, consider migrating from dart:html and package:js to the new interop solutions provided by Dart. Here are the steps:

Replace dart:html with package:web.
Replace package:js with [dart:js_interop](https://dart.dev/interop/js-interop) or dart:js_interop_unsafe.
For more information, refer to the JS interop documentation and the package
migration guide.

**Comment by daohoangson** [comment]
Make sure you are using the latest version of all dependencies. Since #1250, the demo app has been deployed as wasm.

**Comment by bivu029** [comment]
yeah i am  using the latest version of all dependencies. when i  removed flutter_widget_from_html: ^0.15.0 package then  flutter build web --wasm command working perfectly fine

**Comment by daohoangson** [comment]
I think you are using an older version of `chewie`. The recent versions switch to `wakelock_plus` already. Take a look at this lock file https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/pubspec.lock

**Comment by bivu029** [comment]
**You are absolutely right**
I checked my pubspec.lock file and found that the chewie package was indeed an older version. After deleting the chewie package, running flutter clean, and then flutter pub get, the issue is resolved. The flutter build web --wasm command is now working perfectly fine.
