### ISSUE TITLE
More than one New line <br> is not shown.

### ISSUE THREAD

**Issue by AnithaB05** [daohoangson/flutter_widget_from_html#1285]
## Steps to Reproduce

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/140070723/a8e5709e-b685-4a08-9b7b-576d99de6ff1)

Flutter usage:

Padding(
                    padding: EdgeInsets.all(16.0),
                    child: HtmlWidget(htmlText),
                  ),

## Expected results

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/140070723/41ba8297-9415-4b82-8b3b-951ad5dd1375)

## Actual results

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/140070723/7a10ca6e-6986-4aea-ac3c-ffa14a231ed0)

**Comment by daohoangson** [comment]
Which version of this package are you using?

**Comment by daohoangson** [comment]
I cannot reproduce this bug, as you can see here https://try.fwfh.dev/?id=f34d1086558fbf0756094f91b00a22ed

<img width="1478" alt="Screenshot 2024-07-06 at 22 29 46" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/586c211b-838e-4364-bbf6-6d346b4a515e">
