### ISSUE TITLE
It give me a huge APK after used this package

### ISSUE THREAD

**Issue by lucasjinreal** [daohoangson/flutter_widget_from_html#1297]
1M + added when import this package, anyway to reduce it?

**Comment by daohoangson** [comment]
You can use `flutter_widget_from_html_core` package if you don't need to support multimedia tags like AUDIO, IFRAME, VIDEO etc.

**Comment by lucasjinreal** [comment]
Does the API same?

**Comment by daohoangson** [comment]
Yes. Same API, just with fewer supported HTML tags.
