### ISSUE TITLE
Monitor long press event of "a" tag

### ISSUE THREAD

**Issue by hwh97** [daohoangson/flutter_widget_from_html#130]
Hello, I would like to ask how to monitor the long press event of the "a" tag？

**Comment by hwh97** [comment]
I find a way to add listener. is it correct?

 @override
  Iterable<Widget> buildText(BuilderContext bc, Iterable<Widget> _, TextBlock block) {
    final textWidget = super.buildText(bc, _, block);
    return textWidget.map((widget) {
      return GestureDetector(
        onLongPress: () {
          print("long press");
        },
        child: widget,
      );
    }).toList();
  }

**Comment by daohoangson** [comment]
There are a few days to do this depending on your use case. Normally I would override `buildGestureDetectors`.

**Comment by hwh97** [comment]
Thanks for your reply, i try overide `buildGestureDetectors` like this,  but i can't get any callback with long press.

```
class _CustomWidgetFactory extends WidgetFactory {
  _CustomWidgetFactory(HtmlWidgetConfig config) : super(config);

  @override
  Iterable<Widget> buildGestureDetectors(
      BuilderContext bc, Iterable<Widget> widgets, onTap) {
    return widgets.map((widget) => InkWell(
          child: widget,
          onTap: onTap,
          onLongPress: () {
            print("onLongPress");
          },
        ));
  }
}
```

**Comment by daohoangson** [comment]
Ah, I have just checked the code. `buildGestureDetectors` only works if the `A` tag contains a render block (e.g. a `DIV` or a `P`). If your link is within a text paragraph, it is rendered differently.

What is your specific use case?

**Comment by hwh97** [comment]
It is within a text paragraph. Is there any other way to listen? 
My use case
```
 HtmlWidget(
          """
          <p><br/><a href="https://www.baidu.cn/" isconvert="1" target="_blank">https://www.baidu.cn/</a></p>
          """,
          onTapUrl: (url) {
            print(url);
          },
          hyperlinkColor: Colors.pink,
          factoryBuilder: (config) => _CustomWidgetFactory(config),
),
```

**Comment by daohoangson** [comment]
I have reviewed several approaches for this and it looks like your [first solution](https://github.com/daohoangson/flutter_widget_from_html/issues/130#issuecomment-581164778) is the best one. It will capture long press for the whole paragraph (not just the `A` tag) though.

**Comment by hwh97** [comment]
Ok, Thanks for you help.

**Comment by daohoangson** [comment]
Hi @hwh97,

The builder has been modified a bit and it is now possible to handle any supported gestures (not just on tap). Not sure if you are still in need of this? I can come up with some sample code to capture long press.

**Comment by hwh97** [comment]
I am facing this problem now, can you provide some sample code, thank you. It seems that TextSpan can only accept one recognizer.

**Comment by daohoangson** [comment]
Something like this should work

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

const kHtml = '''
This is <a href="https://flutter.dev">a link</a>.
''';

class HelloWorldScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 130')),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: HtmlWidget(
              kHtml,
              key: UniqueKey(),
              factoryBuilder: () => _WidgetFactory(),
            ),
          ),
        ),
      );
}

class _WidgetFactory extends WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    super.parse(meta);

    if (meta.element.localName == 'a') {
      meta.register(BuildOp(
        onTree: _setupLongPress,
        // the priority is required to make sure
        // the custom op runs after the built-in one
        priority: 9999,
      ));
    }
  }

  void _setupLongPress(BuildMetadata meta, BuildTree tree) {
    for (final bit in tree.bits.toList(growable: false)) {
      _LongPressBit(bit.parent, bit.tsb, () => print('Long press'))
          .insertAfter(bit);
    }
  }
}

class _LongPressBit extends BuildBit<GestureRecognizer, GestureRecognizer> {
  final Function onLongPress;

  _LongPressBit(BuildTree parent, TextStyleBuilder tsb, this.onLongPress)
      : super(parent, tsb);

  @override
  bool get swallowWhitespace => null;

  @override
  GestureRecognizer buildBit(GestureRecognizer recognizer) {
    if (recognizer is TapGestureRecognizer) {
      // keep a copy of the normal tap callback
      final onTap = recognizer.onTap;
      // then unset it from the recognizer
      recognizer.onTap = null;

      // keep track of the down time
      DateTime onTapDown;
      recognizer.onTapDown = (_) => onTapDown = DateTime.now();

      // check tap duration to execute the appropriate callback
      recognizer.onTapUp = (_) {
        if (DateTime.now().difference(onTapDown) < kLongPressTimeout) {
          onTap();
        } else {
          onLongPress();
        }
      };
    }

    return recognizer;
  }

  @override
  BuildBit copyWith({BuildTree parent, TextStyleBuilder tsb}) =>
      _LongPressBit(parent ?? this.parent, tsb ?? this.tsb, onLongPress);
}
```

**Comment by hwh97** [comment]
it worked, thx.

**Comment by casimir** [comment]
This last solution use several deprecated elements in recent versions (tested on `flutter_widget_from_html_core` 0.15.2). What would be a more current solution?

Just for context, my use case is to have a better platform integration by launching a share sheet when long pressing an hyperlink.
