### ISSUE TITLE
specifici iframe is not working on ios

### ISSUE THREAD

**Issue by rodrigocanepa** [daohoangson/flutter_widget_from_html#131]
Thaks a lot for this marvelours library! buy when I try to put this iframe 

<iframe src="http://cdn.voscast.com/player/player.php?host=s1.voscast.com&amp;port=7000&amp;autoplay=true" scrolling="no" allow="autoplay" width="150" height="30" frameborder="0"></iframe>

on ios devices the app doesn't show anything (when I paste the iframe for youtube works) in android there are not problem

**Comment by daohoangson** [comment]
It shows an audio player for me. Can you give more details regarding your setup? e.g. `flutter doctor -v` output. Did you test on real device or the iOS Simulator?

**Comment by daohoangson** [comment]
Hello @rodrigocanepa?
