### ISSUE TITLE
RenderSliver mode error when `html` input is empty

### ISSUE THREAD

**Issue by vanvixi** [daohoangson/flutter_widget_from_html#1320]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```
   HtmlWidget(
      '',
      renderMode: RenderMode.sliverList,
   )
```
</details>

<details>
  <summary>Tesing environment</summary>

```
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (5 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

</details>

## Actual results

A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.

**Comment by daohoangson** [comment]
Thank you for the bug report & also for the PR. `v0.15.2` has been released with the fix.

**Comment by vanvixi** [comment]
@daohoangson 
Good job.
Thank you for created this wonderful lib 🚀🚀🚀
