### ISSUE TITLE
Upgrade versions

### ISSUE THREAD

**Issue by AdelDaniel** [daohoangson/flutter_widget_from_html#1332]
Upgrade Packages, please.

I got this error:

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

|   |-- flutter_widget_from_html 0.15.2
|   |   |-- flutter_widget_from_html_core 0.15.2
|   |   |   |-- csslib...
|   |   |   |-- flutter...
|   |   |   |-- html...

|   |   |   '-- logging...
|   |   |-- fwfh_cached_network_image 0.14.3
|   |   |   |-- cached_network_image...
|   |   |   |-- flutter...
|   |   |   |-- flutter_cache_manager...
|   |   |   '-- flutter_widget_from_html_core...
|   |   |-- fwfh_chewie 0.14.8
|   |   |   |-- chewie 1.0.0
|   |   |   |   |-- wakelock 0.4.0
|   |   |   |   |   |-- wakelock_macos 0.1.0+3
|   |   |   |   |   |   |-- flutter...
|   |   |   |   |   |   |-- flutter_web_plugins...
|   |   |   |   |   |   '-- wakelock_platform_interface...
|   |   |   |   |   |-- wakelock_platform_interface 0.2.1+3
|   |   |   |   |   |   |-- flutter...
|   |   |   |   |   |   '-- meta...
|   |   |   |   |   |-- wakelock_web 0.2.0+3
|   |   |   |   |   |   |-- flutter...
|   |   |   |   |   |   |-- flutter_web_plugins...
|   |   |   |   |   |   |-- js...
|   |   |   |   |   |   '-- wakelock_platform_interface...
|   |   |   |   |   |-- flutter...
|   |   |   |   |   '-- meta...
|   |   |   |   |-- cupertino_icons...
|   |   |   |   |-- flutter...
|   |   |   |   '-- video_player...
|   |   |   |-- flutter...
|   |   |   |-- flutter_widget_from_html_core...
|   |   |   '-- video_player...
|   |   |-- fwfh_just_audio 0.15.2
|   |   |   |-- just_audio 0.9.36
|   |   |   |   |-- audio_session 0.1.18
|   |   |   |   |   |-- flutter...
|   |   |   |   |   |-- flutter_web_plugins...
|   |   |   |   |   |-- meta...
|   |   |   |   |   '-- rxdart...
|   |   |   |   |-- just_audio_platform_interface 4.2.2
|   |   |   |   |   |-- flutter...
|   |   |   |   |   '-- plugin_platform_interface...
|   |   |   |   |-- just_audio_web 0.4.9
|   |   |   |   |   |-- flutter...
|   |   |   |   |   |-- flutter_web_plugins...
|   |   |   |   |   '-- just_audio_platform_interface...
|   |   |   |   |-- async...
|   |   |   |   |-- crypto...
|   |   |   |   |-- flutter...
|   |   |   |   |-- meta...
|   |   |   |   |-- path...
|   |   |   |   |-- path_provider...
|   |   |   |   |-- rxdart...
|   |   |   |   '-- uuid...
|   |   |   |-- flutter...
|   |   |   '-- flutter_widget_from_html_core...
|   |   |-- fwfh_svg 0.8.3
|   |   |   |-- flutter...
|   |   |   |-- flutter_svg...
|   |   |   '-- flutter_widget_from_html_core...
|   |   |-- fwfh_url_launcher 0.9.1
|   |   |   |-- flutter...
|   |   |   |-- flutter_widget_from_html_core...
|   |   |   '-- url_launcher...
|   |   |-- fwfh_webview 0.15.2
|   |   |   |-- flutter...
|   |   |   |-- flutter_widget_from_html_core...
|   |   |   |-- logging...
|   |   |   |-- web...
|   |   |   |-- webview_flutter...
|   |   |   |-- webview_flutter_android...
|   |   |   '-- webview_flutter_wkwebview...
|   |   |-- flutter...
|   |   '-- html...

**Comment by daohoangson** [comment]
You can specify a newer version of `chewie` package as needed. The latest is [v1.8.5](https://pub.dev/packages/chewie/versions/1.8.5) and it should work fine with this package.
