### ISSUE TITLE
Doesn't this plugin support video or audio ? How can I play a music?

### ISSUE THREAD

**Issue by Dorbmon** [daohoangson/flutter_widget_from_html#134]

**Comment by daohoangson** [comment]
This plugin does support html VIDEO tag, just use it in your html as usual:

```html
  <video controls>
    <source src="video.mp4" type="video/mp4">
  </video>
```

**Comment by Dorbmon** [comment]
@daohoangson Thanks for your answer : )

**Comment by daohoangson** [comment]
Since this issue has been resolved, I'm closing it now. Feel free to reopen it or create a new one if you run into any other issue.
