### ISSUE TITLE
Execution failed for task ':video_player_android:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by emircanerkul** [daohoangson/flutter_widget_from_html#1344]
error: warnings found and -Werror specified

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Used 0.15.2 also tried with 0.15.0 but same error.

**Comment by emircanerkul** [comment]
```
flutter.ndkVersion=27.0.12077973
flutter.targetSdkVersion=34
flutter.compileSdkVersion=34

distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip

    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.2.2" apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.3.15" apply false
    id "com.google.firebase.firebase-perf" version "1.4.1" apply false
    id "com.google.firebase.crashlytics" version "2.8.1" apply false
    // END: FlutterFire Configuration
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
```

**Comment by emircanerkul** [comment]
HEEEY Anyone there?

**Comment by daohoangson** [comment]
I think it may be a conflict with some other Android dependency. If you don't need VIDEO tag support, switching to `flutter_widget_from_html_core` should help. If you do want to render videos, you probably need to provide the entire build log. And the pubspec in full too.

**Comment by emircanerkul** [comment]
Thank you flutter_widget_from_html_core worked, and it was enough for me.
