### ISSUE TITLE
YouTube videos should not be played in background

### ISSUE THREAD

**Issue by JanNovakFRI** [daohoangson/flutter_widget_from_html#135]
Hello,

is it possible to prevent video (in iframe) from playing in background.

Thanks in advance
Jan

**Comment by daohoangson** [comment]
Probably related to #37. Have you tried using HtmlWidget with `unsupportedWebViewWorkaroundForIssue37=true`?

**Comment by JanNovakFRI** [comment]
Thank you. Setting this flag did solve the problem.

**Comment by JinHwanOh** [comment]
Hi, I don't see unsupportedWebViewWorkaroundForIssue37 option on HtmlWidget. What's the workaround? I'm having an issue where the Youtube video (audio) keeps playing when navigated to another screen.
