### ISSUE TITLE
The long height image display incorrect in iOS

### ISSUE THREAD

**Issue by AnhToof** [daohoangson/flutter_widget_from_html#1353]
Hello, i'm facing issue when display the long height image on iOS. It's auto scale
<img src=\"https://i.postimg.cc/9QJ04GZq/Simulator-Screenshot-i-Phone-15-Pro-Max-2024-11-07-at-09-05-06.png\" class=\"img-chap-item\" />

Result:
![simulator_screenshot_726A01AC-1E3B-4E68-BB3B-52C1EDEEDFC3](https://github.com/user-attachments/assets/754edae3-dba1-4f9a-9f11-a9dd17eb43ce)

flutter_widget_from_html_core: ^0.15.2
Flutter v3.22.2

Any solution for this?
Thank in advanced

**Comment by daohoangson** [comment]
How did you render the `HtmlWidget`? You may need to put it inside something scrollable for this kind of contents.

**Comment by AnhToof** [comment]
Well, I just found that it's iOS issue
https://github.com/flutter/flutter/issues/158232
