### ISSUE TITLE
Outdated dependency: webview_flutter_android

### ISSUE THREAD

**Issue by mauriziopinotti** [daohoangson/flutter_widget_from_html#1359]
## Steps to Reproduce

Create a new project and add the following dependencies:
```yaml
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
```

Result:

```console
Because flutter_widget_from_html >=0.15.2 depends on fwfh_webview ^0.15.2 which depends on webview_flutter_android ^3.10.0, flutter_widget_from_html >=0.15.2 requires webview_flutter_android ^3.10.0.
And because webview_flutter >=4.10.0 depends on webview_flutter_android ^4.0.0, flutter_widget_from_html >=0.15.2 is incompatible with webview_flutter >=4.10.0.
So, because easyhour_app depends on both webview_flutter ^4.10.0 and flutter_widget_from_html ^0.15.2, version solving failed.
```

## Expected results

Projects should be able to use the latest versions, namely webview_flutter_android 4.x.

## Actual results

fwfh_webview has a dependency on webview_flutter_android 3.x.

**Comment by daohoangson** [comment]
A new version `0.15.3` has been released to support `webview_flutter_android@4`, please try upgrading and see whether it works for you.

**Comment by mauriziopinotti** [comment]
> A new version `0.15.3` has been released to support `webview_flutter_android@4`, please try upgrading and see whether it works for you.

Thanks, it works like a charm!
