### ISSUE TITLE
The current Flutter SDK version is 1.12.13.

### ISSUE THREAD

**Issue by dashenxiwo** [daohoangson/flutter_widget_from_html#136]
The current Flutter SDK version is 1.12.13.
Because cloud_player depends on flutter_widget_from_html >=0.3.2+1 which requires Flutter SDK version >=1.12.13+hotfix.5 <2.0.0, version solving failed.
pub get failed (1; Because cloud_player depends on flutter_widget_from_html >=0.3.2+1 which requires Flutter SDK version >=1.12.13+hotfix.5 <2.0.0, version solving failed.)
exit code 1

**Comment by daohoangson** [comment]
Can you try upgrading Flutter to the latest stable? One of the dependencies of this plugin (`webview_flutter`) requires the hotfix version.

If you don't need the webview support, you can use the core plugin instead. https://pub.dev/packages/flutter_widget_from_html_core
