### ISSUE TITLE
My video doesn't appear

### ISSUE THREAD

**Issue by rudineizilio** [daohoangson/flutter_widget_from_html#139]
I did all the steps indicated in the link (**https://github.com/daohoangson/flutter_widget_from_html/blob/master/packages/example/lib/screens/iframe.dart**) and even then my video did not appear.
Would you help me?

**Comment by daohoangson** [comment]
Can you share your HTML and your Dart code rendering the `HtmlWidget`? Output of `flutter doctor -v` would be helpful too.

**Comment by rudineizilio** [comment]
Hello, everything went well. I made some adjustments to my source code and it worked.
Thanks

**Comment by daohoangson** [comment]
Awesome 🎉
