### ISSUE TITLE
Is it possible to style the background color or the splash color (color when clicked on) on pieces of text?

### ISSUE THREAD

**Issue by victor-baxan** [daohoangson/flutter_widget_from_html#151]
I would like to display various pieces of text with extra styling (mentioned in the title).

For the background color part, I've only managed to replace the given piece of text with a `WidgetSpan`, containing a `RichText`, but this is still not 100% accurate, since this widget doesn't stay in line if it spans across multiple rows:
![image](https://user-images.githubusercontent.com/5735279/78549044-6653de80-780a-11ea-9192-c2d3335e213d.png)

For the splash color part, for example when tapping on links, is it possible to configure this at all?
I could also replace this with a `WidgetSpan`, but there is again the problem of the text not staying in line with the text surrounding it when it is long.

Is there a better way of inserting text spans and customizing them?
Thank you.

**Comment by daohoangson** [comment]
For background color, you should be able to use `background-color` inline style. It will be line wrapped properly.

```html
<p>
  Lorem ipsum dolor sit amet,
  <span style="background-color: #f00">
    consectetur adipiscing elit.
    Mauris blandit urna in leo interdum, ut ornare ante efficitur.
    Quisque ullamcorper mattis euismod.
    Nam libero eros, laoreet vitae ultrices sit amet, eleifend id lorem.
    Aliquam aliquet sit amet magna dictum finibus.
    Fusce posuere neque eu turpis volutpat, sit amet ornare dolor tristique.
  </span>
  Vivamus sit amet nibh suscipit, volutpat quam quis, lacinia mi.
  In hac habitasse platea dictumst.
  Morbi et dolor sit amet augue posuere volutpat eu vel augue.
  Proin imperdiet erat vitae suscipit consequat.
  Sed porta lorem at lobortis dignissim.
  Vivamus sem mi, tristique et ipsum id, iaculis lacinia purus.
</p>
```

![Simulator Screen Shot - iPhone 11 - 2020-04-06 at 21 49 15](https://user-images.githubusercontent.com/239336/78571526-7db5ba80-7850-11ea-9f78-fbc7218b1d2f.png)

For the splash color, I'm not sure it's possible...

**Comment by victor-baxan** [comment]
When the tag is a 'span', then yes - inline styles would work. What if I want to have the same effect off of a different tag? For example 'code', like in the example screenshot.

**Comment by daohoangson** [comment]
If you change my HTML from `<p>` to `<code>`, it will be styled the same way. It will display differently though because CODE won't line wrap (it was put in a scroll view). Basically for background color, Flutter has built-in support in `TextStyle` so all you have to do set it `style.copyWith(background: Paint()..color = Colors.red)`. 

For your use case, I think you don't need `WidgetSpan` for the background.

**Comment by victor-baxan** [comment]
OK, I got it. The thing here is that there are two different kind of `<code>` tags in my input - one which is standalone, like in my example, and a second one, which is embedded in a `<pre>` tag - to have preformatted code blocks.

For the latter, I am using code syntax highlighting as well, plus different themes, this is why I have to use a different widget entirely, which suits me, because that has to be an individual widget anyway and not be displayed inline.

For the former though, I should have it inline and line wrap.

If it's not possible to distinguish between these two cases, then I think I'll just have to live with it.

Anyway, many thanks for your feedback.

**Comment by daohoangson** [comment]
Hmm, you can put `<code>` inside `<pre>`? I have always thought it is plain text only...

You can check `meta.parents` to detect whether the current dom element is within another. Doing that is error prone though, so if your app does not specifically require that then just let it be 😁

**Comment by victor-baxan** [comment]
I already managed to distinguish between the two cases in my code, but the underlying handling of the `<code>` tag lets me use a `WidgetSpan` at best, in order to achieve custom styling of this piece of text.
It doesn't line wrap of course if it is long, because it still isn't inserting `TextSpan`s directly into the existing text, but I'll just let it be ;)
