### ISSUE TITLE
iframe size not working

### ISSUE THREAD

**Issue by Maclaon** [daohoangson/flutter_widget_from_html#158]
```
static const kHtml = """
  <iframe src="https://www.bilibili.com/blackboard/html5mobileplayer.html?aid=540142790&bvid=BV19i4y1b79H&cid=176097342&page=1" width="320" height="240"> </iframe>
  """;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(discover.title),
          centerTitle: true,
        ),
        backgroundColor: Color.fromRGBO(244, 245, 245, 1.0),
        body: SingleChildScrollView(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            AspectRatio(
                aspectRatio: 624 / 351,
                child: HtmlWidget(
                  kHtml,
                  webView: true,
                  webViewJs: true,
                )),
          ],
        )));
  }
```
The video can be shown, but its size is not working!

**Comment by Maclaon** [comment]
@daohoangson hi~ can u spare sometime to see this issue? i appreciate it~

**Comment by daohoangson** [comment]
What do you mean iframe size not working? Since you are putting the `HtmlWidget` within an `AspectRatio`, the web view won't be able to resize itself properly. Have you tried removing the aspect ratio?

In my testing, it seems to work well without `AspectRatio`:

![Simulator Screen Shot - iPhone 11 - 2020-04-13 at 23 16 54](https://user-images.githubusercontent.com/239336/79137420-e4048500-7ddc-11ea-94f7-c748e5d48883.png)

**Comment by Maclaon** [comment]
```
static const kHtml = """
  <iframe src="https://www.bilibili.com/blackboard/html5mobileplayer.html?aid=540142790&bvid=BV19i4y1b79H&cid=176097342&page=1" width="320" height="240"> </iframe>
  """;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          // title: Text(discover.title),
          centerTitle: true,
        ),
        backgroundColor: Color.fromRGBO(244, 245, 245, 1.0),
        body: SingleChildScrollView(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            HtmlWidget(
                  kHtml,
                  webView: true,
                  webViewJs: true,
                ),
          ],
        )));
  }
```

When i remove `AspectRatio `, it is still not working!  i run it on my real android device. 
![S00414-225348](https://user-images.githubusercontent.com/5398475/79239786-8e46e000-7ea3-11ea-872a-0acd6adbdcbe.jpg)
![S00414-225030](https://user-images.githubusercontent.com/5398475/79239962-c3533280-7ea3-11ea-9ad0-caa29701b65f.jpg)

when i test it on a simulator, it is still the same issue! can u post your entire code? i appreciate it!

**Comment by Maclaon** [comment]
I set the `width` and `height` of that `iframe`, but its internal video cover can not be sized! it is werid!
```
<iframe src="" width="320" height="240"> 
```
IFRAME via WebView. Available configurations：
+ If the IFRAME has no `width` and `height` attributes, the web view will be rendered initially in a 16:9 box and automatically resize itself afterwards.

**Comment by daohoangson** [comment]
This is the full code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

const kHtml = """
<iframe src="https://www.bilibili.com/blackboard/html5mobileplayer.html?aid=540142790&bvid=BV19i4y1b79H&cid=176097342&page=1" width="320" height="240"> </iframe>
""";

void main() => runApp(MaterialApp(home: Scaffold(body: Home())));

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) => SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            HtmlWidget(
              kHtml,
              webView: true,
              webViewJs: true,
            ),
          ],
        ),
      );
}
```

Screenshot on a real device:

![photo_2020-04-15 09 58 58](https://user-images.githubusercontent.com/239336/79294209-cf6cdd80-7eff-11ea-9893-906de26701c3.jpeg)

> If the IFRAME has no width and height attributes, the web view will be rendered initially in a 16:9 box and automatically resize itself afterwards.

This is true. Because your IFRAME html has both `width` and `height` attributes, auto resize won't activate and the webview will have a fixed aspect ratio of `1.3333` (it was `320 / 240`).

> but its internal video cover can not be sized! it is werid!

The video shows up correctly on my device but it didn't on yours. This is probably a problem with that specific web page, can you test with a different URL? If the webpage is yours, try changing the CSS a bit. The webviews render things differently between OSes and versions.

**Comment by daohoangson** [comment]
Oh, I took another look into my screenshot and realized it didn't work. So maybe this webpage doesn't work on Android?

**Comment by Victor116** [comment]
@override
  Widget build( BuildContext context ){
    double widgthScreen = MediaQuery.of(context).size.width;
    double heightScreen = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Container(
        width: widgthScreen * 1,
        height: heightScreen * 99,
        child: HtmlWidget(
           """ <iframe src="https://consumelocalchiapas.com/" height="auto" width="auto"></iframe> """,
          webView: true,
        )
      )
    );
  }

**Comment by Victor116** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class ConsumeLocalChiapasPage extends StatefulWidget{
  @override
  ConsumeLocalChiapasPageState createState() => new ConsumeLocalChiapasPageState();
}

class ConsumeLocalChiapasPageState extends State<ConsumeLocalChiapasPage>{

  @override
  Widget build( BuildContext context ){
    double widgthScreen = MediaQuery.of(context).size.width;
    double heightScreen = MediaQuery.of(context).size.height;

    return Scaffold(
      body: Container(
        width: widgthScreen * 1,
        height: heightScreen * 95,
        child: HtmlWidget(
          """ <iframe src="https://consumelocalchiapas.com/" height="auto" width="auto"></iframe> """,
          webView: true,
        )
      )
    );
  }
}

**Comment by daohoangson** [comment]
What is your problem @Victor116 ?

**Comment by Maclaon** [comment]
```
 <iframe src="https://xbeibeix.com/api/bilibili/biliplayer/?url=BV19i4y1b79H" autoplay="true"
             allowfullscreen="allowfullscreen" width="100%" height="500" scrolling="no" frameborder="0" sandbox="allow-top-navigation allow-same-origin allow-forms allow-scripts">
             </iframe>
```
i agree with your conclusion. it showed the correct size of a video when i used anther `html`. thank u, buddy!

**Comment by daohoangson** [comment]
That's great! @Maclaon
