### ISSUE TITLE
Is it possible to make bullet in list bigger?

### ISSUE THREAD

**Issue by fryette** [daohoangson/flutter_widget_from_html#166]
Is it possible to make a bullet in the list bigger?

     <ul>
            <li><li>
     <ul>

**Comment by daohoangson** [comment]
No, the bullet is rendered with the same font size of the `<li></li>`. You can increase font size of the entire `<ul></ul>` though, it will make the bullet larger with the text.

Another option is to use a custom `WidgetFactory` and override `getListStyleMarker`. You will be able to use a different character for the bullets but they will be still in the same font size.

**Comment by fryette** [comment]
thanks, closed!
