### ISSUE TITLE
in version 0.3.3, the problem still exists.

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#170]
#159 Sorry, in version 0.3.3, the problem still exists.

**Comment by daohoangson** [comment]
This is expected because the fix is only available in the 0.4.0 rc. You don't want to use the rc version in your app?

**Comment by dvzhou** [comment]
I don't know if this problem will be fixed in a later version, because I want to keep the control up to date.

**Comment by daohoangson** [comment]
That's a good point.

I have released `0.3.3+2` with the fix for this so you should be able to use the stable version without issue.

**Comment by dvzhou** [comment]
Thank you for your support. Thank you very much.
