### ISSUE TITLE
Table tags not rendering 

### ISSUE THREAD

**Issue by ragu-swaminathan** [daohoangson/flutter_widget_from_html#171]
I could see the below set of tag is not getting rendered in HTML widget. However it gets rendered in browser. 

<center>
<table border="1" >
		<tr>
			<th style="padding: 6px;padding-left: 3px;color:white;background-color:#9472af;border:  2px solid white;">&nbsp;Age<br />
			&nbsp;</th>
			<th style="padding: 6px;padding-left: 3px;color:white;background-color:#9472af;border:  2px solid white;">&nbsp;Age 2</th>
		</tr>
		<tr>
			<td style="padding: 6px;padding-left: 3px;background-color:#ece0f4;border:  2px solid white;">&nbsp; 2-3 years</td>
			<td style="padding: 6px;padding-left: 3px;background-color:#ece0f4;border:  2px solid white;">&nbsp; 4-18 years</td>
		</tr>
		<tr>
			<td style="padding: 6px;padding-left: 3px;background-color:#ece0f4;border:  2px solid white;">&nbsp; 1-2</td>
			<td style="padding: 6px;padding-left: 3px;background-color:#ece0f4;border:  2px solid white;">&nbsp; 6-8</td>
		</tr>
</table>
</center>

What might be the reason for not rendering? Or is there any problem in the attributes / properties used within tags?  
 
@daohoangson any help is welcomed.

**Comment by daohoangson** [comment]
Looks like there is bug with `background-color`. I'll see and issue a fix asap.

**Comment by daohoangson** [comment]
Version `0.3.3+1` has been released with the fix for this. Please try upgrading and see if it works for you. Sorry for the inconvenience.

**Comment by ragu-swaminathan** [comment]
Does the fix will be available in dev version as well ??

**Comment by daohoangson** [comment]
Yes, the latest rc (`0.4.0-rc.2020043001`) also includes the fix.

**Comment by ragu-swaminathan** [comment]
@daohoangson  , Thanks for fix.  I have tried the latest version(0.4.0-rc.2020043001). But unfortunately , it is not working as expected. Please refer the screen shot of how it appears. And the relevant HTML code below. 

![Screenshot_1588605527](https://user-images.githubusercontent.com/20772180/80982383-e04aa800-8e48-11ea-8488-c1b60091a0d3.png)

HTML Code : 
` <table border="1" style="text-align:left;" width="60%">
	<tbody>
		<tr>
			<th style="padding: 6px;padding-left: 3px;color:white;background-color:#eabac2;border:  2px solid white;">&nbsp;Column 1<br />
			&nbsp;</th>
			<th style="padding: 6px;padding-left: 3px;color:white;background-color:#eabac2;border:  2px solid white;">&nbsp;Column 2</th>
			<th style="padding: 6px;padding-left: 3px;color:white;background-color:#eabac2;border:  2px solid white;">&nbsp;Column 3</th>
		</tr>
		<tr>
			<td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp; Data 1</td>
			<td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp;265</td>
			<td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp;278</td>
		</tr>
		<tr>
			<td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp; 767</td><td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp;89</td>
			<td style="padding: 6px;padding-left: 3px;background-color:#f9c6b2;border:  2px solid white;">&nbsp;78</td>
		</tr>
	</tbody>
</table>`

It is expected to fill the entire table cell. Please let me know if we have any work around / fix for them.

**Comment by daohoangson** [comment]
So, with the latest pre-release version (`0.4.1-rc.2020052701`), it works better but still not correct:

![Screen Shot 2020-05-27 at 11 07 26 PM](https://user-images.githubusercontent.com/239336/83044795-e0684d00-a06e-11ea-83b2-c59eb9a269bc.jpg)

Without the inline style in TABLE (`style="text-align:left;"`), it looks like this:

![Screen Shot 2020-05-27 at 11 08 26 PM](https://user-images.githubusercontent.com/239336/83044877-fd9d1b80-a06e-11ea-9fbb-5c15627a4cbe.jpg)

Hmm, I'll see what can be done.

**Comment by ragu-swaminathan** [comment]
@daohoangson , Please let know, once the issue is fixed and available. By the way great work. 👍 👍 👍

**Comment by daohoangson** [comment]
After #157 is merged, your table should work correctly!

![Simulator Screen Shot - iPhone 11 - 2020-07-08 at 15 19 31](https://user-images.githubusercontent.com/239336/86895286-75f70200-c12e-11ea-9f91-92abbf39111f.png)

**Comment by daohoangson** [comment]
Good news! Version `0.5.0-rc.2020071301` has been released with the new table rendering logic. Please try upgrading and see whether it works for you.
