### ISSUE TITLE
LI tag alignment between cells in TABLE row

### ISSUE THREAD

**Issue by ethel39** [daohoangson/flutter_widget_from_html#176]
hello, 
first of all thanks for a great plugin,
i tried this plugin working really good but found there's a weird line when i used ul tag inside a table

this is my html code i used
 [ul in table.txt](https://github.com/daohoangson/flutter_widget_from_html/files/4572794/ul.in.table.txt)

also this is the result i got
![result](https://user-images.githubusercontent.com/28940782/80936837-6218e200-8e05-11ea-825b-331aa3222790.png)

**Comment by daohoangson** [comment]
Your AMD Ryzen bit is missing the `<li />` tag?

**Comment by daohoangson** [comment]
Also, which version of this package are you using? And I don't see the weird line in your screenshot, can you point it out?

**Comment by ethel39** [comment]
both notebook and amd ryzen are not in a same line like amd quad core
i wonder is this a bug or not
also i deleted <li/> in amd just to make comparison that it's happens in <ul/> tag, not in <li/>
i'm using latest version 0.3.3+2
already tried dev version but also got a same result

**Comment by daohoangson** [comment]
Ah I see.

**Comment by daohoangson** [comment]
Version `0.5.2` has just been released with improvement regarding your use case. Please try upgrading and let me know whether it works for you. Thank you.
