### ISSUE TITLE
Table with joined cells not rendering correctly

### ISSUE THREAD

**Issue by theneshofficial** [daohoangson/flutter_widget_from_html#178]
The tables with columns joined (usage of rowspan & colspan) are not rendering as expected. Please see below. Thank you.

## Table code
```
<table style="border-collapse: collapse; width: 100%;" border="1">
   <tbody>
      <tr style="height: 23px;">
         <td style="width: 50.2874%; height: 23px;" colspan="2"><strong>Face Mask Details</strong></td>
         <td style="width: 25%; text-align: center; height: 23px;"><strong>Number</strong></td>
         <td style="width: 25%; text-align: center; height: 23px;"><strong>Percentage</strong></td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 50.2874%; height: 23px;" colspan="2">Mask Worn or Available&nbsp;(around neck)</td>
         <td style="width: 25%; text-align: center; height: 23px;">339</td>
         <td style="width: 25%; text-align: center; height: 23px;">95.5%</td>
      </tr>
      <tr style="height: 74px;">
         <td style="width: 50.2874%; height: 74px;" colspan="2">Limited Adequacy of Face Covering (mask present but hanging around neck or nose exposed)</td>
         <td style="width: 25%; text-align: center; height: 74px;">10</td>
         <td style="width: 25%; text-align: center; height: 74px;">3.0%</td>
      </tr>
      <tr style="height: 49px;">
         <td style="width: 20.1075%; height: 118px;" rowspan="4">Type of Masks</td>
         <td style="width: 30.1799%; height: 49px;">3-Ply Surgical Mask</td>
         <td style="width: 25%; text-align: center; height: 49px;">230</td>
         <td style="width: 25%; text-align: center; height: 49px;">67.8%</td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 30.1799%; height: 23px;">N-95 Mask</td>
         <td style="width: 25%; text-align: center; height: 23px;">6</td>
         <td style="width: 25%; text-align: center; height: 23px;">1.8</td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 30.1799%; height: 23px;">Cloth mask</td>
         <td style="width: 25%; text-align: center; height: 23px;">109</td>
         <td style="width: 25%; text-align: center; height: 23px;">32.2%</td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 30.1799%; height: 23px;">Bandana</td>
         <td style="width: 25%; text-align: center; height: 23px;">4*</td>
         <td style="width: 25%; text-align: center; height: 23px;">1.2%</td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 50.2874%; height: 23px;" colspan="2">Mask Touched/Handled</td>
         <td style="width: 25%; text-align: center; height: 23px;">11</td>
         <td style="width: 25%; text-align: center; height: 23px;">3.2%</td>
      </tr>
      <tr style="height: 49px;">
         <td style="width: 50.2874%; height: 49px;" colspan="2">Use of Face Shield</td>
         <td style="width: 25%; text-align: center; height: 49px;">2<br>
            (security personnel)
         </td>
         <td style="width: 25%; text-align: center; height: 49px;">0.6%</td>
      </tr>
      <tr style="height: 23px;">
         <td style="width: 50.2874%; height: 23px;" colspan="2">Use of Gloves</td>
         <td style="width: 25%; text-align: center; height: 23px;">7</td>
         <td style="width: 25%; text-align: center; height: 23px;">2.1%</td>
      </tr>
   </tbody>
</table>
```

## Expected Output
<img width="734" alt="Screenshot 2020-05-06 at 12 32 37 PM" src="https://user-images.githubusercontent.com/45613977/81141460-4d705180-8f9f-11ea-9b0a-8e982df45a8f.png">

## Returned result on App
<img width="723" alt="Screenshot 2020-05-06 at 1 00 16 PM" src="https://user-images.githubusercontent.com/45613977/81141480-5b25d700-8f9f-11ea-8ced-2db564d71512.png">

**Comment by daohoangson** [comment]
Ah, I have a PR for colspan / rowspan support (#157) but it's being blocked by a dependency. When it is merged, your table will render correctly:

| flutter_widget_from_html | flutter_widget_from_html_core |
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 - 2020-05-07 at 15 03 50](https://user-images.githubusercontent.com/239336/81269938-3d767180-9074-11ea-9f37-2544591b0ad3.png) | ![Simulator Screen Shot - iPhone 11 - 2020-05-07 at 15 03 52](https://user-images.githubusercontent.com/239336/81269915-32bbdc80-9074-11ea-8922-a3d09005faf1.png) |

Notice that the rowspan / colspan are not merged with the core package but all other cells are positioned correctly. The enhanced package uses a dependency (flutter_layout_grid) to render the merged cells.

**Comment by theneshofficial** [comment]
Noted on that @daohoangson , waiting for the PR to be merged. Thank you.

**Comment by ragu-swaminathan** [comment]
Any update on this enhancement ??

**Comment by Clean-Cole** [comment]
Hey, our team is looking to get this as well.  How can we help?

**Comment by daohoangson** [comment]
Since the PR on our dependency is not moving, I'm implementing in this package directly at #219. It was the original plan but I didn't want to maintain that piece of complicated rendering code. I guess there is no choice now 😤

**Comment by daohoangson** [comment]
The PR has been merged and version `0.5.0-rc.2020071301` has been released. Please try upgrading and see whether it works for your app.

**Comment by Clean-Cole** [comment]
No luck here unfortunately.  

Using 
```
<table border="1" cellpadding="4">
  <caption>colspan (<a href="https://www.w3schools.com/tags/att_td_colspan.asp">w3schools</a>)</caption>
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>\$100</td>
  </tr>
  <tr>
    <td>February</td>
    <td>\$80</td>
  </tr>
  <tr>
    <td colspan="2">Sum: $180 - longer line here for example</td>
  </tr>
</table>
```

we still get 
![image](https://user-images.githubusercontent.com/389053/87683601-e44b4e00-c746-11ea-90bf-73e6fdf6faca.png)

Will start poking around with breakpoints over the weekend to try and help pinpoint the issue.

**Comment by daohoangson** [comment]
Are you sure you are on the 0.5-rc?

**Comment by Clean-Cole** [comment]
that was the first thing I thought.  I nuked my entire pub cache and re-installed to make sure. Entirely possible something is still stuck, sometimes pub does very strange things for me.  I will post back if I find out different.

**Comment by daohoangson** [comment]
In my experience, checking `.packages` is the best way to make sure `pub` installed the correct version.

**Comment by daohoangson** [comment]
Also, please double check that you import `flutter_widget_from_html`, not `flutter_widget_from_html_core`. The colspan support requires an external dependency which is not included in the core package.
