### ISSUE TITLE
Inline CSS line-height

### ISSUE THREAD

**Issue by 127** [daohoangson/flutter_widget_from_html#181]
Please, add line-height is a very helpful  property — there's no possibility to change line lead.

**Comment by daohoangson** [comment]
I think this is a great feature and shouldn't be too hard to implement. Let me see what can be done.

**Comment by MadhwaniKishan** [comment]
> I think this is a great feature and shouldn't be too hard to implement. Let me see what can be done.

Hi, can you give some example about how can I use it?

**Comment by daohoangson** [comment]
It was not possible right now. What I was saying is I'm looking into it. Sorry for the confusion.

**Comment by daohoangson** [comment]
@127 @MadhwaniKishan `v0.4.1` has been released with support for `line-height`. Please try upgrading and let me know if it works for you. Thank you.

**Comment by 127** [comment]
Awesome, man! Thank you!
