### ISSUE TITLE
script and ins tag not work

### ISSUE THREAD

**Issue by KaungZawHtet** [daohoangson/flutter_widget_from_html#182]
I planned to add adsense block as widget but script and ins tags are not processed as tag but as raw string.
This is the planned code:

```
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="xxxxxxx"
     data-ad-client="ca-pub-xxxxxxxxxxxx"
     data-ad-slot="xxxxxxxx"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

**Comment by daohoangson** [comment]
SCRIPT tag is not supported and your INS tag is empty. The current version will fallback to raw html if no contents found (the next major update will render nothing).

If you want to display ad, use AdMob for your app.

**Comment by KaungZawHtet** [comment]
i tested only with ins tag and not work too

**Comment by daohoangson** [comment]
Yes, because the INS tag is empty. It has no contents.

AdSense uses that tag as a placeholder for later ad initialization. Without AdSense's JavaScript,  the INS tag is effectively invisible.

**Comment by KaungZawHtet** [comment]
Can that ins work in coming version or any advice for me ?

**Comment by daohoangson** [comment]
Probably no, you shouldn't run AdSense web on mobile app anyway. Have you tried AdMob?

**Comment by KaungZawHtet** [comment]
This is flutter web sadly. Admob won't work

**Comment by daohoangson** [comment]
Oh, you are targeting web? That's interesting, I haven't thought of this. Are you using `flutter_widget_from_html` or `flutter_widget_from_html_core`?

**Comment by KaungZawHtet** [comment]
flutter_widget_from_html_core cux it supports web according to pub.dev

**Comment by daohoangson** [comment]
For AdSense on Flutter Web, you probably need to follow this issue https://github.com/flutter/flutter/issues/40376. Actually, there are several others too.

Since this is not related to this package, I'm closing this now.
