### ISSUE TITLE
A new question

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#183]
![image](https://user-images.githubusercontent.com/40446804/82187143-8d7bf080-991e-11ea-93b4-f154cb735450.png)
When I use this component in tabbarview, when I switch back and forth, there will be incomplete display in the picture, which is all picture links.

**Comment by daohoangson** [comment]
So your HTML has many IMG tags? And you switch back and forth between the tabs? Can you record a screencast or similar? I don't understand the issue yet.

**Comment by dvzhou** [comment]
[周星星คิดถึง 2020-05-05 16.44.30.mp4.zip](https://github.com/daohoangson/flutter_widget_from_html/files/4643039/2020-05-05.16.44.30.mp4.zip)
I recorded a demo video. You see, I switch back and forth in the same page. This is the HTML data will change

**Comment by daohoangson** [comment]
Hmm, the images are blurry huh? I think this is unrelated to the tabs. Can you share your HTML so I can reproduce and debug? Which version of the package are you using? Also, what is your `flutter doctor -v` output?

**Comment by dvzhou** [comment]
[datas.txt](https://github.com/daohoangson/flutter_widget_from_html/files/4643091/datas.txt)
The content field in the attachment is the data I use to display. I use the latest version

**Comment by daohoangson** [comment]
I have just tried your HTMLs in a `TabBarView` and they seemed to work fine. Check out this screen record:

https://youtu.be/6nla75M_hkk

Can you provide sample code that can reproduce this bug?

**Comment by dvzhou** [comment]
Sorry, I don't describe it accurately. What I want to express is that the top level of this page is a tabview, and then these HTML are dynamically switched under a tab in the tabview. Only one HTML content is displayed at a time. When I click the next and the previous, the HTML content is dynamically replaced.

**Comment by daohoangson** [comment]
I have been able to reproduce your issue. This can be workaround by assigning a key to the `HtmlWidget`. Assuming you have a list of `htmls` and your stateful widget uses `i` to keep track of the current one. This is the code to render it:

```dart
        HtmlWidget(
          widget.htmls[i],
        ),
```

To fix, just add a key like this:

```dart
        HtmlWidget(
          widget.htmls[i],
          key: ValueKey(i),
        ),
```

**Comment by dvzhou** [comment]
Yes, after setting a key, there will be no problem. Thank you for your advice. thanks a lot.

**Comment by daohoangson** [comment]
Great to hear that it's resolved. I'm closing this issue now.

**Comment by dvzhou** [comment]
Thank you very much ！
