### ISSUE TITLE
Non-breaking Space

### ISSUE THREAD

**Issue by egorges** [daohoangson/flutter_widget_from_html#185]
Feature Request:
**& nbsp;** 
and also the corresponding handling of '**\u00A0**' (unicode non-breaking space) .

**Comment by daohoangson** [comment]
Can you elaborate on what is **not** working as intended?

**Comment by egorges** [comment]
Non-breaking space is used to keep continuous text together, so you can avoid formatting like:
```
xxxx longe text xxxx US$
1.00
```
and force it to format like
```
xxx long text xxxx
US$ 1.00

```
**nbsp** is HTML standard. It can be simulated with the unicode non-breaking space char: '\u00A0' , which should give the same result.

**Comment by daohoangson** [comment]
Hmm, yeah. Let me see what can be done.

**Comment by daohoangson** [comment]
I have just released `v0.3.3+4` with the fix for this. Can you try upgrading?

**Comment by egorges** [comment]
> I have just released `v0.3.3+4` with the fix for this. Can you try upgrading?

Worked perfectly! Thanks a lot.

**Comment by daohoangson** [comment]
Great to hear. I'm closing this issue for now.
