### ISSUE TITLE
Not support RGB color inline style

### ISSUE THREAD

**Issue by leewonghao** [daohoangson/flutter_widget_from_html#192]
I have a code:
`<p color: rgb(23, 156, 97); font-size: 18px; font-weight: bold;">Hello word!</p>`

But I see it doesn't support RGB color style.
Please help me. Thanks

**Comment by daohoangson** [comment]
Yes, this package only supports hex values for now, from the README:

> color: hex values only (#F00, #0F08, #00FF00 or #00FF0080)

I do plan to expand to support rgb, rgba, etc. though.

**Comment by leewonghao** [comment]
> Yes, this package only supports hex values for now, from the README:
> 
> > color: hex values only (#F00, #0F08, #00FF00 or #00FF0080)
> 
> I do plan to expand to support rgb, rgba, etc. though.

I understood, thank you so much.

**Comment by starup** [comment]
also need this feature, please support  color name，eg:   body{ background-color:red}；

**Comment by daohoangson** [comment]
> also need this feature, please support color name

Yes, this is planned.

**Comment by leewonghao** [comment]
Thanks @daohoangson ! After update v0.4.1 it was worked fine :).

**Comment by daohoangson** [comment]
Awesome, I'm closing this issue now.
