### ISSUE TITLE
Add handle for "Poster" attribute in Video tag

### ISSUE THREAD

**Issue by ssivagnanam** [daohoangson/flutter_widget_from_html#195]
Add a support/handle for Poster attribute in video tag.  

<video controls=\"\" data-autovideo=\"true\" width=\"100%\" poster=\"https://dummyurl.com/image.jpg\">
      <source src=\"https://dummyurl.com/video.mp4">
      Your browser does not support the video tag.
   </video>

**Comment by daohoangson** [comment]
This sounds useful. I'll see what can be done.

**Comment by daohoangson** [comment]
`v0.4.1` has been released with support for this. Please try upgrading.

**Comment by ssivagnanam** [comment]
Thanks for your update. its working fine.
But, Is it possible to show thumbnail image until user start playing that video?

**Comment by daohoangson** [comment]
I don't think that's possible. Let me check and get back to you.

**Comment by daohoangson** [comment]
The video player package (`chewie`) doesn't allow fine tuning of the placeholder so I'm closing this issue.
