### ISSUE TITLE
how to change TextStyle?

### ISSUE THREAD

**Issue by glin94** [daohoangson/flutter_widget_from_html#2]

**Comment by daohoangson** [comment]
You can wrap it inside a `DefaultTextStyle`, something like this:

```dart
return DefaultTextStyle(
    child: HtmlWidget(...),
    style: Theme.of(context).textTheme.body1,
);
```

**Comment by glin94** [comment]
thank you!

**Comment by daohoangson** [comment]
That's weird. Can I see some code?

**Comment by glin94** [comment]
```dart 
DefaultTextStyle(
 style: Theme.of(context).textTheme.body1.copyWith(fontFamily: "Open Sans"),
 child: HtmlWidget(detail.content'))
```

**Comment by daohoangson** [comment]
Which device/os are you testing on?

I'm afraid the Open Sans font is not available therefore it won't work.

**Comment by glin94** [comment]
Open Sans work in another TextStyle
![image](https://user-images.githubusercontent.com/34025626/48463120-08c18b00-e7ec-11e8-96d2-35148f17f0b0.png)

**Comment by glin94** [comment]
sorry, it's work. thanks!
