### ISSUE TITLE
Using the new widgetBuilder

### ISSUE THREAD

**Issue by cschellhas** [daohoangson/flutter_widget_from_html#208]
Hi,

I used the factoryBuilder before 0.41 for changing a single class with custom name to build a custom widget only for the position. The smilie example is outdated.

Now I use the new widgetBuilder but I wont work as expected. If i use the widgetBuilder I get a white screen if he wont find the specific element. 

Example

`customWidgetBuilder: (e) => e.classes.contains('imagebtn')
            ? imageGal(n.imageList)
            : Text('this is a test'),`

I look for a class "imagebtn" and want to replace it with imageGal() widget else use normal behavior of flutter_widget_from_html.

Kindly regards

**Comment by daohoangson** [comment]
To fallback to default behavior, you will need to return `null` in `customWidgetBuilder`.

However, `customStylesBuilder` and `customWidgetBuilder` are designed to be easy to use so they are not as powerful as using your own `WidgetFactory`. You should be able to change your existing code from version `0.3.x` to `0.4.x` without much issue. The method signature for `factoryBuilder` only changed from ` WidgetFactory Function(BuildContext)` into ` WidgetFactory Function()`.

**Comment by cschellhas** [comment]
Thank you very much :-) , it's works.
