### ISSUE TITLE
td width does not support

### ISSUE THREAD

**Issue by IkromjonMamatov95** [daohoangson/flutter_widget_from_html#209]
The plugin does not support the html table data width for example:
### text-align:right;\">eorgwjoerjgowfekg ergerpgqre. /td
then the result is shown in the table the table data width equally seperated not shown in the percentage like 73% for the first one and 26 % for the second one. The result is shown like 50 / 50 for both table data.

**Comment by daohoangson** [comment]
Yes, this is something I wanted to support but it's not possible yet.

**Comment by IkromjonMamatov95** [comment]
Hi daohoangson ! 
Thank you for response I have used WebViews for the issue it is working as supposed to be but rendering with list view is another issue happened like not smooth scrolling and gesturing. So then, I used this plugin again with "WebView" flag "true" because I thought that if the flag is enabled then the plugin support all the features of the WebView but it does not. I hope to hear news soon about this issue.
Thank you in advance.

**Comment by daohoangson** [comment]
The `webView` param of `HtmlWidget` does not uses `WebView`, it just enable rendering of `WebView` for IFRAME tag.

You can use `WebView` but the performance won't be great because it uses a `PlatformView` widget under the hood, which is always slower than native Flutter widget.

**Comment by oggam** [comment]
any updates on this one? urgently need this feature.

**Comment by daohoangson** [comment]
I'm closing this issue. The umbrella issue for table column width is #531. Please follow that one if you want to be notified of new development.
