### ISSUE TITLE
Web no Build IFRAME

### ISSUE THREAD

**Issue by JMCodebr** [daohoangson/flutter_widget_from_html#211]
Error: PlatformException(Unregistered factory, No factory registered for viewtype 'plugins.flutter.io/webview', null)
    at Object.throw_ [as throw] (http://localhost:53334/dart_sdk.js:4463:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:53334/packages/flutter/src/services/platform_channel.dart.lib.js:1186:19)

my code:

```
                               HtmlWidget(
                                '''
                                <p>And YouTube video!</p>
                                <iframe src="https://www.youtube.com/embed/jNQXAC9IVRw" width="560" height="315"></iframe>
                                ''',
                                webView: true,
                                ),
```

I need display video youtube in flutter web

**Comment by daohoangson** [comment]
Yes, this is an issue with the `webview_flutter` package, see https://github.com/flutter/flutter/issues/45295.

**Comment by daohoangson** [comment]
`IFRAME` support within Flutter Web has been added since version 0.5.0. I'm closing this issue for now.
