### ISSUE TITLE
[Exception caught by widgets library] (MediaQuery.of() called with a context that does not contain a MediaQuery)

### ISSUE THREAD

**Issue by JustNeedKeyboard** [daohoangson/flutter_widget_from_html#213]
I am a freshman.
I just tried sample code but ı am in the trouble now.

### My Error

The following assertion was thrown building MyApp:
I/flutter (12224): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (12224): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (12224): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (12224): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (12224): The context used was:
I/flutter (12224):   Scaffold
I/flutter (12224): 
I/flutter (12224): The relevant error-causing widget was:
I/flutter (12224):   MyApp file:///C:/src/Flutter_projects/flutter_app/lib/main.dart:24:23
I/flutter (12224): 
I/flutter (12224): When the exception was thrown, this was the stack:
I/flutter (12224): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:813:5)
I/flutter (12224): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:2172:50)
I/flutter (12224): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
I/flutter (12224): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (12224): ...     Normal element mounting (7 frames)
I/flutter (12224): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12224): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (12224): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter (12224): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter (12224): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter (12224): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (12224): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter (12224): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter (12224): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter (12224): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (12224): 
I

**Comment by JustNeedKeyboard** [comment]
The relevant error-causing widget was:
I/flutter (12224): MyApp file:///C:/src/Flutter_projects/flutter_app/lib/main.dart:24:23


I just added one line of code to the sample
void main() => runApp(MyApp());

**Comment by JustNeedKeyboard** [comment]
I tried the first readme sample. Somehow I solved with in example/main.dart. But I need to know what there is problem?

**Comment by daohoangson** [comment]
Ah, that happened because you didn't wrap it in a `MaterialApp` or `WidgetsApp` (as mentioned in the error message). I'll update the READMEs so it's clearer. Thank you for the report.

**Comment by JustNeedKeyboard** [comment]
Thank you for the answer.
