### ISSUE TITLE
Hey I am having issue in embedding.

### ISSUE THREAD

**Issue by shanu12joshi** [daohoangson/flutter_widget_from_html#216]
Hey @daohoangson , I am facing 2 issues as of now: 1) Twitter embeds are opening half i.e not loading completely they load when we refresh again 2) I am attaching a youtube video of the problem. i.e The embeds loads when I move over to that section, Can't I store them in the cache so it doesn't load again and again? Because it's reducing the efficiency of the app.

Link to the video: https://youtu.be/gJNlZ1aphOE

![WhatsApp Image 2020-07-02 at 8 22 35 PM](https://user-images.githubusercontent.com/42548654/86374131-d7881e00-bca1-11ea-9945-6cd22cb504ed.jpeg)

**Comment by daohoangson** [comment]
Rendering `WebView`s is slow because they use `PlatformView` (e.g. native web view) instead of Flutter's own rendering pipeline. In your screen recording, it looks like you have multiple Twitter embeds in the same screen? I'm afraid nothing can be done in this case.

If you plan to have this many embeds without any other contents, I think it will be faster to put them all in 1 `WebView` instead of using `HtmlWidget`.

**Comment by shanu12joshi** [comment]
Oh Ok

**Comment by shanu12joshi** [comment]
I would like to tell you one more thing 
Do you remember that server we need o play videos on twitter embeds,
We don't need it actually. 
https://pub.dev/packages/video_player#installation - This installation is only required that's it.

**Comment by daohoangson** [comment]
> We don't need it actually.
> https://pub.dev/packages/video_player#installation - This installation is only required that's it.

How so? You followed the installation steps of that package and Twitter embed works without external server?

**Comment by shanu12joshi** [comment]
Yes, The twitter embed works without an external server.

**Comment by shanu12joshi** [comment]
Hey! Can you tell me how I can remove the padding and margin around the HtmlWidget?

**Comment by daohoangson** [comment]
> Yes, The twitter embed works without an external server.

That's weird. But I'm glad that it works for you.

> Hey! Can you tell me how I can remove the padding and margin around the HtmlWidget?

Which version are you using? v0.4 doesn't have default padding.

**Comment by shanu12joshi** [comment]
I am using 0.4.0-rc.2020043001 Version

**Comment by daohoangson** [comment]
v0.4 stable has been released. You should update your dependency.

**Comment by shanu12joshi** [comment]
I changed the version to v0.4
Still have some margin on the sides
![WhatsApp Image 2020-07-08 at 8 13 21 PM](https://user-images.githubusercontent.com/42548654/86932888-8bcced00-c157-11ea-8f9f-e695a1df066f.jpeg)

**Comment by daohoangson** [comment]
Is your HTML has a `BLOCKQUOTE`? That tag has default padding, you will need `customStylesBuilder` to reset it.

**Comment by shanu12joshi** [comment]
Yes using 'BLOCKQUOTE',
used customStylesBuilder. But it's not removing :(

**Comment by daohoangson** [comment]
How did you remove it? Can you share the `customStylesBuilder` code?

**Comment by shanu12joshi** [comment]
customStylesBuilder: (e) {
                          switch (e.localName) {
                            case 'blockquote':
                              return ['padding', '0'];
                          }
                          return null;
                        },

**Comment by daohoangson** [comment]
Ah, looks like `BLOCKQUOTE` has default `margin`, not `padding`. You will have to reset it like this:

```dart
customStylesBuilder: (e) {
  switch (e.localName) {
    case 'blockquote':
      return ['margin', '0'];
  }
  return null;
},
```

**Comment by shanu12joshi** [comment]
Haha I tried both not happening

**Comment by daohoangson** [comment]
Hmm, can you share a complete sample with Dart code and HTML so I can reproduce?

**Comment by romasunichuk** [comment]
Hi, I'm facing a problem with embedded tweet video on IOS meanwhile on Android everything is fine. Using factoryBuilder:

`class _BlockquoteWebViewWf extends WidgetFactory {
  final blockquoteOp = BuildOp(
    onWidgets: (meta, _) {
      String source = Uri.dataFromString(
        """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
</head>
<body>
  ${meta.domElement.outerHtml}
  
  <script type="text/javascript" async defer src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</body>
</html>""",
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8'),
      ).toString();

      return [WebView(
        source,
        aspectRatio: 9/16,
        getDimensions: true,
        js: true,
      )];
    },
  );

  @override
  void parseTag(NodeMetadata meta, String tag, Map<dynamic, String> attrs) {
    if (tag == 'blockquote') {
      meta.op = blockquoteOp;
      return;
    }

    return super.parseTag(meta, tag, attrs);
  }
}`

**Comment by shanu12joshi** [comment]
@romasunichuk Try this https://pub.dev/packages/video_player#installation
The installation part for playing videos on twitter.

**Comment by romasunichuk** [comment]
@shanu12joshi I have already done it but doesn't help. After tapping on the video only loader is spinning.

**Comment by daohoangson** [comment]
@romasunichuk try this code https://github.com/daohoangson/flutter_widget_from_html/issues/161#issuecomment-633203552 which uses a special made api for Twitter embed.

**Comment by shanu12joshi** [comment]
HtmlWidget(
                        '<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/CCHoQlMp3UK/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="12" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CCHoQlMp3UK/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;"> View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CCHoQlMp3UK/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by ESPN MMA (@espnmma)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2020-07-02T00:15:35+00:00">Jul 1, 2020 at 5:15pm PDT</time></p></div></blockquote> <script async src="//www.instagram.com/embed.js"></script>',
                        customStylesBuilder: (e) {
                          switch (e.localName) {
                            case 'blockquote':
                              return ['margin', '0'];
                          }
                          return null;
                        },
                        customWidgetBuilder: (e) {
                          if (e.localName == 'blockquote') {
                            switch (e.attributes['class']) {
                              case 'instagram-media':
                                return buildForInstagram(e.outerHtml);
                              case 'twitter-tweet':
                                return buildForTwitter(e.outerHtml);
                            }
                          }
//                  else if (e.localName == 'div') {
//                    return buildDisqus(e.outerHtml);
//                  }

                          return null;
                        },
                        webView: true,
                      )




  Widget buildForInstagram(String html) => WebView(
        Uri.dataFromString(
          """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
</head>
<body>
  $html
  <script async src="https://www.instagram.com/embed.js"></script>
</body>
</html>""",
          mimeType: 'text/html',
          encoding: Encoding.getByName('utf-8'),
        ).toString(),
        aspectRatio: 16 / 9,
        getDimensions: true,
      );

**Comment by shanu12joshi** [comment]
@daohoangson One more thing the twitter embed crashes the app when doing any action on twitter embed.

**Comment by daohoangson** [comment]
What is your `flutter doctor -v` output? Also, which device are you testing on?

**Comment by shanu12joshi** [comment]
Hey @daohoangson 
I am facing another issue 
How to resolve it?
![WhatsApp Image 2020-07-23 at 2 50 26 PM](https://user-images.githubusercontent.com/42548654/88282587-7afbaa00-cd07-11ea-99f0-04c98bb13238.jpeg)

**Comment by daohoangson** [comment]
Is this Twitter embed? If it's not, can you open another issue for easy tracking? Also, it would be useful to provide the HTML and Dart code to reproduce the bug.

**Comment by shanu12joshi** [comment]
I have tested on One Plus, App crashes every time we do any actions on it,

The output of flutter doctor -v :

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.17.5 at /Users/shanujoshi/Downloads/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shanujoshi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by daohoangson** [comment]
Regarding the crashing Twitter embed, can you confirm these info:

- Flutter version 1.17.5
- flutter_widget_from_html version 0.4.2 (or 0.5 rc?)
- Twitter blockquote is being rendered with `Uri.dataFromString` or iframe API? You mentioned the API is no longer needed after following the steps of https://pub.dev/packages/video_player#installation so I'm not sure.

**Comment by shanu12joshi** [comment]
Yes
Flutter version 1.17.5
flutter_widget_from_html version 0.4.2 
Twitter is being rendered from 'Uri.dataFromString'
Yes, the API is no longer needed in android apps, My app is running without API by using the installation I have shared, Haven't tested on ios yet.

What is this method of the iframe to render twitter, Is it faster?

**Comment by daohoangson** [comment]
I believe Twitter does some security check in the embed code. That's probably why it crashed in your test (probably Android version specific, device specific). When I test with `Uri.dataFromString` on my Note9, it seems to work fine (without video playback).  Can you test with the iframe API?
