### ISSUE TITLE
images cant be aligned

### ISSUE THREAD

**Issue by martipello** [daohoangson/flutter_widget_from_html#217]
im using the customWidgetBuilder and if i swap out an 'img' tag to instead show a text view i get padding on the left side https://drive.google.com/file/d/17PKWI4OT0rKoT7FrI-m2jEdwu60P52IP/view?usp=sharing

return HtmlWidget(htmlData, customWidgetBuilder: (element){
      print('element ${element.localName}');
      if (element.localName == 'h2') {
        return Text('H2 TEXT');
      }
      if (element.localName == 'img') {
        return Text('IMAGE');
      }  
      return null;
    },);

**Comment by daohoangson** [comment]
What is your HTML?

If your `IMG` is inside some `FIGURE` or `BLOCKQUOTE` then they have default padding. You should be able to use `customStylesBuilder` to reset those.
