### ISSUE TITLE
Phantom padding on parent widget

### ISSUE THREAD

**Issue by benPesso** [daohoangson/flutter_widget_from_html#225]
Before version 0.4.1 it was possible to use `bodyPadding` to get rid of the hard-coded 10px padding of the parent `HtmlWidget` container. Now that it is deprecated, the padding is forever there, which is bad. By default, widgets shouldn't force padding on the developer. I would advise setting it to `EdgeInsets.zero` by default.

<img width="699" alt="Screen Shot 2020-07-10 at 12 47 01" src="https://user-images.githubusercontent.com/921173/87143589-08261400-c2af-11ea-9f30-bfe3c2f356eb.png">

**Comment by daohoangson** [comment]
What is your HTML code?

**Comment by benPesso** [comment]
Oh sorry, forgot to include it...

```
<center>
  <b>${_user.title}</b> is now <b>\$${_user.status}</b>.
</center>
```

**Comment by daohoangson** [comment]
Are you sure you are on the latest 0.4? I have just tried this and it seems to work as expected:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class Issue225 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 225')),
        body: SingleChildScrollView(
          child: HtmlWidget(kHtml),
        ),
      );
}

const kHtml = """
<center>
  <b>User title</b> is now <b>User status</b>.
</center>
""";
```

![Screen Shot 2020-07-10 at 7 17 19 PM](https://user-images.githubusercontent.com/239336/87153651-03c71e80-c2e2-11ea-9542-e22bc021fe25.jpg)

**Comment by benPesso** [comment]
I am, yes. I got the deprecation message for `bodyPadding`, which is how I ran into this issue again.

`  flutter_widget_from_html_core: ^0.4.1`

This is the full code that is generating the widget:
```
    String description = """
    <center>
    <b>${_user.title}</b> is now <b>${_user.status}</b>.
    </center>
    """;
    return HtmlWidget(
      description,
    );
```

What can cause it to add padding inside the `HtmlWidget` widget?

**Comment by daohoangson** [comment]
Hmm, that param was removed in `0.4.1` without deprecation message. It was only noted in the CHANGELOG.

It's possible that you applied some margin in `customStylesBuilder`, maybe?

**Comment by benPesso** [comment]
The message was an error in the debug console, as I upgraded from 0.3.3 to 0.4.1.

I don't have any instance of `customStylesBuilder` in the code, so that's not it, I guess.

I just created a test app with the widget alone, and got the same results as you - there was no Padding widget.
That said, I don't have any custom configuration for the library, so whatever behavior that causes the padding to be added is coming from something else.

**Comment by daohoangson** [comment]
My best guess is somehow the app was running an outdated bundle. Can you try running `flutter clean` then `flutter run` again? Also, you should double check `.packages` file and make sure it has something like this (notice the version number):

```
flutter_widget_from_html:file:///flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html-0.4.1/lib/
```

**Comment by benPesso** [comment]
Alright. I cleaned up the project, and that was indeed the issue. No more phantom padding. Should have thought about it myself.  😐

**Comment by daohoangson** [comment]
Awesome. This issue is indeed a head scratcher 🤣 I'm glad that it worked out.
