### ISSUE TITLE
Unexpected behaviour with padding or margin in style attribute

### ISSUE THREAD

**Issue by skytect** [daohoangson/flutter_widget_from_html#231]
### Working
```html
A<strong>B</strong>A
```
Result:
A**B**A

### Not Working
```html
A<strong style="padding: 8px">B</strong>A
```
Expected Result:
A&ensp;**B**&ensp;A

Actual Result:
A
&ensp;**B**
A

This issue also occurs when using `style="margin: 8px"`

**Comment by daohoangson** [comment]
This happened because `margin` and `padding` support forces the element to be rendered as block. This will be probably updated after a few releases.
