### ISSUE TITLE
problem reading svg image

### ISSUE THREAD

**Issue by jheimesilveirazup** [daohoangson/flutter_widget_from_html#232]
Hi, I have the following text, which contains an svg annotation, but the plugin can't read the file, is there a way to be able to read an svg file?

Below is an example of the image I wish I could read.

<p><img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a7.svg" alt="????" width="15" /><img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a8.svg" alt="????" width="15" height="15" /> ATTENTIONS<img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a8.svg" alt="????" width="15" height="15" /> <img class="emoji" role="img" draggable="false" src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f6a7.svg" alt="????" width="15" height="15" /></p>

**Comment by daohoangson** [comment]
Currently only inline SVG is supported (the `SVG` tag). The image tag (`IMG`) doesn't support svg files yet.

See #175.

**Comment by daohoangson** [comment]
Version `0.5.0-rc.2020071301` has been released with support for svg file over network or asset. Please try upgrading and see whether it works for you.
