### ISSUE TITLE
Add support for inline style `background` 

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#234]
`background-color` has already been supported. It would be great if `background` works too.

- [x] background-color
- [x] background-image
- [x] repeat-style?
- [ ] layers?

https://developer.mozilla.org/en-US/docs/Web/CSS/background

**Comment by daohoangson** [comment]
`background: red` now works, thanks to #275

**Comment by DFelten** [comment]
Any progress on the background image here? :)

**Comment by daohoangson** [comment]
No update since August last year 😅

**Comment by daohoangson** [comment]
`v0.14.6` has been released with support for background image, thanks to contributions from @anttileppa 🔥🔥🔥🔥 I'm gonna close this issue today because layers support is unlikely to be implemented anytime soon.
