### ISSUE TITLE
onTapUrl only reacting to 'real' urls

### ISSUE THREAD

**Issue by ventr1x** [daohoangson/flutter_widget_from_html#238]
Is there a reason behind not putting any content of href on a tags through to the event?

I'm currently trying to build an article system where the need exists to include internal links that redirect to other app screens.
So for this the simple onTapUrl is a god send, so it made me quite sad to see it not working at all.
An internal link could of course look like anything, like simply {article:1234}; or #article:1234, or (article:1234), or &article:1234. None of these examples trigger the event. Not even hash bangs and parameters.
Only plain text 'article:1234' or http/https seem to work.

**Comment by daohoangson** [comment]
> Is there a reason behind not putting any content of href on a tags through to the event?

For most use cases, doing it this way makes more sense IMHO. e.g. the developer grab the HTML from some API and just render it for user to read. Most links will be some web page on the Internet.

If you want more control regarding link routing, you can set your own special `baseUrl` then within `onTapUrl` do your own check. Something like: if url starts with the base url then push some named route, otherwise let `super.onTapUrl` handle it.

**Comment by ventr1x** [comment]
If you just want to handle "most use cases" then why even offer such an event which is supposed to let us handle other use cases? I just can't come up with a single reason to not simply put the content of href through to the event. Everyone that just wants to redirect, can call super.* or not set the callback at all.
Of course I can decide a simple string and use this, hoping it won't conflict with something else. Which is basically exactly what something like "{link-info}" is supposed to be.
It just feels so arbitrarily limited and unnecessarily opinionated to parse the string and decide for yourself internally which combination is allowed to go to the callback.

**Comment by daohoangson** [comment]
The callback is optional, most people won't have to implement it in the app. Unless they use the core package I guess... It was there as an escape hatch for complicated apps that need special logic for some classes or URL etc. like yours.

**Comment by ventr1x** [comment]
And I just mentioned that my use case is impossible as the callback is not being called unless the content is plain text, or at least does not start with any "special" character. Even though many of these are even url relevant, like #, ?, &...

But it's fine, I'll use something hacky or simply fork the package.

**Comment by daohoangson** [comment]
It is not idea but for special characters, you can use query string param and encode those with `Uri.encodeComponent` or similar. If it was me, I would use the path as named route. Params will fit in nicely that way.
