### ISSUE TITLE
table not rendering at all when inline style applied

### ISSUE THREAD

**Issue by ventr1x** [daohoangson/flutter_widget_from_html#239]
I'm testing a very simple table:

```
<table>
<tr style="height: 21px;">
<td>U1</td>
</tr>
<tr style="height: 21px;">
<td>U8</td>
</tr>
</table>
```

Which is only rendering when any "style=*" is removed. Is that expected behaviour to simply not render anything instead of dismissing unsupported attributes?
That destroys compatibility with.. well.. any website and any wysiwyg editor. I don't mind styles not being applied, but not rendering at all?

It also does not render anything when tbody is used. Which is part of the html spec and also generated by most editors.

Newest dev version 0.5.*

**Comment by daohoangson** [comment]
In the latest rc, a few things are not supported inside TABLE like list,
sizing inline or IMG. I have fixed list which should be included in the
next rc. For the other things, they will be updated soon.

Regarding your table, you'll need to remove the inline height for now.

**Comment by ventr1x** [comment]
And tbody? 
I cant remove such things without writing my own parser, just because your code decides to completely fail when it finds some unsupported attribute. Why wouldnt it just render everthing supported? This looks extremely unstable and far from any kind of production ready.

I wouldnt mind supporting the plugin, be it financially or with PRs. But this is the second breaking thing for me I cant understand after just a short test.

**Comment by daohoangson** [comment]
TBODY is supported. The list of tags are in the README.md by the way.

The rc is a pre-release version so I do expect it to have some bugs. If you
check the change log, TABLE is rewritten in v0.5 for colspan and rowspan
support so bugs are more likely to happen there actually. Hopefully with
reports from early adopter like you, they will be ironed out before stable
release.

**Comment by daohoangson** [comment]
The latest 0.5 release `v0.5.0-rc.2020081901` includes the fix for sizing styles and rendered your HTML without issue.

<img src="https://user-images.githubusercontent.com/239336/90613778-09464b80-e234-11ea-93b1-e9f005748a5c.png" width="300" />

Please try upgrading and let me know if it works for you.
