### ISSUE TITLE
Support for custom tag on HTML

### ISSUE THREAD

**Issue by prsolucoes** [daohoangson/flutter_widget_from_html#244]
Hi,

Im trying render a bible text that have the following content:

```
<sup>4</sup> E jesus, respondendo, disse-lhes: <J>Acautelai-vos, que ninguém vos engane.</J>
```

Can i set custom style for tag "J" with this library?

Thanks.

**Comment by daohoangson** [comment]
You should be able to use `customStylesBuilder` for this, example code below. All supported inline styles should work with your custom `J` tag, see the updated list at [pub.dev](https://pub.dev/packages/flutter_widget_from_html).

```dart
                  HtmlWidget(
                    html,
                    customStylesBuilder: (e) {
                      switch (e.localName) {
                        case 'j':
                          return ['color', 'red', 'font-style', 'italic'];
                      }

                      return null;
                    },
                  ),
```

Screenshots:

| HTML | Without `customStylesBuilder` | With `customStylesBuilder` |
| --- | --- | --- |
| ![Screenshot_20200720-170417](https://user-images.githubusercontent.com/239336/87926230-979ba600-caab-11ea-9315-1c1c088a69d9.jpg) | ![Screenshot_20200720-170423](https://user-images.githubusercontent.com/239336/87926240-9bc7c380-caab-11ea-81f5-0c1b7026ca28.jpg) | ![Screenshot_20200720-170431](https://user-images.githubusercontent.com/239336/87926245-9cf8f080-caab-11ea-8cad-26e9120f54c2.jpg) |

**Comment by prsolucoes** [comment]
wow
thanks
you are the best

i will test and will post here my screenshot with it working

im using other library but have some bugs...now i will change to yours...one minute

**Comment by prsolucoes** [comment]
Perfect

![IMG_45AFBCA7E015-1](https://user-images.githubusercontent.com/395096/87974659-ca8c6c80-caa0-11ea-9d22-1faf24ce1558.jpeg)

**Comment by daohoangson** [comment]
Awesome, I'm closing this issue now. Feel free to open another issue if you run into something else.

Cheers.
