### ISSUE TITLE
Images are going out of bound in htmlWidget

### ISSUE THREAD

**Issue by shanu12joshi** [daohoangson/flutter_widget_from_html#252]
Hey! @daohoangson 
This is the issue we're facing 
The html is: `<img class="size-full wp-image-319346" src="https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2.jpg" alt="aljamain-sterling" width="1200" height="800" srcset="https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2.jpg 1200w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-473x315.jpg 473w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-225x150.jpg 225w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-768x512.jpg 768w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-370x247.jpg 370w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-800x533.jpg 800w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-20x13.jpg 20w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-185x123.jpg 185w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-740x493.jpg 740w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-1110x740.jpg 1110w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-400x267.jpg 400w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-72x48.jpg 72w" sizes="(max-width: 1200px) 100vw, 1200px" />`

Just wrapping the content in htmlWidget 

Custome style builder code:

`customStylesBuilder: (e) {
                  Analytics().reachedHalf();
                  switch (e.localName) {
                    case 'blockquote':
                      return ['margin', '0'];
                    case 'a':
                      return [
                        'color',
                        '#000',
                        'text-decoration',
                        'none',
                        'pointer-events',
                        'none',
//                        'font-weight',
//                        '600'
                      ];
                    case 'p':
                      return [
                        'line-height',
                        '1.5',
                        'margin-bottom',
                        '16px',
                        'font-family',
                        'Roboto',
                        'font-size',
                        '16px',
                        'text-align',
                        'left',
                        'line-height',
                        '1.4',
                        'font-weight',
                        '500',
                        'color',
                        '#1b1b1b'
                      ];
                    case 'em':
                      return ['font-family', 'Roboto'];
                    case 'h2':
                      return ['font-family', 'Oswald-demibold'];
                    case 'img':
                      return ['border-radius', '20px'];
                  }
                  return null;
                },`

![WhatsApp Image 2020-07-23 at 2 50 26 PM](https://user-images.githubusercontent.com/42548654/88389427-23774000-cdd4-11ea-91b4-86420dfebf82.jpeg)

**Comment by daohoangson** [comment]
Which version of the package are you using? I have tested this code with both latest 0.4 and 0.5-rc and it seems to work fine. 

<details>

<summary>test.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class Issue252 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 252')),
        body: SingleChildScrollView(
          child: HtmlWidget(
            kHtml,
            customStylesBuilder: (e) {
              switch (e.localName) {
                case 'blockquote':
                  return ['margin', '0'];
                case 'a':
                  return [
                    'color',
                    '#000',
                    'text-decoration',
                    'none',
                    'pointer-events',
                    'none',
                  ];
                case 'p':
                  return [
                    'line-height',
                    '1.5',
                    'margin-bottom',
                    '16px',
                    'font-family',
                    'Roboto',
                    'font-size',
                    '16px',
                    'text-align',
                    'left',
                    'line-height',
                    '1.4',
                    'font-weight',
                    '500',
                    'color',
                    '#1b1b1b'
                  ];
                case 'em':
                  return ['font-family', 'Roboto'];
                case 'h2':
                  return ['font-family', 'Oswald-demibold'];
                case 'img':
                  return ['border-radius', '20px'];
              }
              return null;
            },
          ),
        ),
      );
}

const kHtml = """
<img class="size-full wp-image-319346" src="https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2.jpg" alt="aljamain-sterling" width="1200" height="800" srcset="https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2.jpg 1200w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-473x315.jpg 473w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-225x150.jpg 225w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-768x512.jpg 768w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-370x247.jpg 370w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-800x533.jpg 800w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-20x13.jpg 20w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-185x123.jpg 185w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-740x493.jpg 740w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-1110x740.jpg 1110w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-400x267.jpg 400w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200720031645/aljamain-sterling-2-72x48.jpg 72w" sizes="(max-width: 1200px) 100vw, 1200px" />
""";
```

</details>

The image looks different from the one in your screenshot by the way.

<img src="https://user-images.githubusercontent.com/239336/88420261-d1084480-ce10-11ea-9a83-f722d692d538.png" width="300" />

**Comment by shanu12joshi** [comment]
`<p><a href="https://www.ufc.com/athlete/gilbert-burns" target="_blank" rel="noopener noreferrer external" data-wpel-link="external">Gilbert Burns</a> has successfully defeated COVID-19. The UFC welterweight shared his latest negative result on <a href="https://twitter.com/GilbertDurinho/status/1285266694441775106" target="_blank" rel="noopener noreferrer external" data-wpel-link="external">Twitter</a>. With the medical condition behind him, Burns is aiming for a quick return to the Octagon.</p><blockquote class="twitter-tweet" data-width="550" data-dnt="true"><p lang="en" dir="ltr">Covid Free! 🙏🏾<br />Sem Corona! 🙏🏾 <a href="https://t.co/A6Pb4srIaP" data-wpel-link="external" target="_blank" rel="external noopener noreferrer">pic.twitter.com/A6Pb4srIaP</a></p><p>&mdash; GILBERT BURNS DURINHO (@GilbertDurinho) <a href="https://twitter.com/GilbertDurinho/status/1285266694441775106?ref_src=twsrc%5Etfw" data-wpel-link="external" target="_blank" rel="external noopener noreferrer">July 20, 2020</a></p></blockquote><p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p><p>&#8216;Durinho&#8217; was supposed to be one half of the UFC 251 headliner. However, a positive COVID-19 test forced him out of the fight. <a href="https://www.essentiallysports.com/tag/jorge-masvidal/" target="_blank" rel="noopener noreferrer" data-wpel-link="internal">Jorge Masvidal</a>, instead, came to the rescue and fought <a href="https://www.ufc.com/athlete/kamaru-usman" target="_blank" rel="noopener noreferrer external" data-wpel-link="external">Kamaru Usman</a>. Following his loss, Masvidal expressed his desire to run it back with Usman as soon as possible. However, Dana White wants to give the next shot to the original contender, Burns.</p><figure id="attachment_320829" aria-describedby="caption-attachment-320829" style="width: 960px" class="wp-caption alignnone"><img class="wp-image-320829 size-full" src="https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1.jpg" alt="Gilbert-Burns-1" width="960" height="640" srcset="https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1.jpg 960w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-473x315.jpg 473w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-225x150.jpg 225w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-768x512.jpg 768w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-370x247.jpg 370w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-800x533.jpg 800w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-20x13.jpg 20w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-185x123.jpg 185w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-740x493.jpg 740w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-400x267.jpg 400w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024618/Gilbert-Burns-1-1-72x48.jpg 72w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-320829" class="wp-caption-text">(Photo by Jeff Bottari/Zuffa LLC/Zuffa LLC via Getty Images)</figcaption></figure><p><em>&#8220;I’m very happy with the results from the test after being quarantined for two weeks at home,” </em>Burns said while talking to <a href="https://www.mmafighting.com/2020/7/21/21332586/gilbert-burns-very-happy-with-negative-covid-19-test-i-cant-wait-to-fight-for-the-title" target="_blank" rel="noopener noreferrer external" data-wpel-link="external">MMA Fighting</a><em>. “I’m thankful and very happy I can go back to my regular routine.”</em></p><p>Burns also tweeted that he will be back on training tomorrow. With Usman serving a 180-days medical <a href="https://www.essentiallysports.com/ufc-news-kamaru-usman-gets-180-days-medical-suspension-after-ufc-251-jorge-masvidal/" target="_blank" rel="noopener noreferrer" data-wpel-link="internal">suspension</a>, the UFC can aim for a title defense for Usman at the end of the year or the beginning of 2021.</p><blockquote class="twitter-tweet" data-width="550" data-dnt="true"><p lang="en" dir="ltr">Back on training tomorrow! 🔥🔥 <a href="https://t.co/dRDOgrMoP0" data-wpel-link="external" target="_blank" rel="external noopener noreferrer">pic.twitter.com/dRDOgrMoP0</a></p><p>&mdash; GILBERT BURNS DURINHO (@GilbertDurinho) <a href="https://twitter.com/GilbertDurinho/status/1285654786226950155?ref_src=twsrc%5Etfw" data-wpel-link="external" target="_blank" rel="external noopener noreferrer">July 21, 2020</a></p></blockquote><p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p><h2>Gilbert Burns can&#8217;t wait to put up a show for the fans</h2><p>Apart from Burns, the only legitimate contender for a title shot can be <a href="https://en.wikipedia.org/wiki/Leon_Edwards" target="_blank" rel="noopener noreferrer external" data-wpel-link="external">Leon Edwards</a>. The UFC originally went to the Brit when negotiations with Jorge Masvidal to fight against Kamaru Usman fell through. However, owing to the ongoing pandemic, Edwards didn&#8217;t accept the fight.</p><p>After Usman defeated Masvidal, there was a slight debate on who should fight for the belt next. Some argued that Burns should face-off against Edwards to decide the No. 1 contender. However, Dana White came to the rescue of Burns and <a href="https://www.essentiallysports.com/ufc-news-gilbert-burns-is-next-dana-white-shuts-down-a-title-rematch-for-jorge-masvidal/" target="_blank" rel="noopener noreferrer" data-wpel-link="internal">ensured</a> him that he will get the next shot at his training partner, Kamaru Usman.</p><figure id="attachment_320833" aria-describedby="caption-attachment-320833" style="width: 1200px" class="wp-caption alignnone"><img class="size-full wp-image-320833" src="https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1.jpg" alt="Gilbert-Burns-2" width="1200" height="800" srcset="https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1.jpg 1200w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-473x315.jpg 473w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-225x150.jpg 225w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-768x512.jpg 768w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-370x247.jpg 370w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-800x533.jpg 800w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-20x13.jpg 20w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-185x123.jpg 185w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-740x493.jpg 740w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-1110x740.jpg 1110w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-400x267.jpg 400w, https://image-cdn.essentiallysports.com/wp-content/uploads/20200722024847/Gilbert-Burns-2-1-72x48.jpg 72w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-320833" class="wp-caption-text">(Photo by Jeff Bottari/Zuffa LLC)</figcaption></figure><p id="vSYF6f">“<em>It was a hard pill to swallow, but I believe God has a plan for me</em>,” Burns said on What the Heck podcast. “<em>I just spoke with Dana White on Sunday and he said I’m next. He wants to see that fight: Burns vs. Usman. That’s the next fight.&#8221;</em></p><p id="7XF6Os">“<em>It was all for the best. I wasn’t feeling good and that was the only reason they took that title fight from me</em>. <em>I can’t wait to fight for the title and give a show for the fans,&#8221; </em>Burns added.</p><p>With COVID-19 behind him and ample time to prepare, Burns will look to capture UFC gold in his very first attempt.</p><p>The post <a rel="nofollow noopener noreferrer" href="https://www.essentiallysports.com/ufc-news-i-believe-god-has-a-plan-for-me-gilbert-burns/" data-wpel-link="internal" target="_blank">&#8220;I Believe God Has a Plan for Me&#8221; &#8211; Gilbert Burns</a> appeared first on <a rel="nofollow noopener noreferrer" href="https://www.essentiallysports.com" data-wpel-link="internal" target="_blank">EssentiallySports</a>.</p>`

**Comment by shanu12joshi** [comment]
It was working properly with   flutter_widget_from_html: 0.4.0-rc.2020043001
but not with 0.4.2

**Comment by shanu12joshi** [comment]
Found one more: 
![WhatsApp Image 2020-07-25 at 2 06 54 PM](https://user-images.githubusercontent.com/42548654/88452908-36474e80-ce80-11ea-9fc2-6165a2895307.jpeg)

**Comment by shanu12joshi** [comment]
Hey, @daohoangson Can you look into this issue?

**Comment by daohoangson** [comment]
This is happening because of the new sizing support in `0.4.2` and `0.5-rc`. Your HTML specify `style="width: 1200px"` so it tries to respect the requested width but obviously on small devices (e.g. phone), that will cause overflow. A new 0.4 release is going live that will disable sizing support to avoid this kind of error. I have also rewritten sizing support in 0.5 so it's smarter. Sorry for the inconvenience.

**Comment by shanu12joshi** [comment]
@daohoangson  Till when can I expect the release of a new version tom remove this error.

**Comment by daohoangson** [comment]
`v0.4.3` has been released. Please try upgrading and see whether it fixes your issue. Sorry for the inconvenience.

**Comment by shanu12joshi** [comment]
Yes this resolved the issue
Thanks for the update :)

**Comment by daohoangson** [comment]
That's great to hear! I'm closing this issue now 😍
