### ISSUE TITLE
How to change default Loading Indicator?

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [daohoangson/flutter_widget_from_html#255]
I saw that in new release you added CircularProgressIndicator() for loading html content. Can you tell how can I customize that? Tnx :D
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-25 at 13 54 42](https://user-images.githubusercontent.com/36572426/88456520-9a691300-ce7e-11ea-8b6b-b3e891a97b2f.png)

**Comment by daohoangson** [comment]
You can disable that one with `buildAsync: false`. Or customize it with `buildAsyncBuilder`, something like this:

```dart
          HtmlWidget(
            kHtml,
            buildAsyncBuilder: (_, snapshot) =>
                snapshot.hasData ? snapshot.data : Text('Please wait...'),
          ),
```

**Comment by aleksandar-radivojevic** [comment]
Thanks bro! 👍
