### ISSUE TITLE
Crash on Android 10 when loading html [Device specific]

### ISSUE THREAD

**Issue by ragu-swaminathan** [daohoangson/flutter_widget_from_html#257]
Team, 
We are getting the below crash in Android 10 , however same is working in other versions. 

`E/AndroidRuntime( 9037): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime( 9037): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1625)
E/AndroidRuntime( 9037): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1864)
E/AndroidRuntime( 9037): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1183)
E/AndroidRuntime( 9037): 	at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:185)
E/AndroidRuntime( 9037): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 9037): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 9037): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 9037): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 9037): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 9037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/eglCodecCommon( 9037): setVertexArrayObject: set vao to 2 (2) 0 0
W/CrashlyticsCore( 9037): Cannot send reports. Settings are unavailable.`

Below are the version details 
`flutter_widget_from_html: 0.4.1`

**Flutter versions :**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

Any help is appreciated.

**Comment by daohoangson** [comment]
The stack trace doesn't have any useful information.  Can you share the HTML that is causing issue in Android 10? And the Dart code if possible, I need to reproduce it on my end.

By the way, Flutter 1.17.3 is quite old, can you upgrade to latest stable?
