### ISSUE TITLE
Override `font-size` for entire widget?

### ISSUE THREAD

**Issue by markst** [daohoangson/flutter_widget_from_html#262]
We have multiple blocks of html from different sources, some which contain the `font-size` definitions such as:
```html
<p><span style=\"font-family:tahoma,verdana,arial,helvetica,bitstream vera sans,sans-serif; font-size:12px\">Progressive country, roots rock, singer/songwriters, Americana, bluegrass and more. Including new releases, interviews and gig guide.</span></p>
```

However since the font sizes aren't uniform, so we'd like to override the type size of the widget to always be the same. 

The `textStyle` doesn't appear to effect the font size, so I'm trying something such as:

```dart
return HtmlWidget(
  snapshot.data.description ?? "",
  customStylesBuilder: (e) {
    // Override font size?
    if (e.attributes.containsKey('style')) {
      return ['style', 'font-size:18px'];
    }
    return null;
  },
  textStyle: TextStyle(
      fontFamily: "GTWalsheimPro", fontSize: 16.0),
);
```

Is this the right idea? do I need to use a `WidgetFactory`?

https://github.com/daohoangson/flutter_widget_from_html/issues/11#issuecomment-469594432

**Comment by daohoangson** [comment]
Your return statement should be

```dart
return ['font-size', '18px'];
```

Other than that, it should work.

**Comment by markst** [comment]
thanks @daohoangson. unfortunately that doesn't make a difference

**Comment by daohoangson** [comment]
Ah, my bad. Yeah, it didn't work because `customStylesBuilder` ran too early and the font size is overwritten later by the inline styling. You will need a custom `WidgetFactory`, something like this:

```dart

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 262')),
        body: SingleChildScrollView(
          child: HtmlWidget(
            kHtml,
            factoryBuilder: () => _WidgetFactory(),
          ),
        ),
      );
}

class _WidgetFactory extends WidgetFactory {
  @override
  void parseStyle(NodeMetadata meta, String key, String value) {
    if (key == 'font-size') return;

    super.parseStyle(meta, key, value);
  }
}

const kHtml = """
<p><span style=\"font-family:tahoma,verdana,arial,helvetica,bitstream vera sans,sans-serif; font-size:12px\">Progressive country, roots rock, singer/songwriters, Americana, bluegrass and more. Including new releases, interviews and gig guide.</span></p>
""";

```

**Comment by markst** [comment]
Thanks @daohoangson, this solved it for me!

Ended up with something like this:
```dart
@override
void parseStyle(NodeMetadata meta, String key, String value) {
  switch (key) {
    case "font-size":
      return super.parseStyle(meta, key, "18px");
    case "font-family":
      return super.parseStyle(meta, key, "GTWalsheimPro");
    default:
      super.parseStyle(meta, key, value);
  }
```

**Comment by anisalibegic** [comment]
@daohoangson How to do the same with the new version when there is `String key` parameter in the `parseStyle` method?

**Comment by daohoangson** [comment]
@anisalibegic you probably asked about version `>0.6.0` when the `parseStyle` method removed the `key` param? This should work:


```dart
  @override
  void parseStyle(BuildMetadata meta, css.Declaration style) {
    switch (style.property) {
      case 'font-size':
      case 'font-family':
        // ignore all inline style font-size and family
        return;
    }

    super.parseStyle(meta, style);
  }
```

**Comment by anisalibegic** [comment]
> @anisalibegic you probably asked about version `>0.6.0` when the `parseStyle` method removed the `key` param? This should work:
> 
> ```dart
>   @override
>   void parseStyle(BuildMetadata meta, css.Declaration style) {
>     switch (style.property) {
>       case 'font-size':
>       case 'font-family':
>         // ignore all inline style font-size and family
>         return;
>     }
> 
>     super.parseStyle(meta, style);
>   }
> ```

Hmm... how do you provide a custom value in that case?

> ```dart
> @override
> void parseStyle(NodeMetadata meta, String key, String value) {
>   switch (key) {
>     case "font-size":
>       return super.parseStyle(meta, key, "18px");
>     case "font-family":
>       return super.parseStyle(meta, key, "GTWalsheimPro");
>     default:
>       super.parseStyle(meta, key, value);
>   }
> ```

Old approach would just pass the new value but how to do it now?

**Comment by daohoangson** [comment]
What is your use case @anisalibegic?

If you want to keep the default font for the entire HTML document, the above sample should work.

If you want to specific a specific font, use the above sample and pass in a `textStyle` when you create the `HtmlWidget`.

If you want to "redirect" font: keep default font X and use font Y2 if the inline font is Y1 then you can use `customStylesBuilder`.

**Comment by praveenb** [comment]
> @anisalibegic you probably asked about version `>0.6.0` when the `parseStyle` method removed the `key` param? This should work:
> 
> ```dart
>   @override
>   void parseStyle(BuildMetadata meta, css.Declaration style) {
>     switch (style.property) {
>       case 'font-size':
>       case 'font-family':
>         // ignore all inline style font-size and family
>         return;
>     }
> 
>     super.parseStyle(meta, style);
>   }
> ```

Hi, @daohoangson ,

based on this I understand inline font-size and font-family ignored.

but here how i can change font-size to 30px. I see  we cannot use below method 

`return super.parseStyle(meta, key, "18px");`


then how how we can submit to below method

`return super.parseStyle(meta, style);`

Please let us  know

Thank you

**Comment by daohoangson** [comment]
The quoted code will ignore font size and family.

If you want to change the size for some element, use `customStylesBuilder`. It'll be easier.

**Comment by praveenb** [comment]
Thanks for reply,

I tried `customStylesBuilder` as below, but I see its not working. 

```
customStylesBuilder: (e) {
              for (final style in e.styles) {
                if (style.property == 'font-size') {
                  return {'font-size': '18px'};
                }
              }
              return null;
            },
```

I see you mentioned as below, regarding this problem

> Ah, my bad. Yeah, it didn't work because `customStylesBuilder` ran too early and the font size is overwritten later by the inline styling. You will need a custom `WidgetFactory`, something like this:
> 
> ```dart
> class Test extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Scaffold(
>         appBar: AppBar(title: Text('Issue 262')),
>         body: SingleChildScrollView(
>           child: HtmlWidget(
>             kHtml,
>             factoryBuilder: () => _WidgetFactory(),
>           ),
>         ),
>       );
> }
> 
> class _WidgetFactory extends WidgetFactory {
>   @override
>   void parseStyle(NodeMetadata meta, String key, String value) {
>     if (key == 'font-size') return;
> 
>     super.parseStyle(meta, key, value);
>   }
> }
> 
> const kHtml = """
> <p><span style=\"font-family:tahoma,verdana,arial,helvetica,bitstream vera sans,sans-serif; font-size:12px\">Progressive country, roots rock, singer/songwriters, Americana, bluegrass and more. Including new releases, interviews and gig guide.</span></p>
> """;
> ```

as per above details, I see code will ignore `font-size` by override  `parseStyle` method of `WidgetFactory`. 

But any way to apply font-size in `parseStyle` method.

Thank you.

**Comment by daohoangson** [comment]
Let's consider this scenario:

- The default font size is 10 (via `DefaultTextStyle` for example)
- The inline font size is 20 (something like `style="font-size: 20px"`)

Specifying font size 30 in `customStylesBuilder` won't work for this because the inline 20 will override it. You will need to override `parseStyle` like this:

https://try.fwfh.dev/?id=26369730c2b1b26657e8bbdc830f96fb

```dart

  @override
  void parseStyle(BuildMetadata meta, css.Declaration style) {
    if (style.property == 'font-size') {
      meta.tsb.enqueue((tsh, _) {
        final style = tsh.style.copyWith(fontSize: 30);
        return tsh.copyWith(style: style);
      });
      return;
    }

    super.parseStyle(meta, style);
  }

```

Yeah, the api usage is still cumbersome. I'm working on simplifying it.
