### ISSUE TITLE
Text Overflow

### ISSUE THREAD

**Issue by MGD1** [daohoangson/flutter_widget_from_html#268]
i want to use ellipses when the text overflows but this isn't working. what am I missing?.... 
![Capture](https://user-images.githubusercontent.com/23202122/89932090-b2f16100-dbd2-11ea-9b80-d246d2770ceb.PNG)

**Comment by daohoangson** [comment]
That looks correct to me. How did it render?

**Comment by MGD1** [comment]
It renders the text but ellipsis doesn't work

**Comment by daohoangson** [comment]
Do you have something else configured? e.g. custom `WidgetFactory`? I have just ran this sample code and it seems to work with both latest 0.4 and 0.5 versions.

<details>

<summary>test.dart</summary>

```dart
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 268')),
        body: SingleChildScrollView(
          child: HtmlWidget(
            kHtml,
          ),
        ),
      );
}

const kHtml = """
<h4 style="text-overflow: ellipsis; max-lines: 2">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat iaculis odio, vel lacinia est bibendum eget. Aenean dapibus mauris nulla, nec convallis dui accumsan eu. Quisque vitae nisl dolor. Donec a nisl vitae augue sodales sodales eget eu nunc. Sed a mattis nibh. Nullam tincidunt ipsum ut eros semper iaculis. Proin posuere a ipsum quis pharetra. Pellentesque eget eros malesuada tortor hendrerit venenatis. In hac habitasse platea dictumst. Duis nec sapien a lacus volutpat elementum vel nec lacus. Nunc eget finibus lorem. Nullam non bibendum nisl. Nam eget accumsan arcu.
</h4>
""";

```

</details>

<img src="https://user-images.githubusercontent.com/239336/89937144-e4a01180-dc3e-11ea-862f-c152b425f5b9.png" width="300" />

**Comment by MGD1** [comment]
I do have my text in a custom widget similar to a List Tile.  Would that
cause a problem?

**Comment by daohoangson** [comment]
It shouldn't. Can you provide a simplified version so I can reproduce the issue from my end?

**Comment by MGD1** [comment]
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class PostTile extends StatelessWidget {
  const PostTile({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: () {},
      child: Container(
        width: MediaQuery.of(context).size.width,
        height: 155,
        child: Row(
          children: <Widget>[
            Flexible(
              flex: 6,
              child: Padding(
                padding: const EdgeInsets.only(left: 10.0),
                child: CachedNetworkImage(
                  fit: BoxFit.cover,
                  imageUrl: "Image goes here",
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                ),
              ),
            ),
            Flexible(
              flex: 10,
              child: Padding(
                padding: const EdgeInsets.symmetric(
                    vertical: 15.0, horizontal: 15.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Flexible(
                      flex: 3,
                      child: Text(
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In blandit, lectus porttitor porta viverra, libero.",
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    Flexible(
                      flex: 8,
                      child: HtmlWidget(
                        """<h4 style= "text-overflow:ellipsis; max-lines: 2;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In blandit, lectus porttitor porta viverra, libero.}</h5>""",
                        bodyPadding: EdgeInsets.only(right: 8.0),
                      ),
                    ),
                    Flexible(
                      flex: 3,
                      child: Text(
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In blandit, lectus porttitor porta viverra, libero.",
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by daohoangson** [comment]
Oh, you are using version 0.3? That version is very old and doesn't have `text-overflow` support. You need to update to at least 0.4.2 for that (see the [change log](https://github.com/daohoangson/flutter_widget_from_html/blob/v0.4.3/CHANGELOG.md#042)).

**Comment by MGD1** [comment]
ahhh let me do that

**Comment by MGD1** [comment]
works!!! thanks for your help and sorry about that lol
