### ISSUE TITLE
How to change URL behavior?

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#28]
> because the fact that extended plugin does handle URLs only through URL launcher, I needed to use the core plugin and manually copy the extended settings to detect URLs and override them with the behavior I want (Open customized webview)

**Comment by daohoangson** [comment]
Sample code below. There are a few important notes after the code btw.

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart'
    show BuildOp, BuiltPiece, BuiltPieceSimple;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'issue28',
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('issue28')),
        body: HtmlWidget(
          "<h1>How to change URL behavior?</h1>" +
              "GitHub issue: <a href=\"https://github.com/daohoangson/flutter_widget_from_html/issues/28\">click here</a>.",
          wfBuilder: (context) => MyWidgetFactory(context),
        ),
      );
}

class MyWidgetFactory extends WidgetFactory {
  MyWidgetFactory(BuildContext context) : super(context, Config());

  @override
  BuildOp tagA(String url) => BuildOp(onPieces: MyTagA(url, this).onPieces);
}

class MyTagA {
  final String url;
  final WidgetFactory wf;

  MyTagA(this.url, this.wf);

  Widget buildGestureDetector(Widget child, GestureTapCallback onTap) =>
      child != null ? GestureDetector(onTap: onTap, child: child) : null;

  List<BuiltPiece> onPieces(List<BuiltPiece> pieces) {
    List<BuiltPiece> newPieces = List();

    final onTap = prepareGestureTapCallback(url);
    final recognizer = TapGestureRecognizer()..onTap = onTap;

    for (final piece in pieces) {
      if (piece.hasTextSpan) {
        newPieces.add(BuiltPieceSimple(
          textSpan: rebuildTextSpanWithRecognizer(piece.textSpan, recognizer),
        ));
      } else if (piece.hasWidgets) {
        final gd = buildGestureDetector(wf.buildColumn(piece.widgets), onTap);
        if (gd != null) {
          newPieces.add(BuiltPieceSimple(widgets: <Widget>[gd]));
        }
      }
    }

    return newPieces;
  }

  GestureTapCallback prepareGestureTapCallback(String url) => () => showDialog(
        context: wf.context,
        builder: (_) => AlertDialog(content: Text(url), title: Text('MyTagA')),
      );

  // this is required because of https://github.com/flutter/flutter/issues/10623
  TextSpan rebuildTextSpanWithRecognizer(TextSpan span, GestureRecognizer r) =>
      TextSpan(
        children: span?.children == null
            ? null
            : span.children
                .map((subSpan) => rebuildTextSpanWithRecognizer(subSpan, r))
                .toList(),
        style: span?.style,
        recognizer: r,
        text: span?.text,
      );
}
```

Notes:

- Next version of the plugin will change the `BuildOp` method signature, so this sample will only work with v0.1.5 and before.
- Good news is: next version will move the `prepareGestureTapCallback` method into `WidgetFactory` so you won't need to implement `MyTagA` just to change the on tap behavior. A new sample code will be posted at a later date.

**Comment by tekno0ryder** [comment]
Thanks for your response!
It works perfectly, but i ran into a minor problem that URLs with the format starting with (www) are styled but not getting onTap geasture

Fixed by replacing the following line in widget.factory.dart: 

`final _isFullUrlRegExp = RegExp(r'^(https?://|mailto:|tel:)');`
with 
`final _isFullUrlRegExp = RegExp(r'^(https?://|mailto:|tel:|www)');`

**Comment by daohoangson** [comment]
@tekno0ryder you meant the html is something like below?

```html
<a href="www.google.com">Google</a>
```

**Comment by tekno0ryder** [comment]
> @tekno0ryder you meant the html is something like below?
> 
> ```
> <a href="www.google.com">Google</a>
> ```

Exactly

**Comment by daohoangson** [comment]
Technically that link is incorrect. For example: if you are on `https://github.com` and click that link, the browser will redirect to `https://github.com/www.google.com` instead of Google home page...

**Comment by tekno0ryder** [comment]
> Technically that link is incorrect. For example: if you are on `https://github.com` and click that link, the browser will redirect to `https://github.com/www.google.com` instead of Google home page...

yes but webview doesn't redirect to http version, that's why i had to do it myself if in case i received non-http link

**Comment by daohoangson** [comment]
In the next release, invalid url like `www.google.com` will be forwarded to the on tap handler. By default it won't do anything because `canLaunch()` returns false but you will be able to catch that event and handle yourself 👍

**Comment by daohoangson** [comment]
v0.2.0 has been released, it is now very easy to customize on tap behavior for url. Just pass your own function into `onTapUrl` like this:

```dart
      return HtmlWidget(
          kHtml,
          onTapUrl: (url) => doYourOwnThing(url),
        );
```

See full example code here https://github.com/daohoangson/flutter_widget_from_html/blob/master/packages/example/lib/screens/hello_world_core.dart

**Comment by tekno0ryder** [comment]
Thanks, this is much cleaner.

**Comment by mcavazotti** [comment]
the `onTap` callback is fired only if the URL is valid, right? wouldn't it be better if `onTap` was called regardless the URL is valid or not?
For example, I could use the links in the HTML to control the routing in my app.

**Comment by daohoangson** [comment]
Yes, that's true. That has been changed in the `master` branch, starting from the next 0.5 release `onTapUrl` will be triggered for incomplete URL too.
