### ISSUE TITLE
Continue playing video after pop the page using iframe

### ISSUE THREAD

**Issue by spporan** [daohoangson/flutter_widget_from_html#298]
When playing a video using iframe then page pop  without pausing this video ,after word this video is playing

**Comment by daohoangson** [comment]
This is a Flutter bug, I have reported it here https://github.com/flutter/flutter/issues/32363.

This package has implemented a workaround for this bug, you can turn it on like this:

```dart
          HtmlWidget(
            html,
            unsupportedWebViewWorkaroundForIssue37: true,
            webView: true,
          ),
```

**Comment by spporan** [comment]
I also face this issue when pop this page  

/MethodChannel#flutter/platform_views(25366): Failed to handle method call
E/MethodChannel#flutter/platform_views(25366): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map
E/MethodChannel#flutter/platform_views(25366): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:113)
E/MethodChannel#flutter/platform_views(25366): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:62)
E/MethodChannel#flutter/platform_views(25366): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter/platform_views(25366): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(25366): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:681)
E/MethodChannel#flutter/platform_views(25366): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(25366): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(25366): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter/platform_views(25366): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter/platform_views(25366): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(25366): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter/platform_views(25366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (25366): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.util.Map, null)
E/flutter (25366): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (25366): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (25366): <asynchronous suspension>
E/flutter (25366): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (25366): #3      AndroidViewController.dispose (package:flutter/src/services/platform_views.dart:534:43)
E/flutter (25366): #4      _AndroidViewState.dispose (package:flutter/src/widgets/platform_view.dart:494:17)
E/flutter (25366): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
E/flutter (25366): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
E/flutter (25366): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (25366): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (25366): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (25366): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (25366): #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (25366): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (25366): #40     _InactiveElements._unmount.

**Comment by daohoangson** [comment]
Looks like something deep encountered an error. I assume the app didn't crash when this happened, is that correct?
Can you share the code so I can try reproducing it on my end?

**Comment by spporan** [comment]
yes, app didn't crash

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';



class VideoPlayerPage extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return _VideoPlayerState();
  }

}
class _VideoPlayerState extends State <VideoPlayerPage>{
  
  String html ;
  
  @override
  void initState() {


    super.initState();
  }
  @override
  void didChangeDependencies() {
    var args=ModalRoute.of(context).settings.arguments;
    html =  "<p><iframe src=\"$args;show_text=0&amp;width=560\" width=\"560\" height=\"315\" style=\"border:none;overflow:hidden\" scrolling=\"no\" frameborder=\"0\" allowtransparency=\"true\" allowfullscreen></iframe></p>";
    super.didChangeDependencies();
  }


  @override
  Widget build(BuildContext context) {
   return Scaffold(
     appBar: AppBar(
       elevation: 0,
     ),
     body:Center(
       child: Container(

         child:
         HtmlWidget(
          html,
           unsupportedWebViewWorkaroundForIssue37: true,
           webView: true,
         ),
       ),
     ),
   );
  }
}

**Comment by daohoangson** [comment]
That's an interesting way to use it you have there. Is it possible to give me an URL so I can run your code? Also, did you test with a real Android device or it was an emulator? Which Android version?

Please also confirm Flutter version (`flutter doctor -v`) and package version. Are you using flutter_widget_from_html version `0.4` or the `0.5` rc?

**Comment by spporan** [comment]
I tested real android device which was Mi note 5 and android version 9.

https://www.youtube.com/watch?v=ab9HctaAtaU

I'm using flutter_widget_from_html 0.4.3 

flutter doctor -v

poran-lab@poran-lab-HP-ProBook-440-G5:~$ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /home/poran-lab/development/flutter
    • Framework revision 0e735e4bca (8 weeks ago), 2020-06-30 18:54:02 -0700
    • Engine revision 2dc202d823
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /home/poran-lab/Android/Sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = /home/poran-lab/Android/Sdk
    • ANDROID_SDK_ROOT = /home/poran-lab/Android/Sdk
    • Java binary at: /home/poran-lab/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/poran-lab/development/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

**Comment by daohoangson** [comment]
Hmm, I couldn't replicate this on Note9 / Android 10. This is probably an issue with Xiaomi and their MIUI OS. Can you try with another phone?

This kind of error happens sometime with Flutter's platform view. They are not as stable as other widgets. I have heard a new WebView plugin is coming out soon from the Flutter team, maybe it'll be better than the current one. For the time being, not much can be done here. Sorry...
