### ISSUE TITLE
How can I change the hyperlink color?

### ISSUE THREAD

**Issue by winsonet** [daohoangson/flutter_widget_from_html#3]
I want to change the hyperlink style , e.g the color, how can I don that?

thanks!

**Comment by daohoangson** [comment]
It will use the accent color from the theme. You can wrap it like this:

```dart
return Theme(
    data: Theme.of(context).copyWith(accentColor: hyperlinkColor),
    child: HtmlWidget(html),
);
```

**Comment by winsonet** [comment]
Oh, thanks, but what if I also need to change the font size? it seem difficult , i also need to wrap it into a DefaultTextStyle ?

**Comment by daohoangson** [comment]
Yep, for text styling just wrap it inside a `DefaultTextStyle`. You can change the font family, size, anything.

**Comment by winsonet** [comment]
I see, thanks a lot!
