### ISSUE TITLE
Update the dependency

### ISSUE THREAD

**Issue by omishah** [daohoangson/flutter_widget_from_html#313]
So, currenly I am using 

```
  flutter_svg: ^0.18.1
  flutter_widget_from_html: ^0.5.0+3
```
Now, there is a newer version of `flutter_svg: ^0.19.0` but whenever I try to use the newer version, I get build error:

> Because flutter_widget_from_html 0.5.0+3 depends on flutter_svg ^0.18.0 and no versions of flutter_widget_from_html match >0.5.0+3 <0.6.0, flutter_widget_from_html ^0.5.0+3 requires flutter_svg ^0.18.0.
> So, because singrauli depends on both flutter_svg ^0.19.0 and flutter_widget_from_html ^0.5.0+3, version solving failed.

Looks like you need to update the `flutter_svg` version in this project.

**Comment by daohoangson** [comment]
That can be done fairly easy but I don't have my laptop right now. As a temporary workaround for your app, you can use `dependency_overrides` to force 0.19.

**Comment by daohoangson** [comment]
PR #315 has been merged to address this. The latest release includes this change already. I'm closing this issue for now.
