### ISSUE TITLE
Hyperlink - add pointer cursor by default, important for Flutter web.

### ISSUE THREAD

**Issue by slavap** [daohoangson/flutter_widget_from_html#316]
Something like that when standard widget for hyperlink is building:
```dart
MouseRegion(
  cursor: SystemMouseCursors.click,
  child: ...
```

**Comment by daohoangson** [comment]
This can be done for link that is an image or some widget but won't work for inline link because `TextSpan` doesn't allow us to specify a cursor.

**Comment by slavap** [comment]
@daohoangson MouseRegion can take TextSpan as child I believe.

**Comment by daohoangson** [comment]
I have just double checked, `MouseRegion` only takes `Widget` as child so it's definitely won't work.

You are probably confused between:
- `TextSpan` (which is an `InlineSpan`)
- and `Text` / `RichText` (which are widgets)?

**Comment by slavap** [comment]
@daohoangson 
Yep, I see. There is issue for adding hover gesture recognizer https://github.com/flutter/flutter/issues/33312
When it is fixed, I think it will be possible to fix this one as well.

**Comment by daohoangson** [comment]
Yes, in the mean time I have added mouse region for widgets. You can try it here:

https://example-c0xyfny5z.vercel.app/#/images

This inline image as link should have the cursor on hover:

<img width="383" alt="Screen Shot 2020-09-25 at 09 14 22" src="https://user-images.githubusercontent.com/239336/94218869-a705f800-ff0f-11ea-84c0-4c4dff7f2ad3.png">

**Comment by daohoangson** [comment]
A pre-release version has been published with support for mouse cursor, it requires Flutter 2.2 (that's why it's pre-release). Update your pubspec into something like this:

```yaml
dependencies:
  flutter_widget_from_html: ^0.7.0-0
```

Let me know if it works for you.

**Comment by slavap** [comment]
@daohoangson 
Tested on flutter_widget_from_html_core: ^0.7.0-dev.2021052101
Works just fine, thank you!

**Comment by slavap** [comment]
@daohoangson Correction to my previous comment. Works fine in Flutter Web, but on Android - still no pointer cursor :-(

**Comment by daohoangson** [comment]
You connect a wireless mouse to your phone?

**Comment by slavap** [comment]
@daohoangson Sounds like you are right, I need to test on real Android with connected mouse, not on emulator.

**Comment by daohoangson** [comment]
Yes, I think you need a real device to test this.
