### ISSUE TITLE
Error: No named parameter with the name 'overflow'.

### ISSUE THREAD

**Issue by shofi-ishraak** [daohoangson/flutter_widget_from_html#319]
../../../.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html_core-0.5.0+3/lib/src/core_widget_factory.dart:140:9: Error: No named parameter with the name 'overflow'.
        overflow: Overflow.visible,
        ^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/basic.dart:3273:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^

Related issue : https://github.com/flutter/flutter/issues/66135

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

**Comment by daohoangson** [comment]
Yes, there is some in compatibility with dev channel at the moment. I'll probably publish a pre-release to address it.

**Comment by bahador-r** [comment]
same issuse +1

**Comment by daohoangson** [comment]
After https://github.com/flutter/flutter/pull/66305, dev channel should work again. I think it'll take a few days to reach dev channel. If you are on the bleeding edge, try master channel maybe?

**Comment by bahador-r** [comment]
@daohoangson  any error was not display in the `master channel`.

**Comment by daohoangson** [comment]
> no error was in the master channel.

Yes, that's expected. But I'm releasing a new version soon anyway.

**Comment by daohoangson** [comment]
`v0.5.0+5` has been released!
