### ISSUE TITLE
custom text blocks

### ISSUE THREAD

**Issue by gtyhn** [daohoangson/flutter_widget_from_html#325]
how do I add a background color to a block of text, or can I customize a background style?

![aaa](https://user-images.githubusercontent.com/8544251/94283012-136e0f00-ff83-11ea-8ac0-e6d31d5d15a0.png)

**Comment by daohoangson** [comment]
> how do I add a background color to a block of text

You can use `background-color: #ccc` for that.

> can I customize a background style

Currently it's not possible to further customize the background style. If you want the blue bar on the left, you will need to use custom `WidgetFactory` with a `BuildOp`, something like this:

<details>

<summary>test.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 325')),
        body: SingleChildScrollView(
          child: Padding(
            child: HtmlWidget(
              kHtml,
              factoryBuilder: () => _MyWidgetFactory(),
            ),
            padding: const EdgeInsets.all(8.0),
          ),
        ),
      );
}

class _MyWidgetFactory extends WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    if (meta.element.classes.contains('highlight')) {
      meta.register(BuildOp(
        onWidgets: (meta, widgets) => listOrNull(
          buildColumnPlaceholder(meta, widgets).wrapWith(
            (context, child) => Container(
              child: child,
              decoration: BoxDecoration(
                border: Border(
                  left: BorderSide(
                    color: Theme.of(context).accentColor,
                    width: 3,
                  ),
                ),
              ),
              padding: EdgeInsets.fromLTRB(8, 8, 0, 8),
            ),
          ),
        ),
      ));
    }

    super.parse(meta);
  }
}

const kHtml = '''
<p>Blah blah blah.</p>

<p style="background-color: #ccc; padding: 8px;">Hello</p>

<p class="highlight">This is awesome!</p>

<p>More rambling...</p>
''';
```

</details>


<img src="https://user-images.githubusercontent.com/239336/94308036-1a574a80-ffa0-11ea-9f14-26de00ce2c7a.png" width="300" />

**Comment by gtyhn** [comment]
can you provide a callback method after processing the child nodes so that the parent decides how to build the background style. like the following

```dart
  final _Op = BuildOp(
      onParent: () {
        return Container(
          padding: EdgeInsets.all(10),
          width: double.infinity,
          decoration: BoxDecoration(
            color: Colors.grey,
            borderRadius: BorderRadius.circular(3.0),
          ),
        );
      },
  ); 
```

of course, this is only a suggestion, i don't know whether it is feasible, for example, i want to customize a tag and then build a parent node style that also includes multiple rows of children，how can I achieve this effect?

```html
<keyword>
	<p>hello world1</p>
	<p>hello world2</p>
	<p>hello world3</p>
</keyword>
```

**Comment by daohoangson** [comment]
You can use `onWidgets` as in the sample code above. Click the "test.dart" link to expand the full source code FYI.

**Comment by gtyhn** [comment]
thank you very much for using onWidgets to achieve what i want, and the freedom to build custom tag background styles. thanks again
