### ISSUE TITLE
video_player 0.11.0 already available

### ISSUE THREAD

**Issue by eltonmorais** [daohoangson/flutter_widget_from_html#332]
There's a dependency linked to 0.10.12 version of video_player. Please, update it to 0.11.0

**Comment by daohoangson** [comment]
We are working on PR #330 to address this.

**Comment by daohoangson** [comment]
`v0.5.0+6` has been released, this version will gladly accept video_player v0.11.0 (and up) as a dependency. Howerver, `chewie` (another dep of this package) hasn't been updated yet so you still need `dependency_overrides` for now.

In v0.6, I'm moving to drop `chewie` as a dependency and implement the audio/video player directly within this package...
