### ISSUE TITLE
Make Image in html Zoomable

### ISSUE THREAD

**Issue by adawi9** [daohoangson/flutter_widget_from_html#343]
How I can make Image in html zoomable?
If this not available can you add this feature as prosperity build in by default this will be great feature

**Comment by daohoangson** [comment]
I'm not sure whether you wanted inline zoomable or popup (tapping the image opens a new screen to interact with it) so I did it both ways.

### Inline

Overriding `WidgetFactory.buildImage` is enough for this.

```dart
  @override
  Widget buildImage(BuildMetadata meta, Object provider, ImageMetadata data) {
    if (provider is ImageProvider) {
      return AspectRatio(
        aspectRatio: 16.0 / 9.0,
        child: ClipRect(
          child: PhotoView(
            imageProvider: provider,
          ),
        ),
      );
    }

    return super.buildImage(meta, provider, data);
  }
```

- `provider is ImageProvider` check is needed because `provider` is not always an `ImageProvider` (e.g. SVG image support)
- `AspectRatio` is needed because `PhotoView` doesn't work if its constraints are unlimited.
- `ClipRect` is needed to avoid the zoomed image being leaked outside of the box

### Popup

Overrides `WidgetFactory.buildImage` again:

```dart
  @override
  Widget buildImage(BuildMetadata meta, Object provider, ImageMetadata data) {
    final built = super.buildImage(meta, provider, data);

    if (provider is ImageProvider) {
      final heroTag = data.sources.first.url;

      return Builder(
        builder: (context) => GestureDetector(
          child: Hero(
            child: built,
            tag: heroTag,
          ),
          onTap: () => Navigator.of(context).push(MaterialPageRoute(
              builder: (_) => Scaffold(
                    appBar: AppBar(),
                    body: Container(
                      child: PhotoView(
                        heroAttributes: PhotoViewHeroAttributes(tag: heroTag),
                        imageProvider: provider,
                      ),
                    ),
                  ))),
        ),
      );
    }

    return built;
  }
```

- `GestureDetector` to capture the tab
- `heroTag` for the next animation on screen transition

Web demo: https://example-n7431ongd.vercel.app/#/photoview

**Comment by daohoangson** [comment]
For full source code, check our the PR #348.

**Comment by adawi9** [comment]
Great!
Thank you

**Comment by emvaized** [comment]
@daohoangson 
In my case photo heroes are not precisely animated into each other on transition for whatever reason... Same code on another screen works just fine
![demo](https://user-images.githubusercontent.com/37851576/103244508-ece6b800-4965-11eb-978e-3273557b7445.gif)

Tried the exact code from PR #348, got the same result

**Comment by daohoangson** [comment]
The hero tag was the image url. It may animate incorrectly if you have more than one image with the same URL? Can you share your exact code and HTML?

**Comment by emvaized** [comment]
@daohoangson 
I use the same code as in pull request example, like the following:
```

if (provider is ImageProvider) {
      final photoUrl = data.sources.first.url;

      return Builder(
        builder: (context) => GestureDetector(
          child: Hero(
          onLongPress: () => print('long press on photo'),
          onTap: () {            
            Navigator.of(context).push(new TransparentMaterialPageRoute<Map>(
                maintainState: true,
                builder: (BuildContext context) {
                  return PhotoViewForOverlay(
                    photo: photoUrl,
                    heroTag: photoUrl,
                  );
                }));
          },
        ),
      );
    }
```

And wrapping Image in `PhotoViewForOverlay` in Hero with `widget.heroTag`
