### ISSUE TITLE
Should check the var 'value' is null or not at that line

### ISSUE THREAD

**Issue by sweatfryash** [daohoangson/flutter_widget_from_html#349]
Hi,at this file `flutter_widget_from_html/packages/core/lib/src/internal/margin_vertical.dart` line 33,should check the var `value` is null or not,this var could be null sometimes and then causes issue.Maybe you could check that code and fix it.
Like this
`if (value !=null && value > existing) return SizedBox(height: value);`

**Comment by daohoangson** [comment]
I think this is a great suggestion, `CssLength.getValue` does return `null` sometime. Can you open a PR? I'm more than happy to merge this fix.

**Comment by sweatfryash** [comment]
I'm sorry I'm not familiar with those operations like PR,you just go to fix it will be better.And thanks to your quick reply,I will just close this issue.
