### ISSUE TITLE
Youtube no fullscreen

### ISSUE THREAD

**Issue by cschellhas** [daohoangson/flutter_widget_from_html#35]
Can not open Fullscreen on Android.

example html:
`    <iframe width="560" height="315" src="https://www.youtube.com/embed/1f0sjiGtWIQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
`

Implementation:
`return  new HtmlWidget(
                kkhtml,
                webView: true,
                onTapUrl: (url) => showGalleryPage(nachricht.imageList)//showDialog(
            );`

**Comment by daohoangson** [comment]
I'm aware of this issue. Unfortunately, this seems to be the case with all implementations of this kind. e.g. if you use React Native and render a Web View of YouTube, it won't be able to go fullscreen.

**Comment by daohoangson** [comment]
webview_flutter_android@3.10.0 has added support for fullscreen in Android. #1022 is being worked on to address this.

**Comment by daohoangson** [comment]
`v0.10.5+3` and the latest `v0.14` has been supported this for a while. I'm closing this issue for good.
