### ISSUE TITLE
[web] <pre><code> tags don't format correctly

### ISSUE THREAD

**Issue by Bobleyl** [daohoangson/flutter_widget_from_html#350]
When trying to use a combination of tags (pre and code) in order to display a code block on web, the library formats it onto a single line, cutting off anything that doesn't fit past ~50 characters.  Have not looked to see if issue occurs on mobile as well, but on web, this combination doesn't render properly.  Here is a sample HTML where it breaks:

```
<body>
<pre><code>void showAlertDialog(BuildContext context) {
	showDialog(
		context: context,
		builder: (BuildContext context) {
			return CustomAlertDialog(
				content: Container(
					width: MediaQuery.of(context).size.width / 1.3,
					height: MediaQuery.of(context).size.height / 2.5,
					decoration: new BoxDecoration(
						shape: BoxShape.rectangle,
						color: const Color(0xFFFFFF),
						borderRadius: new BorderRadius.all(new Radius.circular(32.0)),
					),
					child: //Contents here
				),
			);
		},
	);
}
</code></pre>
</body>
```

**Comment by daohoangson** [comment]
This appears to be a Flutter web issue, it looks fine on mobile:

<img src="https://user-images.githubusercontent.com/239336/95940293-2b111880-0e08-11eb-8583-7fea890b4079.png" width="300" />

**Comment by Bobleyl** [comment]
yes, that's what the issue is for.  Web support for this package doesn't format the pre, code tags properly as it says it does in the documentation.

**Comment by daohoangson** [comment]
Flutter web is still unstable and its has new issues regularly (and old bugs go away equally as fast). After Web reaches stable, we will add more web-focused testing to ensure the package works correctly across all supported platforms.

**Comment by daohoangson** [comment]
The latest stable works correctly on Flutter Web, I have just run it again 🎉

<img width="612" alt="Screen Shot 2021-06-19 at 01 13 35" src="https://user-images.githubusercontent.com/239336/122601547-a6b01d00-d09b-11eb-861f-69deb05a1a4a.png">
