### ISSUE TITLE
Custom Widget Builder not Working on <table> <iframe> <video> tag

### ISSUE THREAD

**Issue by sushilbalami** [daohoangson/flutter_widget_from_html#351]
if (element.localName == 'table') {
      return yourWidget();
    }

return nothing if we set our custom widget and return on when table tag .. nothing is rendered..

same on iframe too why any solution to it ?

**Comment by daohoangson** [comment]
I have been able to reproduce this bug. Working on a fix.

**Comment by daohoangson** [comment]
`v0.5.1+2` has been released with the fix for this. Please try upgrading and let me know if it works for you.

Thank you.

**Comment by sushilbalami** [comment]
Ok I will try and will notify here today.... 
Is it fixed for iframe too ? Iframe is also causing same problem ! 😁

**Comment by daohoangson** [comment]
Ah, I have just tested TABLE and VIDEO. But it should fix IFRAME too.

**Comment by sushilbalami** [comment]
Thank you it's fixed now !
