### ISSUE TITLE
flutter_widget_from_html: ^0.5.1+3  视频问题

### ISSUE THREAD

**Issue by wangchao1016** [daohoangson/flutter_widget_from_html#355]
![image](https://user-images.githubusercontent.com/27325259/96073632-6596b600-0ed9-11eb-997e-79a9f57853ec.png)

视频提示框模糊，全屏展示提示框是好的，我的flutter 版本是 1.22.1

**Comment by daohoangson** [comment]
Can you comment in English please?

**Comment by wangchao1016** [comment]
The video prompt box is fuzzy. It's good to display the prompt box in full screen. My version of flutter is 1.22.1

**Comment by daohoangson** [comment]
Ah, I see. The video player is blurred as in your screenshot? That's weird, can you provide the HTML that has been used to render the screen.

Btw, you are reporting an issue for the package `flutter_widget_from_html`. It's a different package from `flutter_html` as mentioned in your AppBar. I get it that you are using version `0.5.1+3` with Flutter `1.22.1`?

**Comment by wangchao1016** [comment]
I tried it again on a real machine, The bug disappeared.Thank you for the answer

**Comment by daohoangson** [comment]
Ah, that's good to hear. Previously video playback doesn't work on iOS simulator at all. I think simulator support is pretty new, Flutter 1.22 I think.

I'm closing this issue now btw.
