### ISSUE TITLE
My app update got rejected today, because of Device and Network Abuse policy they have attached an image where I am using the HtmlWidget

### ISSUE THREAD

**Issue by shanu12joshi** [daohoangson/flutter_widget_from_html#357]
My app update got rejected today, because of Device and Network Abuse policy they have attached an image where I am using the HTML widget, here's more detail.

![ufc mma news messenger-InAppExperience-191](https://user-images.githubusercontent.com/42548654/97011971-f702c980-1564-11eb-95fc-64cc2075bdee.png)

Is it because we have a share option on youtube?

**Comment by daohoangson** [comment]
Probably because Flutter web view doesn't stop itself if the app is paused (see #37, #135). Try enabling `unsupportedWebViewWorkaroundForIssue37=true` if you expect to have video iframes in your app.
