### ISSUE TITLE
[text-align]-It works fine on initial rendering, but fails after next rendering (like hot reload)

### ISSUE THREAD

**Issue by yhf1414104530** [daohoangson/flutter_widget_from_html#359]
<img width="360" alt="QQ20201101-173442@2x" src="https://user-images.githubusercontent.com/19488692/97799382-eccd8300-1c68-11eb-8e36-fbb20ab214b3.png">

<img width="362" alt="QQ20201101-173620@2x" src="https://user-images.githubusercontent.com/19488692/97799355-c576b600-1c68-11eb-9fb5-750e78a92001.png">

**Comment by daohoangson** [comment]
`v0.5.1+4` has been released with the fix for this. Please consider updating and see whether it works for you. Thank you.
