### ISSUE TITLE
Update path provider dependency to path_provider 1.0.0

### ISSUE THREAD

**Issue by khalithartmann** [daohoangson/flutter_widget_from_html#36]
getting : 
Because no versions of flutter_widget_from_html match >0.2.0 <0.3.0 and flutter_widget_from_html 0.2.0 depends on cached_network_image ^0.7.0, flutter_widget_from_html ^0.2.0 requires cached_network_image ^0.7.0.
And because no versions of cached_network_image match >0.7.0 <0.8.0 and cached_network_image 0.7.0 depends on flutter_cache_manager ^0.3.2, flutter_widget_from_html ^0.2.0 requires flutter_cache_manager ^0.3.2.
Because flutter_cache_manager 0.3.2 depends on path_provider ^0.5.0+1 and no versions of flutter_cache_manager match >0.3.2 <0.4.0, flutter_cache_manager ^0.3.2 requires path_provider ^0.5.0+1.
Thus, flutter_widget_from_html ^0.2.0 requires path_provider ^0.5.0+1.
So, because peqas depends on both flutter_widget_from_html ^0.2.0 and path_provider 1.0.0, version solving failed.
 when trying to install path_provider plugin 1.0.0

**Comment by daohoangson** [comment]
I will release a new version with version bump for dependencies. In the meantime, can you use `any` in your pubspec as a temporary workaround?

**Comment by daohoangson** [comment]
The dependency of this plugin (`cached_network_image`) depends on an old version of `path_provider` so there is no way for me to bump the version at the moment. If you have to use `path_provider@1.0.0` in your app, please use [flutter_widget_from_html_core](https://pub.dev/packages/flutter_widget_from_html_core). It doesn't have this dependency issue.
