### ISSUE TITLE
How can I set background color?

### ISSUE THREAD

**Issue by Martin1024** [daohoangson/flutter_widget_from_html#38]
Or does it support?

**Comment by daohoangson** [comment]
This plugin does support `<div style="background-color: #f00">red background</div>`. Is that what you were asking about?

**Comment by Martin1024** [comment]
@daohoangson Yes. I was planning to implement dark mode by changing background but I was surprised find that HtmlWidget automatically changes background when I change the theme.

**Comment by daohoangson** [comment]
Yeah, it will adapt to the app theme if provided. You can either use `background-color` inline style as above for you can use Flutter's `DecoratedBox`.
