### ISSUE TITLE
Text selection and custom menu support?

### ISSUE THREAD

**Issue by liufan121** [daohoangson/flutter_widget_from_html#381]
大神你好，这个支持文本选择，自定义菜单选项吗？  后续有考虑吗？

**Comment by daohoangson** [comment]
Can you repeat your inquiry in English?

**Comment by liufan121** [comment]
Does this support text selection and custom menu options? Are there any subsequent considerations?

**Comment by daohoangson** [comment]
Regarding text selection, currently it's not supported. More information is available here: https://github.com/daohoangson/flutter_widget_from_html/issues/102

About custom menu, can you be more specific? If you want to open a popup menu on touch, it should be possible using custom widget etc.
