### ISSUE TITLE
[web] List items don't render correctly (no bullets)

### ISSUE THREAD

**Issue by kubaprzetakiewicz** [daohoangson/flutter_widget_from_html#383]
https://github.com/daohoangson/flutter_widget_from_html/commit/cb9ced914b7be59bf339ef255f109ea741313c58#r44664621

this currently doesn't work in Flutter for Web (any branch, `(beta|dev|master)`), neither on DomCanvas nor CanvasKit (Skia)

`m.descent` and `m.unscaledAscent` return `Infinity` which causes the `Offset` to return a `NaN` value which trips the following assertion:
```
The following assertion was thrown during paint():
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/validators.dart:32:10
!offset.dx.isNaN && !offset.dy.isNaN
"Offset argument contained a NaN value."
```

**Comment by daohoangson** [comment]
Hmm, the easy fix is to ignore the metrics on web for the time being I think...

**Comment by pablo3x6** [comment]
Could I get some help with ignoring the metrics? I would need this fixed ASAP, so would do this fix till then.

**Comment by daohoangson** [comment]
Version `0.5.2-rc.2021011801` has been released (quite a while) with the fix for this. I'm closing this issue now.
