### ISSUE TITLE
^0.5.1+5 doesn't match any versions

### ISSUE THREAD

**Issue by bartonhammond** [daohoangson/flutter_widget_from_html#389]
From `pubspec.yaml`:
  `flutter_widget_from_html_core: ^0.5.1+5`
Error
`pub get failed (1; Because MyProject depends on flutter_widget_from_html_core ^0.5.1+5 which doesn't match any versions, version solving failed.`

**Comment by daohoangson** [comment]
The latest `flutter_widget_from_html_core` version is `0.5.1+4`. It doesn't have iframe, video and table colspan/rowspan support. If you want those, you will need `flutter_widget_from_html` (latest is `0.5.1+5`).

**Comment by bartonhammond** [comment]
Ok - thanks.
