### ISSUE TITLE
How to buildAsyncBuilder vertically centered

### ISSUE THREAD

**Issue by gtyhn** [daohoangson/flutter_widget_from_html#390]
I want to take up the rest of the display when it loads and keep it vertically centered, Now it's always centered horizontally at the top, How do I display a vertical horizontal center at load time?

**Comment by DFelten** [comment]
You could for example use something like this:

```dart
HtmlWidget(
  html,
  buildAsync: true,
  buildAsyncBuilder: (_, snapshot) => snapshot.hasData
      ? snapshot.data
      : SizedBox(
          height: MediaQuery.of(context).size.height,
          child: const Center(child: CircularProgressIndicator()),
        ),
);
```

**Comment by gtyhn** [comment]
Thank you very much, my friend @DFelten
