### ISSUE TITLE
Whitespace in video player html

### ISSUE THREAD

**Issue by bayuramadeza** [daohoangson/flutter_widget_from_html#394]
Hi, since I updated to the last version if this package, I got the extra whitespace in <video> tag. In the previous version there is no problem.

Tthe tag is 
`<video width="400" height="200" controls style="margin: 0px !important; padding : 0px !important"><source src="https://www.topkarir.com/assets/klinik-karir/topkarir_klinik.mp4" type="video/mp4"></video>`

This is my screen shot of this bugs.

![WhatsApp Image 2020-12-10 at 15 49 41](https://user-images.githubusercontent.com/32892647/101748716-7ccfd980-3aff-11eb-9639-964364902e64.jpeg)

**Comment by daohoangson** [comment]
It's a problem with one of the dependencies of this package as reported here #371. If your HTML contains VIDEO tags, you may want to restrict `chewie` version in your app pubspec.yaml, something like this should work:

```yaml
  chewie: ^0.9.0
```

**Comment by bayuramadeza** [comment]
I have changed to the newest chewie version. But the white space is still appears.

**Comment by bayuramadeza** [comment]
Okay, thanks. the issue is fixed  right now/
