### ISSUE TITLE
How add tap listener to img and url

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#396]
https://github.com/daohoangson/flutter_widget_from_html/issues/50#issuecomment-742429977

> With flutter_widget_from_html: ^0.4.1, builderCallBack and lazyset removed.
> How to achieve the same now.

**Comment by daohoangson** [comment]
For URL, you can specify a callback for `onTapUrl` when you create the `HtmlWidget`.
For images, a custom `WidgetFactory` is needed, something like this should work:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Issue 396')),
        body: SingleChildScrollView(
          child: Padding(
            child: HtmlWidget(
              kHtml,
              factoryBuilder: () => _WidgetFactory(),
              onTapUrl: (url) => print('url=$url'),
            ),
            padding: const EdgeInsets.all(8),
          ),
        ),
      );
}

class _WidgetFactory extends WidgetFactory {
  @override
  Widget buildImage(BuildMetadata meta, Object provider, ImageMetadata image) {
    final built = super.buildImage(meta, provider, image);
    if (built == null) return built;

    return GestureDetector(
      child: built,
      onTap: () => print('image=$image'),
    );
  }
}

const kHtml = '''
<p>URL: <a href="http://domain.com">tap me</a>.</p>
<p>Image: <img src="https://via.placeholder.com/100x50.png?text=tap+me" /></p>
''';
```

### Screenshot:

<img src="https://user-images.githubusercontent.com/239336/101852840-1abfb480-3b91-11eb-9ee8-2d4345c44ddb.png" width="300" />

### Console output:

```
flutter: url=http://domain.com
flutter: image=ImageMetadata(sources: [ImageSource("https://via.placeholder.com/100x50.png?text=tap+me")])
```

**Comment by DFelten** [comment]
I think it could be a great improvement for the package to add this feature as an own parameter `onImageTap`. 

For example `flutter_html` has such method and it's helpful and straightforward easy to use.

We're using this in oute apps for showing images in some kind of Lightbox.

**Comment by daohoangson** [comment]
@DFelten I have added support for `onTapImage` callback (see #398), it'll be available in the next release.

**Comment by DFelten** [comment]
Great, thank you :)

**Comment by DFelten** [comment]
> @DFelten I have added support for `onTapImage` callback (see #398), it'll be available in the next release.

Here I noticed that `onTapImage` only works if `onTapUrl` was also defined. Is that the expected behaviour?

And one question regarding the onLinkTap: Is it somehow possible to override the onTap behaviour only for some urls? For example, links to Wordpress posts should open a new page within the app, all other urls should behave as always. For example, I want to keep the behavior of the table of content links.

**Comment by DFelten** [comment]
> > @DFelten I have added support for `onTapImage` callback (see #398), it'll be available in the next release.
> 
> @daohoangson Here I noticed that `onTapImage` only works if `onTapUrl` was also defined. Is that the expected behaviour?
> 
> And one question regarding the onLinkTap: Is it somehow possible to override the onTap behaviour only for some urls? For example, links to Wordpress posts should open a new page within the app, all other urls should behave as always. For example, I want to keep the behavior of the table of content links.

@daohoangson Sorry for the impatience, but I'll ask the question again here so it won't be forgotten.

**Comment by daohoangson** [comment]
> Here I noticed that onTapImage only works if onTapUrl was also defined. Is that the expected behaviour?

@DFelten this is not the intended behavior, they should be independent. Unless your image is inline within a link? For that case, I need to see the HTML to be sure. But in general, they are unrelated to each other.


> And one question regarding the onLinkTap: Is it somehow possible to override the onTap behaviour only for some urls? 

It's possible to do this by extending `WidgetFactory` and overrides the `void onTapUrl(String)` method. Basically you can check the URL and decide: (1) handle the tap yourself (e.g. open link to other WP posts within the app) or (2) let `super.onTapUrl()` does the job.

> Sorry for the impatience, but I'll ask the question again here so it won't be forgotten.

Sorry for the late reply, I have quite a few older issues that need taking care of.

**Comment by DFelten** [comment]
> > Here I noticed that onTapImage only works if onTapUrl was also defined. Is that the expected behaviour?
> 
> @DFelten this is not the intended behavior, they should be independent. Unless your image is inline within a link? For that case, I need to see the HTML to be sure. But in general, they are unrelated to each other.

This problem seems to be gone :) 

However, I have another question regarding the image tap. Why is there a list of sources inside the image's metadata? I thought that each image can have only one. So currently I always have to get the first one from the list and read the URL from it.

In which cases can an image have more than one source here?

**Comment by daohoangson** [comment]
That was designed to support `srcset` at some point in the future. Something like this https://html.com/attributes/img-srcset/

**Comment by 2530442368** [comment]
你好，我想请问一下为什么需要加first才可以拿到url，为什么不是直接sources.url
![image](https://user-images.githubusercontent.com/63909463/144738567-31daa1f1-40a5-481c-a00c-813cd89b03a5.png)

**Comment by daohoangson** [comment]
Can you comment in English please? @2530442368

**Comment by 2530442368** [comment]
> 请问可以用英文评论吗？@2530442368

Sorry for not paying attention, I would like to ask why you need to add first to get the url, why not directly sources.url

**Comment by daohoangson** [comment]
Because there may be more than one image source. Something like this https://html.com/attributes/img-srcset/

**Comment by justforworkandstuff** [comment]
Managed to get this working, and leaving here for future references: 

```
// Data
final String content = '<a href=\"https://www.youtube.com/watch?v=M2zEEBWIVMM" rel=\"noopener noreferrer\" target=\"_blank\"><img src=\"https://fastly.picsum.photos/id/237/400/500.jpg?hmac=Hr3GNrOhSXNqxEL2HpWa-Mk1JvleuHF3b0ar8pUX6hI\" style=\"width: 410px;\"></a>';

// Implementation:
HtmlWidget(
  content,
  key: widget.key,
  factoryBuilder: () => CustomImageHtmlWidget(onLinkTapped: (url) {
    if (url.isNotEmpty) {
      // Your custom action here
    }
  }),
),

// CustomWidget extending from WidgetFactory for [factoryBuilder] usage
class CustomImageHtmlWidget extends WidgetFactory {
  CustomImageHtmlWidget({this.onLinkTapped}) : super();

  final Function(String)? onLinkTapped;

  @override
  Widget buildImage(BuildTree tree, ImageMetadata data) {
    final built = super.buildImage(tree, data);
    if (built == null) return const SizedBox.shrink();

    final imageContainsLink = tree.parent.element.attributes.containsKey('href');

    return TouchableOpacity(
      padding: EdgeInsets.zero,
      onPressed: imageContainsLink && onLinkTapped != null
          ? () => onLinkTapped!(tree.parent.element.attributes['href'] ?? '')
          : data.sources.isNotEmpty && data.sources.first.url.isNotEmpty
              ? () => onImageTapped(data)
              : null,
      child: built,
    );
  }

  void onImageTapped(ImageMetadata data) {
    // Your custom action when image tap, e.g. open dialog to view image, etc. 
  }
}
```
