### ISSUE TITLE
Can't change text color 

### ISSUE THREAD

**Issue by huxaiphaer** [daohoangson/flutter_widget_from_html#397]
I tried to change the TextColor but I couldn't, it's still black, what am I missing ?

```
HtmlWidget(
        newsItem.body,
        textStyle: TextStyle(fontSize: 20.0, color: Colors.white),
        enableCaching: true,
        webView: true,
      )
```

**Comment by huxaiphaer** [comment]
After reading through the issues this [solution](https://github.com/daohoangson/flutter_widget_from_html/issues/187#issuecomment-676024869) helped me

**Comment by daohoangson** [comment]
`textStyle` should work. I think your HTML may have specified text color in inline styles or similar. Can you share the HTML? The linked solution overrides the inline style, that explains why it worked for you.

**Comment by huxaiphaer** [comment]
@daohoangson this my [sample](https://gist.github.com/huxaiphaer/38d573e9f0d9f69f4d8ff9018ab271bd) html

**Comment by daohoangson** [comment]
Ah, just as I suspected. The HTML has an inline color set in the first P tag.

```
color: rgb(51, 51, 51);
```

**Comment by huxaiphaer** [comment]
Thanks for the explanation, makes sense. Guess we can close this @daohoangson

**Comment by Punlork** [comment]
@huxaiphaer @daohoangson  Regarding your issues, what would be the solution to override the inline style color? Since I can't seem to change the color while other text syles props work fine.

**Comment by daohoangson** [comment]
Setting the text style in the widget will change the default color. But if some HTLM element specifies a different color (`rgb(0,0,0)` in your example), that color will override the default one.

If you want to, you can ignore `color` inline style declaration using a custom factory. Have you tried that way? If you run into trouble with this approach, please open another issue to discuss later.
