### ISSUE TITLE
[request] Support exponential syntax

### ISSUE THREAD

**Issue by Sunbreak** [daohoangson/flutter_widget_from_html#399]
```html
<div style="background-color: rgba(1e2, .5e1, .5e0, +.25e2%)">Light pink</div>
```

Related: https://github.com/dart-lang/csslib/issues/123

**Comment by daohoangson** [comment]
I have created a PR for this https://github.com/dart-lang/csslib/pull/134, let's follow the progress over there. I'm closing this issue now.
