### ISSUE TITLE
How to change the <ol><li> style and color?

### ISSUE THREAD

**Issue by winsonet** [daohoangson/flutter_widget_from_html#4]
It seems can't change the `<ol><li>` color, how can I do that? 

Thanks!!

**Comment by daohoangson** [comment]
For which element are you trying to change color? Can you take a screenshot and highlight the element?

**Comment by winsonet** [comment]
hum.... I just want to change the` <ol><li>` color, can I ? it's difficult? for example my html like below:
```
<ol>
<li>test.....</li>
<li>test.....</li>
<li>test.....</li>
</ol>
```
it can show as below
```
1. test....
2. test....
3. test....
```
but I can't change the `1.  2.  3.`  color :(

**Comment by winsonet** [comment]
Oh, it works, thanks!!
