### ISSUE TITLE
Table not rendered properly and some data hidden

### ISSUE THREAD

**Issue by Khawlah-Mohammed** [daohoangson/flutter_widget_from_html#400]
An asymptotic problem to https://github.com/daohoangson/flutter_widget_from_html/issues/89  
flutter_widget_from_html version 0.5.1+5
As in the following two pictures:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-23 at 22 19 42](https://user-images.githubusercontent.com/16141396/103031410-d52ac080-456e-11eb-8612-b0e0a54712cf.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-23 at 22 14 46](https://user-images.githubusercontent.com/16141396/103031397-ce03b280-456e-11eb-9214-0815a460f1dd.png)

**Comment by daohoangson** [comment]
What is your HTML?

**Comment by Khawlah-Mohammed** [comment]
**it's autogenerated like** 

 "<p style="text-align:center"><span style="font-size:20px"><strong><span style="font-family:Georgia,serif"><span style="background-color:#ffd700">ملاحظة: تم تمديد المناقصة الى تاريخ 26 اكتوبر 2020</span></span></strong></span></p> <p style="text-align:center"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>Long Terms Agreements Advertisement</strong></span></span></p> <p><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>Office</strong>: Norwegian Refugee Council (NRC)</span></span></p> <p><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>Bids Issue Timetable</strong>: 28<sup>th</sup> September, 2020.</span></span></p> <p><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>Deadline for Submission</strong>: 26<sup>th</sup> Oct, 2020, time: before 03:00 PM</span></span></p> <p><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>Tenders Subject: </strong><strong>Provision of Several Supplies, Services &amp; Works under Long Terms Agreements (Valid for One Year &ndash; Renewable for Two Individual years) </strong></span></span></p> <p><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><u>Introduction</u></strong><strong>:</strong></span></span></p> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">The Norwegian Refugee Council (NRC) is an International NGO with regional competence and expertise in working with displaced populations. The Regional Office is based in Nairobi, Kenya with Offices and operations in Somalia and Yemen.</span></span></p> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">Norwegian Refugee Council invites potential suppliers/contractors to apply to the following LTAs:</span></span></p> <table border="0" cellpadding="5" cellspacing="5" style="width:100%"> <tbody> <tr> <td style="height:26px; width:114px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>Reference Number</u></strong></span></span></p> </td> <td style="height:26px; width:300px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>LTA Description</u></strong></span></span></p> </td> <td style="height:26px; width:96px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>Bank Guarantee</u></strong></span></span></p> </td> <td style="height:26px; width:126px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>Documents</u></strong></span></span></p> </td> </tr> <tr> <td style="height:20px; width:114px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">NRC/YE/21/009</span></span></p> </td> <td style="height:20px; width:300px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">Supplying Office Supplies Items (buffet items)</span></span></p> </td> <td style="height:20px; width:96px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">N/A</span></span></p> </td> <td style="height:20px; width:126px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/EaUS2ThrRFFKvzYdeeCchpoBAME_C5bj35l6hzp7wcW8Mw?e=KzkWIR">Download</a></span></span></p> </td> </tr> <tr> <td style="height:20px; width:114px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">NRC/YE/21/012</span></span></p> </td> <td style="height:20px; width:300px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">Supplying Scholastics Kit Items</span></span></p> </td> <td style="height:20px; width:96px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">USD 5,000</span></span></p> </td> <td style="height:20px; width:126px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/EcTWrL5fp7lLpiKQcVeJ8F0BJ7q7O_FqZOq6eOztLGjkTw?e=HAyjBd">Download</a></span></span></p> </td> </tr> <tr> <td style="height:20px; width:114px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">NRC/YE/21/016</span></span></p> </td> <td style="height:20px; width:300px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">Provision of Legal Consultancy Services</span></span></p> </td> <td style="height:20px; width:96px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px">N/A</span></span></p> </td> <td style="height:20px; width:126px"> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/Ec2-u0XFjCtEqpkfd15LBI0Br2zht1Aqh43GHoWzeytE9g?e=IsCCDm">Download</a></span></span></p> </td> </tr> </tbody> </table> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>Manner of</u></strong><strong><u> Submission:</u></strong></span></span></p> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong>Followings must be considered by all interested bidders:</strong></span></span></p> <ol> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Interested bidders are requested to download the LTA documents from links above against each LTA.</span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Any request for clarification must be received by NRC in writing to <a href="mailto:ye.procurement@nrc.no">ye.procurement@nrc.no</a> at least 5 working days before the deadline for submission of tenders. NRC will reply to bidders&#39; questions at least 2 working days before the deadline for submission of tenders. </span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Tender must be submitted in sealed envelopes and indicate the reference number and location in the envelop cover. We look forward to receiving your tender sealed envelops as follwos (Financial offer &ndash; Technical offer - and the accompanying tender bank guarantee as per the above table.</span></span></li> </ol> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong><u>Offers should clearly include the following</u></strong><strong>:</strong></span></span></p> <ol> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Company Valid commercial local registration, TAX card, and Zakat card.</span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Documented experience &amp; references from other similar transactions, companies, NGO&rsquo;s, and UN agencies (Technical offer).<br /> Validity of the submitted offer and to indicate implementation period in your respected offer.</span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Net price for each item (Financial offer).</span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Interested bidders must have a physical participation in Yemen under the company name. </span></span></li> <li><span style="font-family:Georgia,serif"><span style="font-size:18px">Bank guarantee (if required) with value mentioned in above table valid for three months as willingness proof to participate to NRC LTAs (To be submitted separately out of the financial &amp; technical sealed envelopes).</span></span></li> </ol> <p><span style="font-family:Georgia,serif"><span style="font-size:18px"><strong>Bids should be submitted in a physical sealed envelope as stated above to the Norwegian Refugee Council Offices in&nbsp;Yemen by Date <span dir="RTL">26</span><sup>th</sup> Oct,&nbsp;2020&nbsp;Before 03:00 pm (Late bids will not be considered)</strong></span></span></p> <hr /> <p dir="rtl" style="text-align:center"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span dir="RTL">اعـــــــلان</span></strong><strong><span dir="RTL"> اتفاقيات شراء عامة </span></strong>&nbsp;</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>المكان:&nbsp;</strong>المجلس النرويجي للاجئين</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>موعد اصدار المناقصة:&nbsp;</strong>من تاريخ <span dir="LTR">28</span> سبتمبر - 2020</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>أخر موعد لتقديم العطاءات:&nbsp;</strong>إلى تاريخ 26 - اكتوبر -2020<strong>&nbsp;, السا</strong>عة 03:00 مساءً</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>موضوع المناقصة:&nbsp;</strong><strong>اتفاقيات متعددة طويلة الاجل &nbsp;( توريد &ndash; خدمات &ndash; اعمال ) لمدة سنة واحدة &ndash; قابلة للتمديد لعاميين بشكل فردي.</strong></span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><u><span dir="RTL">مــقــدمــة</span></u></strong></span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><span dir="RTL">هــي منظـــمة دوليـــة غير </span><span dir="RTL">حكوميـــة </span>(NRC) <span dir="RTL">المجلــــس النرويجــــي للاجئيــــن</span></span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><span dir="RTL">ذات الاختصــاص والخبـــرة الإقليميـــة في العمـــل مع السكــــان و النـــازحيـــن. ويقـــع المكتب الإقليمـــي فــي نيروبـــي، كينيـــا مع مكـــاتب العمليــات في الصومـــال، كينيــــا، إثيوبيـــا واليمــــن.</span></span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><span dir="RTL">يدعوا المجلس النرويجي للاجئين التجار والمقاولين الراغبين في التقديم للاتفاقيات التالية : </span></span></span></p> <table border="0" cellpadding="5" cellspacing="5" style="width:100%"> <tbody> <tr> <td style="height:26px; width:108px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span dir="RTL">المرجع</span></strong></span></span></p> </td> <td style="height:26px; width:246px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>وصف الاتفاقية</strong></span></span></p> </td> <td style="height:26px; width:138px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>الضمان</strong></span></span></p> </td> <td style="height:26px; width:139px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>المستندات</strong></span></span></p> </td> </tr> <tr> <td style="height:20px; width:108px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">NRC/YE/21/009</span></span></p> </td> <td style="height:20px; width:246px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">توريد مواد للمكتب (احتياجيات البوفية)</span></span></p> </td> <td style="height:20px; width:138px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">N/A</span></span></p> </td> <td style="height:20px; width:139px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/EaUS2ThrRFFKvzYdeeCchpoBAME_C5bj35l6hzp7wcW8Mw?e=KzkWIR">تحميل</a></span></span></p> </td> </tr> <tr> <td style="height:20px; width:108px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">NRC/YE/21/012</span></span></p> </td> <td style="height:20px; width:246px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">توريد مستلزمات مدرسية</span></span></p> </td> <td style="height:20px; width:138px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">USD 5,000</span></span></p> </td> <td style="height:20px; width:139px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/EcTWrL5fp7lLpiKQcVeJ8F0BJ7q7O_FqZOq6eOztLGjkTw?e=HAyjBd">تحميل</a></span></span></p> </td> </tr> <tr> <td style="height:20px; width:108px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">NRC/YE/21/016</span></span></p> </td> <td style="height:20px; width:246px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">تقديم خدمة الاستشارات القانونية</span></span></p> </td> <td style="height:20px; width:138px"> <p style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">N/A</span></span></p> </td> <td style="height:20px; width:139px"> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif"><a href="https://norwegianrefugeecouncil-my.sharepoint.com/:b:/g/personal/bassam_alsharjabie_nrc_no/Ec2-u0XFjCtEqpkfd15LBI0Br2zht1Aqh43GHoWzeytE9g?e=IsCCDm">تحميل</a></span></span></p> </td> </tr> </tbody> </table> <p dir="rtl" style="text-align:center"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span style="background-color:#ffd700">يمكن لجميع الموردين تحميل الملفات المرفقة بالضغط على الرابط المقابل لكل طلب، أو تنزيل جميع الملفات من يمين هذه الصفحة تحت قسم &quot;Downloads &amp; Attachments &quot; </span></strong></span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span dir="RTL">طريقــــــة التقـــــــديم</span></strong></span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">يجب عــلى الراغبيــــن&nbsp; في التقديم الاتي:</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">1:على الموردين الراغبين في المشاركة &nbsp;تحميل ملفات الاتفاقيات من روابط التحميل في الجدول اعلاة مقابل كل اتفاقية &nbsp;.</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">2: لاي استفسارات او توضيحات يجب ان تسلم الى المجلس النرويجي للاجئين عن طريق ارسال بريد الكتروني خطي الى <a href="mailto:ye.procurement@nrc.no"><strong><span dir="LTR">ye.procurement@nrc.no</span></strong></a>&nbsp;</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">على الاقل قبل موعد تسليم&nbsp; وثائق المناقصة بخمسة ايام&nbsp; وسيقوم المجلس النرويجي للاجئيين بالاجابة على اسئلة مقدمي العروض على الاقل بيومين عمل من موعد تسليم وثائق المناقصة.</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">3: يجيب تقديم العطاء في مظاريف مختومة مع ذكر الرقم المرجعي والموقع في غلاف الظرف نحن نتطلع الى استلام مظاريف العطاء المختومة على النحو الاتي: ( عرض مالي &ndash; عرض فني &ndash; وضمان بنك العطاء المصاحب كما هو موضح في الجدول اعلاة).</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">&nbsp;4: تم اخذ اجازة عيد الاضحى في الاعتبار خلال فترة الاعلان.</span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span dir="RTL">وينبغــــي أن تشمـــــل العـــــروض بوضـــــوح ما يلـــــي</span>:</strong></span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">-&nbsp; سجـــل الشركــــة التجـــاري المحلي, والبطاقه الضريبيه والبطاقة الزكوية ساريات المفعول.</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">-&nbsp; &nbsp;الخبرة والمراجع الموثقة من المعاملات المماثلة ، والشركات ، والمنظمات غير الحكومية ، ووكالات الأمم المتحدة( تضاف ضمن العطاء الفني).</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">- &nbsp;السعر الصافي لكل عنصر (عرض مالي).</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">-&nbsp; &nbsp;على المتقدمين &nbsp;المهتمين بالمشاركة الفعلية ان يكونوا متواجدين في اليمن تحت اسم الشركة المقدم العرض باسمها.</span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">- ضمان بنكي (اذا كان مطلوب) بالقيمة المحددة في الجدول اعلاة صالح لمدة ثلاثة شهور كدليل على الاستعداد للمشاركة في اتفاقيات المجلس النرويجي &nbsp;يتم تقديمه بشكل منفصل خارج الأظرف المالية والفنية المختومة).</span></span></p> <p dir="rtl"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong><span dir="RTL">يجب تقديم العطاءات في مظروف مغلق فعليًا كما هو مذكور أعلاه إلى مكاتب مجلس اللاجئين النرويجي في اليمن بتاريخ 26&nbsp;اكتوبر 2020 قبل الساعة 03:00 مساءً (لن يتم النظر في العطاءات المتأخرة)</span></strong></span></span></p>"



**or**

"<p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif"><strong>الاعلان لمشروع (اعمال بناء مكاتب الشئون البشرية) الهلال الاحمر اليمني &ndash; المركز الرئيسي</strong></span></span></p> <p dir="RTL"><span style="font-size:18px"><span style="font-family:Georgia,serif">تعلن جمعية الهلال الاحمر اليمني &ndash; المركز الرئيسي للمناقصة اعلاه &nbsp;بحسب الجدول التالي :</span></span></p> <table align="right" border="1" cellpadding="2" cellspacing="2" dir="rtl" style="width:100%"> <tbody> <tr> <td style="height:76px; width:59px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">رقم المناقصة</span></span></strong></p> </td> <td style="height:76px; width:75px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">اسم المشروع</span></span></strong></p> </td> <td style="height:76px; width:65px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">مكونات المناقصة</span></span></strong></p> </td> <td style="height:76px; width:79px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">مصدر التمويل</span></span></strong></p> </td> <td style="height:76px; width:93px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">الخبرات المطلوبة</span></span></strong></p> </td> <td style="height:76px; width:56px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">عملة العطاء</span></span></strong></p> </td> <td style="height:76px; width:66px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">الرسوم بالريال</span></span></strong></p> </td> <td style="height:76px; width:85px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">مدة صلاحية العطاء (يوم)</span></span></strong></p> </td> <td style="height:76px; width:75px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">صلاحية ضمان العطاء (يوم)</span></span></strong></p> </td> <td style="height:76px; width:133px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">قيمة الضمان</span></span></strong></p> </td> <td style="height:76px; width:151px"> <p style="text-align: center;"><strong><span style="font-size:16px"><span style="font-family:Georgia,serif">موعد فتح المظاريف</span></span></strong></p> </td> </tr> <tr> <td style="height:142px; width:59px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif"><span dir="LTR">1/2020</span></span></span></p> </td> <td style="height:142px; width:75px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif"><strong>اعمال بناء مكاتب الشئون البشرية -المركز الرئيسي</strong></span></span></p> </td> <td style="height:142px; width:65px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">اعمال مدنية بناء تلابيس ، دهان ، سباكة ، كهرباء.....الخ</span></span></p> </td> <td style="height:142px; width:79px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif"><span dir="LTR">GRC</span></span></span></p> </td> <td style="height:142px; width:93px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">خبره سابقة في نفس المجال وان يكون لدية عقد تنفيذي واحد على الاقل في نفس المجال خلال الثلاث السنوات السابقة</span></span></p> </td> <td style="height:142px; width:56px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">الدولار الامريكي</span></span></p> </td> <td style="height:142px; width:66px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">20000</span></span></p> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">ريال</span></span></p> </td> <td style="height:142px; width:85px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">90</span></span></p> </td> <td style="height:142px; width:75px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif">120</span></span></p> </td> <td style="height:142px; width:133px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif"><span dir="LTR">450</span>$</span></span></p> </td> <td style="height:142px; width:151px"> <p style="text-align: center;"><span style="font-size:14px"><span style="font-family:Georgia,serif"><span dir="LTR">05</span>/<span dir="LTR">01</span>/21<span dir="LTR">20</span>م، الساعة الحادية عشرونصف صباحا</span></span></p> </td> </tr> </tbody> </table> <div dir="rtl" style="text-align: center;">&nbsp;</div> <p dir="RTL" style="text-align: center;">&nbsp;</p> <p dir="RTL" style="text-align: center;"><span style="font-size:18px"><span style="font-family:Georgia,serif">وعلية تدعو جمعية الهلال الاحمر اليمني &ndash; المركز الرئيسي المقاولين المؤهلين والذين سبق وان عملوا في نفس المجال تقديم عطاءتهم وفقا للتالي:</span></span></p> <ol dir="rtl"> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يمكن الحصول على وثائق المناقصات من مقر جمعية الهلال الاحمر اليمني &ndash; المركز الرئيسي &ndash; شارع 26 سبتمبر مبنى رقم 10 جوار رئاسة الوزراء &ndash;تلفون وفاكس <span dir="LTR">01-283131/2/3</span>او خلال ساعات الدوام الرسمي مقابل رسوم لا ترد حسب ما هو موضح أعلاه قرين كل اسم وبحسب العناوين الموضحة أعلاه.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">على المتقدم ارفاق عقود سابقة وشهادات انجاز لمشاريع مشابهة مع احضار الكتالوجات اللازمة للعرض المقدم.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يسلم العطاء في مظروف مغلق ومختوم بالشمع الاحمر مكتوب علية اسم المشروع ورقم المناقصة ويحتوي على عرضين فني ومالي منفصلين في او قبل الموعد المحدد أعلاه لفتح المظاريف .</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">تفتح المظاريف في مقر جمعية الهلال الاحمر اليمني &ndash; المركز الرئيسي &ndash; شارع 26 سبتمبر مبنى رقم 10 جوار رئاسة الوزراء &ndash;تلفون وفاكس <span dir="LTR">01-283131/2/3</span> حسب المواعيد المحددة اعلاه في نفس الساعة واليوم المذكورين اعلاه بحضور المقاولين المتقدمين ومندوبيهم واي عطاء يقدم او يصل بعد هذا الموعد سيرفض وسوف يعاد الى صاحبة مقفلا.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">على المتقدم احضار صورة من البطاقة الضريبية سارية المفعول واحضار سند الشراء للوثائق.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">على المتقدم احضار صورة من شهادة تسجيل ضريبة المبيعات.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">على المتقدم احضار صورة من البطاقة التأمينية والزكويه سارية المفعول.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">احضار صورة شهادة مزاولة المهنة سارية المفعول.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يرفق مع العطاء ضمان بنكي غير مشروط او شيك مقبول الدفع بالمبلغ المحدد اعلاه صالح للفترة المذكورة للمشروع ابتداء من تاريخ فتح المظاريف وسيرفض اي عطاء غير مصحوب بضمان المناقصة</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">مدة صلاحية العطاء حسب ما هو محدد أعلاه.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يقدم العطاء بالعملة المذكورة أعلاه وسيتم استبعاد اي عطاء يتم تقديمة بعملة مغايرة.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">رب العمل غير ملزم بقبول اقل عطاء او غيره من العطاءات.</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يجب على مقدم العطاء وعلى حسابة الخاص ان يقوم بزيارة الموقع قبل تقديم عطائه ويتحمل مسئولية عدم زيارته للموقع.&nbsp; &nbsp;</span></span></li> <li><span style="font-size:18px"><span style="font-family:Georgia,serif">يجب على مقدم العطاء ارفاق وثائق المناقصة المرفقة بعد الاطلاع والتوقيع والختم لكل ورقة</span></span></li> </ol>"


**but I used at these screenshots the code that you use at this link** 
https://gist.github.com/daohoangson/ac391ae13aa5d53c293687cbc83db0bb#gistcomment-3039982

And repeat some columns in the second screenshot to try to test the situation and the code that I will encounter

Because most of the tables that will be generated are large tables and need to scroll to display the data properly

**Comment by daohoangson** [comment]
It looks like your HTML specifies a cell height, like this `<td style="height:76px; width:59px">`. That's why the text is cutoff. There are a few options:

- Do a replace before sending the HTML for rendering, something to replace `height:` -> `height-x:` should work.
- Use a custom `WidgetFactory` to disable sizing logic

**Comment by Khawlah-Mohammed** [comment]
Okay, it's work.
thank you.

but still, the big tables didn't work fine. like this vedio.



https://user-images.githubusercontent.com/16141396/103511646-7facb880-4e78-11eb-8023-cef148d0a3b1.mp4

**Comment by daohoangson** [comment]
I'm consolidating table improvements into #531, this package should have better column width support. I'm closing this issue for now, please follow the other one if you want to be notified when it's ready.
