### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DevNHQ** [daohoangson/flutter_widget_from_html#402]
not supported playvideo in IOS
ex : <iframe src="https://embed.vietnamnettv.vn/v/208042.html" width="560" height="315" frameborder="0" allowfullscreen=""></iframe>

**Comment by daohoangson** [comment]
This happened because of the default playback policy on iOS. Version `0.5.2` has been released with a new parameter for this. You can set `webViewMediaPlaybackAlwaysAllow: true` to enable it for your HTML and the video should play. Please try upgrading and let me know if it works for you.
