### ISSUE TITLE
[Help] Render only body of webpage (reader mode)

### ISSUE THREAD

**Issue by emvaized** [daohoangson/flutter_widget_from_html#403]
I want to implement some sort of reader mode functionality in my app, similar to what some Chrome extensions provide (like [this](https://chrome.google.com/webstore/detail/reader-mode/llimhhconnjiflfimocjggfjdlmlhblm) one).

Is it possible somehow to render only main article body, excluding all footers/headers/'similar posts' blocs and so on?

**Comment by emvaized** [comment]
I managed to achieve the result I wanted using some css rules from [Just-Read](https://github.com/ZachSaucier/Just-Read/blob/master/hide-segments.css) in `customWidgetBuilder`.

Will leave this issue open for now in case somebody will share a better approach

**Comment by daohoangson** [comment]
The hardest part for this kind of rendering is knowing what is useful and what is rubbish. Normally people would use tools like Goose to implement an api that accepts an URL then returns the contents HTML. That way you can update the backend to handle more sites or when a site updates their layout etc. (that happens a lot, a small webpage change can break extractor easily). The frontend (Flutter app) should take the contents HTML that has been cleaned and render that directly.

**Comment by emvaized** [comment]
I've managed to achieve what I wanted with [mercury-parser](https://github.com/postlight/mercury-parser) running on backend, and I guess this is the best possible solution, so closing now
