### ISSUE TITLE
Do you support base64 image or local image file stored in user shared directory?

### ISSUE THREAD

**Issue by eliranwong** [daohoangson/flutter_widget_from_html#407]
Do you support base64 image or local image file stored in user shared directory?

**Comment by daohoangson** [comment]
Yes, data URI support includes base64 encoded image.

**Comment by daohoangson** [comment]
And no, currently local storage is not supported.

**Comment by eliranwong** [comment]
Thanks.  It is good enough.  at least I can convert convert local image file to base64 encoded image, then load with your widget.

**Comment by daohoangson** [comment]
What is your use case? You download images into storage then generate HTML later to show those?

**Comment by eliranwong** [comment]
> What is your use case? You download images into storage then generate HTML later to show those?

@daohoangson thanks for asking.  I describe my case below, I believe your package could be very useful for my case.

I have developed a desktop version of a bible app at https://github.com/eliranwong/UniqueBible , written in python.
I am porting this app to mobile platform https://github.com/eliranwong/UniqueBibleAppHybrid 

As a bible app, users can download many different kinds of references books, which include images or bible map images "optionally".  Depends on the number of files users need, the file size vary from MBs to many GBs.  Therefore, I cannot include all in the initial bundle.  They have to download and put in storage for offline access.  Most of the established modules are now in html format.

Users can access any files downloaded and installed inside in folder "userDirectory.path" as worked out below.  My app needs to access image files located in this shared user directory and load them together with html content.

class StorageMx {

  // Check if storage permission is granted.
  static Future<bool> checkStoragePermission() async {
    final permissionResult = await Permission.storage.request();
    return (permissionResult.isGranted) ? true : false;
  }

  // get user directory
  static Future<String> getUserDirectoryPath() async {
    if (await checkStoragePermission()) {
      final Directory userDirectory = (Platform.isAndroid)
          ? await getExternalStorageDirectory()
          : await getApplicationDocumentsDirectory();
      return userDirectory.path;
    } else {
      return "";
    }
  }

}

**Comment by daohoangson** [comment]
Assuming you have a list of file paths in external storage or similar, it should be fairly straightforward to extend the package to support `file://` path for those images.

**Comment by eliranwong** [comment]
> Assuming you have a list of file paths in external storage or similar, it should be fairly straightforward to extend the package to support `file://` path for those images.

Great! I am looking forward to the support of using "file://".  Many thanks in advance.

**Comment by daohoangson** [comment]
Version `0.5.2` has just been released with support for `file://` images. Please try upgrading and let me know whether it works for you. Thank you.
