### ISSUE TITLE
How "scroll to anchor" work?  Is it possible to give an example?

### ISSUE THREAD

**Issue by eliranwong** [daohoangson/flutter_widget_from_html#408]
You have the following description about your package.

A: underline, theme accent color
Scroll to anchor

I think this feature is very useful, but I do not know how does it work, can you kindly give me a simple example?  Do I need a scrollable widget?

**Comment by daohoangson** [comment]
Just make sure your HTML contains the anchor (e.g. `<a name="foo">Anchor</a>`) with a link to it (e.g. `<a href="#foo">Go to anchor</a>`). And yes, `HtmlWidget` needs to be put inside a `CustomScrollView` or similar for the jump to work.

**Comment by eliranwong** [comment]
Wonderful! Thanks for your good work.

**Comment by daohoangson** [comment]
You are welcome. I'm closing this now, if you run into another issue, feel free to open a new one.
