### ISSUE TITLE
Is div tag with inline-block display supported?

### ISSUE THREAD

**Issue by eliranwong** [daohoangson/flutter_widget_from_html#409]
I guess chance is low, but no harm to ask.

I want to display content having nested div tag with inline-block display like content showing in the following links:

https://marvel.bible/index.php?text=MAB&b=2&c=1&v=1
or
https://marvel.bible/index.php?text=MAB&b=41&c=1&v=1

Is it possible with flutter_widget_from_html?

btw, I have Hebrew content needs to show text direction from right to left.  Does flutter_widget_from_html support right-to-left text direction?

Many thanks.  I think your package is a very good package.

**Comment by daohoangson** [comment]
You will need to use inline styling or `customStylesBuilder` to specify `display: inline-block`. The package will render that DIV inline instead of in its own block.

`dir="rtl"` attribute and `direction: rtl" inline style are both supported.

**Comment by eliranwong** [comment]
> You will need to use inline styling or `customStylesBuilder` to specify `display: inline-block`. The package will render that DIV inline instead of in its own block.
> 
> `dir="rtl"` attribute and `direction: rtl" inline style are both supported.

wow! I must try.  Thanks a lot for instructions.  much appreciated.
