### ISSUE TITLE
[Question] Blue splash on tap for links

### ISSUE THREAD

**Issue by emvaized** [daohoangson/flutter_widget_from_html#410]
Is it possible to get this regular `InkWell`'s splash effect when tapping on links? 
So that it will behave like in Chrome/any other browser on Android
![photo_2021-01-12_02-29-20](https://user-images.githubusercontent.com/37851576/104254725-16343780-5480-11eb-8aaf-daf4b23524ff.jpg)

**Comment by daohoangson** [comment]
If your link is a block element (e.g. `display: block`) then it will be rendered with `InkWell`. But most of the time it will use Flutter's inline span for better performance and they won't have the splash.

Do you have control of the HTML?

**Comment by emvaized** [comment]
> If your link is a block element (e.g. `display: block`) then it will be rendered with `InkWell`. But most of the time it will use Flutter's inline span for better performance and they won't have the splash.
> 
> Do you have control of the HTML?

No, unfortunately I don't

**Comment by emvaized** [comment]
I just thought of implementing this effect using maybe the `customWidgetBuilder`, or overriding the `buildText` function in factory builder - but if it will decrease performance, okay then

**Comment by daohoangson** [comment]
It's entirely possible and shouldn't affect much if you do it for a couple of links per page (e.g. important CTA links only). As mentioned earlier, adding `display: block` should be enough.

**Comment by emvaized** [comment]
@daohoangson 
It works! However, every inline-link is now displayed on a new line, which is not quite of what I wanted, so I guess I'll give it up.
But huge thanks for your help
