### ISSUE TITLE
 RangeError was thrown during a scheduler callback:

### ISSUE THREAD

**Issue by himanshu64** [daohoangson/flutter_widget_from_html#413]
`
════════ Exception caught by scheduler library ═════════════════════════════════
The following RangeError was thrown during a scheduler callback:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      List.elementAt (dart:core-patch/growable_array.dart:386:16)
#2      RenderParagraph.assembleSemanticsNode
package:flutter/…/rendering/paragraph.dart:921
#3      _SwitchableSemanticsFragment.compileChildren
package:flutter/…/rendering/object.dart:3717
#4      _SwitchableSemanticsFragment.compileChildren
package:flutter/…/rendering/object.dart:3663
...
════════════════════════════════════════════════════════════════════════════════
Reloaded 30 of 1599 libraries in 2,274ms.

════════ Exception caught by scheduler library ═════════════════════════════════
RangeError (index): Invalid value: Valid value range is empty: 0
════════════════════════════════════════════════════════════════════════════════
`

**Comment by daohoangson** [comment]
Were you running Flutter web?

**Comment by himanshu64** [comment]
on Android

**Comment by daohoangson** [comment]
Hmm, this is new. Can you share the HTML causing the error? And maybe the Dart code rendering the `HtmlWidget` too? Do you have a custom `WidgetFactory`?

**Comment by daohoangson** [comment]
Pinging again @himanshu64. Please try upgrading to the latest version of Flutter and this package. I think this may be a bug within Flutter's text rendering logic (not a problem with this package). Since there is no repro, I can't do anything here. Please open a new issue if you are still having trouble.
