### ISSUE TITLE
How to make the display better

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#414]
[html.txt](https://github.com/daohoangson/flutter_widget_from_html/files/5823747/html.txt)

Hello, the attachment is a mixed HTML content, when I use our plug-in to display on my mobile phone, the effect is not very ideal, the picture will be displayed on the top, and it is not very good-looking when mixed with the text. Please ask if there is a good way to make their display effect better. thank you

**Comment by daohoangson** [comment]
For LaTeX expressions, it's best to avoid image because they render slowly and often out of line. It's pretty simple to customize this package to render the expressions, see this https://github.com/daohoangson/flutter_widget_from_html/issues/177#issuecomment-735752720

**Comment by daohoangson** [comment]
If you are interested in math syntax support, please follow #471. I'm closing this issue for now
