### ISSUE TITLE
How to make the display better too

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#415]
[html.txt](https://github.com/daohoangson/flutter_widget_from_html/files/5824093/html.txt)
<img width="317" alt="WX20210116-164052@2x" src="https://user-images.githubusercontent.com/40446804/104807534-a543a580-581a-11eb-9ead-9c02842093d8.png">

The attachment above is the HTML content and display effect. It doesn't look very good. In fact, one line can be displayed completely. Is there a good way to make the display effect better。thank you！

**Comment by daohoangson** [comment]
I can't run the sample HTML but this looks like a column width issue within table... I'm closing this issue in favor of #531, please follow that one if you need better width support.
