### ISSUE TITLE
Render issue when <sup> and <a> tags are inverted

### ISSUE THREAD

**Issue by Kacpur** [daohoangson/flutter_widget_from_html#416]
Hi,

during one of our app development my team discovered an issue with rendering html to widget. The error occurs when inside tag \<sup\> is tag <a [something]>. We made a workaround by placing \<sup\> tag inside <a [something]> tag using regex but I think this case should also be included in your library with some more elegant solution.

**Comment by daohoangson** [comment]
Do you have the error message / stack trace? I have just tested with this HTML and it seems to work fine:

```html
<p>Hello <sup>--  this is a <a href="https://google.com">link</a> --</sup> world.</p>
```

**Comment by arunmt024** [comment]
@daohoangson  I am facing issue with <sup></sup> and <sub></sub> Html element in flutter web with latest release and I have also tried pre release any thoughts on that ? I have enabled skia for web so if that helps you ?

**Comment by daohoangson** [comment]
@arunmt024 your issue seems to be different from the one being reported here? Btw, I have just tried your HTML with `canvaskit` and it worked without error. Please open a new issue with your `flutter doctor -v` output so I can track it down better. Thank you.
