### ISSUE TITLE
Hidden elements still take space in widget tree

### ISSUE THREAD

**Issue by emvaized** [daohoangson/flutter_widget_from_html#421]
Imagine using `customWidgetBuilder` to hide some element on the resulting page.
For example:
```
customStylesBuilder: (element) {
    if (element.localName.toLowerCase() == 'img')
         return {
             'visibility': 'hidden',
             'display': 'none',
              'width': '0px',
              'height': '0px',
              'padding': '0px',
              'border-width': '0px',
              'overflow': 'hidden',
        };
 return null;
},

```
On a resulting page you get this gap in the place where image was supposed to be:
![Screenshot_20210124_181129](https://user-images.githubusercontent.com/37851576/105636155-96d73880-5e6f-11eb-9b2d-fa8de0226114.png)

**Comment by daohoangson** [comment]
Can you provide a sample HTML? I think the gap may be some padding / margin from the parent element or something similar.

**Comment by emvaized** [comment]
@daohoangson 
Thanks for idea!
Now I've paid more attention to origin html, and found all these <br> elements that created spaces
![Screenshot_20210124_202903](https://user-images.githubusercontent.com/37851576/105639817-ed9a3d80-5e82-11eb-81af-4f295db94a05.png)
