### ISSUE TITLE
An error is reported after the cache is deleted

### ISSUE THREAD

**Issue by Tinaltt** [daohoangson/flutter_widget_from_html#423]
After deleting the cache, an error is reported as follows:

flutter: CacheManager: Failed to download file from http://lunatech.oss-cn-shenzhen.aliyuncs.com/admin/img/1586788321993_5hcyowge4f4.jpg with error:
FileSystemException: Cannot open file, path = '/Users/baomeng/Library/Developer/CoreSimulator/Devices/8E62B471-BB01-485F-AC4C-34566AC22CA9/data/Containers/Data/Application/596D26C5-C97B-4DD6-8002-9A82DEE2E194/Library/Caches/libCachedImageData/c047f130-60a6-11eb-8dc6-0f4cd9078c57.jpg' (OS Error: No such file or directory, errno = 2)
flutter: CacheManager: Failed to download file from http://lunatech.oss-cn-shenzhen.aliyuncs.com/admin/img/1586788316373_xph652acrrq.jpg with error:
FileSystemException: Cannot open file, path = '/Users/baomeng/Library/Developer/CoreSimulator/Devices/8E62B471-BB01-485F-AC4C-34566AC22CA9/data/Containers/Data/Application/596D26C5-C97B-4DD6-8002-9A82DEE2E194/Library/Caches/libCachedImageData/c048b480-60a6-11eb-aeae-635cb8f5db8f.jpg' (OS Error: No such file or directory, errno = 2)
flutter: CacheManager: Failed to download file from http://lunatech.oss-cn-shenzhen.aliyuncs.com/admin/img/1586788318093_izij87r01f.jpg with error:
FileSystemException: Cannot open file, path = '/Users/baomeng/Library/Developer/CoreSimulator/Devices/8E62B471-BB01-485F-AC4C-34566AC22CA9/data/Containers/Data/Application/596D26C5-C97B-4DD6-8002-9A82DEE2E194/Library/Caches/libCachedImageData/c048db90-60a6-11eb-a7ba-3b68c882aac7.jpg' (OS Error: No such file or directory, errno = 2)
flutter: CacheManager: Failed to download file from http://lunatech.oss-cn-shenzhen.aliyuncs.com/admin/img/1586788325155_3h74xpffeua.jpg with error:
FileSystemException: Cannot open file, path = '/Users/baomeng/Library/Developer/CoreSimulator/Devices/8E62B471-BB01-485F-AC4C-34566AC22CA9/data/Containers/Data/Application/596D26C5-C97B-4DD6-8002-9A82DEE2E194/Library/Caches/libCachedImageData/c04902a0-60a6-11eb-9adc-f11e7631111d.jpg' (OS Error: No such file or directory, errno = 2)

All images loaded incorrectly and will not be reloaded。

**Comment by daohoangson** [comment]
Your description matches this issue https://github.com/Baseflow/flutter_cache_manager/issues/135#issuecomment-638753854. Basically this package uses `cached_network_image` which in turn uses `flutter_cache_manager` to cache images from the network. This is a problem with the underlying package when the cache is cleaned up.

Apparently it has been fixed 13 days ago (see https://github.com/Baseflow/flutter_cache_manager/pull/264) but no release has been made since then. If you want to, you can override the dependency in your app and re-test this test case. Or you can just wait for the new release.

**Comment by Tinaltt** [comment]
> Your description matches this issue [Baseflow/flutter_cache_manager#135 (comment)](https://github.com/Baseflow/flutter_cache_manager/issues/135#issuecomment-638753854). Basically this package uses `cached_network_image` which in turn uses `flutter_cache_manager` to cache images from the network. This is a problem with the underlying package when the cache is cleaned up.
> 
> Apparently it has been fixed 13 days ago (see [Baseflow/flutter_cache_manager#264](https://github.com/Baseflow/flutter_cache_manager/pull/264)) but no release has been made since then. If you want to, you can override the dependency in your app and re-test this test case. Or you can just wait for the new release.

Thanks, Upgrade the cached_network_image version to 2.5.0 and this problem is resolved。

**Comment by sudha-anecure** [comment]
This is still happening with 3.2.2
