### ISSUE TITLE
[FEATURE] Is script tag allowed ?

### ISSUE THREAD

**Issue by EArminjon** [daohoangson/flutter_widget_from_html#428]
Hello,

I would display html from an api which give me text and something embed (twitter for ex.).
Embeds need js.

The html data :
```
HtmlWidget('''
<blockquote class="twitter-tweet">
   <p lang="fr" dir="ltr">⚠️🔴 Grave accident de la route sur le périphérique sud à <a href="https://twitter.com/hashtag/Lyon?src=hash&amp;ref_src=twsrc%5Etfw">#Lyon</a><br>➡️ une voiture est entrée à contresens à hauteur de Gerland.<br>2 personnes sont décédées <br>4 blessés légers pris en charge par <a href="https://twitter.com/SDMIS69?ref_src=twsrc%5Etfw">@SDMIS69</a> <br><br>Le trafic a pu rendre à 10h30 dans les deux sens de circulation.<a href="https://twitter.com/PoliceNat69?ref_src=twsrc%5Etfw">@PoliceNat69</a></p>&mdash; Préfet de région Auvergne-Rhône-Alpes et du Rhône (@prefetrhone) <a href="https://twitter.com/prefetrhone/status/1355452127410352130?ref_src=twsrc%5Etfw">January 30, 2021</a></blockquote>
<script src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
''')
```
What i got with HtmlWidget :
![image](https://user-images.githubusercontent.com/37028599/106937515-23121700-671e-11eb-887b-2463087865b5.png)

It should be equal like : 
![image](https://user-images.githubusercontent.com/37028599/106934956-13450380-671b-11eb-915b-4f27f8aa797e.png)

I can't use some simples WebView packages because, with them, I can't handle properly the height (so i got scroll bar).
(If you have an other solution, I'm listening !)

**Comment by daohoangson** [comment]
`SCRIPT` tags won't be supported, they are in fact stripped before rendering even. For Twitter embed, take a look into the [demo app](https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/lib/screens/iframe_twitter.dart). This package uses the official webview package but it does have auto height so it works most of the time.

**Comment by EArminjon** [comment]
> `SCRIPT` tags won't be supported, they are in fact stripped before rendering even. For Twitter embed, take a look into the [demo app](https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/lib/screens/iframe_twitter.dart). This package uses the official webview package but it does have auto height so it works most of the time.

Thanks for your answer but i didn't help me (i can got all type of embed : twitter, facebook, instagram, etc).
I hope this feature be supported one day :) (maybe with an async builder something like that ?)

**Comment by daohoangson** [comment]
Normally embedded contents are put inside some special container, a DIV with a specific class name etc., you can use that to trigger the webview and display the rich embedded post within your app. I have help a few people to implement this, it's quite simple if you control the HTML generation too (e.g. you have some backend that generates HTML for your app). Hit me at daohoangson at gmail dot com if you need further assistance on this. I'm closing this issue for now.
