### ISSUE TITLE
Link Color Not Using Accent Color

### ISSUE THREAD

**Issue by sanders41** [daohoangson/flutter_widget_from_html#43]
Instead of using the theme accent color for links they are showing up as a "default" html blue color. My theme data is:

    theme: ThemeData(
      primaryColor: Colors.green,
      accentColor: Colors.greenAccent,
      fontFamily: 'Roboto',
    ),

Do I need to somehow pass the theme color to the HtmlWidget with theme.of(context) or something like that?

My HtmlWidget currently looks like this:

    HtmlWidget(
      post.content.rendered,
    )

I also tried wrapping it in a theme widget, but the link color is the same blue with this.

    Theme(
      data: Theme.of(context).copyWith(accentColor: Colors.greenAccent),
      child: HtmlWidget(
        post.content.rendered,
      ),
    ),

**Comment by daohoangson** [comment]
Which package are you using? This plugin publishes 2 packages on pub.dev: [flutter_widget_from_html](https://pub.dev/packages/flutter_widget_from_html) and [flutter_widget_from_html_core](https://pub.dev/packages/flutter_widget_from_html_core). The core one has fewer dependencies and will render link in blue.

**Comment by sanders41** [comment]
I'm using flutter_widget_from_html `flutter_widget_from_html: ^0.2.0`

**Comment by daohoangson** [comment]
Ah, the accent color has been implemented recently so it's not in `0.2.0` yet. A new minor version is being pushed right now, I will update this issue when that's done.

**Comment by daohoangson** [comment]
`v0.2.1` has just been released, please try again with this version.

**Comment by sanders41** [comment]
That fixed it. Thanks for releasing so quickly.
