### ISSUE TITLE
[web] ul html element is not rendering correctly with canvaskit in web

### ISSUE THREAD

**Issue by arunmt024** [daohoangson/flutter_widget_from_html#437]
Simple `ul `tag is not rendering correctly in web. And I am using below command 

`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true` 

```
<ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul>
```

**Comment by arunmt024** [comment]
@daohoangson  any suggestion or work around until next release ?

**Comment by daohoangson** [comment]
Version `0.5.2+1` has been released with the workaround for this. Please try upgrading and let me know if it works for you.

**Comment by arunmt024** [comment]
@daohoangson  I have tested your changes and its working for me Thank you :-)
