### ISSUE TITLE
Is the package support WKWebView for ios?

### ISSUE THREAD

**Issue by sunilsharma2** [daohoangson/flutter_widget_from_html#442]
I have used the package to render the html but its third time Apple store reject the application, showing issue with the Webview. It shows For Guideline 4.2 - Design - Minimum Functionality, with screenshot of Web view.The  content is rendered using an API from a Wordpress website.
please help.

**Comment by daohoangson** [comment]
Yes, this package uses the official Flutter package to render webview and it uses `WKWebView` on iOS.

Howerver, if your app is rejected with 4.2 - Minimum Functionality note, that means your app is too simple. E.g. you need to have more features in the app. It cannot be just a wrapper of a website.
