### ISSUE TITLE
Images show src url when displayed.

### ISSUE THREAD

**Issue by mtkgeek** [daohoangson/flutter_widget_from_html#443]
Hi, great package. My images are displayed with their source URL beneath them. How do I get rid of the URL.

**Comment by daohoangson** [comment]
That's weird... Can you share your HTML and preferably some screenshot?

**Comment by daohoangson** [comment]
Pinging @mtkgeek again. Sorry if this is bothering you.

**Comment by mtkgeek** [comment]
Hi @daohoangson, i totally forgot about this issue. This is not an issue with the package, the image element was in a Figure element that had a FigCaption which i totally missed.

**Comment by daohoangson** [comment]
Thanks for clearing things up and closing the issue 👍
