### ISSUE TITLE
Can I add a property to set the center display

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#445]
<img width="308" alt="QQ20210225-100754@2x" src="https://user-images.githubusercontent.com/40446804/109092416-6f66da80-7751-11eb-8965-3d77c49fe0d0.png">

The figure is the result of HTML parsing and display. It is a mixed text structure. Is there an attribute that can set the horizontal alignment of pictures and text? Now it seems that the default is bottom alignment. Thank you！

**Comment by daohoangson** [comment]
Can you share your HTML?

**Comment by dvzhou** [comment]
[html.txt](https://github.com/daohoangson/flutter_widget_from_html/files/6179037/html.txt)

Attached is the HTML content corresponding to the screenshot when I asked a question. I want the text and picture to be horizontally centered, but now they are aligned at the bottom. thanks.

**Comment by daohoangson** [comment]
If you can change the HTML, you can use `vertical-align` to set a center alignment but it isn't any better (I tried). Probably because the image is quite high in comparison with the surrounding text. It doesn't even look good in browsers.
