### ISSUE TITLE
The parsed picture is blurred on some phones

### ISSUE THREAD

**Issue by mulieli** [daohoangson/flutter_widget_from_html#446]
解析后的图片在部分手机会产生模糊
The parsed picture will be blurred on some phones
我不确定是哪里的问题
I'm not sure where the problem is

**Comment by daohoangson** [comment]
Sorry I don't speak Chinese. Can you do English please?

**Comment by mulieli** [comment]
> Sorry I don't speak Chinese. Can you do English please?

The picture will be blurred in some phones

**Comment by mulieli** [comment]
> Sorry I don't speak Chinese. Can you do English please?

I'm not sure what other factors affected

**Comment by daohoangson** [comment]
That's weird. What is your Flutter version? (`flutter doctor -v` output would be useful). And do you have sample HTML / specific phone models where this is happening?

**Comment by mulieli** [comment]
> That's weird. What is your Flutter version? (`flutter doctor -v` output would be useful). And do you have sample HTML / specific phone models where this is happening?

![image](https://user-images.githubusercontent.com/24307960/109131868-2b45fb00-778e-11eb-82f2-8457dd99c0c4.png)

A Huawei mobile phone was found

I am still not sure if it is a library problem

**Comment by mulieli** [comment]
> That's weird. What is your Flutter version? (`flutter doctor -v` output would be useful). And do you have sample HTML / specific phone models where this is happening?

Could it have something to do with the phone?

**Comment by mulieli** [comment]
Thanks, I found that it is not a problem with the library. This problem can be closed
