### ISSUE TITLE
Text disappears upon using the "textStyle" property of HtmlWidget

### ISSUE THREAD

**Issue by ShantanuBalse** [daohoangson/flutter_widget_from_html#45]
I would really like to be able to change the font size but it seems that the rendered text disappears entirely as soon as I assign a new TextStyle to the "textStyle" property.
Here's what my code looks like:

`HtmlWidget(this.content, webView: true, webViewJs: true, textStyle: new TextStyle(fontSize: 15.0));`

It works fine without the textStyle:

`HtmlWidget(this.content, webView: true, webViewJs: true);`

Any thoughts on this?

**Comment by daohoangson** [comment]
You need to get the default text style and adjust it instead of creating a new style from scratch (it won't have a color so it's invisible). I will try to improve this in the next version. In the mean time, please try this:

```dart
final defaultStyle = DefaultTextStyle.of(context).style;
final textStyle = defaultStyle.copyWith(fontSize: 15);

return HtmlWidget(...);
```
```

**Comment by ShantanuBalse** [comment]
That worked. Many thanks for all your hard work :)

**Comment by daohoangson** [comment]
`v0.2.1+1` has been released with smarter TextStyle support. It's now possible to give `HtmlWidget` an incomplete text stype.

**Comment by daohoangson** [comment]
I'm closing this issue because a new version has been released to address it.
