### ISSUE TITLE
Can't play html 5 player

### ISSUE THREAD

**Issue by daracodecourse** [daohoangson/flutter_widget_from_html#46]
Your browser does not support HTML5 video

**Comment by daohoangson** [comment]
What is the html that triggers this error?

**Comment by daracodecourse** [comment]
<video width="100%" controls>
  <source src="https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>

**Comment by daohoangson** [comment]
Err, I was asking about the actual html that triggered the error, not the error message itself.

**Comment by daracodecourse** [comment]
I just put html 5 video tag with src

**Comment by daohoangson** [comment]
Do you have some html I can use to reproduce the issue? Also, which device are you testing on? Simulator/emulator or real iOS/Android device?

**Comment by daracodecourse** [comment]
i test it on android

**Comment by daohoangson** [comment]
I have just tried this html

```html
<video width="400" controls>
  <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
  <source src="https://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">
  Your browser does not support HTML5 video.
</video>
```

And it does show "Your browser does not support HTML5 video." so I guess your html is something similar (couldn't see it in your comment above). 

This is expected behavior because VIDEO tag is currently not supported. You can see the list of supported tags at [the repo root](https://github.com/daohoangson/flutter_widget_from_html). However, I do plan to add support for VIDEO eventually so... Let's see whether this can be implemented quick enough.

**Comment by daracodecourse** [comment]
Ok thank. But I have another problem. In iOS device it always auto play.

**Comment by daohoangson** [comment]
How can it autoplay if the video tag is not supported? Can you share the html?

**Comment by daracodecourse** [comment]
I use iframe instate of video tag
`
<iframe src="https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4" width="1", height="1"></iframe>
`

**Comment by daohoangson** [comment]
Oh, it's the default behavior of web view. I'm afraid you can't change it.

If you are comfortable with running unreleased code, I have a working implementation for VIDEO tag in this PR #47

**Comment by daracodecourse** [comment]
Ok i will try it.

**Comment by daohoangson** [comment]
Have you had a chance to checkout the PR? @daracodecourse

**Comment by daracodecourse** [comment]
Not yet

**Comment by daohoangson** [comment]
Just FYI: v0.2.2 has been released with support for VIDEO tag.

**Comment by daracodecourse** [comment]
Ok i will test it
