### ISSUE TITLE
DefaultTextStyle triggers Unexpected Null Value using header tags

### ISSUE THREAD

**Issue by bamnet** [daohoangson/flutter_widget_from_html#460]
Using a `DefaultTextStyle` to change the default color of text works for simple elements like a `<p>` tag, but causes a null value error if the HTML contains `<h1>` tags (or alike).

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('HelloWorldCoreScreen')),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: DefaultTextStyle(
                style: TextStyle(color: Colors.red),
                child: HtmlWidget("<h1>Header</h1>")),
          ),
        ),
      );
}
```

The error appears to be coming from the `getValue` method on the `CssLength` class --

```
case CssLengthUnit.em:
        baseValue ??= tsh.style.fontSize;
        value = baseValue * number;

Exception has occurred.
"Error: NoSuchMethodError: '<Unexpected Null Value>'
method not found
Receiver: null
```

**Comment by daohoangson** [comment]
With `DefaultTextStyle`, you must give it a full style (all properties must be not null). If you only need to specify the color, use `HtmlWidget.textStyle` property, it will be merged with the existing default style and should work properly. Something like this:

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('HelloWorldCoreScreen')),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: HtmlWidget(
                "<h1>Header</h1>",
                textStyle: TextStyle(color: Colors.red),
            ),
          ),
        ),
      );
}
```

**Comment by bamnet** [comment]
Oh interesting, I can work around this by adding a `fontSize: 14` to my `DefaultTextStyle`.  Since it's applied much higher in the hierarchy it's not very easy to remove and switch to the textStyle approach.

To me this feels like bug, the documentation for DefaultTextStyle doesn't specify the fontSize property is required so users may not expect this behavior. If there's no way for this library to access the font size, perhaps falling back to a default like 14 would make sense.  Just my 2 cents tho

**Comment by daohoangson** [comment]
I see your point. Let me check if we can improve this.

**Comment by daohoangson** [comment]
A temporary workaround for this is:

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('HelloWorldCoreScreen')),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: DefaultTextStyle(
                style: DefaultTextStyle.of(context).style.copyWith(color: Colors.red),
                child: HtmlWidget("<h1>Header</h1>")),
          ),
        ),
      );
}
```

**Comment by daohoangson** [comment]
The latest 0.6.0 pre-release includes the fix for this: it will fallback gracefully if the font-size is unavailable.

**Comment by bamnet** [comment]
I got a chance to test out `0.6.0-rc.2021030401`.  I no longer get the null error :partying_face: but it looks like all the elements are falling back to the same size; an H1 is the same size as a H2, etc.  That may be good enough given the workaround from https://github.com/daohoangson/flutter_widget_from_html/issues/460#issuecomment-788735313 fixes the issue all together.

**Comment by daohoangson** [comment]
> but it looks like all the elements are falling back to the same size; an H1 is the same size as a H2, etc. 

That is expected because those headers are configured like "1.3 times the default font size" so when the default value is missing, they will be undefined. Thanks for your feedback 🚀
