### ISSUE TITLE
Image fit is inconsistent for large images

### ISSUE THREAD

**Issue by vycius** [daohoangson/flutter_widget_from_html#467]
Image fit is inconsistent for large images between loading and getting from the cache. See the following GIF:

![inconsistent-fit](https://user-images.githubusercontent.com/3719141/110596423-f4a5b280-8187-11eb-8695-123227d8c9df.gif)

# Code to reproduce
```dart
flutter_widget_from_html: ^0.5.2+1

HtmlWidget(
'<img src="https://upload.wikimedia.org/wikipedia/commons/4/4e/Pleiades_large.jpg?q=3129" style="height:1476px; width:1063px" />',
)
```

**Comment by daohoangson** [comment]
Without the inline dimensions, it shows up fine. Is there any reason you have those inline styles? And the ratio of the width/height is wrong too.

**Comment by vycius** [comment]
For us it's quite a low priority. Although, I believe that for some people it might be quite unpleasant bug.

My use case. 
While adding html from backend using wysiwyg editor width and height style attributes are automatically added to the image tag. If image doesn't fit, bug appears on first load. Fortunatelly, we have a really simple workaround: removing width and height attributes by hand. 

For ratio it's my mistake by changing image, but it doesn't really matter for this bug.

**Comment by daohoangson** [comment]
Understood. I'll see what can be done here, hmm...

**Comment by daohoangson** [comment]
The new `v0.6.0` release is out, there are a few underlying changes and it appears this specific instance of the buggy behavior has been gone. Please try upgrading and let me know.

**Comment by vycius** [comment]
Thank you.
