### ISSUE TITLE
when used flutter_widget_from_html: ^0.5.2+1  resizeToAvoidBottomPadding: false,

### ISSUE THREAD

**Issue by mohamedElsayed-course** [daohoangson/flutter_widget_from_html#470]
![Screen Shot 2021-03-14 at 12 57 57 PM](https://user-images.githubusercontent.com/67856481/111065905-e8da2900-84c4-11eb-9306-7444b82fb944.png)

**Comment by daohoangson** [comment]
What is your Flutter version? We don't enforce a specific `chewie` version so you may need to specify a compatible version in your `pubspec.yaml`.

**Comment by mohamedElsayed-Qtoof** [comment]
![Uploading Screen Shot 2021-03-15 at 11.01.56 AM.png…]()

**Comment by mohamedElsayed-Qtoof** [comment]
![Screen Shot 2021-03-15 at 11 01 56 AM](https://user-images.githubusercontent.com/67856481/111128953-31a1e880-857e-11eb-9513-b5a67038b8ae.png)

**Comment by daohoangson** [comment]
Adding override should help:

```yaml
  dependency_overrides:
     chewie: ^1.0.0
```

Or you can migrate to `flutter_widget_from_html: ^0.6.0-0`.
