### ISSUE TITLE
How  self define PlaceholderAlignment of image tag.

### ISSUE THREAD

**Issue by ykrank** [daohoangson/flutter_widget_from_html#476]
I changed local source  TagImg with
```
tree.replaceWith(meta.willBuildSubtree!
              ? WidgetBit.block(tree, placeholder)
              : WidgetBit.inline(tree, placeholder, alignment: PlaceholderAlignment.bottom));
```
but perhaps there has other better solution?

**Comment by daohoangson** [comment]
Are you in control of the HTML? If you do, you can do something like `<img src="..." style="vertical-align: bottom" />` to force a bottom alignment.

**Comment by ykrank** [comment]
finally，i reg another self defined TagImg with higher priority
