### ISSUE TITLE
not able to use with webview_flutter: ^2.0.2

### ISSUE THREAD

**Issue by DevMalik08** [daohoangson/flutter_widget_from_html#477]
trying to use flutte_widget_from_html with webview_flutter package. but showing following error while running pub get:

Because flutter_widget_from_html >=0.5.0+7 <0.6.0-rc.2021030201 depends on webview_flutter >=0.3.22 <2.0.0 and samajho_learning_app depends on webview_flutter ^2.0.2, flutter_widget_from_html >=0.5.0+7 <0.6.0-rc.2021030201 is forbidden.
So, because samajho_learning_app depends on flutter_widget_from_html ^0.5.2+1, version solving failed.
pub get failed (1; So, because samajho_learning_app depends on flutter_widget_from_html ^0.5.2+1, version solving failed.)

**Comment by daohoangson** [comment]
A new release has just been made available: `v0.6.0` which includes proper Flutter 2 support. It should solve your issue with the dependencies. Please try upgrading and let me know if it works for you.
