### ISSUE TITLE
How to remove the default margin bottom of "p" tag?

### ISSUE THREAD

**Issue by dangduoc** [daohoangson/flutter_widget_from_html#482]

**Comment by daohoangson** [comment]
You can use `customStylesBuilder` to override the default margins, something like this:

```dart
            HtmlWidget(
              html,
              customStylesBuilder: (e) {
                switch (e.localName) {
                  case 'p':
                    return {'margin': '0'};
                }

                return null;
              },
            ),
```

**Comment by dangduoc** [comment]
> You can use `customStylesBuilder` to override the default margins, something like this:
> 
> ```dart
>             HtmlWidget(
>               html,
>               customStylesBuilder: (e) {
>                 switch (e.localName) {
>                   case 'p':
>                     return {'margin': '0'};
>                 }
> 
>                 return null;
>               },
>             ),
> ```

Thanks! I have tried the same way but if there are more than one "p" tag, only one would be applied customStyles
html sample:
<p>line one</p>
<p>line two</p>
<p>line three</p> (only this one has margin = 0)
...

**Comment by daohoangson** [comment]
Can you share a small reproducible example? I'm running this and it seems to work:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

const kHtml = '''
<p>line one</p>
<p>line two</p>
<p>line three</p>
''';

class HelloWorldScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('HelloWorldScreen')),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: HtmlWidget(
              kHtml,
              customStylesBuilder: (e) {
                switch (e.localName) {
                  case 'p':
                    return {'margin': '0'};
                }

                return null;
              },
            ),
          ),
        ),
      );
}
```

<img src="https://user-images.githubusercontent.com/239336/114119154-4f136980-9914-11eb-88d4-1e6638a44f4c.png" width="300" />

**Comment by dangduoc** [comment]
> Can you share a small reproducible example? I'm running this and it seems to work:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
> 
> const kHtml = '''
> <p>line one</p>
> <p>line two</p>
> <p>line three</p>
> ''';
> 
> class HelloWorldScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Scaffold(
>         appBar: AppBar(title: Text('HelloWorldScreen')),
>         body: SingleChildScrollView(
>           child: Padding(
>             padding: const EdgeInsets.all(8.0),
>             child: HtmlWidget(
>               kHtml,
>               customStylesBuilder: (e) {
>                 switch (e.localName) {
>                   case 'p':
>                     return {'margin': '0'};
>                 }
> 
>                 return null;
>               },
>             ),
>           ),
>         ),
>       );
> }
> ```
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/239336/114119154-4f136980-9914-11eb-88d4-1e6638a44f4c.png">

Thanks you, it turned out working well.
