### ISSUE TITLE
`div.id` anchor doesn't works correctly if contents are huge

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#487]

**Comment by DFelten** [comment]
Maybe our current solution with flutter_html and anchor link could help here. It's a bit "dirty", but it works. 

We're adding a global key to each widget that includes an anchor link. This global key is stored together with the corresponding id and a position within a map. The position is at the beginning null.

```dart
@freezed
class TocSectionProperties with _$TocSectionProperties {
  const factory TocSectionProperties({
    String? elementId,
    GlobalKey? globalKey,
    double? position,
  }) = _TocSectionProperties;
}
```
The example is from flutter_html, but I think the logic is understandable.
```dart
Widget _buildTocSections(Widget child, dom.Element element) {
  final String? id = element.children[0].attributes['id'];
  final Map<String, TocSectionProperties?> tocMap = _htmlElementPropertyMaps.tocMap;

  if (id != null && tocMap[id] == null) {
    final GlobalKey globalKey = GlobalKey(debugLabel: 'ToC');
    tocMap[id] = TocSectionProperties(elementId: id, globalKey: globalKey);
  }

  final GlobalKey? tocKey = id != null ? tocMap[id]?.globalKey : null;

  return Container(
    key: tocKey ?? GlobalKey(debugLabel: 'ToC 2'),
    child: child,
  );
}
```

When a user selects the anchor link, we load the entire HTML list, calculate the positions of each item and store them in the map. Then we display the HTML again as a ListView. Now it's possible to jump to the position within the ListView.

The code for the jump:

```dart
void _jumpToKeyWhenKeyIsReady(String key) {
  // Jump to a table of content link. On the first jump a list of each toc position is build. This position is
  // used for jumping and all following jumps. To get the positions, the html content must be completely built
  // up once. For this, the ListView is deactivated and activated again later.
  // Jumping is tried until the key is available or it has been tried ten times.
  final TocSectionProperties? tocSectionProperties = _htmlElementPropertyMaps.tocMap[key];

  if (tocSectionProperties?.position == null) {
    _showContentAsListView(false);

    Future.delayed(const Duration(milliseconds: 10)).then((value) {
      if (_htmlElementPropertyMaps.tocMap[key] != null) {
        _buildSectionPositionList();
        _animateToElement(key);
        _showContentAsListView(true);
      } else {
        if (counter < 10) {
          _jumpToKeyWhenKeyIsReady(key);
        } else {
          _showContentAsListView(true);
        }
      }
      counter++;
    });
  } else {
    _animateToElement(key);
  }
}
```
The solution is not beautiful, but it works and maybe it will help to find a better one.

**Comment by daohoangson** [comment]
This is interesting. Thank you for the suggestion, I'll see what can be done.

**Comment by DFelten** [comment]
But as far as I can see the fix only works for html list with columns, right? Not for the list and sliver lists.

**Comment by daohoangson** [comment]
That is correct @DFelten. The current fix deals with a smaller bug as mentioned in this issue (DIVs with `id` don't work). It doesn't change anything about anchors in list view. I'll try to address that in the render mode PR, maybe something similar to your implementation above. I'm not sure yet.
