### ISSUE TITLE
Iframe change postion when scroll

### ISSUE THREAD

**Issue by anh-ht** [daohoangson/flutter_widget_from_html#490]
Hi guy,
Can you investigate and fix it ? 
https://user-images.githubusercontent.com/17286061/114986131-cf5e3f80-9ebd-11eb-980c-5c42d8a12551.mov

**Comment by daohoangson** [comment]
I did notice this in the demo app but I don't have a real iPhone right now to verify. It works fine on Android though. My initial guess is it's a debug/simulator thing. Have you been able to reproduce on a real device?

**Comment by anh-ht** [comment]
Same issue :(. But has not been fixed.
https://github.com/flutter/flutter/issues/30336

**Comment by daohoangson** [comment]
This looks like an issue with PlatformView / WebView within iOS in general. It is not specific to this package...
