### ISSUE TITLE
TD Tag empty manipulate to have width

### ISSUE THREAD

**Issue by ralphskie** [daohoangson/flutter_widget_from_html#494]
Hi, im wondering on how to do this.

been checking the **customWidgetBuilder** but im not sure what to put.

basically my HTML table has an empty `<td></td>`,I want to put an `&nbsp;` inside of it so it can have a width.

sample of my HTML table

```html
<table>
<tbody>
<tr>
<th>SPECIFICATIONS</th>
<th data-colwidth="112"></th>
<th data-colwidth="844"></th>
</tr>
<tr>
<td><strong>NETWORK</strong></td>
<td data-colwidth="112"><strong>Technology</strong></td>
<td data-colwidth="844">GSM / HSPA / LTE</td>
</tr>
<tr>
<td><strong>LAUNCH</strong></td>
<td data-colwidth="112"><strong>Released</strong></td>
<td data-colwidth="844">2021. Feb. 25</td>
</tr>
<tr>
<td><strong>BODY</strong></td>
<td data-colwidth="112"><strong>Dimensions</strong></td>
<td data-colwidth="844">6.26 x 2.90 x 0.33 in</td>
</tr>
<tr>
<td></td>
<td data-colwidth="112"><strong>Weight</strong></td>
<td data-colwidth="844">184 g</td>
</tr>
<tr>
<td></td>
<td data-colwidth="112"><strong>SIM</strong></td>
<td data-colwidth="844">Dual SIM (Nano-SIM)</td>
</tr>
<tr>
<td><strong>DISPLAY</strong></td>
<td data-colwidth="112"><strong>Type</strong></td>
<td data-colwidth="844">Super AMOLED</td>
</tr>

</tbody>
</table>
```

**When rendered on simulator it becomes like this**
![2021-04-21 11_40_11-ralph-personal-laptop@ad - AnyDesk](https://user-images.githubusercontent.com/5318148/115493921-32bde800-a297-11eb-8a42-ffbd8def42c1.png)

But when I change it to `<td>$nbsp</td>` it will be like this, which I prefer
![2021-04-21 11_41_28-ralph-personal-laptop@ad - AnyDesk](https://user-images.githubusercontent.com/5318148/115493998-5a14b500-a297-11eb-99cd-6c99195e0576.png)

Kindly see the **Weight row**

Edit : Fix it (temp) already by `string.replaceAll('<td></td>', '<td>&nbsp</td>');` but maybe there are more better solution than this

**Comment by daohoangson** [comment]
This looks like a bug, which version of this package are you using?

**Comment by ralphskie** [comment]
im using the latest version **0.6.0**

**Comment by daohoangson** [comment]
Version `0.6.1` has been released with the fix for this. Please try upgrading and see whether it works, thank you.

**Comment by ralphskie** [comment]
Just tested, new version **0.6.1** fix this issue. Thank you
