### ISSUE TITLE
Open link in HtmlWidget

### ISSUE THREAD

**Issue by JuanNova** [daohoangson/flutter_widget_from_html#5]
Hi,

I only have a problem with android platform when I try to open a link inside the HtmlWidget, in iOS platform it's ok. 

The problem that I reach is:

`E/MethodChannel#plugins.flutter.io/url_launcher( 6924): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.app.ContextImpl.startActivity(ContextImpl.java:682)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.app.ContextImpl.startActivity(ContextImpl.java:669)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at io.flutter.plugins.urllauncher.UrlLauncherPlugin.onMethodCall(UrlLauncherPlugin.java:61)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#plugins.flutter.io/url_launcher( 6924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter ( 6924): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6924): PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null)
E/flutter ( 6924): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 6924): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 6924): <asynchronous suspension>
E/flutter ( 6924): #2      launch (package:url_launcher/url_launcher.dart:66:19)
E/flutter ( 6924): #3      WidgetFactory.prepareGestureTapCallbackToLaunchUrl.<anonymous closure> (package:flutter_widget_from_html/src/widget_factory.dart:134:17)
E/flutter ( 6924): <asynchronous suspension>
E/flutter ( 6924): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 6924): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 6924): #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 6924): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 6924): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 6924): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 6924): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter ( 6924): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 6924): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 6924): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 6924): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 6924): #15     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 6924): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
`
Displayed in One Plus One : android 6.0
Widget Version: flutter_widget_from_html: ^0.1.0

**Comment by daohoangson** [comment]
Can you give me some reproduce code? e.g. how did you build the widget tree, what is the html being rendered etc.

**Comment by JuanNova** [comment]
Hi,

I know what's hapenning!!!! In my project that I am developing, I have an older version of the url_launcher extension, I only have to go to [url_launcher install instructions](https://pub.dartlang.org/packages/url_launcher#-installing-tab-) and add it on my pubspec.yaml file.

It rules like a charm, Thx

**Comment by daohoangson** [comment]
It's great that you have figured it out 🥳
