### ISSUE TITLE
Clip the content to a specific size?

### ISSUE THREAD

**Issue by kenthinson** [daohoangson/flutter_widget_from_html#502]
Hello I am trying to limit he size of the content. I tried using CipPath however the Widget still takes up the full amount of space even though it's visually clipped. Do you have a recommendation?

**Comment by daohoangson** [comment]
I'm having a hard time to visualize this. Can you share your HTML, dart code and screenshot is possible?

**Comment by kenthinson** [comment]
@daohoangson I found a different workaround my limiting the content server side. It was more efficient anyways. So Closing this.
