### ISSUE TITLE
Images from wordpress content description are not using max width or height or cropped.

### ISSUE THREAD

**Issue by rakib205** [daohoangson/flutter_widget_from_html#505]
Hi there, I am using this package to show my WordPress website contents and its description. Everything works fine but the images from the content description are slightly cropped or not using the full width though I tried to change the image width from the WordPress editor. Please look at the picture below : 

### Screenshot of the content screen
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-03 at 12 04 29](https://user-images.githubusercontent.com/34546369/116845666-46a70980-ac08-11eb-85a8-148258dadfc9.png)

### My Code for this screen
```
Container(
      child: HtmlWidget(
        article.content,
        enableCaching: true,
        webView: true,
        webViewMediaPlaybackAlwaysAllow: true,
      ),
);
```

### WordPress Html code for the image

`<figure class="wp-block-image size-full"><img src="http://recipehour.xyz/wp-content/uploads/2021/04/529416e3-b77a-4133-a4b0-3866e2edf860-2019-0110_zuni-inspired-grilled-chicken-salad_3x2_ty-mecham.jpg" alt="" class="wp-image-103"/></figure>`

### What I Want
How can I remove the extra padding? I mean I want to use the full width of the picture.

Thanks

**Comment by daohoangson** [comment]
That's the `FIGURE` tag's default margin, take a look at the two possible solutions here https://github.com/daohoangson/flutter_widget_from_html/issues/401#issuecomment-753740708. Let me know if it works for you.

**Comment by rakib205** [comment]
> That's the `FIGURE` tag's default margin, take a look at the two possible solutions here [#401 (comment)](https://github.com/daohoangson/flutter_widget_from_html/issues/401#issuecomment-753740708). Let me know if it works for you.

Thanks. It works!

**Comment by daohoangson** [comment]
That's great to hear 🚀 I'm closing this issue now. Feel free to open another one if you run into something else.
