### ISSUE TITLE
I am using a version of the web flutter, and img does not render on the screen

### ISSUE THREAD

**Issue by jheimes-silveira** [daohoangson/flutter_widget_from_html#524]
when I use it on the Android device, everything works normally, but for the web version, it does not render the image on the screen.

I used the HTML code below

```
<p>✅✅✅ Winnnn em nossa entrada das 13h!!!!!✅✅✅✅<br />🟠💰 PLANO VITALÍCIO! Assine agora o INSIDERS com plano VITALÍCIO! Tenha para sempre acesso a todas as SALAS, CURSOS E PRODUTOS!<br /><a href="https://insiderscap.com/pro/convite-final">https://insiderscap.com/pro/convite-final</a></p>
<p><img class="alignnone size-full wp-image-3342" src="https://insiderscap.com/members/wp-content/uploads/2021/05/14-05-13h.png" alt="" width="413" height="369" /></p>
```
<p>✅✅✅ Winnnn em nossa entrada das 13h!!!!!✅✅✅✅<br />🟠💰 PLANO VITALÍCIO! Assine agora o INSIDERS com plano VITALÍCIO! Tenha para sempre acesso a todas as SALAS, CURSOS E PRODUTOS!<br /><a href="https://insiderscap.com/pro/convite-final">https://insiderscap.com/pro/convite-final</a></p>
<p><img class="alignnone size-full wp-image-3342" src="https://insiderscap.com/members/wp-content/uploads/2021/05/14-05-13h.png" alt="" width="413" height="369" /></p>

**Comment by daohoangson** [comment]
Do you have your web app uploaded somewhere for me to check? I think you may have some CORS issue with the images. Read it in full here https://flutter.dev/docs/development/platform-integration/web-images

Basically you have two options:

1. Enable CORS header for the images, if you control that web server
2. Switch to HTML renderer

**Comment by jheimes-silveira** [comment]
can show me some example that i can follow, where i can switch to HTML renderer

**Comment by daohoangson** [comment]
You can force the renderer this way:

```bash
flutter build web --web-renderer html
```

**Comment by daohoangson** [comment]
It has been a while, I'm closing this issue now. Feel free to reopen it if you are still having issue.
