### ISSUE TITLE
app keeps crashing on android

### ISSUE THREAD

**Issue by himanshu64** [daohoangson/flutter_widget_from_html#534]
## Steps to Reproduce
when i tried to render iframe with webview its keeps crashing

<details>
  <summary>HTML</summary>

```html

Welcome to The , we are glad you’re here!

Use the videos below to start your library journey.

<iframe src="https://www.youtube.com/embed/0woOKoGtsFI" width="100%" height="500" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

<iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 500px;" src="https://www.loom.com/embed/0ca7196d6d504f5d916a05d25af240d9" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

```

</details>

<details>

 flutter_widget_from_html: ^0.5.2+1

```dart

                HtmlWidget(
                  welcomeSnapshot.content,
                  webView: true,
                  webViewJs: true,
                  enableCaching: true,
                  // webView: true,
                  unsupportedWebViewWorkaroundForIssue37: true,
                )

```

</details>

<details>
  <summary>Tesing environment</summary>

```
Running "flutter pub get" in flutter_tools...                      808ms
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.6 at /home/app/snap/flutter/common/flutter
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/app/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • ASUS X01AD (mobile)         • JCAAGF03L9339U6 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554   • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome          • web-javascript • Google Chrome 91.0.4472.77
```

</details>

## Actual results

I/Choreographer(22116): Skipped 66 frames!  The application may be doing too much work on its main thread.
E/GLConsumer(22116): [SurfaceTexture-0-22116-0] attachToContext: invalid current EGLDisplay
E/flutter (22116): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter (22116): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:289)
E/flutter (22116):
F/flutter (22116): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1062)] Check failed: CheckException(env).
F/libc    (22116): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22162 (1.raster), pid 22116 (utritionlibrary)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'asus/WW_X01AD/ASUS_X01A_1:9/WW_Phone-202011271133/16.2018.2011.78-20201127:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 22116, tid: 22162, name: 1.raster  >>> com.theprenatalnutritionlibrary <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1062)] Check failed: CheckException(env).
'
    x0  0000000000000000  x1  0000000000005692  x2  0000000000000006  x3  0000000000000008
    x4  0000000000008000  x5  0000000000008000  x6  0000000000008000  x7  0080000000000000
    x8  0000000000000083  x9  0e86749c801625b9  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000008  x14 ffffffffffffffff  x15 0000bc5c6b1420b9
    x16 0000007eab9732b8  x17 0000007eab894a50  x18 0000000000000010  x19 0000000000005664
    x20 0000000000005692  x21 0000007e0977e4b8  x22 0000007e04c31188  x23 0000000000000000
    x24 0000000000000000  x25 0000000000000001  x26 0000007e09780588  x27 000000000000003f
    x28 0000000000000001  x29 0000007e0977e4a0
    sp  0000007e0977e460  lr  0000007eab886084  pc  0000007eab8860ac
backtrace:
    #00 pc 00000000000220ac  /system/lib64/libc.so (abort+116)
    #01 pc 0000000001287244  /data/app/com.app-gQMRVOBRzgAqnjNCtFepOQ==/lib/arm64/libflutter.so (offset 0x126e000)
    #02 pc 00000000000020dc  [anon:.bss:0000007e0b483000]
Lost connection to device.

**Comment by daohoangson** [comment]
I can't test right now but can you do a quick test by removing the heights from the HTML? Something like this:

```html
Welcome to The , we are glad you’re here!

Use the videos below to start your library journey.

<iframe src="https://www.youtube.com/embed/0woOKoGtsFI" width="100%" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

<iframe style="position: absolute; top: 0; left: 0; width: 100%;" src="https://www.loom.com/embed/0ca7196d6d504f5d916a05d25af240d9" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
```

**Comment by himanshu64** [comment]
**its not working either**

**Comment by daohoangson** [comment]
Have you been able to figure this out?
