### ISSUE TITLE
Add method to find the position of rendered Tag

### ISSUE THREAD

**Issue by sanjeevbishnoi** [daohoangson/flutter_widget_from_html#536]
## Use case

First, of all, thanks for making such a wonderful plugin, But I got stuck on a feature,  On the Web, we normally see when we search for something, then all occurrences of text got highlighted. We see a controller to go to different occurrences of it and the screen scrolls automatically.  I have highlighted the searched term with the help of the <mark> tag. But now the I want to find out all the positions(position on a mobile screen) of these <mark> tags to move to and forth. 
is there any method to find out the global or local position of these <mark> tags so that I can move the HTML text accordingly?

## Proposal

We need something like customWidgetBuilder with BuildContext(which tells about the position of the widget in the widget tree)  after the mark or any tag has rendered. My idea is to store all these positions in Map and scrolls the scrollbar accordingly. I am afraid, I am going in the right direction. If anybody has a better way, please suggest me. I am one step away from Launching my app.

**Comment by daohoangson** [comment]
I think this is an interesting use case. Probably easiest to take advantage of the anchor system. Basically you need to render the highlighted text with an anchor (there are a few ways to do this). Then I can expose the scroll to anchor method for you to call from outside the widget (not possible with the current version of this package). 

Keeping track of the position yourself in a map is between hard and impossible, especially with the new `ListView` mode (coming soon in v0.7).

**Comment by daohoangson** [comment]
`v0.7.0` has been released with support for the `scrollToAnchor` method. It is now possible to use a `GlobalKey` to keep track of the `HtmlWidgetState` and request a scroll when appropriate. Please try upgrading and let me know if it works for you.

**Comment by atul-chaudhary** [comment]
Hey @daohoangson thanks for adding functionality was a lifesaver for me 😉

**Comment by daohoangson** [comment]
Thanks @atul-chaudhary for the kind words. This has been a while, I'm closing this issue now.

**Comment by atul-chaudhary** [comment]
Hey @daohoangson  wanted to know whether there is a search functionality in-built in HtmlWidget when we are dealing with huge HTML .

**Comment by daohoangson** [comment]
No, there is no built-in search feature.

**Comment by japatel225** [comment]
Hey @daohoangson - thank you for the amazing plugin. `scrollToAnchor` works great for the search feature in my app. However, when the matched word is inside a table element, it doesn't scroll to it. It only scrolls to the top of the table it seems. Is there a way it can work?
