### ISSUE TITLE
Update chewie dependency  from 1.0.0 to 1.2.2 

### ISSUE THREAD

**Issue by figengungor** [daohoangson/flutter_widget_from_html#539]
flutter_widget_from_html and better_player has dependency conflicts because of chewie version.

**Comment by daohoangson** [comment]
Which version of this package are you using? The latest one uses `^1.0.0` for `chewie` so it should be compatible with `1.2.2` if your app needs that specific version.

**Comment by figengungor** [comment]
Sorry, I misunderstood the conflict. It was Dart version.
