### ISSUE TITLE
How rewrite tag style

### ISSUE THREAD

**Issue by ykrank** [daohoangson/flutter_widget_from_html#54]
In core_widget_factory, i found you set default style to blockquote
```dart
case 'blockquote':
      case 'figure':
        meta = lazySet(meta, styles: [kCssMargin, '1em 40px']);
        break;
```
I need change this style, so i lazyset stylesPrepend in builderCallback, like
```dart
meta = lazySet(meta, stylesPrepend: []);
```
but crash in assert(!meta._stylesFrozen); 
How can i change this style?

**Comment by daohoangson** [comment]
To overwrite those, you can either (1) use html inline style (`<blockquote style="margin: 2em">`) or (2) use a custom `WidgetFactory`.

**Comment by ykrank** [comment]
> To overwrite those, you can either (1) use html inline style (`<blockquote style="margin: 2em">`) or (2) use a custom `WidgetFactory`.

I see, thanks.
