### ISSUE TITLE
Migrate away from pedantic

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#541]
It has been deprecated (https://github.com/google/pedantic/pull/87)

Alternatives:

- https://pub.dev/packages/flutter_lints
- https://pub.dev/packages/lint

**Comment by DFelten** [comment]
We are currently using the lint package.  Out of interest, why did you choose this one? :)

**Comment by daohoangson** [comment]
I haven't decided yet. Added `lint` into the list, thank you!
