### ISSUE TITLE
how to use    buildAsyncBuilder  

### ISSUE THREAD

**Issue by samithe7** [daohoangson/flutter_widget_from_html#545]
buildAsyncBuilder: (_, snapshot) {
              

                  return snapshot.hasData
                    ? snapshot.data
                    : SizedBox(
                        height: MediaQuery.of(context).size.height,
                        child: const Center(child: CircularProgressIndicator()),
                      );
                },

it's not work

**Comment by daohoangson** [comment]
By default the async builder only kicks it if the HTML is longer than 10000 characters.

You can set `buildAsync: true` if you want to activate it always.

**Comment by samithe7** [comment]
thanks
