### ISSUE TITLE
First whitespaces trimmed

### ISSUE THREAD

**Issue by harujuki** [daohoangson/flutter_widget_from_html#546]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<p> Hello World!</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget('<p> Hello World!</p>');
```
</details>

<details>
  <summary>Tesing environment</summary>

No dependency on the testing environment
</details>

## Expected results

"\<p> Hello World!\</p>" shows " Hello World!"   
## Actual results

"\<p> Hello World!\</p>" shows "Hello World!"

**Comment by daohoangson** [comment]
This package tries to mimics whitespace rendering logic from browsers and Chrome seems to agree this time. What is your use case that needs the whitespace there?

<img width="1392" alt="Screen Shot 2021-07-11 at 00 32 38" src="https://user-images.githubusercontent.com/239336/125171652-82011e00-e1df-11eb-943c-3e4ef6c147cc.png">

**Comment by harujuki** [comment]
@daohoangson
I'm sorry, you are correct
The whitespace shoud not be trimmed was "　" (full-width whitespace)

**Comment by daohoangson** [comment]
`flutter_widget_from_html_core@0.6.1+4` has just been released with the fix for this. If you have the core package in your pubspec, you should update the version constraint. Otherwise running `flutter pub upgrade` should work.

**Comment by harujuki** [comment]
I confirmed the issue has fixed!
Thank you!
