### ISSUE TITLE
How to scale image when tap

### ISSUE THREAD

**Issue by yuankui** [daohoangson/flutter_widget_from_html#55]
Hello, my use case is like this:

1. tap a image
2. show the image in a new windows

is there some way that I can get the image tap callback with a image parameter.

> there is a `onImageTap` callback, but without paramater, so I don't know which image is tapped.

**Comment by daohoangson** [comment]
Which `onImageTap` callback were you talking about? This plugin doesn't have it.

For this, I think you should use a custom `WidgetFactory` and override the `buildImage` method. It will be called to render IMG tags.

https://github.com/daohoangson/flutter_widget_from_html/blob/5f4325485f85bc8b231f2b7acb9a0f9f8b409a30/packages/core/lib/src/core_widget_factory.dart#L116

**Comment by yuankui** [comment]
I'm sorry, I was a fool. 
I regarded  this lib as https://pub.dev/packages/flutter_html
