### ISSUE TITLE
Device orientation, after full screen video in IOS

### ISSUE THREAD

**Issue by Philippe-Nau** [daohoangson/flutter_widget_from_html#552]
On IOS the app does not return to DeviceOrientation.portraitUp, after full screen video.

**Comment by daohoangson** [comment]
Do you have a sample HTML?

**Comment by Philippe-Nau** [comment]
'<h1>What is Lorem Ipsum?</h1> <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p> <video controls> <source src="https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/GTYSdDW/man-getting-bloodpressure-checked-by-doctor-close-dolly_ekmmvwks__75d2ba6e098bf4e573a04680a4ceed4f__P360.mp4" type="video/mp4"></video> <p>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo</p>'

**Comment by daohoangson** [comment]
I have successfully reproduced your issue on iOS: the phone is stuck in landscape after fullscreen. A manual rotate is required to force it back to portrait.

It seems to be a problem with how [chewie](https://pub.dev/packages/chewie) (the video player) handles the orientation and a Flutter bug: https://github.com/flutter/flutter/issues/57748. I want to switch the default video player to [better_player](https://pub.dev/packages/better_player) soon but I'm not sure there is a better way to handle orientation change.

**Comment by Philippe-Nau** [comment]
Thanks brother, I created my own player, to solve this.

**Comment by daohoangson** [comment]
How did you handle this if you don't mind me asking?

**Comment by pepe19000** [comment]
Chewie has a parameter: deviceOrientationsAfterFullScreen.
Can you add this parameter to your package and connect to chewie?

**Comment by Philippe-Nau** [comment]
I used this parameter but the problem persisted.
I used another package for html.
I don't know if the problem happened because I was using it on a stack

**Comment by pepe19000** [comment]
How you used it if this package have not support this parameter yet?
My message was for @daohoangson

**Comment by Philippe-Nau** [comment]
i created my chewie

**Comment by daohoangson** [comment]
You can always override the method that builds the video player @pepe19000. It has all the HTML attributes prepared, ready to be used:

https://github.com/daohoangson/flutter_widget_from_html/blob/96db9bb64c43d2450b16da19ff802b8784e5fcc4/packages/fwfh_chewie/lib/src/chewie_factory.dart#L10-L19

**Comment by daohoangson** [comment]
Thank you for your feedback @Philippe-Nau

**Comment by pepe19000** [comment]
> You can always override the method that builds the video player @pepe19000. It has all the HTML attributes prepared, ready to be used:

It is not clear to me this how to solve my fullscreen orientation problem. Can you share me an example?

**Comment by Rezki-Pratama** [comment]
> You can always override the method that builds the video player @pepe19000. It has all the HTML attributes prepared, ready to be used:
> 
> https://github.com/daohoangson/flutter_widget_from_html/blob/96db9bb64c43d2450b16da19ff802b8784e5fcc4/packages/fwfh_chewie/lib/src/chewie_factory.dart#L10-L19

can you give me an example, how to override this chewie factory ?

**Comment by daohoangson** [comment]
Something like this should work:

```dart
// override the built-in widget factory
class MyWidgetFactory extends WidgetFactory {
  @override
  Widget? buildVideoPlayer(
    BuildMetadata meta,
    String url, {
    required bool autoplay,
    required bool controls,
    double? height,
    required bool loop,
    String? posterUrl,
    double? width,
  }) {
    var controller; // initialize Chewie controller
    return Chewie(controller: controller);
  }
}

// use the new factory
HtmlWidget(
  html,
  factoryBuilder: () => MyWidgetFactory(),
),
```
