### ISSUE TITLE
BuildOp using tree.replaceWith will "randomly" show raw smilie codes (alt or title attributes)

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#558]
This is happening intermittently and without any specific pattern I can pick up yet.

I have smilies for which I pick up the image by its classname and then using my own widget generate the image, as follows:    (all my smilie images are located in a folder called `images/smilies/`)

```
  void parse(BuildMetadata meta) {

    if (meta.element.classes.contains('bbcode_smiley')) {

      var _smilieName = meta.element.attributes["src"].toString();
          _smilieName = _smilieName.substring(0, _smilieName.indexOf('.'));
          _smilieName = _smilieName.substring(1, _smilieName.length);

      meta.register(BuildOp(
        onTree: (meta, tree) {
          tree.replaceWith(WidgetBit.inline(tree, _smilieOp(name:_smilieName)));
        },
      ));

    }

  }
```

```
class _smilieOp extends StatelessWidget{
 final String name;
  _smilieOp({this.name = ''});

  @override
  Widget build(BuildContext context) {

    var _finalName = 'images/smilies/'+name+'.gif';
    return Image.asset(_finalName);
  }
}
```

This is all working great about 80% of the time.  But sometimes, a smilie code remains on the screen for some reason.  This happens seemingly randomly.  Right now on my screen the following set of smilies is giving me this weird behavior:

#### HTML ####
```
<img src="/smash.gif" width="" height="" alt=":smash:" title=":smash:" class="bbcode_smiley" /> <img src="/splat.gif" width="" height="" alt=":splat:" title=":splat:" class="bbcode_smiley" /> cool
```

#### Expected Result ####
[MY SMASH IMAGE] [MY SPLAT IMAGE] cool

#### Actual Result ####
[MY SMASH IMAGE]:smash: [MY SPLAT IMAGE]:splat: cool

Hard to show in words, but what's happening is the words `:smash:` and `:splat:` are appearing after the images.  Its intermittent and usually this is not happening and the code works great.  But it happens enough that its quite noticeable.  Its as if the `alt` or `title` tags are sneaking in

**Comment by daohoangson** [comment]
Your build op is probably fighting with the built-in IMG op. Try setting a `priority` in your op, a value of 10 should work.

**Comment by mark8044** [comment]
Yes now it makes sense.  I ended up moving all the logic into the `buildImage` area and problem solved
