### ISSUE TITLE
Not able to change anchor tag color to white

### ISSUE THREAD

**Issue by kamleshwebtech** [daohoangson/flutter_widget_from_html#568]
I have set textstyle and also set text color in style but still anchor typed message text is not displaying in white color, please see my below code:

```
String message = '<div>Hello John, see my new photo: <a href="https://images.unsplash.com/photo-1494790108377-be9c29b29330">https://images.unsplash.com/photo-1494790108377-be9c29b29330</a></div>'

HtmlWidget(
          "<span style='line-height: 1.5;text-align:left;color: white;'>$message</span>",
          webView: true,
          textStyle: Theme.of(context)
              .textTheme
              .bodyText2!
              .copyWith(color: Colors.white),
        );
```

and suggest me how can I show anchor (a href) typed data in white color. Thanks a lot.

Look forward to hear you.

**Comment by daohoangson** [comment]
I don't see any anchor in your HTML? Only a `span` tag?

**Comment by kamleshwebtech** [comment]
@daohoangson  Thanks for your quick reply, I have added html data in message variable. Please see and suggest me. Thanks a lot.

**Comment by daohoangson** [comment]
The `A` tag has its own styling so your white color is overridden. You can use `customStylesBuilder` to change the anchor color:

```dart
            HtmlWidget(
              "<span style='line-height: 1.5;text-align:left;color: white;'>$message</span>",
              webView: true,
              textStyle: Theme.of(context)
                  .textTheme
                  .bodyText2
                  .copyWith(color: Colors.white),
              customStylesBuilder: (e) {
                switch (e.localName) {
                  case 'a':
                    return {'color': 'white'};
                }
                return null;
              },
            ),
```

**Comment by kamleshwebtech** [comment]
Thank you so much @daohoangson  I was not aware about `customStylesBuilder` your suggestion worked like charm. Many Thanks Again :)

**Comment by kamleshwebtech** [comment]
@daohoangson  Can we add multiple properties in `customStylesBuilder` map. I have added it like:

```
customStylesBuilder: (e) {
            switch (e.localName) {
              case 'a':
                **return {'color': 'white', 'text-decoration': 'underline', 'text-decoration-color': 'white'};**
            }
            return null;
          },
```
I want to add underline with white color to anchor tag. Could you please suggest me how can I achieve it. Thanks a lot. Look forward to hear you.

**Comment by kamleshwebtech** [comment]
@daohoangson  I have also changed properties name strings to `camelCase` but still not working:

```
customStylesBuilder: (e) {
            switch (e.localName) {
              case 'a':
                return {'color': 'white', 'textDecoration': 'underline', 'textDecorationColor': 'white'};
            }
            return null;
          },
```

Kindly suggest me. Thanks.

**Comment by daohoangson** [comment]
- You can returning multiple properties.
- The `A` tag has underline by default so `text-decoration: underline` is not needed.
- The `text-decoration-color` is not supported though.

**Comment by daohoangson** [comment]
v0.7.0 has been released with color support in decoration. Please try upgrading and see whether it works for you.
