### ISSUE TITLE
Is possible to support "float" css property

### ISSUE THREAD

**Issue by zhiyangyou** [daohoangson/flutter_widget_from_html#572]
## Effect of target
![image](https://user-images.githubusercontent.com/70576712/130189151-75d56e4c-1020-47f1-b4c8-169416d88253.png)

 
 
[demo.txt](https://github.com/daohoangson/flutter_widget_from_html/files/7019535/demo.txt)

**Comment by daohoangson** [comment]
I don't plan to support floating with this package, or flex box etc. Sorry.

**Comment by zhiyangyou** [comment]
oh, thank you.
