### ISSUE TITLE
Rendered widget have width of parent, but user should be able to wrap it by content

### ISSUE THREAD

**Issue by mishatronAstaMobi** [daohoangson/flutter_widget_from_html#573]
Rendered widget have width of parent, but user should be able to wrap it by content. This behavior was in some of previous versions but not we don't have it

**Comment by daohoangson** [comment]
What did you mean saying "wrap by content"? Do you have an example?

**Comment by mishatron** [comment]
![image](https://user-images.githubusercontent.com/16293762/131730537-abbd842a-84eb-4784-ba23-93cee17e297f.png)
for example we have chat items. and i have message data as HTML. why is it expanded to all available width? item should be small as text inside HTML. and in some of previous versions it was working as I describe

**Comment by daohoangson** [comment]
It depends on the HTML. If you have `div` elements for example, it will expand the full width. A simpler HTML with only `span` won't do that (e.g. it will "wrap by content").
