### ISSUE TITLE
Cannot launch using 0.7.x

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#582]
Im able to use `0.6.x` just fine

Just tried to launch using `0.7.x` and I get the following error

```
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html-0.7.0-dev.2021080801/lib/src/html_widget.dart:65:11: Error: No named parameter with the name 'buildAsyncBuilder'.
              buildAsyncBuilder: buildAsyncBuilder,
              ^^^^^^^^^^^^^^^^^
```

**Comment by daohoangson** [comment]
Let me cut a new 0.7 release. The latest ones are mismatched, sorry for that.

**Comment by mark8044** [comment]
> Let me cut a new 0.7 release. The latest ones are mismatched, sorry for that.

Looks like its working now
