### ISSUE TITLE
webview iFrame question

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#585]
In my structure, sometimes I need `iframe` support for YouTube videos, so I have `webview` set to true.  

I have about 20 `HtmlWidgets` sitting inside a listview

Right now I have `web view` set to true generically on all instances of `HtmlWidget`, even if no `iframe` is within the text.

- Is this wrong?  
- Does `flutter_widget_from_html` only use the webview if an `iframe` is present?  
- Should I be pre-filtering my HTML to see if there is an `iframe` in it and then deciding if I should active web view support?

**Comment by daohoangson** [comment]
> Is this wrong?
No.

> Does flutter_widget_from_html only use the webview if an iframe is present?
Yes.

> Should I be pre-filtering my HTML to see if there is an iframe in it and then deciding if I should active web view support?
You don't need to do that.

**Comment by mark8044** [comment]
Outstanding!  thank you
