### ISSUE TITLE
How to get attribute src in tag name video

### ISSUE THREAD

**Issue by tuantiensiu** [daohoangson/flutter_widget_from_html#589]
## Use case

```html
<p><video class="link_iframe" width="320" height="240" controls="controls">
  <source src="http://api.talkschool-cambodia.com/video/1627925251.mp4" type="video/mp4" />
  Your browser does not support the video tag.</video></p>
```
## Proposal

I want to get value attribute src. I hope you can help me solution for it. Thanks you

**Comment by daohoangson** [comment]
What do you need the `src` for? The easiest way is using a custom `WidgetFactory` and override the `parseTag` method. Each dom element will go through that method so you will be able to catch the `src`.

**Comment by tuantiensiu** [comment]
I want to get the `src` then I will put it in my `Widget` and then play this video in my app

**Comment by daohoangson** [comment]
It's probably easier to use the `flutter_widget_from_html` package then override the `buildVideoPlayer` method?

**Comment by tuantiensiu** [comment]
I'm also using this now, but I need to get the value `src` in the tag name `video` and then pass `buildVideoPlayer` method

**Comment by daohoangson** [comment]
The `HtmlWidget` will parse the DOM elements and call that method with the video URL as the second parameters. Just override it and return your widget.

<img width="283" alt="Screen Shot 2021-09-20 at 17 11 47" src="https://user-images.githubusercontent.com/239336/133986306-452d50a9-2a95-481b-9901-3128c22cc4d4.png">

**Comment by tuantiensiu** [comment]
Thanks you for your solution, I will use it in my widget.
