### ISSUE TITLE
customStylesBuilder did not change color

### ISSUE THREAD

**Issue by itsdani121** [daohoangson/flutter_widget_from_html#590]
i want to change specific class color but it did not change the even i remove default style tag but still facing the issue. here is code

          customStylesBuilder: (element) {
                      
                        if (element.classes.contains('font-weight-bold')) {//to check class contain
                     
                          return {'color': '0xffffffff'};// for color pass
                        }
when i check clsas it give me value true but did not change color , also i want to align the text of this class and pass background color so kindly tell me how i do that . thanks advance

**Comment by daohoangson** [comment]
For `customStylesBuilder`, you need to use CSS colors, something like `white` or `#FFFFFF`.

**Comment by itsdani121** [comment]
i want to change th tag color change etc so how can i do it?

**Comment by daohoangson** [comment]
You can do `if (element.localName == 'th')` for example.

**Comment by itsdani121** [comment]
actually i want to change background color of row or column is it possible?

**Comment by daohoangson** [comment]
It should be possible to set `background-color` for a `TR`. But you can't do it for a column, you will need to change the color for each cell in that column.

**Comment by itsdani121** [comment]
thanks  i will try
