### ISSUE TITLE
Html Render Error.

### ISSUE THREAD

**Issue by HeartDawnWY** [daohoangson/flutter_widget_from_html#597]
when use below html occur error.

![bug](https://user-images.githubusercontent.com/16017650/136642980-d34bb9ba-f787-4235-942f-de62a6f7af4d.png)

```html
<section id="nice" data-tool="md edit."
  style="font-size: 16px; color: black; padding: 0 10px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: left; font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
<h2 data-tool="md edit"
    style="margin-top: 30px; margin-bottom: 15px; padding: 0px; font-weight: bold; color: black; font-size: 22px; margin: 10px auto; height: 40px; background-color: rgb(251, 251, 251); border-bottom: 1px solid rgb(246, 246, 246); overflow: hidden; box-sizing: border-box;">
    <span class="prefix" style="display: none;"></span><span class="content"
      style="margin-left: -10px; display: inline-block; width: auto; height: 40px; background-color: rgb(33, 33, 34); border-bottom-right-radius: 100px; color: rgb(255, 255, 255); padding-right: 30px; padding-left: 30px; line-height: 40px; font-size: 16px;">1
      MarkDown Edit.</span><span class="suffix"></span></h2>
</section>
```

if i remove the inline style( padding-right: 30px; padding-left: 30px;  ) from span is can work.
but Incorrect display.

this is my want to diplay.
![20211009123126](https://user-images.githubusercontent.com/16017650/136642809-3518a43f-4c4e-48ec-b013-8c1f855a6239.png)

**Comment by daohoangson** [comment]
With the latest PR #608 (will be merged soon). Your HTML is working as expected:

<img width="912" alt="Screen Shot 2021-10-17 at 14 58 56" src="https://user-images.githubusercontent.com/239336/137617701-eb95b406-87b5-4333-b59f-96a72c1fe8ce.png">

**Comment by HeartDawnWY** [comment]
> With the latest PR #608 (will be merged soon). Your HTML is working as expected:
> 
> 
> 
> <img width="912" alt="Screen Shot 2021-10-17 at 14 58 56" src="https://user-images.githubusercontent.com/239336/137617701-eb95b406-87b5-4333-b59f-96a72c1fe8ce.png">
> 
> 

Thanks!
