### ISSUE TITLE
How can I support multiple br or p elements with no content?

### ISSUE THREAD

**Issue by winsonet** [daohoangson/flutter_widget_from_html#6]
I just want to put multiple lines in the html as below:
~~~
test1
<br>
<br>
<br>
test2
~~~
but after the widget render, it just will keep one ```<br>```, but I suppose there will show 3 blank lines, so how can I do that? I also try 
~~~
test1
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
test2
~~~
and it's same result :(

thx~

**Comment by daohoangson** [comment]
The plugin currently trims standalone whitespaces to avoid too much spacing being rendered.

What is your use case for multiple line breaks? You can change the margin if you want to increase spacing between text paragraphs.

**Comment by winsonet** [comment]
oh, in my case, I let user to input the html content in the CMS backend, and show in the app, so I can't control that, but I also want to know how can I set the margin in the html content by div or other elements?

**Comment by daohoangson** [comment]
Ah, I can add support for `margin` inline styling quite easily. With that feature, you can write something like `<div style="margin-top: 20px">...</div>` to render extra top spacing.

Is that good enough for your use case?

**Comment by winsonet** [comment]
I thank that's will be better, so that I can replace the BR to margin, thx😀

**Comment by daohoangson** [comment]
v0.1.1 now has margin support, please let me know if it works for you.

**Comment by winsonet** [comment]
thanks, it's working now!!
