### ISSUE TITLE
With removal of `replaceWith`, what is the proper way to replace something?

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#620]
With your help in the past, I came up with a way to make links into a custom widget as follows:

```

    if (meta.element.localName == 'a') {

           meta.register(BuildOp(
             onTree: (meta, tree) {
               tree.replaceWith(WidgetBit.inline(tree, _linkWidget(text:meta.element.text, url:meta.element.attributes['href'].toString())));
            },
           ));

     }

```

This would then pass that text into my `_linkWidget` and returned a nicely stylized widget of my choice.  But now with it gone, what would be the proper way of dealing with this?

Thanks!

**Comment by DFelten** [comment]
> The `replaceWith` method is dangerous to use so it has been removed. Something like this should work for you:
> 
> ```dart
> WidgetBit.inline(tree.parent, child).insertBefore(tree);
> tree.detach();
> ```

@daohoangson 
I'm not sure if I'm doing something wrong, but detaching doesn't work for me. Inserting works without problems, but then the content is duplicated.

Code snippet:

```dart
mixin TMXWebViewFactory on WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    if (meta.element.classes.contains('flutter-wv')) {
      meta.register(BuildOp(
        onTree: (_, tree) {
          final widget = WebViewFromHtml(
            htmlString: meta.element.innerHtml,
            attributes: meta.element.attributes,
          );
          // tree.replaceWith(WidgetBit.block(tree, widget));
          if (tree.parent != null) {
            WidgetBit.block(tree.parent!, widget).insertBefore(tree);
          }
          tree.detach();
        },
      ));
    }
    return super.parse(meta);
  }
}
```

**Comment by daohoangson** [comment]
I think you can use `BuildOp.onWidgets` for this. 

Way easier than dealing with the build tree, it's getting too complicated to handle all the weird cases, I'm working on simplifying.

**Comment by DFelten** [comment]
Wouldn't that mean that the content of the WebView is built unnecessarily and then discarded? OnTree would be more performant as far as I understand, right?

**Comment by daohoangson** [comment]
That's true. Can you share your HTML? Maybe one of the default ops alters the tree before yours.

**Comment by DFelten** [comment]
This is the example html:

```html
<div>
  <div class="flutter-wv" data-flutter-wv-type='popup' data-flutter-wv-options='{"title": "Buttontext", "shortcode": "shortxyz"}'>
    <p>Old content which should not be visible</p>
  </div>
</div>
```

This is the factory:

```dart
mixin TMXWebViewFactory on WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    if (meta.element.classes.contains('flutter-wv')) {
      meta.register(BuildOp(
        onTree: (_, tree) {
          final widget = WebViewFromHtml(
            htmlString: meta.element.innerHtml,
            attributes: meta.element.attributes,
          );
          // tree.replaceWith(WidgetBit.block(tree, widget));
          if (tree.parent != null) {
            WidgetBit.block(tree.parent!, Text('Replacement')).insertBefore(tree);
          }
          tree.detach();
        },
      ));
    }
    return super.parse(meta);
  }
}
```

`tree.replaceWith` worked here before.

The result:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/1169185/144475947-5a2e2753-8d44-450d-bb46-c15b56756caa.png">

Thanks so much for checking it out!

**Comment by DFelten** [comment]
@daohoangson Unfortunately, replacing the Replace with insertBefore does not work for my Factories with the latest version (0.8.3). 

The error is the following:

`'package:flutter_widget_from_html_core/src/data/build_bits.dart': Failed assertion: line 123 pos 12: 'parent == another.parent': is not true.`

Widget Factory

```dart
class CustomWidgetFactory extends WidgetFactory with FaFactory {}

mixin FaFactory on WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    if (meta.element.classes.contains('fas')) {
      meta.register(BuildOp(
        onTree: (_, tree) {
          const Widget widget = Text('Test Widget');
          WidgetBit.inline(tree, widget).insertBefore(tree);
          tree.detach();
        },
      ));
    }
    return super.parse(meta);
  }
}
```

Html Widget
```dart
HtmlWidget(
  htmlCode,
  renderMode: RenderMode.sliverList,
  factoryBuilder: () => CustomWidgetFactory(),
);
```

Html:
```html
<h3 style="color: white"><b>Alle Infos auf einen Blick</b></h3>
<p><i class="fas fa-check"></i> ab 5,99€<br />
</p></div>
```

Alternatively, how would I replace things on the Tree? The example is of course only a simple one for illustration.

**Comment by daohoangson** [comment]
This line:

```dart
WidgetBit.inline(tree, widget).insertBefore(tree);
```

Should be:

```dart
WidgetBit.inline(tree.parent!, widget).insertBefore(tree);
```

**Comment by daohoangson** [comment]
Btw, I'm bringing back `replaceWith` in v0.9 🙈

**Comment by DFelten** [comment]
> This line:
> 
> ```dart
> WidgetBit.inline(tree, widget).insertBefore(tree);
> ```
> 
> Should be:
> 
> ```dart
> WidgetBit.inline(tree.parent!, widget).insertBefore(tree);
> ```

Oh, I should read more carefully. Thanks for the quick help!

> Btw, I'm bringing back `replaceWith` in v0.9 🙈

That would be great :)

**Comment by daohoangson** [comment]
Sorry for the breaking changes, I'm trying to make it easier to use and stable enough for a v1.0.
