### ISSUE TITLE
Pass the child that would be rendered by default to customWidgetBuilder

### ISSUE THREAD

**Issue by NamanShergill** [daohoangson/flutter_widget_from_html#635]
## Use case
If you just want to say, add a gray background to how the library renders \<pre> tags, you should be able to just wrap it in a container with the color.

## Proposal

```dart
customWidgetBuilder: (element, child) {
    if (element.attributes['foo'] == 'bar') {
      return Container(
                color: Colors.grey,
                child: child,
         );
    }

    return null;
  },
```

Similar to how flutter_html does it with their custom render API.

**Comment by daohoangson** [comment]
The `customWidgetBuilder` runs early in the rendering process so there is no `child` widget (it hasn't been built by then). With the current version, you will need a `BuildOp` with a custom `WidgetFactory` to "wrap" things.

**Comment by NamanShergill** [comment]
I see

> With the current version, you will need a BuildOp with a custom WidgetFactory to "wrap" things.

Are there any examples of this for reference?

**Comment by daohoangson** [comment]
Something like this should work https://try.fwfh.dev/?id=c4c506a6191e5de8f0e14b8cc6cf6e9b

```dart
     BuildOp(
        onWidgets: (meta, children) {
          return listOrNull( 
            buildColumnPlaceholder(meta, children)?.wrapWith( 
              (context, child) => Container(
                color: Colors.grey,
                child: child,
              ),
            ),
          );
        },
      )
```

**Comment by NamanShergill** [comment]
> Something like this should work https://try.fwfh.dev/?id=c4c506a6191e5de8f0e14b8cc6cf6e9b
> 
> ```dart
>      BuildOp(
>         onWidgets: (meta, children) {
>           return listOrNull( 
>             buildColumnPlaceholder(meta, children)?.wrapWith( 
>               (context, child) => Container(
>                 color: Colors.grey,
>                 child: child,
>               ),
>             ),
>           );
>         },
>       )
> ```

Thank you! This should do!
