### ISSUE TITLE
underline, theme accent color

### ISSUE THREAD

**Issue by Liliana99** [daohoangson/flutter_widget_from_html#637]
## Steps to Reproduce

<details>
          <summary>  Because the accent color has been deprecated from theme in Dart. The flutter_widget are not  update    with the migration.
                theme: theme.copyWith(
                    colorScheme: theme.colorScheme.copyWith(secondary: myColor),
                  ).

   My migration
               theme: ThemeData(
                    brightness: Brightness.light,
                    primarySwatch: kCompanyGreenMaterialColor,
                    colorScheme: theme.colorScheme.copyWith(
                      primary: kCompanyGreenMaterialColor,
                      secondary: kCompanyBrownColor,
                      brightness: Brightness.light,
                    ),</summary>

```html
```
</details>
The color on underline link doesn't change, although I've done the migration because the  html widget needs 
'accentColor' from theme.
<details>
  <summary>`HtmlWidget` configuration</summary>

          HtmlWidget(
                      'Company XYZ, <a href=\"https://www.mydomain.com/\" target=\"_blank\" '
                      'title=\"CompanyXYZ"\"></a> '
                    );
</details>

<details>
  <summary>Tesing environment</summary>

[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale es)
    • Flutter version 2.5.3 at /Users/administradorlili/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/administradorlili/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • ZTE B2017G (mobile) • 8947deaa • android-arm64  • Android 6.0.1 (API 23)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
exit code 0
</details>

## Expected results
  The underline links should change color from colorSheme.

## Actual results
 The underline links doesn't change color .

**Comment by daohoangson** [comment]
Which version of this package are you using? The latest one has already migrated away from `accentColor`.

**Comment by Liliana99** [comment]
Ups!! ok, mi current version is 0.7.0

**Comment by daohoangson** [comment]
The latest is `v0.8.2`, can you upgrade?

**Comment by Liliana99** [comment]
Yes, I've done. Although the colorSheme doesn't apply on my widget. 
This is my configuration on myApp

theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: kCompanyGreenMaterialColor,
        colorScheme: theme.colorScheme.copyWith(
          primary: kCompanyGreenMaterialColor,
          secondary: kCompanyBrownColor,
          brightness: Brightness.light,
        ),
        backgroundColor: Colors.white,
        shadowColor: Colors.grey,
        textTheme: Theme.of(context).textTheme.apply(
              bodyColor: kCompanyGreenColor,
              displayColor: kCompanyBrownColor,
              fontFamily: 'Jost',
            ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),



And this is my widget


child: HtmlWidget(
          textHtml,
          textStyle: TextStyle(
            color: Theme.of(context).primaryColor,
            fontSize: 14,
          ),
        ),

**Comment by daohoangson** [comment]
Upon further inspection, the A tag uses the primary color so this is working as expected.

https://github.com/daohoangson/flutter_widget_from_html/blob/949cf49e490d5450ea434d53a3be2ed4d9f0179a/packages/core/lib/src/core_widget_factory.dart#L643-L647

**Comment by Liliana99** [comment]
I've installed   flutter_widget_from_html_core: ^0.8.2 , without change the configuration on myApp, the same 
themeData as I'd put here before, the result is the same.
The underline colours link doesn't change to colorScheme.secondary

What I should do to make the undenderline color text change?

Thanks you.

**Comment by daohoangson** [comment]
It will pick up the primary color, not the secondary. You can see it here:

https://try.fwfh.dev/?id=0e019986eb7491a2183d7c95cfe1bc9f

<img width="1829" alt="Screen Shot 2021-11-26 at 06 26 41" src="https://user-images.githubusercontent.com/239336/143507433-98bd064c-ca26-4d0b-afde-69d19d6106be.png">


If you don't like the default color, you can specify another one like this:

```dart
      customStylesBuilder: (element) {
        if (element.localName == 'a') {
          return {'color': '#0000FF'};
        }

        return null;
      }
```

https://try.fwfh.dev/?id=950d4e7a3a608867fa60c36d2e455716

<img width="1829" alt="Screen Shot 2021-11-26 at 06 30 43" src="https://user-images.githubusercontent.com/239336/143507613-0dbecc19-bf7e-4a1d-88da-12b7c7be9c9b.png">

**Comment by Liliana99** [comment]
Yes, I can see, I will apply that solution for the underline links.

Thank you!!
