### ISSUE TITLE
Iframe tag video in html is not displayed

### ISSUE THREAD

**Issue by lushangdefeng55** [daohoangson/flutter_widget_from_html#644]
Videos containing iframe tags in HTML are not displayed, and other contents are displayed normally.

**Comment by lushangdefeng55** [comment]
It runs on Android and IOS mobile devices and is not displayed

**Comment by lushangdefeng55** [comment]
The specific content was sent to you by email

**Comment by lushangdefeng55** [comment]
Hello, have you received the email I sent?

**Comment by daohoangson** [comment]
Yes, I have received your email with the YouTube iframe.

**Comment by lushangdefeng55** [comment]
When you are free, help solve this bug. We are in a hurry to wait for a solution. Thank you!

**Comment by lushangdefeng55** [comment]
> Videos containing iframe tags in HTML are not displayed, and other contents are displayed normally.

**Comment by daohoangson** [comment]
Have you solved this issue?
