### ISSUE TITLE
Need callback for OnSelection

### ISSUE THREAD

**Issue by bksubhuti** [daohoangson/flutter_widget_from_html#656]

**Comment by daohoangson** [comment]
v0.8.3+1 has been released with support for this. Please try upgrading and let me know if it works.

**Comment by bksubhuti** [comment]
it seems that the beta was taken down and also the isSelectable feature.  I have installed  
flutter_widget_from_html_core: ^0.8.3+1
and it is not finding this feature.  Because of this I cannot give the "jumping selection" video

**Comment by daohoangson** [comment]
To avoid requiring Flutter 2.8 in the core package, this feature has been removed from `flutter_widget_from_html_core`. You will need to use `flutter_widget_from_html` for this.

Alternatively, you can keep using core with the pre-built mixin from https://pub.dev/packages/fwfh_selectable_text.
