### ISSUE TITLE
selection jumps position 

### ISSUE THREAD

**Issue by bksubhuti** [daohoangson/flutter_widget_from_html#658]
## Steps to Reproduce

Code is checked in with this project.
https://github.com/bksubhuti/Tipitaka-Pali-Projector
(need to get the db from my drive listed on git page and then run script in database folder.)
Open a book
click on a word
long press a word.

If there is a lot of text, the selection will jump out of view.
<details>
  <summary>HTML</summary>

expected to see the selected text in the same place without a forced scroll operation (which shows as a "jump" 

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

## Expected results

wanted to see selection in the same place.. no jumping

## Actual results
it jumps.. but not always.  depends on position of word selected.

**Comment by daohoangson** [comment]
Can you record the screen when it jumps?

**Comment by bksubhuti** [comment]
it seems that the beta was taken down and also the isSelectable feature. I have installed
flutter_widget_from_html_core: ^0.8.3+1
and it is not finding this feature. Because of this I cannot give the "jumping selection" video

**Comment by daohoangson** [comment]
To avoid requiring Flutter 2.8 in the core package, this feature has been removed from `flutter_widget_from_html_core`. You will need to use `flutter_widget_from_html` for this.

Alternatively, you can keep using core with the pre-built mixin from https://pub.dev/packages/fwfh_selectable_text.

**Comment by bksubhuti** [comment]
does not build with the new pkg 
My other dev also confirmed .. can build on ios but not android.
i'm only on android.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/bhante/.gradle/caches/transforms-2/files-2.1/14010dacc44ddd79bf30b8a631f3f7d7/media2-session-1.1.3/AndroidManifest.xml:24:5-34:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s

**Comment by daohoangson** [comment]
This package cannot affect Android linking, probably something else is causing that. Maybe do a `flutter clean` and try again?

**Comment by bksubhuti** [comment]
it still does not work.. with 
`flutter clean 
`and 
`flutter build apk`
Is this tested on android?
ios works on the other computer.

**Comment by daohoangson** [comment]
Yes, we do have GitHub workflows that compile an iOS / Android app for each commit.

**Comment by bksubhuti** [comment]
I don't know what to do.  If I remove the pkg it works fine.  If I add it, it does not build with the above mentioned errors.  I'm building on linux.  The other developer cannot build on mac.  Perhaps it works on Windows only?
Do I need both packages included.  I'm using only the new one.
I also both old and new packages included in yaml but only one actual import definition file.

Gradle has recently been updated earlier this week.  Do I need to update again?
I'm in myanmar so not all Android Studio/gradle updates are easy.
 
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on Ubuntu 21.10 5.13.0-22-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by daohoangson** [comment]
Why don't you email me at daohoangson at gmail dot com. Maybe we can arrange a TeamViewer or something similar?

**Comment by daohoangson** [comment]
The bug has been resolved so I'm closing this issue.
