### ISSUE TITLE
<a> tag must not be decorated and clickable when href is missing.

### ISSUE THREAD

**Issue by EA-YOUHOU** [daohoangson/flutter_widget_from_html#676]
Standard behavior of the `<a>` tag, it must not be clickable when href is missing.

```html
<a>test</a> no underline and no clickable effect
<a href>test</a> underline and clickable effect
<a href="">test</a> underline and clickable effect
<a href="test">test</a> underline and clickable effect
```

**Comment by EA-YOUHOU** [comment]
https://github.com/daohoangson/flutter_widget_from_html/pull/678

**Comment by daohoangson** [comment]
Your PR has been merged  🎉 Thank you for the contribution. It will be included in the next release.

**Comment by daohoangson** [comment]
`v0.8.4` has been released with your PR fyi.
