### ISSUE TITLE
Support border arguments orders

### ISSUE THREAD

**Issue by EA-YOUHOU** [daohoangson/flutter_widget_from_html#684]
## Steps to Reproduce

When element have a border style, the current css parser didn't handle the case where style if before the width.
I suggest to support this case.

<details>
  <summary>HTML</summary>

```html
<html>
      <body>
      <table>
        <tr>
            <td style='border:1.0pt solid'>test 1</td>
            <td style='border:1.0pt solid'>test 1</td>
        </tr>
        <tr>
            <td style='border:solid 1.0pt'>test3</td>
            <td style='border:solid 1.0pt'>test3</td>
        </tr>
      </table>    
      </body>
      </html>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
      HtmlWidget(
        html,
      );
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

## Expected results

![Capture d’écran 2021-12-14 à 11 04 18](https://user-images.githubusercontent.com/92172436/145977023-cac4e89f-1bda-4345-96dc-32918e18b415.png)

## Actual results

![Capture d’écran 2021-12-14 à 11 05 52](https://user-images.githubusercontent.com/92172436/145977249-3c73d8c1-9781-41d6-9f65-ccad5efcca97.png)

**Comment by EA-YOUHOU** [comment]
https://github.com/daohoangson/flutter_widget_from_html/pull/685

**Comment by daohoangson** [comment]
`v0.8.4` has been released with your PR. Thank your for contributing!
