### ISSUE TITLE
Text Size large with isSelectable = true

### ISSUE THREAD

**Issue by bksubhuti** [daohoangson/flutter_widget_from_html#687]
text size very large with isSelectable enabled

If the feature is enabled, the text size is large.
If the feature is not enabled the text size is not (extra large) large
`<p class="definition">[Dhātu+ṇvu+ī] CL=0 Ati Thayan Chit Tin Croatian Dhataki; န ဒါ ဒီ၊ Dhan, T. 589.] Pattaki Pin.</p><!-- 
`
https://github.com/bksubhuti/tipitaka-pali-reader
webview 3.0 has been removed from project before posting this bug report.  It is pushed to the git
https://github.com/bksubhuti/tipitaka-pali-reader

## Expected results

standard text size is what i wanted to see.

## Actual results

picture below:
![Screenshot_20211215-133142](https://user-images.githubusercontent.com/18184280/146139927-c9e49bfe-ce38-4503-8460-1f74564194b1.jpg)

**Comment by bksubhuti** [comment]
it seems that the emulator does not produce this bug.  It is specific to my phone it seems..  I will try release mode.  Perhaps that is the problem.

**Comment by bksubhuti** [comment]
update it is only my phone.. emulator works fine in release too.

**Comment by bksubhuti** [comment]
I see now.. my phone has the system font size a little bigger (+10-15%).  So when the isSelectable = true then the font size goes based relative to the system.  system was not  that big but something is affecting it.
When isSelectable is not turned on, this is not affected.

This is why it did not get reproduced on Linux or the Emulator.

I still think this is a bug.. but our div does not have a size given.

I/flutter (29310): <h3>Concise Pali-English Dictionary</h3>
I/flutter (29310): <br>
I/flutter (29310): <p class="definition">phassa/m./touch; contact.</p>

**Comment by bksubhuti** [comment]
our problem is solved by doing a textStyle , but maybe a bug since it behaves differently for isSelectable.

**Comment by daohoangson** [comment]
Yes, this is still a bug. How did you workaround with a `TextStyle`?

**Comment by bksubhuti** [comment]
```
                child: HtmlWidget(
                  content,
                  textStyle: TextStyle(fontSize: Prefs.fontSize.toDouble()),
                  factoryBuilder: () => _MyFactory(),
                  //isSelectable: true,
                  //onSelectionChanged: (selection, cause) {
                  //  print(selection);
                  //},
                ))),
```

**Comment by daohoangson** [comment]
This is a bug, I'm working on it at #689.

**Comment by daohoangson** [comment]
`fwfh_selectable_text@0.8.3+1` has been released with the fix for this. Please try upgrading, it should work on your real device (the one with the scaled up font size) without any workaround.

**Comment by bksubhuti** [comment]
sorry for being slow to verify
