### ISSUE TITLE
Border radius not working with span

### ISSUE THREAD

**Issue by DFelten** [daohoangson/flutter_widget_from_html#688]
Border radius not working with span. I'm using flutter_widget_from_html 0.8.3+1.

## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
test <span class="badge">Update</span> test
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget(
  'test <span class="badge">Update</span> test',
  renderMode: RenderMode.sliverList,
  // factoryBuilder: () => CustomWidgetFactory(),
  customStylesBuilder: (dom.Element element) {
    if (element.classes.contains('badge')) {
      return {
        'background-color': 'orange',
        'border-radius': '12px',
        'padding': '5px',
      };
    }
    return {};
  },
),
```
</details>

<details>
  <summary>Tesing environment</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale
    de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.64.0-insider)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

(Not sure why there is an error with IntelliJ)
```
</details>

## Expected results

Round borders for the content of the span tag.

This is the correct html behavior in the browser.

<img width="118" alt="image" src="https://user-images.githubusercontent.com/1169185/146237582-5695a490-2c07-43a8-ab22-5dbdbe29588b.png">

## Actual results

No round borders.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/1169185/146237506-50624f11-9b13-4c13-a2fe-00c77ff9691c.png">

**Comment by daohoangson** [comment]
Looks like the border was render fine but the background was duplicated so it doesn't have the right visual.

**Comment by daohoangson** [comment]
The fix has been merged, it should render correctly now:

![](https://github.com/daohoangson/flutter_widget_from_html/raw/810c11d3896f58822abb95fb864593a604469071/demo_app/test/goldens/inline/border-radius/inline.png)

A new version will be released soon.

**Comment by daohoangson** [comment]
`v0.8.4` has been released with the fix for this. Please try upgrading and let me know if it works for you.

**Comment by DFelten** [comment]
Thanks, it's working :)

**Comment by Xelorium** [comment]
The same problem still continues on v0.15.1.

**Comment by daohoangson** [comment]
Please open a new issue since this one is pretty old + already closed.
