### ISSUE TITLE
Youtube Link not rendering 

### ISSUE THREAD

**Issue by kunaldas1997** [daohoangson/flutter_widget_from_html#69]
Only once I saw the Youtube Video render on the page, later it shows only the link to the YT video, but clicking on the video it opens the YT app on the device.
![Screenshot_20190908-235222](https://user-images.githubusercontent.com/26971428/64492668-fc834e80-d293-11e9-9d2e-3b86cc8c4b6b.jpg)

**Comment by daohoangson** [comment]
What is the HTML for this screenshot? For YouTube player to be rendered, it must be something like `<iframe src="xxx"></iframe>`.

**Comment by kunaldas1997** [comment]
It generally comes from the content that is being rendered from the Wordpress REST API, I guess it does have iFrame because it gets embedded when we paste the link to the Wordpress, it returns content in iFrame only. 

![image](https://user-images.githubusercontent.com/26971428/64626351-58bcae80-d40b-11e9-80c9-acf5f7f5ece4.png)

**Comment by kunaldas1997** [comment]
have to try it again. I guess I turned on webView: True already

**Comment by daohoangson** [comment]
Have you had the time to verify the `webView` param? @kunaldas1997

**Comment by kunaldas1997** [comment]
I guess i messed up with the webview thing. I am right now testing the YT thing again. Sorry for that. Also, why there is no option to go full screen?

**Comment by daohoangson** [comment]
> Also, why there is no option to go full screen?

It's a limitation of running video player within a WebView. It's not easy to support fullscreen even in native code. You can follow this Flutter issue https://github.com/flutter/flutter/issues/27101

**Comment by kunaldas1997** [comment]
ah...so flutter team's fault. anyways, thanks. I am closing this post. Have a great day!
