### ISSUE TITLE
Hyperlink color - question

### ISSUE THREAD

**Issue by ChrisZi** [daohoangson/flutter_widget_from_html#690]
After, BREAKING: Remove HtmlWidget.hyperlinkColor (#571),  how can i change the hyperlink color?

**Comment by daohoangson** [comment]
You can use `customStylesBuilder` like this:

```dart
  customStylesBuilder: (element) {
    if (element.localName == 'a') {
      return {'color': 'red'};
    }

    return null;
  },
```

The hyperlink color defaults to the primary color of the theme so you can also change the app theme.

**Comment by ChrisZi** [comment]
It works, thank you for the quick answer. Greetings.
