### ISSUE TITLE
How I can use textAlign: TextAlign.justify?

### ISSUE THREAD

**Issue by MAFR1983** [daohoangson/flutter_widget_from_html#692]
How I can use textAlign: TextAlign.justify

**Comment by daohoangson** [comment]
If you need to align some specific class, `customStylesBuilder` should work. Something like this:

```dart
  customStylesBuilder: (element) {
    if (element.classes.contains('justity-me')) {
      return {'text-align': 'justify'};
    }

    return null;
  },
```

[Try on fwfh.dev](https://try.fwfh.dev/?id=b22d931134dfb4f249529bdf78653f87) or see screenshot below:


<img width="1234" alt="Screen Shot 2021-12-16 at 21 35 50" src="https://user-images.githubusercontent.com/239336/146391455-e0415673-56cf-4aed-a809-c8a292e1af3e.png">
