### ISSUE TITLE
Display Image Inline

### ISSUE THREAD

**Issue by ibrokemypie** [daohoangson/flutter_widget_from_html#7]
Hey, do you think it would be possible to add displaying of images inline (taking a size parameter in the tag)
Someone has done this for richtext at https://github.com/bytedance/RealRichText
I had a look at using the flutter_widget_from_html_core package and extending the widget builder but i am afraid i dont really understand how

**Comment by daohoangson** [comment]
Regarding inline image, I'm still waiting for the official support from Flutter https://github.com/flutter/flutter/issues/2022. It was an old issue but it has been updated recently (6 days ago) without an ETA.

**Comment by ibrokemypie** [comment]
They added an eta of september this year. Would it be possible to integrate with that realrichtext  widget? Would just need to generate widgets and append them to a list, textspans for text (with relevant formatting) and imagespans for images

**Comment by numez** [comment]
I published package [drop_cap_text ](https://pub.dartlang.org/packages/drop_cap_text) to achive DropCapText, you can also put an **image** as custom widget inside DropCap.

![image](https://user-images.githubusercontent.com/6752432/53761455-d2f10100-3ec5-11e9-83ed-d12565623cc3.png)

**Comment by skipness** [comment]
[Support](https://github.com/flutter/engine/pull/8207#issue-262272706) for inline widget is coming!

**Comment by daohoangson** [comment]
@skipness yes!!!1

**Comment by daohoangson** [comment]
The PR is merged now (see https://github.com/flutter/flutter/issues/2022#issuecomment-501869775), hopefully I can release this for 0.2.2.

**Comment by daohoangson** [comment]
Good news, I have got `WidgetSpan` working with images (see #53) 🎉 

<img width="384" alt="Screen Shot 2019-06-17 at 12 41 41 AM" src="https://user-images.githubusercontent.com/239336/59567490-c2d9e780-9098-11e9-942a-716f444e32f7.png">

**Comment by daohoangson** [comment]
v0.2.2 has been released with proper support for inline images 🎉

**Comment by Shahmirzali-Huseynov** [comment]
@daohoangson  0.8.5 is support inline image?  because I don't find anything about it.

**Comment by daohoangson** [comment]
Yes, inline image is supported. `IMG` tag should render without issue.
