### ISSUE TITLE
How to fix this warning

### ISSUE THREAD

**Issue by mdddj** [daohoangson/flutter_widget_from_html#702]
![image](https://user-images.githubusercontent.com/29020213/148630164-77f9d74b-2f50-4672-bdbd-d26bff7c6d6e.png)

'webView' is deprecated and shouldn't be used. Override WidgetFactory.webView instead.

**Comment by daohoangson** [comment]
If you are using `webView: true` you can safely ignore that warning, next version will remove that param and turn on web view by default.
