### ISSUE TITLE
fwfh_text_style 2.7.2 causing build to fail when updated to flutter 2.8

### ISSUE THREAD

**Issue by Tinomuchenje** [daohoangson/flutter_widget_from_html#704]
## Steps to Reproduce

1.  Update to the latest flutter 2.8
2.  Start Debbuging

### 

## Actual results

![bug](https://user-images.githubusercontent.com/31763088/149151634-31b54d57-22d9-486c-b271-3d7cf42ed900.jpeg)

**Comment by daohoangson** [comment]
The error indicates that it was still using an old version. Try running `flutter pub upgrade fwfh_text_style` maybe?
