### ISSUE TITLE
Hello author, I would like to ask why it is rendered like this, is there a solution?

### ISSUE THREAD

**Issue by 2530442368** [daohoangson/flutter_widget_from_html#705]
<span style="background-color: #e03e2d; color: #ecf0f1;">《关于委托开展&ldquo;十四五&rdquo;规划输电通道配套水风光及调节电源研究论证的函》</span>
![1642522430(1)](https://user-images.githubusercontent.com/63909463/149975412-a8aa1408-742e-4a6a-95c8-c86d9a0c8cbe.png)

expected：
![image](https://user-images.githubusercontent.com/63909463/149975439-8cedec2e-4f49-4b9b-8b5a-c1140a5d5758.png)

**Comment by 2530442368** [comment]
` <span style="background-color: #e03e2d; color: #ecf0f1;">《关于委托开展&ldquo;十四五&rdquo;规划输电通道配套水风光及调节电源研究论证的函》</span>， `

**Comment by daohoangson** [comment]
According to https://github.com/daohoangson/flutter_widget_from_html/issues/412#issuecomment-799307524, this is a Flutter bug flutter/flutter#24337.
