### ISSUE TITLE
How can we limit a text to limited lines?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [daohoangson/flutter_widget_from_html#706]
I am using HtmlWidget for showing html data but I want to limit my text to 2 or 3 lines but I never find the property of maxlines as we can do in simple Text Widget.
If available please tell me...

**Comment by daohoangson** [comment]
The html contents may contain all sort of things so the `HtmlWidget` doesn't have max lines property. You will need to wrap your text in something like this:

```html
<div style="max-lines: 3; text-overflow: ellipsis">text goes here</div>
```


It will look like this (you can try it [here](https://try.fwfh.dev/?id=d6ac685a0221d5ebb2a1f5b784ce9426)):

<img width="1364" alt="Screen Shot 2022-01-27 at 09 20 30" src="https://user-images.githubusercontent.com/239336/151280286-665f396f-3657-47fc-b854-5197c7671c3e.png">

**Comment by UmairSaqibBhutta** [comment]
@daohoangson this solution works for me but there must be a property for this.
But thanks a lot .

**Comment by red-star25** [comment]
@daohoangson I tried your solution but it is not working for me

![Screenshot 2024-03-22 at 5 25 38 PM](https://github.com/daohoangson/flutter_widget_from_html/assets/54853762/e8b35e07-d936-4bf6-8618-e3daa7ac9c12)

**Comment by Dabbit-Chan** [comment]
> [@daohoangson](https://github.com/daohoangson) I tried your solution but it is not working for me
> 
> ![Screenshot 2024-03-22 at 5 25 38 PM](https://github.com/daohoangson/flutter_widget_from_html/assets/54853762/e8b35e07-d936-4bf6-8618-e3daa7ac9c12)
> 
> This is the content: `<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up </p>`

You can try to edit the html like this: `'<div style="max-lines: 3;">${text.replaceAll('<p>', '').replaceAll('</p>', '<br>')}</div>'`
