### ISSUE TITLE
embeded facebook videos leads to an infinite loop

### ISSUE THREAD

**Issue by ahmadkhedr** [daohoangson/flutter_widget_from_html#71]
whenever there is an included facebook video it directs the app to the default browser of the phone and leads to an infinite loop of opened windows with the same link of the video

**Comment by daohoangson** [comment]
What is the full HTML that triggers this bug? 

Also, are you testing on Android / iOS, device or simulator?

**Comment by ahmadkhedr** [comment]
the html : <p>أبرز الاخبار المحلية والعالمية التي تنــــاولها موقع الوكيل الإخباري وموقع هلا أخبارلهذا اليـــــــوم الخميس الموافق 5/9/2019:</p><p>&nbsp;</p><p><iframe src=\"https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FMohammadAlwakeelshow%2Fvideos%2F455133578548821%2F&amp;show_text=0&amp;width=560\" width=\"560\" height=\"315\" style=\"border:none;overflow:hidden\" scrolling=\"no\" frameborder=\"0\" allowtransparency=\"true\" allowfullscreen=\"true\"></iframe></p>"
The code That Iam using it inside : 
HtmlWidget(
                     html,
                      webView: true,
                      webViewJs: true,
                      unsupportedWebViewWorkaroundForIssue37: true,
                    //  factoryBuilder: (c, hw) => _BlockquoteWebViewWf(c, hw),
                    ),

Thanks in advance

**Comment by ahmadkhedr** [comment]
And I have tested it on Andriod emulator and read device...didnot test it on ios yet

**Comment by ahmadkhedr** [comment]
Any updates regarding this issue?

**Comment by ahmadkhedr** [comment]
Thanks a lot...It works perfectly now
