### ISSUE TITLE
Adding number of lines

### ISSUE THREAD

**Issue by etekumoses** [daohoangson/flutter_widget_from_html#710]
i have data coming from api and its in html format i want to limit to only 3 lines but i dont see any way of limiting cause the data is like 2000k lines long . Has anyone tried fixing this.
Thanks

**Comment by daohoangson** [comment]
The html contents may contain all sort of things so the `HtmlWidget` doesn't have max lines property. You will need to wrap your text in something like this:

```html
<div style="max-lines: 3; text-overflow: ellipsis">text goes here</div>
```


It will look like this (you can try it [here](https://try.fwfh.dev/?id=d6ac685a0221d5ebb2a1f5b784ce9426)):

<img width="1364" alt="Screen Shot 2022-01-27 at 09 20 30" src="https://user-images.githubusercontent.com/239336/151280286-665f396f-3657-47fc-b854-5197c7671c3e.png">

(from https://github.com/daohoangson/flutter_widget_from_html/issues/706#issuecomment-1022784038)
