### ISSUE TITLE
Cannot show svg images

### ISSUE THREAD

**Issue by ChivialK** [daohoangson/flutter_widget_from_html#711]
Using code from example:
```dart
Widget _buildHtml(String html) => SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: HtmlWidget(
            '$html<hr /><pre>${const HtmlEscape().convert(html)}</pre>',
          ),
        ));

String _htmlAsset() {
    const android = 'asset:assets/images/android.jpeg';
    const ios = 'asset:assets/images/ios.jpeg';
    const svg = 'asset:assets/images/svg-path.svg';

    return '''
<p>
  Android:
  <img src="$android" />
  <img src="$android" width="48" height="48" />
  <img src="$android" width="12" height="12" />
</p>
<p>
  iOS:
  <img src="$ios" />
  <img src="$ios" width="48" height="48" />
  <img src="$ios" width="12" height="12" />
</p>
<p>
  svg:
  <img src="$svg" />
  <img src="$svg" width="48" height="48" />
  <img src="$svg" width="12" height="12" />
</p>
''';
  }
```
```dart
@override
Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: <Widget>[
          _buildHtml(_htmlAsset()),
        ],
    ));
```

Result:
![resize_Screenshot_20220128_111127-crop](https://user-images.githubusercontent.com/8535276/151481464-e567c659-b0f0-46cd-a6ac-a8ff226c946d.png)

I'm sure that .svg file is in the assets folder, but it didn't render.
Also tried the network and data uri in the example class to load svg, both failed.

---
flutter_widget_from_html_core: ^0.8.4

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)

**Comment by daohoangson** [comment]
You are using the core package, it doesn't include svg support. Please switch to `flutter_widget_from_html` (without the _core suffix) and try again.
