### ISSUE TITLE
YouTube full screen does not work on Android

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#716]
On Android, the fullscreen button for videos on the bottom right does not have any effect for making videos goto full screen.  The other controls, such as play, pause, etc.. do work properly.

On iOS the video successfully goes full screen, so the problem seems confined to android

Thank you!

**Comment by daohoangson** [comment]
This is a duplicated of #35.

> I'm aware of this issue. Unfortunately, this seems to be the case with all implementations of this kind. e.g. if you use React Native and render a Web View of YouTube, it won't be able to go fullscreen.

**Comment by mark8044** [comment]
Ok thanks much, sorry about the duplicate!

**Comment by daohoangson** [comment]
Ah that's great to hear 👍
