### ISSUE TITLE
Some tag make the widget full width

### ISSUE THREAD

**Issue by Erchil66** [daohoangson/flutter_widget_from_html#719]
I have a tag like  "p" not div at start its "p" tag with text example test then when am trying to view it in it always give a widget having a full with how can i control the width of a certain tag? Am quite bind at this for hours.

**Comment by daohoangson** [comment]
Some tag (e.g. the P or the DIV tag) does expand to occupy as much width as available. If you want to control the width of the `HtmlWidget`, you can put it inside a `SizedBox` for example.

**Comment by Erchil66** [comment]
i Solve doing like this thanks @daohoangson 

```
SizeBox(
 width : null,
 child: HtmlWidget(
    """$message""",
    customStylesBuilder: (e){
        switch(e.localName){
          case 'p':
             return {
                   "width":"auto"
             };
        }
        return null;
    },
  ),
),
```

**Comment by Erchil66** [comment]
am closing this now really thanks..

**Comment by daoibrahim** [comment]
This helped me as well. Thank you
