### ISSUE TITLE
Scroll to text in html_widget

### ISSUE THREAD

**Issue by berkaycelebi00** [daohoangson/flutter_widget_from_html#720]
## Use case

We are using flutter_widget_from_html_core for our windows project but we need scroll to text in HtmlWidget and we could not find any way to do that. 

## Proposal

Is there any way to scroll to the text in HtmlWidget or is it possible to add this as a feature?

**Comment by daohoangson** [comment]
It's possible to scroll to anchor (element with `id` attribute or `A` tag with `name` attribute) using [scrollToAnchor](https://pub.dev/documentation/flutter_widget_from_html_core/latest/flutter_widget_from_html_core/HtmlWidgetState/scrollToAnchor.html) method. You will need to use a `GlobalKey` to keep track of the current render tree though, something like this:

```dart
final key = GlobalKey<HtmlWidgetState>();

// ...

return HtmlWidget(
  html,
  key: key,
);

// ...

key.currentState?.scrollToAnchor('foo');
```

**Comment by berkaycelebi00** [comment]
Thanks for replying.

We are trying to implement search ability for our htmlWidget.

 We created an empty project and it worked with our test html. Then when we analyzed our html code we realized that we have inline html tags like `mark` .

 And in test environment when we used:
 `<a name="testName""><span>This is an example test for htmlwidget</span></a>`
 or
`<span id="testName"">This is an example test for htmlwidget</span>`
 

It did not scroll. 

But if we use blocks like:
` <a name="testName""><h1>This is an example test for htmlwidget</h1></a>`  or
`<h1 id="testName"">This is an example test for htmlwidget</h1>`
it works.

Is it possible using scrollToAnchor method for inline tags or are we missing something in our code?

**Comment by daohoangson** [comment]
It should work for both block and inline element. Do you have a complete example for me to investigate?

**Comment by berkaycelebi00** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import 'package:fwfh_selectable_text/fwfh_selectable_text.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey<HtmlWidgetState> key = GlobalKey<HtmlWidgetState>();

  void _incrementCounter() {
    key.currentState!.scrollToAnchor("testName");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: HtmlWidget(
          """
      
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <h1>This is an example test for htmlwidget</h1>
        <a name="testName""><span>This is an example test for htmlwidget</span></a>
      
      """,
          key: key,
          onTapUrl: (String test) {
            return false;
          },
          factoryBuilder: () => MyWidgetFactory(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class MyWidgetFactory extends WidgetFactory with SelectableTextFactory {}
`
Ok now we also realized that when we added selectable text factory it does not scroll

**Comment by daohoangson** [comment]
> Ok now we also realized that when we added selectable text factory it does not scroll

So it works without the selectable mixin?

**Comment by berkaycelebi00** [comment]
Yes it works without selectable mixin. But it does not work when we use selectable mixin.

**Comment by berkaycelebi00** [comment]
Thank you for fix. The problem seems like solved. We tried and now `selectableText` and `scrollToAnchor` works fine.

**Comment by daohoangson** [comment]
That's great to hear 🎉
