### ISSUE TITLE
is supported text inline image? 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [daohoangson/flutter_widget_from_html#721]
I mean like this. 

![53761455-d2f10100-3ec5-11e9-83ed-d12565623cc3](https://user-images.githubusercontent.com/49102327/152697008-ed396fa5-b6b3-4cf3-ba8d-24ead1948b61.png)

**Comment by daohoangson** [comment]
Inline image works but the dropcap effect is not supported.

**Comment by Shahmirzali-Huseynov** [comment]
@daohoangson okay, is it available doing this ? or it will be supporting or never will be?
