### ISSUE TITLE
Can't load html with video?

### ISSUE THREAD

**Issue by alanFri** [daohoangson/flutter_widget_from_html#722]
`"<p>This is a coach draft</p >\r\n<p><span style=\"text-decoration: underline;\"><strong>How life go better</strong></span></p >\r\n<p><span style=\"font-family: arial, helvetica, sans-serif;\"><em>sleep more</em></span></p >\r\n<p><span style=\"font-family: arial, helvetica, sans-serif;\"><em>do less</em></span></p >\r\n<p>Coach record：</p >\r\n<p><video controls=\"controls\" width=\"300\" height=\"150\">\r\n<source src=\"http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4\" type=\"video/mp4\" /></video></p >\r\n<p>Visit baidu.com</p >\r\n<p>Call hotline&nbsp; 010-2345678 or Email hotline@gmail.com&nbsp;</p >"`

**Comment by daohoangson** [comment]
Can you recreate the issue with the bug template? It has some required information like Flutter version, package version etc.
