### ISSUE TITLE
Words in a table wrap in the middle of the word -> Problem with percentage

### ISSUE THREAD

**Issue by DFelten** [daohoangson/flutter_widget_from_html#733]
With the latest version a bug was fixed, by which percentage values work. Unfortunately this change breaks our tables. The behavior in the browser is different than in the app. In the browser, the text never wraps in the middle of a word.

There is also a problem with the percentages. Our example table has a width of 70%, but they are set to 100% via CSS. On the web it's working, but with this package it seems not possible to override the percentage. The custom styles are not working here. 

## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<div class="table-responsive">
    <table style="width: 79.0765%;">
        <tbody>
            <tr style="height: 55px">
                <td style="width: 15.6051%;height: 55px"></td>
                <td style="width: 19.7054%;height: 55px"><strong>Dreame H11 Max</strong></td>
                <td style="width: 19.7054%;height: 55px">Dreame H11</td>
            </tr>
            <tr style="height: 23px">
                <td style="width: 15.6051%;height: 23px">Saugkraft</td>
                <td style="width: 19.7054%;height: 23px"><strong>10.000 pa</strong></td>
                <td style="width: 19.7054%;height: 23px"><strong>5.500 pa</strong></td>
            </tr>
        </tbody>
    </table>
</div>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
class CustomHtmlWidget extends StatelessWidget {
  const CustomHtmlWidget();

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(slivers: [
      const SliverToBoxAdapter(),
      HtmlWidget(
        htmlCode,
        renderMode: RenderMode.sliverList,
        customStylesBuilder: _customStylesBuilder,
      ),
    ]);
  }

  Map<String, String>? _customStylesBuilder(dom.Element element) {
    if (element.localName == 'table') {
      return {'width': '100%'};
    }
    if (element.localName == 'td') {
      return {'width': '100%'};
    }
    return null;
  }
}
```
</details>

<details>
  <summary>Tesing environment</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.65.0-insider)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```
</details>

## Expected results

Result in the browser

<img width="497" alt="CleanShot 2022-02-14 at 17 29 25@2x" src="https://user-images.githubusercontent.com/1169185/153905050-b9355eed-2301-447b-b918-5c1a967fa967.png">

## Actual results

Result in the flutter app

<img width="391" alt="CleanShot 2022-02-14 at 17 24 28@2x" src="https://user-images.githubusercontent.com/1169185/153904087-81253189-e0bb-4b4f-8551-f00d03a79d43.png">

Without the percentage fix with 0.8.5 of flutter_widget_from_html and 0.8.4 of flutter_widget_from_html_core:

<img width="390" alt="CleanShot 2022-02-14 at 17 58 49@2x" src="https://user-images.githubusercontent.com/1169185/153910388-1b9e4216-046e-403a-a611-9dc63190a7b7.png">

**Comment by daohoangson** [comment]
> On the web it's working, but with this package it seems not possible to override the percentage. The custom styles are not working here.

This is expected because they are applied in this order: tag styling, custom styles then inline styles.

> The behavior in the browser is different than in the app. 

This is a known issue. Previously the TD width worked in an acceptable way but after #712 it turns out to be quite critical. I'll try to fast track #531.

**Comment by DFelten** [comment]
Thanks for the fast reply!

> This is expected because they are applied in this order: tag styling, custom styles then inline styles.

On the web, this order makes sense because we can also override inline styles using !important. This is currently not possible with the package as far as I know. Would it be possible to allow the important addition or alternatively add a way to optionally change the order of the applied styles? Alternatively another styling variable would be possible, important styles. 

WordPress unfortunately very often sets percentages as inline style. Like this we can't use the current version of the package and have to use an older version.

**Comment by DFelten** [comment]
Anything new here since you closed the MR with the possibility to use important within custom styles? :) 

We're currently not able to update your package because of the percentage problem. We have to use my custom fork or use the old version.

**Comment by daohoangson** [comment]
Sorry, no update in this front yet. The apply order of styling may be changed in the next major release since it's a breaking change, I'm still doing API simplification for that release. In the mean time, #531 needs more work.

**Comment by daohoangson** [comment]
Column width is being worked on in #747, with the latest commits, your HTML will look like this:

![issue733](https://user-images.githubusercontent.com/239336/160310668-daafa6f6-d1ba-44da-9e53-d6dbc3343d84.png)

The calculation is now closer to browser's (not a perfect match). It doesn't support `!important` yet though.

**Comment by daohoangson** [comment]
`flutter_widget_from_html_core@0.9.0+2` has been released with the fix for your usage. Previously, the viewport width is divided between available columns. In your HTML, the width is set to be very narrow so the cell contents cannot be rendered properly.

After the fix, the cell intrinsic width is taken into account but it is not applied forcefully. The table won't occupy the full width all the time. It will measure its children and choose some sensible value. Please try the new version and let me know if it breaks anything.

**Comment by DFelten** [comment]
Thanks for the update. With the latest version it's definitely better. But not perfect.

Html

```html
<div class="table-responsive">
    <table>
        <tbody>
            <tr >
                <td style="width: 15.6051%;height: 55px"></td>
                <td style="width: 19.7054%;height: 55px"><strong>Dreame H11 Max</strong></td>
                <td style="width: 19.7054%;height: 55px">Dreame H11</td>
            </tr>
            <tr >
                <td style="width: 15.6051%;height: 23px">Saugkraft</td>
                <td style="width: 19.7054%;height: 23px"><strong>10.000 pa</strong></td>
                <td style="width: 19.7054%;height: 23px"><strong>5.500 pa</strong></td>
            </tr>
        </tbody>
    </table>
</div>
```

App

![CleanShot 2023-01-09 at 09 50 51](https://user-images.githubusercontent.com/1169185/211270183-d086cd57-7978-4ed6-af87-ff4d77789b0a.png)

Browser

![CleanShot 2023-01-09 at 09 51 57](https://user-images.githubusercontent.com/1169185/211270368-21efefc1-2a7a-4185-aa8e-f12127853000.png)

Without the width it's working, but an improper width still creates a mid-word line break.

**Comment by daohoangson** [comment]
Hmm, I see.

**Comment by daohoangson** [comment]
I'm closing this issue. Let's use https://github.com/daohoangson/flutter_widget_from_html/issues/817 to keep track of the word breaking enhancement.
