### ISSUE TITLE
VIDEO support is not enabled

### ISSUE THREAD

**Issue by PranayDosii** [daohoangson/flutter_widget_from_html#745]
I am trying to use this plugin I followed all documentation but I am getting error like the video support is not enabled
can anyone help out. Here is my code

```

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      // ignore: prefer_const_constructors
      body: HtmlWidget(
        _html,
        baseUrl: Uri.parse(
          'https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html',
        ),
      ),
    );
  }

  final _html = """  
<video controls width="250">
  <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">
  <code>VIDEO</code> support is not enabled.
</video>
             """;
}
```

**Comment by daohoangson** [comment]
Are you using `flutter_widget_from_html` or `flutter_widget_from_html_core`?

**Comment by PranayDosii** [comment]
I have used asa same as the example code here
[Video.dart](https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/lib/screens/video.dart)

**Comment by daohoangson** [comment]
That should work. Can you provide `flutter doctor -v` output? And which version of this package are you using?

**Comment by PranayDosii** [comment]
`
PS H:\dosii_video_player\dosii_video_player> flutter doctor -v
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.556], locale en-IN)
    • Flutter version 2.10.0 at H:\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\My_android_sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.`

**Comment by PranayDosii** [comment]
Hey `import 'package:flutter_widget_from_html/flutter_widget_from_html.dart'` this import fixed my issue I was using 
`flutter_widget_from_html_core` that's why it's happening thanks for helping
