### ISSUE TITLE
'webView' is deprecated and shouldn't be used. Override WidgetFactory.webView instead

### ISSUE THREAD

**Issue by gamestap99** [daohoangson/flutter_widget_from_html#749]
Hi, I tried removing the webview flag and video of youtube not show. It was turned into a chain. I found webview flag inside WidgetFactory and it has value is true. I used it but not working. I still have to use the webview flag.

```
                                          HtmlWidget(
                                            state.item!.description,
                                            factoryBuilder: ()=> WidgetFactory(),
                                            textStyle: TextStyle(
                                              fontFamily: Font.robotoRegular,
                                              fontSize: RpsText.size15,
                                            ),
                                            webView: true,
                                          )
```

**Comment by daohoangson** [comment]
You need to extend the factory, something like this:

```dart
class _MyFactory extends WidgetFactory {
  @override
  bool get webView => true;
}
```

Then use it in your `build` method:

```dart
                                        HtmlWidget(
                                          state.item!.description,
                                          factoryBuilder: () => _MyFactory(),
                                          textStyle: TextStyle(
                                            fontFamily: Font.robotoRegular,
                                            fontSize: RpsText.size15,
                                          ),
                                        )
```

**Comment by gamestap99** [comment]
> You need to extend the factory, something like this:
> 
> ```dart
> class _MyFactory extends WidgetFactory {
>   @override
>   bool get webView => true;
> }
> ```
> 
> Then use it in your `build` method:
> 
> ```dart
>                                         HtmlWidget(
>                                           state.item!.description,
>                                           factoryBuilder: () => _MyFactory(),
>                                           textStyle: TextStyle(
>                                             fontFamily: Font.robotoRegular,
>                                             fontSize: RpsText.size15,
>                                           ),
>                                         )
> ```

Thank for question
