### ISSUE TITLE
Text not honoring device accessibility settings

### ISSUE THREAD

**Issue by mclark4386** [daohoangson/flutter_widget_from_html#75]
I put the title and body of these cards in HTMLWidgets to parse them and the text scale of the widgets isn't scaling with the accessibility settings of the phone:

![Simulator Screen Shot - iPhone Xʀ - 2019-09-21 at 01 09 19](https://user-images.githubusercontent.com/484943/65368959-cedfc300-dc0c-11e9-9400-687d3538b329.png)

You can see how the AppBar title and the labels on the bottom nav are MUCH larger than normal... I didn't set the size on those, so that's all the device accessibility settings.

**Comment by daohoangson** [comment]
This is definitely a bug, I'll see what can be done.

**Comment by daohoangson** [comment]
`v0.2.3+1` has been released with the fix for this, please try upgrading @mclark4386

**Comment by mclark4386** [comment]
Looks good! thanks!
