### ISSUE TITLE
Line breaks in a string not rendered correct.

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [daohoangson/flutter_widget_from_html#753]
I have a string that can sometimes have HTML. String has line breaks ( not `<br/>` ).
If I use the `Text` Widget then, the string shows the right line breaks but in `HtmlWidget` this string is not showing in the right format.
E.g. String has data like:

```
First
Second 
Third
```

but the result in HtmlWidget is :
First Second Third

**Comment by daohoangson** [comment]
This is working as intended. Regular line breaks are rendered as spaces in HTML.

**Comment by UmairSaqibBhutta** [comment]
but I want to show them as line breaks...
as the simple `Text` widget does.

**Comment by daohoangson** [comment]
You will need to consult your data source (backend API?) regarding this. A string should be defined clearly whether it is plain text or HTML. It's hard to render correctly if the formatting is unknown.

If you really want to enforce new line on regular line break, doing a `replace("\r\n", "<br />")` should work.
