### ISSUE TITLE
Endlessly spinning loading circle

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#754]
I have a fairly complex WidgetFactory and sometimes when the rendered element is very large or has a lot of elements to it, the widget never fully loads and I have an endlessly spinning blue loading circle.

With the exact same content, this doesn't happen all the time, only sometimes.

And no error messages are thrown at all.

Do you have any ideas on how I can track down why this is happening?  Could it be an issue with memory (why it sometimes happens and sometimes doesn't happen with the same content).  Is there a way I can switch all error logging on in some way?  Does the endlessly spinning loading circle indicate something else?

Thanks!

**Comment by daohoangson** [comment]
Do you happen to catch it during development? When it kept spinning, is there any logging?

**Comment by daohoangson** [comment]
No, we don't have timeout anywhere in the `HtmlWidget` rendering pipeline.

> Whats interesting to me is that ever since I added `onErrorBuilder` I don't see the problem happen as much anymore.  I don't know if its coincidence, but I have a phone which is still running an earlier version of the app without `onErrorBuilder: (context, element, error) => Text('$element error: $error'),` and just a minute ago the spinning circle came up again.  The only difference in the app between the version on that phone and the one I'm running in simulator is `onErrorBuilder`.

This probably means there is a bug some where that tries to call `onErrorBuilder` but failed because it is `null`.

**Comment by mark8044** [comment]
> No, we don't have timeout anywhere in the `HtmlWidget` rendering pipeline.
> 
> > Whats interesting to me is that ever since I added `onErrorBuilder` I don't see the problem happen as much anymore.  I don't know if its coincidence, but I have a phone which is still running an earlier version of the app without `onErrorBuilder: (context, element, error) => Text('$element error: $error'),` and just a minute ago the spinning circle came up again.  The only difference in the app between the version on that phone and the one I'm running in simulator is `onErrorBuilder`.
> 
> This probably means there is a bug some where that tries to call `onErrorBuilder` but failed because it is `null`.

Well, I can happily say that ever since I implemented `onErrorBuilder` the endlessly loading circle no longer appears.  👍

**Comment by daohoangson** [comment]
I couldn't produce a sample where WF failure causes infinite spinning but I found (and fixed) another related bug via #760 🤣 If you run into this bug again, feel free to open a new issue. Hopefully with some error messages.
