### ISSUE TITLE
video in iframe is autoplay

### ISSUE THREAD

**Issue by kent2508** [daohoangson/flutter_widget_from_html#755]
Hi, my video in iframe tag is autoplay and I can not fix it. I tried to add autoplay=0 or autoplay=false to iframe property but nothing change. Is this a new bug in newest version?

**Comment by daohoangson** [comment]
What is your HTML? If the website autoplays video, changing the query param won't work.

**Comment by kent2508** [comment]
It's just a static html string contains this line:
`<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="http://192.168.0.149:55000/articles/65/56475_sample-mp4-file-smal.mp4?rel=0">`

**Comment by daohoangson** [comment]
Ah, it always autoplays when you give a direct video link to a webview. Use
some kind of video player to avoid this maybe?

This widget supports the VIDEO tag for example.

**Comment by kent2508** [comment]
you mean replace iframe tag with VIDEO tag like:
`'<VIDEO src="http://192.168.0.149:55000/articles/65/56475_sample-mp4-file-smal.mp4?rel=0"></VIDEO>'`
I tried but it was not working.
Sorry for asking too much, but there's no sample about this tag in the pub.dev.

**Comment by kent2508** [comment]
I found the sample of video tag in Chewie github:
`<video controls>
  <source src="http://192.168.0.149:55000/articles/65/56475_sample-mp4-file-smal.mp4?rel=0">
</video>`

**Comment by daohoangson** [comment]
That looks good. Does it work for you?

**Comment by kent2508** [comment]
Yeah! Thanks so much. It works.

**Comment by daohoangson** [comment]
Awesome. I'm closing this issue now.
