### ISSUE TITLE
selectable text stops scrolling when inside a card body which is part of a list. 

### ISSUE THREAD

**Issue by nandakav** [daohoangson/flutter_widget_from_html#757]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by daohoangson** [comment]
Can you provide more details as suggested in the issue template?
