### ISSUE TITLE
Change CachedNetworkImage to NetworkImage

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [daohoangson/flutter_widget_from_html#76]
Hello, I want to use NetworkImage instead of CachedNetworkImage, how can I change this? I want to use flutter_widget_from_html, so changing to flutter_widget_from_html_core is not a solution for me, because I need a webview functionality. Tnx in advance

**Comment by daohoangson** [comment]
You can override the `buildImageFromUrl` method, full example [here](https://gist.github.com/daohoangson/111e103f92e0261e0077855f4e9f5e0a), screenshot running in iOS Simulator:

![Simulator Screen Shot - iPhone Xʀ - 2019-09-21 at 16 58 24](https://user-images.githubusercontent.com/239336/65371766-33446600-dc91-11e9-9747-d94d7378b5a6.png)

Screenshot from Dart DevTools:

<img width="1410" alt="Screen Shot 2019-09-21 at 4 58 39 PM" src="https://user-images.githubusercontent.com/239336/65371767-33446600-dc91-11e9-928f-a3f4cac85deb.png">

**Comment by aleksandar-radivojevic** [comment]
Ok tnx bro, it worked. I have one more question. I'm building news app and I'm using your plugin for single post content which is in SingleChildScrollView widget. Loading of iframes is kinda slow, it takes couple of seconds(3,4s) to load AND while iframe is loading scrolling is extreme laggy, when loading is finished scrolling is smooth again.
So I was wondering is there a way around this, maybe to wrap Webview with AnimatedContainer and use CircularProgressIndicator while iframe is loading and than fade in iframe? Thats my idea on this and I try to implement it, but no success... Loading time is not that much of a problem as is laggy scrolling while loading iframe

**Comment by daohoangson** [comment]
Yeah, WebView performance is not the best. I'm not sure it's possible to fade in the WebView because Flutter uses PlatformView for this and it might not initialize properly in the background. I have open a new issue for this, feel free to subscribe if you want to be notified when it's ready (or not). https://github.com/daohoangson/flutter_widget_from_html/issues/77

**Comment by aleksandar-radivojevic** [comment]
Thank you very much bro!! I wil close this issue.

**Comment by aleksandar-radivojevic** [comment]
I'm getting this error while using your solution to override buildImageFromUrl :
_MyWidgetFactory.buildImageFromUrl' ('Widget Function(String)') isn't a valid override of 'WidgetFactory.buildImageFromUrl' ('buildImageFromUrl')

**Comment by daohoangson** [comment]
I have answered in your newly created issue https://github.com/daohoangson/flutter_widget_from_html/issues/93. Basically the plugin's API have changed a bit so you need to update the code.
