### ISSUE TITLE
Inline padding squashes image

### ISSUE THREAD

**Issue by glen-84** [daohoangson/flutter_widget_from_html#764]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
      <p>Para 1</p>
      <p>
        Para 2
        <a href="#" target="_blank">
          <img
            src="https://github.githubassets.com/favicons/favicon.svg"
            width="24"
            height="24"
            style="padding-inline-end: 10px; vertical-align: middle;"
            title="Text" /><strong>text</strong></a> more text
      </p>
      <p>Para 3</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
// default from try.fwfh.dev
```
</details>

<details>
  <summary>Tesing environment</summary>

```
(not applicable)
```
</details>

## Expected results

The image should not be squashed when adding padding.

## Actual results

The image is squashed.

![image](https://user-images.githubusercontent.com/261509/166144291-92fb53fe-bd1e-47ab-b638-460a98843985.png)

**Comment by daohoangson** [comment]
v0.9.1 has been released with the fix for this. Please try upgrading and see whether it works in your app.

**Comment by glen-84** [comment]
@daohoangson Has `try.fwfh.dev` been updated?

**Comment by daohoangson** [comment]
Not yet, let me attempt it now. There was some breaking change earlier which failed the deployment so that playground is lagging behind a bit.

**Comment by daohoangson** [comment]
It's up.

**Comment by glen-84** [comment]
Yep, seems to work:

![image](https://user-images.githubusercontent.com/261509/211389898-547ddf2b-683b-4e92-b104-635108e841aa.png)

Thank you.
