### ISSUE TITLE
Leaving space when the video display on Safari browser 

### ISSUE THREAD

**Issue by PranayDosii** [daohoangson/flutter_widget_from_html#766]
I am using a mac m1 having safari browser `Version 15.4 (17613.1.17.1.13)` and the `flutter_widget_from_html: ^0.8.5`. When I try to load the video it leaves the space between the bottom and top. Here is my code
```
   _html = """
<figure>
  <video autoplay muted loop>
    <source src="${widget.videoUrl}" type="video/mp4">
    <code>VIDEO</code> support is not enabled.
  </video>
  
</figure>
"""
```
Here is the screenshot when loading 
<img width="1101" alt="Screenshot 2022-05-06 at 9 58 46 AM" src="https://user-images.githubusercontent.com/95602652/167067272-77ebd903-55df-47bc-87f8-eed8ad989fae.png">

After Loaded
<img width="1101" alt="Screenshot 2022-05-06 at 9 59 04 AM" src="https://user-images.githubusercontent.com/95602652/167067333-8b97e3b6-2957-40c5-9aeb-b95725256c1c.png">

No issues with chromium-based browsers

**Comment by daohoangson** [comment]
You are building Flutter Web right? Which renderer is this? Do you have the app deployed somewhere so I can take a look?

**Comment by daohoangson** [comment]
Sorry for the late reply, the Firebase hosting URL has been dead. Can you re-upload it somewhere else?
