### ISSUE TITLE
Problem with image parsing

### ISSUE THREAD

**Issue by Wratheus** [daohoangson/flutter_widget_from_html#774]
Hello, I have such trouble while parsing html. (sorry for stupid issue)
I think I missed something, maybe images are too big and to avoid render flex they are cutted off? Is there any way how I can fix width for them? 

This is example of how widget is acting, the blank space is where images are supposed to be.
<img src="https://i.imgur.com/C3TlAQt.png" height=300/>

This is raw html.txt file, that i'm trying to load
[html.txt](https://github.com/daohoangson/flutter_widget_from_html/files/8740191/html.txt)

![Без имени](https://user-images.githubusercontent.com/71131015/169531033-bebb1d8e-f613-4e75-8b94-bbe39e4dddb5.png)

**Comment by daohoangson** [comment]
The web page is using some lazy loading JavaScript library so it puts the real image URL inside a custom attribute (`data-normal`), you have to parse that in your Flutter app to display the remote image, something like this:

```dart

class MyWidgetFactory extends WidgetFactory {
  @override
  Widget? buildImage(BuildTree tree, ImageMetadata data) {
    final attrs = tree.element.attributes;
    final url = attrs['data-normal'];
    if (url != null) {
      final newData = ImageMetadata(sources: [ImageSource(url)]);
      return super.buildImage(tree, newData);
    }

    return super.buildImage(tree, data);
  }
}

```

It will render like this:

<img width="912" alt="Screen Shot 2023-05-22 at 15 12 18" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/e9d85391-ab28-4c26-bc15-29206ce2cfa6">

**Comment by Wratheus** [comment]
Thank you!
