### ISSUE TITLE
Scroll to anchor doesn't work with baseUrl specified

### ISSUE THREAD

**Issue by raminsafaei** [daohoangson/flutter_widget_from_html#776]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<a id="testid" href="#tohere">example place</a>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget(
   '''<a id="testid" href="#tohere">example place</a>''',
   baseUrl: Uri.parse('http://example.com'),
   buildAsync: true,
   isSelectable: true,
 );
```
</details>

<details>
  <summary>Tesing environment</summary>

```
Flutter 3.0.0
flutter_widget_from_html: ^0.8.5
```
</details>

## Expected results

should scroll to tapped url

## Actual results

opens full link: http://example.com/#tohere

**Comment by daohoangson** [comment]
FYI, the latest stable (`v0.14.2`) has been released with the fix for anchor doesn't work with `baseUrl` specified.
