### ISSUE TITLE
Audio in html is too low.

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [daohoangson/flutter_widget_from_html#785]
I am using `HtmlWidget `as a audio player for a URL. Everything working well but audio is too low and difficult to hear.
My code is:

`HtmlWidget("""<audio controls
                  src=${message.uri}
                  </audio>""")`

**Comment by daohoangson** [comment]
I saw that you enabled the controls for audio player, increasing the volume doesn't help? Can you share the HTML?

**Comment by UmairSaqibBhutta** [comment]
I have share working code earlier in this issue. And nothing works if we remove controls.
I have tried every way i.e. increasing device sound etc but the problem is with lib.
you can paste any audio link at `message.uri` to verify.

**Comment by daohoangson** [comment]
You can always grab the latest APK built for each commit in this repo, e.g. this one https://github.com/daohoangson/flutter_widget_from_html/commit/9025337fc5c3fd805e4572da7bda625e14fc4776#commitcomment-94201798

The demo app has a audio screen. Do you hear normal volume level with that app?

**Comment by UmairSaqibBhutta** [comment]
yeah! In the demo app, voice seems normal.

**Comment by UmairSaqibBhutta** [comment]
yeah! in the provided demo app, volume level is normal.

**Comment by daohoangson** [comment]
There is no recent change relates to this. I think you should grab the latest version from pub.dev and try it again in your app.
