### ISSUE TITLE
Buy Me a Coffee Link Leads to 404

### ISSUE THREAD

**Issue by ScottWallace** [daohoangson/flutter_widget_from_html#788]
## Steps to Reproduce

1) Click on "Buy me a coffee" link on github for flutter_widget_from_html.
2) Notice that the web page issues a 404 error.

## Expected results

I expected to be able to buy you a coffee!

## Actual results

The link [Buy me a coffee link](https://www.buymeacoffee.com/daohoangson) returns a 404 error.

**Comment by daohoangson** [comment]
Thank you for reporting, there was a typo in my setup. It has been fixed.
