### ISSUE TITLE
TextStyle copyWith exception

### ISSUE THREAD

**Issue by akshayru** [daohoangson/flutter_widget_from_html#790]
After adding plugin i am getting below exception.

```
 HtmlWidget(
                                              '<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=pratiksharu-20&language=en_US&marketplace=amazon&region=US&placement=B09C48JHRG&asins=B09C48JHRG&linkId=de0ac5de72ebff676228cc6a6c17994c&show_border=true&link_opens_in_new_window=true"></iframe>',
                                              customStylesBuilder: (element) {
                                                if (element.classes
                                                    .contains('name')) {
                                                  return {'color': 'red'};
                                                }
                                                return null;
                                              },
                                            ),
```

/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.7.3+2/lib/fwfh_text_style.dart:103:13: Error: The method 'FwfhTextStyle.copyWith' doesn't have the named parameter 'fontVariations' of overridden method 'TextStyle.copyWith'.

  TextStyle copyWith({
            ^
/C:/Flutter/flutter/packages/flutter/lib/src/painting/text_style.dart:814:13: Context: This is the overridden method ('copyWith').
  TextStyle copyWith({

**Comment by zambetpentru** [comment]
I am also seeing this when I upgraded to the latest master today

**Comment by daohoangson** [comment]
A new version has been made available at https://pub.dev/packages/fwfh_text_style/versions/2.13.0. It should fix your issue with Flutter beta. Please try upgrading and let me know if it works for you.
