### ISSUE TITLE
Missing Arguments

### ISSUE THREAD

**Issue by CaseyBall** [daohoangson/flutter_widget_from_html#792]
## Steps to Reproduce

just run flutter upgrade
then try to run the example you have provided
<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by daohoangson** [comment]
Hmm, what is the error?
