### ISSUE TITLE
VIDEO tag doesn't work

### ISSUE THREAD

**Issue by dackArrogant** [daohoangson/flutter_widget_from_html#802]
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
A borderRadius can only be given for a uniform Border.

The following is not uniform:
BorderSide.color
BorderSide.width
BorderSide.style
The relevant error-causing widget was: 
  HtmlWidget HtmlWidget:file:///Users/admin/Developer/src/ddhy_member/branchs/member/lib/utils/ddhy_common_utils.dart:187:12
When the exception was thrown, this was the stack: 
#0      Border.paint.<anonymous closure> (package:flutter/src/painting/box_border.dart:523:9)
#1      Border.paint (package:flutter/src/painting/box_border.dart:532:6)
#2      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:484:25)
#3      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2150:17)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#12     RenderParagraph.paint.<anonymous closure> (package:flutter/src/rendering/paragraph.dart:759:19)
#13     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#14     PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:568:7)
#15     RenderParagraph.paint (package:flutter/src/rendering/paragraph.dart:754:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#21     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#25     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2169:11)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#34     RenderParagraph.paint.<anonymous closure> (package:flutter/src/rendering/paragraph.dart:759:19)
#35     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#36     PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:568:7)
#37     RenderParagraph.paint (package:flutter/src/rendering/paragraph.dart:754:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#43     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#44     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#47     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#53     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#56     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#57     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#60     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#63     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#64     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#67     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#70     RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1779:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#73     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:660:17)
#74     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#75     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:443:7)
#76     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:635:38)
#77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#78     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#79     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#80     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#81     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#82     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#83     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#84     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#85     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#86     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#90     _invoke (dart:ui/hooks.dart:151:10)
#91     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#92     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#4318e relayoutBoundary=up20
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
...  size: Size(368.0, 41.0)
...  decoration: BoxDecoration
...    color: Color(0xffffd658)
...    border: Border(bottom: BorderSide(Color(0xff3e3e3e), 1.0, BorderStyle.solid))
...    borderRadius: BorderRadius.zero
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#5eb0d(), devicePixelRatio: 3.0, locale: zh_CH, textDirection: TextDirection.ltr, platform: iOS)
RenderObject: RenderDecoratedBox#4318e relayoutBoundary=up20
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
  size: Size(368.0, 41.0)
  decoration: BoxDecoration
    color: Color(0xffffd658)
    border: Border(bottom: BorderSide(Color(0xff3e3e3e), 1.0, BorderStyle.solid))
    borderRadius: BorderRadius.zero
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#5eb0d(), devicePixelRatio: 3.0, locale: zh_CH, textDirection: TextDirection.ltr, platform: iOS)
...  child: RenderPadding#79580 relayoutBoundary=up21 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
...    size: Size(368.0, 41.0)
...    padding: EdgeInsets(0.0, 0.0, 0.0, 1.0)
...    textDirection: ltr
...    child: RenderPositionedBox#36d12 relayoutBoundary=up22 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
...      size: Size(368.0, 40.0)
...      alignment: Alignment.topLeft
...      textDirection: ltr
...      widthFactor: expand
...      heightFactor: expand
...      child: RenderPadding#601c4 relayoutBoundary=up23 NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
...        size: Size(368.0, 40.0)
...        padding: EdgeInsets(15.0, 5.0, 15.0, 5.0)
...        textDirection: ltr
...        child: _RenderCssSizing#b7a5f relayoutBoundary=up24 NEEDS-PAINT
...          needs compositing
...          parentData: offset=Offset(15.0, 5.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=338.0, 0.0<=h<=Infinity)
...          size: Size(338.0, 30.0)
====================================================================================================

**Comment by daohoangson** [comment]
What is your HTML

**Comment by LinMaris** [comment]
> 

This can not show
"<video src=\"https://xiaoheitan.oss-cn-shenzhen.aliyuncs.com/htkb/2022-08-08/1659948354031.mp4\" controls=\"controls\" style=\"max-width:100%\"></video>"

**Comment by LinMaris** [comment]
> What is your HTML

This can not show
```
"<video src=\"https://xiaoheitan.oss-cn-shenzhen.aliyuncs.com/htkb/2022-08-08/1659948354031.mp4\" controls=\"controls\" style=\"max-width:100%\"></video>"
```

**Comment by daohoangson** [comment]
Which package are you using? `flutter_widget_from_html_core` doesn't support VIDEO tag. `flutter_widget_from_html` does.

**Comment by LinMaris** [comment]
> Which package are you using? `flutter_widget_from_html_core` doesn't support VIDEO tag. `flutter_widget_from_html` does.

I use `flutter_widget_from_html`, you can try that html String

**Comment by daohoangson** [comment]
This didn't work because `src` attribute in VIDEO was not supported. You have to use the SOURCE child tag.
I'm releasing a new version to support this feature, see #848.

**Comment by daohoangson** [comment]
v0.9.1 has been released with support for this. Please try upgrading and see whether it works in your app.
