### ISSUE TITLE
Error: No named parameter with the name 'fontVariations'.

### ISSUE THREAD

**Issue by true2thepen** [daohoangson/flutter_widget_from_html#803]
## Steps to Reproduce
Full Code:
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Widget from HTML'),
        ),
        body: const Center(
          child: HtmlWidget('<html><body>Me</body></html>'),
        ),
      ),
    );
  }
}

pubspec.yaml:
name: brokenapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_widget_from_html_core: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

<details>
  <summary>HTML</summary>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.15.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/steven/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/steven/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/steven/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave-browser

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /home/steven/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/steven/Android/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.15.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.41.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

## Expected results

The working app.

## Actual results

Launching lib/main.dart on Chrome in debug mode...
../flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:98:11: Error: No named parameter with the name
'fontVariations'.
          fontVariations: fontVariations,
          ^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:164:9: Error: No named parameter with the name
'fontVariations'.
        fontVariations: fontVariations ?? this.fontVariations,
        ^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/painting/text_style.dart:468:9: Context: Found this candidate, but the arguments don't match.
  const TextStyle({
        ^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:244:53: Error: The getter 'fontVariations' isn't
defined for the class 'TextStyle'.
 - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('../flutter/packages/flutter/lib/src/painting/text_style.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fontVariations'.
  List<ui.FontVariation>? get fontVariations => ref.fontVariations;
                                                    ^^^^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             49.4s
Failed to compile application.

**Comment by dJani97** [comment]
You beat me by a few minutes :)

I think I submitted a duplicate: https://github.com/daohoangson/flutter_widget_from_html/issues/804

**Comment by true2thepen** [comment]
Thanks. Tried that and it works. Though we shouldn't have to do that.

**Comment by dJani97** [comment]
Awesome. Just suggesting it as a workaround, I hope it will get fixed soon.

**Comment by daohoangson** [comment]
Yes, the new version has in correct Flutter SDK constraint, fix is coming. Sorry for the inconvenience.

**Comment by daohoangson** [comment]
This should be resolved by now. Installing this package in a new app should work out of the box for both Flutter stable, beta and master channels.

**Comment by dJani97** [comment]
Running `flutter pub upgrade` pulls in the new version (`2.22.08`), and building an APK works now. Thank you!

**Comment by daohoangson** [comment]
Great to hear!

**Comment by true2thepen** [comment]
Cursory testing shows no problems. Appreciate the fast fix. As such, I am closing this as being fixed.
