### ISSUE TITLE
Flutter 3.3 :  The non-abstract class 'FwfhTextStyle' is missing implementations for these members

### ISSUE THREAD

**Issue by shirne** [daohoangson/flutter_widget_from_html#814]
lib/fwfh_text_style.dart:11:7: Error: The non-abstract class 'FwfhTextStyle' is missing implementations for these members:
 - TextStyle.fontVariations
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [版本 10.0.19044.1889], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.17)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by daohoangson** [comment]
Please try `flutter pub upgrade fwfh_text_style` to bump it to the latest version.

**Comment by shirne** [comment]
> Please try `flutter pub upgrade fwfh_text_style` to bump it to the latest version.

thanks.  resolved.

**Comment by ziadsarour** [comment]
> Please try `flutter pub upgrade fwfh_text_style` to bump it to the latest version.

Thank you ! 🎉
