### ISSUE TITLE
Flutter 3.3 stable release build error

### ISSUE THREAD

**Issue by ScottWallace** [daohoangson/flutter_widget_from_html#815]
Building using Flutter 3.3 stable produces the following error:

 Error: The non-abstract class 'FwfhTextStyle' is missing implementations for these members:
../…/lib/fwfh_text_style.dart:11
     - TextStyle.fontVariations
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
    class FwfhTextStyle extends _TextStyleProxy {
          ^^^^^^^^^^^^^
: Context: 'TextStyle.fontVariations' is defined here.
../…/painting/text_style.dart:789
      final List<ui.FontVariation>? fontVariations;
                                    ^^^^^^^^^^^^^^
: Error: The method 'FwfhTextStyle.apply' has fewer named arguments than those of overridden method 'TextStyle.apply'.
../…/lib/fwfh_text_style.dart:43
      TextStyle apply({
                ^
: Context: This is the overridden method ('apply').
../…/painting/text_style.dart:911
      TextStyle apply({
                ^
: Error: The method 'FwfhTextStyle.apply' doesn't have the named parameter 'fontVariations' of overridden method 'TextStyle.apply'.
../…/lib/fwfh_text_style.dart:43
      TextStyle apply({
                ^
: Context: This is the overridden method ('apply').
../…/painting/text_style.dart:911
      TextStyle apply({
                ^
: Error: The method 'FwfhTextStyle.copyWith' has fewer named arguments than those of overridden method 'TextStyle.copyWith'.
../…/lib/fwfh_text_style.dart:103
      TextStyle copyWith({
                ^
: Context: This is the overridden method ('copyWith').
../…/painting/text_style.dart:814
      TextStyle copyWith({
                ^
: Error: The method 'FwfhTextStyle.copyWith' doesn't have the named parameter 'fontVariations' of overridden method 'TextStyle.copyWith'.
../…/lib/fwfh_text_style.dart:103
      TextStyle copyWith({
                ^
: Context: This is the overridden method ('copyWith').
../…/painting/text_style.dart:814
      TextStyle copyWith({
                ^

**Comment by daohoangson** [comment]
Your app was building fine before upgrading to Flutter 3.3 right? Please try `flutter pub upgrade fwfh_text_style` to bump one of the dependency to a Flutter 3.3 compatible version.

**Comment by ScottWallace** [comment]
Yes, that fixed it. Thanks!
