### ISSUE TITLE
Set a fixed height to the widget

### ISSUE THREAD

**Issue by georgeraveen** [daohoangson/flutter_widget_from_html#820]
I want to set a height to the HTML widget
<br>
`
Container(
    height: 100,
    color: Colors.white,
    child: Wrap(
      children: [
        HtmlWidget(
          product.description,
        ),
      ],
    ),
  ),
Container(
// rest of the widgets
)
`
<br>
When I set a fixed height using a container, size is fixed. But the overflow content is displayed under the rest of the widgets as a stack
<br>
![image](https://user-images.githubusercontent.com/34133131/190840725-e247d2c5-7498-400f-a5b5-ab95c71644e6.png)
I also tried with wrap widget. I there any way to hide the overflow content?

**Comment by daohoangson** [comment]
You can use `ClipRect` to hide the overflow contents.

**Comment by georgeraveen** [comment]
Yes ClipRect solves the issue. but It works only with Align widget as a child. Align widget takes height as a percentage.

My usecase is to give a fixed height to the widget. Using a Container or Sizedbox instead of Align widget gives a small overflow.
```
ClipRect(
  child: SizedBox(
    height:100,
    child: HtmlWidget(
      widget.product.description,
    ),
  ),
),
```
![image](https://user-images.githubusercontent.com/34133131/190915994-01de795d-ae37-4b9f-a49a-7dbd7f1bfeee.png)

**Comment by daohoangson** [comment]
Sorry for the late response. For your use case, it's probably better to implement a short of height limiter like this https://stackoverflow.com/questions/55091863/flutter-detect-content-overflow-and-clip-it

<details>
<summary>Code snippet from StackOverflow</summary>

```dart
class HeightLimiter extends StatefulWidget {
  final Widget child;
  final double maxHeight;
  final double fadeEffectHeight;

  const HeightLimiter({Key key, this.maxHeight, this.child, this.fadeEffectHeight = 72}) : super(key: key);

  @override
  _HeightLimiterState createState() => _HeightLimiterState();
}

class _HeightLimiterState extends State<HeightLimiter> {
  var _size = Size.zero;

  @override
  Widget build(BuildContext context) {
    return ConstrainedBox(
      constraints: BoxConstraints(
        maxHeight: widget.maxHeight,
      ),
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          Positioned(
            top: 0,
            left: 0,
            right: 0,
            child: MeasureSize(
              onChange: (size) => setState(() => _size = size),
              child: widget.child,
            ),
          ),
          if (_size.height >= widget.maxHeight)
            Positioned(
              bottom: 0,
              left: 0,
              width: _size.width,
              child: _buildOverflowIndicator(),
            ),
        ],
      ),
    );
  }

  Widget _buildOverflowIndicator() {
    return Container(
      height: widget.fadeEffectHeight,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.bottomCenter,
          end: Alignment.topCenter,
          colors: [
            Colors.white.withAlpha(200),
            Colors.white.withAlpha(0),
          ],
          tileMode: TileMode.clamp,
        ),
      ),
    );
  }
}
```
</details>
