### ISSUE TITLE
list item is aligned to right instead of left

### ISSUE THREAD

**Issue by ristiisa** [daohoangson/flutter_widget_from_html#826]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<ol style="padding-left: 0; list-style: inside decimal;">
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ol>
```

![image](https://user-images.githubusercontent.com/514571/193595694-3ae9326f-cb87-42f1-9eb2-f27cc8e61126.png)

</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
void main() {
  var html = '''
<ol style="padding-left: 0; list-style: inside decimal;">
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ol>
  ''';

  runApp(MaterialApp(home: Scaffold(body: SafeArea(
    child: Padding(
      padding: EdgeInsets.only(left: 50),
      child: Container(decoration: BoxDecoration(border: Border.all()), child: HtmlWidget(html)),
    ),
  ))));
}
```
</details>

<details>
  <summary>Tesing environment</summary>

```
flutter_widget_from_html: ^0.8.5

[✓] Flutter (Channel stable, 3.3.3, on macOS 11.6.2 20G314 darwin-x64, locale en-EE)
    • Flutter version 3.3.3 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (5 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0
```
</details>

## Expected results

![image](https://user-images.githubusercontent.com/514571/193595757-f501db17-9e60-40b8-b609-b5689703f402.png)

## Actual results

![image](https://user-images.githubusercontent.com/514571/193597363-a515d173-ab0e-41b1-9b0e-3f9515a893b2.png)

1. The numbers are drawn outside
2. The numbers are aligned right instead of left

**Comment by daohoangson** [comment]
This is expected, `list-style` is not supported yet. It's being tracked in #514.
