### ISSUE TITLE
<br> does not do the same as it does in HTML.

### ISSUE THREAD

**Issue by andreyeurope** [daohoangson/flutter_widget_from_html#83]
This it how it looks using your widget:
![image](https://user-images.githubusercontent.com/10363862/65547417-bc6dce00-df19-11e9-97a6-c08390aea7f4.png)

This is how it looks in HTML (on W3schools):
![image](https://user-images.githubusercontent.com/10363862/65547498-e0c9aa80-df19-11e9-86fe-9638a0474a47.png)

**Comment by daohoangson** [comment]
What is your HTML?

**Comment by andreyeurope** [comment]
These are some places where line breaks can be found:
![image](https://user-images.githubusercontent.com/10363862/65580984-fa4f0e80-df7a-11e9-95c6-b711b6ab7c58.png)

**Comment by andreyeurope** [comment]
They look like this:
`
<p> text text <br> text <br> text <br> </p>
`

**Comment by daohoangson** [comment]
I see. Let me check it out.

**Comment by daohoangson** [comment]
`v0.2.3+3` has been released with the fix for this. Please let me know if it works for you.
