### ISSUE TITLE
Why isSelectable property is removed in new version?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [daohoangson/flutter_widget_from_html#832]
I used this lib and its property `isSelectable ` but in the latest version, this property is removed. Any new option for this feature?

**Comment by daohoangson** [comment]
For Flutter 3.3, use the new [SelectionArea](https://api.flutter.dev/flutter/material/SelectionArea-class.html) to control selection behavior. Basically you can put the `HtmlWidget` inside a  `SelectionArea` to make it selectable. Selecting across different paragraphs should work etc.

**Comment by mark8044** [comment]
This new way with `SelectionArea` is working like a charm!

**Comment by daohoangson** [comment]
Awesome.

**Comment by UmairSaqibBhutta** [comment]
@daohoangson thanks a lot.
