### ISSUE TITLE
Table Problem

### ISSUE THREAD

**Issue by SinanKanmaz** [daohoangson/flutter_widget_from_html#85]
Hello.
The problem arises when there are two tables in the file. How can I solve this problem?
this is error:

Duplicate keys found.

If multiple keyed nodes exist as children of another node, they must have unique keys.
Column(direction: vertical, mainAxisAlignment: start, crossAxisAlignment: stretch) has multiple children with key [<'table'>].

**Comment by daohoangson** [comment]
This is a bug, I will release a new patch version soon to address it.

**Comment by daohoangson** [comment]
`v0.2.3+3` has been released with the fix for this. Please let me know if it works for you.

**Comment by SinanKanmaz** [comment]
This version worked very well for me. Thank you so much.

**Comment by daohoangson** [comment]
That's great. I'm closing this issue now.

/close
