### ISSUE TITLE
Prevent url tap to open in external browser, On Tap we should get Url and deal by our own way

### ISSUE THREAD

**Issue by dev-nestedpie** [daohoangson/flutter_widget_from_html#858]

**Comment by jlemanski1** [comment]
FYI Your comment is missing any text underneath the two headers you have.

You can use the `onTapUrl` property of the HtmlWidget to handle any urls however you'd like. I've used it to launch urls using InAppWebView, the browser, block certain urls, etc.
This feature already exists.

**Comment by putrautama007** [comment]
you can set `return true ` on `onTapUrl` 
```
onTapUrl: (url) {
<this is your own handling>
return true;
}
```
