### ISSUE TITLE
Add support to get Url without navigating to brower

### ISSUE THREAD

**Issue by dev-nestedpie** [daohoangson/flutter_widget_from_html#859]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by dev-nestedpie** [comment]
https://www.loom.com/share/f332b8ebba6a4672b37cf609e48b3069

**Comment by daohoangson** [comment]
Duplicated of #858.
