### ISSUE TITLE
[fwfh_svg] Update `flutter_svg` to 2.0.0

### ISSUE THREAD

**Issue by Skyost** [daohoangson/flutter_widget_from_html#863]
`flutter_svg` has recently released its 2.0.0 version. I've embedded [an updated version of `fwfh_svg`](https://github.com/Skyost/EscapeGameKit/tree/master/lib/src/utils/fwfh_svg) into my `EscapeGameKit` project. Feel free to use it to upgrade `fwfh_svg`.

**Comment by daohoangson** [comment]
This looks nice, thank you!

**Comment by daohoangson** [comment]
`v0.10.0` has been released with support for `flutter_svg@2`.
