### ISSUE TITLE
the cursor shape does not appear correct when wrapping with a SelectionArea

### ISSUE THREAD

**Issue by pndaza** [daohoangson/flutter_widget_from_html#874]
When wrapping HtmlWidget with a SelectionArea, the cursor shape does not appear correct. 

## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<p>some text</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
SelectionArea(
  child: HtmlWidget(html),
)
```
</details>

<details>
  <summary>Testing environment</summary>

macOS Monterey

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 12.5.1 21G83 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
```
</details>

## Expected results

I-Beam cursor
## Actual results
Arrow cursor

**Comment by daohoangson** [comment]
Do you have a screenshot of the incorrect cursor?

**Comment by pndaza** [comment]
![IMG_20230304_234804.jpg](https://user-images.githubusercontent.com/37981688/222919784-d30442af-fb0f-42dc-b16b-34106bf8d710.jpg)

Actual result

**Comment by pndaza** [comment]
![IMG_20230304_234650.jpg](https://user-images.githubusercontent.com/37981688/222919827-d0a087e5-b5d9-46d7-8547-b002a8283498.jpg)

expected results

**Comment by pndaza** [comment]
I can get correct cursor by overriding WidgetFactory's buildText method.

```dart
class CustomFactory extends WidgetFactory {
  @override
  Widget? buildText(BuildMetadata meta, TextStyleHtml tsh, InlineSpan text) {
    if (meta.overflow == TextOverflow.clip && text is TextSpan) {
      return Text.rich(
        text,
        style: tsh.style,
        maxLines: meta.maxLines > 0 ? meta.maxLines : null,
        textAlign: tsh.textAlign ?? TextAlign.start,
        textDirection: tsh.textDirection,
      );
    }
    return super.buildText(meta, tsh, text);
  }
}
```

**Comment by daohoangson** [comment]
Ah, I see. With the incorrect cursor, does selection / multi selection still work?

**Comment by pndaza** [comment]
Yes. Selection/Multi-Selection works regardless of the cursor's shape.

**Comment by daohoangson** [comment]
`v0.11.0-alpha.2` has been released with the fix for this. Please try upgrading and let me know if it works for you.

**Comment by pndaza** [comment]
Thanks. Now cursor is shown correctly.

**Comment by daohoangson** [comment]
FYI, the latest stable (`v0.14.2`) has been released with the fix for incorrect cursor inside `SelectionArea`.
