### ISSUE TITLE
How to update the css dynamically?

### ISSUE THREAD

**Issue by BadPistol97** [daohoangson/flutter_widget_from_html#878]
I want to render HTML and allow font size to be changed dynamically by user event. I use a consumer widget for this and `ref.watch` the state of font size value. But every time I change the value it doesn't  affect the rendered HTML. 

```
@override
  Widget build(BuildContext context) {

    double fontSize = ref.watch(fontSizeProvider);

    print('hello');

    return HtmlWidget(
        '${widget.content.values.first[0]}',
      customStylesBuilder: (e) {

          print('hi');

        return {
          'margin': '0px',
          'font-size':'${fontSize}px',
        };

      },
    );
  }
```
I can see `hello` printed every time I update the font size value but not the `hi`. 

How do I achieve this?

**Comment by daohoangson** [comment]
The `HtmlWidget` has caching enabled by default so it won't rebuild if the HTML is unchanged. Using rebuild triggers should help in your situation. Something like this:

```dart
return HtmlWidget(
    'html',
    customStylesBuilder: (e) { ... },
    rebuildTriggers: RebuildTriggers([
        // put your own dependencies here
        fontSize,
    ]),
);
```

https://try.fwfh.dev/?id=5a440a2a34a3056be40d45d25e04411f
