### ISSUE TITLE
Nested Details in a Table

### ISSUE THREAD

**Issue by bksubhuti** [daohoangson/flutter_widget_from_html#886]
Can you support nested details?

Example below works on w3schools tryit editor but not our app:
I just assume it is not supported.

We only need to go 1 nested level deep but inside a table.
We need to have the items "clickable"
We support all 5OS and we have nearly 2000 on Android alone as a free noncommercial app.
(We are still waiting for clickable and formatting styles at the same time).

![image](https://user-images.githubusercontent.com/18184280/236684412-f897f0c8-c571-408c-9f4f-3c5e00dfee11.png)

<p>
  <div>
    <details>
      <summary><b>purisa 1</b>: masc. <b>man; person</b></summary>
      <table>
        <tr>
          <th valign="top">Pāḷi</th>
          <td>puriso</td>
        </tr>
        <tr>
          <th valign="top">Grammar</th>
          <td>masc</td>
        </tr>
        <tr>
          <th valign="top">Meaning</th>
          <td><b>man; person</b>.</td>
        </tr>
        <tr>
          <th valign="top">Sanskrit</th>
          <td>puruṣa</td>
        </tr>
        <tr>
          <th valign="top">Compounds</th>
          <td>
            <details>
              <summary>compounds</summary>
              <ul>
                <li>aṭṭhapurisabhūmiyo</li>
                <li>aḍḍhaporisa (adj)</li>
                <li>appapurisa (adj)</li>
                <li>amanussapurisa</li>
                <li>ambho purisa</li>
                <li>asappurisa</li>
              </ul>
            </details>
          </td>
        </tr>
        <tr>
          <th valign="top">Word Family</th>
          <td>
            <details>
              <summary>word family</summary>
              <ul>
                <li>nippurisa</li>
                <li>purisa 1</li>
                <li>purisa 2</li>
                <li>purisa 3</li>
                <li>purisaka 1</li>
                <li>purisaka 2</li>
              </ul>
            </details>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSf9boBe7k5tCwq7LdWgBHHGIPVc4ROO5yjVDo1X5LDAxkmGWQ/viewform?usp=pp_url&entry.438735500=purisa%201&entry.1433863141=TPR%202023-05-04" target="_blank">Submit a correction</a>
          </td>
        </tr>
      </table>
    </details>
  </div>
</p>

```

<p>
  <div>
    <details>
      <summary><b>purisa 1</b>: masc. <b>man; person</b></summary>
      <table>
        <tr>
          <th valign="top">Pāḷi</th>
          <td>puriso</td>
        </tr>
        <tr>
          <th valign="top">Grammar</th>
          <td>masc</td>
        </tr>
        <tr>
          <th valign="top">Meaning</th>
          <td><b>man; person</b>.</td>
        </tr>
        <tr>
          <th valign="top">Sanskrit</th>
          <td>puruṣa</td>
        </tr>
        <tr>
          <th valign="top">Compounds</th>
          <td>
            <details>
              <summary>compounds</summary>
              <ul>
                <li>aṭṭhapurisabhūmiyo</li>
                <li>aḍḍhaporisa (adj)</li>
                <li>appapurisa (adj)</li>
                <li>amanussapurisa</li>
                <li>ambho purisa</li>
                <li>asappurisa</li>
              </ul>
            </details>
          </td>
        </tr>
        <tr>
          <th valign="top">Word Family</th>
          <td>
            <details>
              <summary>word family</summary>
              <ul>
                <li>nippurisa</li>
                <li>purisa 1</li>
                <li>purisa 2</li>
                <li>purisa 3</li>
                <li>purisaka 1</li>
                <li>purisaka 2</li>
              </ul>
            </details>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSf9boBe7k5tCwq7LdWgBHHGIPVc4ROO5yjVDo1X5LDAxkmGWQ/viewform?usp=pp_url&entry.438735500=purisa%201&entry.1433863141=TPR%202023-05-04" target="_blank">Submit a correction</a>
          </td>
        </tr>
      </table>
    </details>
  </div>
</p>

```

**Comment by bksubhuti** [comment]
If there is a quick way to make this work by modifying the HTML Please let us know .

**Comment by daohoangson** [comment]
Web playground https://try.fwfh.dev/?id=b3baa076757afe92e9685e8be3e343fd also works.

<img width="1499" alt="Screen Shot 2023-05-11 at 17 45 45" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/29eb43c3-7cf0-423c-b189-727fda50778f">

**Comment by bksubhuti** [comment]
I believe you.. however, I get an error and cannot run from this link  you gave me.
![image](https://github.com/daohoangson/flutter_widget_from_html/assets/18184280/915ff095-d169-4f13-86e6-0e733a1a1a37)

The whole entry is not showing.. perhaps I can show you the entire code.

**Comment by bksubhuti** [comment]
okay.. now it seems to work.
Before the modified html was not showing up.

I will close the issue.  (but still waiting for clickable with formatting)

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/18184280/0ba35957-1504-49dd-8543-ce72ad604ab4)
