### ISSUE TITLE
Table not rendered properly

### ISSUE THREAD

**Issue by Vinoth1094** [daohoangson/flutter_widget_from_html#89]
Hi,
    We are having some issues in rendering Tables and list(Letters and Bullet point lists).        
    We've attached sample HTML string which is rendered incorrectly with this along with the screenshot of the mobile with the table rendered incorrectly and the expected correct output screenshot taken from the web.
    Please let us know if you can help us resolve the issue.

[flutter_widget_from_html_Rendering_Issue.txt](https://github.com/daohoangson/flutter_widget_from_html/files/3665365/flutter_widget_from_html_Rendering_Issue.txt)
<img width="535" alt="Screenshot 2019-09-27 at 8 47 11 PM" src="https://user-images.githubusercontent.com/19289848/65815412-c12dcd00-e20c-11e9-8482-47504905d89c.png">
<img width="576" alt="Screenshot 2019-09-27 at 8 47 46 PM" src="https://user-images.githubusercontent.com/19289848/65815414-c428bd80-e20c-11e9-8f06-e19fa1d7a0fd.png">

**Comment by daohoangson** [comment]
I have created a new Flutter app and updated `main.dart` to this: https://gist.github.com/daohoangson/ac391ae13aa5d53c293687cbc83db0bb. It seems to work fine:

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-28 at 21 28 37](https://user-images.githubusercontent.com/239336/65817949-11218980-e237-11e9-8d35-ada7c1f14b47.png)

Can you share how you configured the `HtmlWidget` in your app?

**Comment by daohoangson** [comment]
As mentioned here https://gist.github.com/daohoangson/ac391ae13aa5d53c293687cbc83db0bb#gistcomment-3039982

> Seems like upgrading the plugin version worked like charm.

I'm closing this issue. I have also created a new issue for your other suggestion (https://github.com/daohoangson/flutter_widget_from_html/issues/90).

**Comment by Khawlah-Mohammed** [comment]
An asymptotic problem in version 0.5.1+5 


![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-23 at 22 14 46](https://user-images.githubusercontent.com/16141396/103031074-330ad880-456e-11eb-833d-d5bf03cb5bdb.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-23 at 22 19 42](https://user-images.githubusercontent.com/16141396/103031102-3c944080-456e-11eb-83e8-1dbb9a02fba2.png)
