### ISSUE TITLE
Deploy for flutter 3.10

### ISSUE THREAD

**Issue by nimr77** [daohoangson/flutter_widget_from_html#891]
there is an issue with the build on flutter 3.10

Error (Xcode): ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
chewie_player.dart:144
Could not build the application for the simulator.
Error launching application on iPhone 14 Plus.

this is the flutter doctor
``` console
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by daohoangson** [comment]
Which version of this package are you using? You should be able to tell pubspec to use chewie 1.4 directly too.

**Comment by nimr77** [comment]
the latest on dart pub,
I even used the GitHub repo to install the package and it still same error
here 

  flutter_widget_from_html: ^0.10.0
  
  and I changed to:
    flutter_widget_from_html:
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html.git
      path: packages/enhanced
      
same error

**Comment by daohoangson** [comment]
Using 0.10 should be fine. Try specifying `chewie: ^1.4.0` too maybe?

**Comment by nimr77** [comment]
Thanks for replying, but where to add  to specifying

**Comment by nimr77** [comment]
does the issue from share_plus

**Comment by daohoangson** [comment]
The `flutter_widget_from_html` package supports up to `chewie@1.4` but your app cannot use that yet. The maximum version of chewie that is compatible with your version of share_plus is `chewie@1.0` so it has to use that one. You will need to ask wakelock package developer to bump their win32 dependency. Doing that may be hard though, another option is to use dependency override if you don't care about Windows support.

**Comment by nimr77** [comment]
I think I will do it myself and update the package, Thanks this will save me time

**Comment by marcuscorreasmash** [comment]
same problem here in flutter 3.10 

> não, eu tenho isso
> 
> ```
> Because no versions of share_plus match >7.0.0 <8.0.0 and share_plus 7.0.0 depends on win32 ^4.0.0, share_plus ^7.0.0 requires win32 ^4.0.0.
> Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows requires win32 ^2.0.0 or ^3.0.0.
> Thus, share_plus ^7.0.0 is incompatible with wakelock_windows.
> And because chewie >=1.3.5 depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, share_plus ^7.0.0 is incompatible with chewie >=1.3.5.
> So, because ticket depends on both chewie ^1.4.0 and share_plus ^7.0.0, version solving failed.
> exit code 1
> ```

**Comment by marcuscorreasmash** [comment]
> Resolving dependencies...
Because chewie >=1.3.5 depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, chewie >=1.3.5 requires wakelock_windows ^0.2.0.
Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows requires win32 ^2.0.0 or ^3.0.0.
Thus, chewie >=1.3.5 requires win32 ^2.0.0 or ^3.0.0.
And because file_picker 5.3.0 depends on win32 ^4.1.3, chewie >=1.3.5 is incompatible with file_picker 5.3.0.
So, because smash_shop depends on both file_picker 5.3.0 and chewie ^1.5.0, version solving failed.
exit code 1

**Comment by daohoangson** [comment]
If you don't use VIDEO in your HTML, you can switch to `flutter_widget_from_html_core` which is faster and doesn't pull in `chewie` as a dependency.

If you do need VIDEO tags, downgrading `share_plus` to version 6.0.0 should work.

**Comment by KabaDH** [comment]
> 

Thanks a lot! It works.

**Comment by marcuscorreasmash** [comment]
one of the solutions I got was to add the packages:

chewie: ^1.5.0
wakelock: ^0.6.2
wakelock_windows: ^0.2.1

and 

dependency_overrides:  
  win32: ^5.0.0

maybe dont the better solution, but until the package refresh to dart 3.0 and flutter 3.10
