### ISSUE TITLE
chewie player giving 

### ISSUE THREAD

**Issue by efazalk** [daohoangson/flutter_widget_from_html#898]
## Steps to Reproduce

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/27408112/977ca438-5073-416d-a2a8-c053a57b6f88)

<details>
  <summary>I am running the app on iPhone simulator and getting  this error 
**"Error (Xcode): ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'."**
on android was working fine when flutter version was 3.0.5 but when i upgraded to flutter 3.1.0 I keep getting this error while trying to run the app.
Can you please guide me through the issue.
Best Regards
</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by daohoangson** [comment]
For some reason pub is using `chewie@1.0` which is very old. Try adding `chewie: ^1.5.0` in your pubspec to see what is preventing pub from using the latest version.

**Comment by soanpr123** [comment]
Gặp lỗi tương tự với flutter  3.10.0 @daohoangson

**Comment by daohoangson** [comment]
Mình trả lời bên #900 rồi nha @soanpr123, trao đổi tiếp bên đó nha.

**Comment by jstdk** [comment]
This worked for me. Flutter kept looking for chewie 1.0. Nothing worked (cache repairs etc). Hardcoding it in the dependencies did the trick. Nevertheless, 'flutter pub deps' keeps saying that the package depends on chewie 1.0

**Comment by daohoangson** [comment]
Did you put it under normal dependency or override? @jstdk

**Comment by jstdk** [comment]
@daohoangson, normal

**Comment by daohoangson** [comment]
That's weird.

**Comment by daohoangson** [comment]
Since it's working in your app, I'm closing this issue for now.

**Comment by jstdk** [comment]
@daohoangson, sorry for late response. Yes, please close, I am pretty sure it is something on my side, weird stuff happening since the upgrade.
