### ISSUE TITLE
chewie version 1.0.0 on flutter 3.10.0

### ISSUE THREAD

**Issue by soanpr123** [daohoangson/flutter_widget_from_html#900]
I am getting this error when updating SDK to 3.10.0

![Ảnh màn hình 2023-05-18 lúc 08 53 38](https://github.com/daohoangson/flutter_widget_from_html/assets/44558413/a74b2f10-902a-4b95-9ce3-7d33af4ec6dc)

**Comment by soanpr123** [comment]
![Ảnh màn hình 2023-05-18 lúc 09 11 07](https://github.com/daohoangson/flutter_widget_from_html/assets/44558413/0c4ce66b-46f0-4e22-933c-bfe9747d18b8)

Thêm chewie 1.5.0 vào thì đang gặp vấn đề này cậu ạ

**Comment by soanpr123** [comment]
có vẻ đã được rồi sau khi thêm chewie: ^1.5.0 và sửa lại 1 số xung đột lib thì nó hoạt động bình thường rồi

**Comment by daohoangson** [comment]
Nó bị đụng với lib `shared` của bạn. Cái `chewie` mới nó cần win32 v2 hoặc v3 mà cái shared thì cần win32 v4.

- Nếu app của bạn không định build cho Windows thì bạn override cái dependency win32 để force nó lên v4 là được.
- Còn nếu bạn target cả Windows thì follow PR này https://github.com/creativecreatorormaybenot/wakelock/pull/203. Cơ bản là cũng override dependency hoặc đợi fork ra wakelock2.

**Comment by daohoangson** [comment]
Xử lý được rồi nên mình đóng nha.
