### ISSUE TITLE
A borderRadius can only be given for a uniform Border.

### ISSUE THREAD

**Issue by rslz** [daohoangson/flutter_widget_from_html#909]
<details>
  <summary>HTML</summary>

html source ： https://mw-hkt.oss-accelerate.aliyuncs.com/good/detail/fd54721d0227dc2ec7e2250e8c9778f7/55714.html

</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

      HtmlWidget(
        html,
      );
</details>

<details>
  <summary>Tesing environment</summary>

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.3.1 22E261 darwin-x64, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

</details>

## Actual results

flutter: ====error==== A borderRadius can only be given for a uniform Border.
The following is not uniform:
BorderSide.color
BorderSide.style
flutter: ====stack==== #0 Border.paint. (package:flutter/src/painting/box_border.dart:550:9)
#1 Border.paint (package:flutter/src/painting/box_border.dart:560:6)
#2 _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:499:25)
#3 RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2363:17)
#4 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#5 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#6 RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#7 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#8 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#9 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#10 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#11 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#12 RenderParagraph.paint. (package:flutter/src/rendering/paragraph.dart:934:19)
#13 PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:474:12)
#14 PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:667:7)
#15 RenderParagraph.paint (package:flutter/src/rendering/paragraph.dart:929:15)
#16 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#17 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#18 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#19 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#20 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#21 RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#22 RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
#23 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#24 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#25 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#26 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#27 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#28 _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:547:17)
#29 _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:561:9)
#30 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#31 PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#32 PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#33 PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1137:31)
#34 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#35 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#36 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#37 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#38 _rootRun (dart:async/zone.dart:1398:13)
#39 _CustomZone.run (dart:async/zone.dart:1300:19)
#40 _CustomZone.runGuarded (dart:async/zone.dart:1208:7)

**Comment by daohoangson** [comment]
Because of the limitation of Flutter's border decoration, I will remove border radius if the border is not uniform. Working on this at #910.

I also found the package https://pub.dev/packages/non_uniform_border, will see whether it can be included.

**Comment by rslz** [comment]
Thanks for support.

**Comment by rslz** [comment]
When will v0.11.0-alpha.2 be released?  @daohoangson
