### ISSUE TITLE
Table right part cut off

### ISSUE THREAD

**Issue by dinhan92** [daohoangson/flutter_widget_from_html#921]
![image](https://github.com/daohoangson/flutter_widget_from_html/assets/86275789/d6cfac55-a29e-4d04-bf48-bcc548f55c52)
I use flutter_widget_from_html_core 0.10.1 and the right part of my table seem to be cut off, how to fix it? My table is generated by ckeditor of a react app, and I also want the table to algin center, how to do it?
Anh ơi, e dùng flutter_widget_from_html_core 0.10.1, phần bên phải bảng của em bị mất, làm sao sửa ak? Bảng của e tạo bởi cái ckeditor của react ak, với cả e muốn table vào giữa, làm thế nào ạ?

**Comment by daohoangson** [comment]
Bạn share `HTML` đang render với code build `HtmlWidget` để mình coi thử nha.

**Comment by dinhan92** [comment]
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Phân bón: Lượng phân tổng số tính cho 1 ha/vụ:</span></p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Phân chuồng hoai: 25-30m<sup>3</sup>; phân hữu cơ vi sinh: 1.000kg; vôi bột: 800-1.000kg, tùy theo pH đất canh tác;</span></p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">- Phân vô cơ lượng nguyên chất: 140kg N - 85kg P<sub>2</sub>O<sub>5</sub>&nbsp;- 180kg K<sub>2</sub>O.</span></p>
<p style="text-align: justify;">
    <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><u>Lưu ý:</u>&nbsp;Chuyển lượng phân hóa học nguyên chất qua phân đơn hoặc NPK tương đương:</span>
</p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Cách 1: Ure: 304kg; Super lân: 531kg; KCl: 300kg.</span></p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Cách 2: NPK 15-5-20: 900 kg; Ure: 11kg; Super lân: 250kg.</span></p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Bón theo cách 1:</span></p>
<figure class="table">
    <table>
        <tbody>
            <tr>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Hạng mục</strong></span>
                    </p>
                </td>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Tổng số</strong></span>
                    </p>
                </td>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Bón lót</strong></span>
                    </p>
                </td>
                <td colspan="3">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Bón thúc</strong></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 1</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>10 NST</strong></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 2</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>25 NST</strong></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 3</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>45 NST</strong></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Phân chuồng hoai</span></p>
                </td>
                <td>
                    <p style="text-align: right;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">25-30 m<sup>3</sup></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: right;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">25-30 m<sup>3</sup></span>
                    </p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Vôi bột</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">800 - 1000 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">800 - 1000kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Hữu cơ vi sinh</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">1.000 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">1.000 kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Ure</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">304 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">104 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">40 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">70 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">90 kg</span></p>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Super lân</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">531 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">400 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">131</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">KCl</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">300 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">120 kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">60 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">120 kg</span></p>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Bón theo cách 2:</span></p>
<figure class="table">
    <table>
        <tbody>
            <tr>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Hạng mục</strong></span>
                    </p>
                </td>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Tổng số</strong></span>
                    </p>
                </td>
                <td rowspan="2">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Bón lót</strong></span>
                    </p>
                </td>
                <td colspan="3">
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Bón thúc</strong></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 1</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>10 NST</strong></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 2</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>25 NST</strong></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>Lần 3</strong></span>
                    </p>
                    <p style="text-align: center;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;"><strong>45 NST</strong></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Phân chuồng hoai</span></p>
                </td>
                <td>
                    <p style="text-align: right;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">30-40 m<sup>3</sup></span>
                    </p>
                </td>
                <td>
                    <p style="text-align: right;">
                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">30-40 m<sup>3</sup></span>
                    </p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Vôi bột</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">800 - 1000 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">800 - 1000kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Hữu cơ vi sinh</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">300 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">300 kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Ure</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">11 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">11 kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Super lân</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">250 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">250 kg</span></p>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">NPK 15-5-20</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">900 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">250 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">50 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">250 kg</span></p>
                </td>
                <td>
                    <p style="text-align: right;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">350 kg</span></p>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
<p style="text-align: justify;">
    <span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">*&nbsp;<i>Ghi chú</i>:<strong>&nbsp;</strong>Phân bón lá sử dụng theo khuyến cáo in trên bao bì.</span>
</p>
<p style="text-align: justify;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Chỉ sử dụng các loại phân bón có tên trong Danh mục phân bón được phép sản xuất, kinh doanh và sử dụng tại Việt Nam.</span></p>
Đây a ơi

**Comment by daohoangson** [comment]
Với table rộng như thế này bạn có thể nhét nó vào trong scroll view thử.

```dart
class MyWidgetFactory extends WidgetFactory {
  @override
  void parse(BuildMetadata meta) {
    final e = meta.element;
    if (e.localName == 'figure' && e.classes.contains('table')) {
      meta.register(
        BuildOp(
          onWidgets: (meta, widgets) {
            final column = buildColumnPlaceholder(meta, widgets)?.wrapWith(
              (context, child) => buildHorizontalScrollView(meta, child),
            );
            return listOrNull(column);
          },
        ),
      );
    } else {
      super.parse(meta);
    }
  }
}
```

**Comment by dinhan92** [comment]
A ơi, WidgetFactory chỉ có ở flutter_widget_from_html thôi ạ? core ko có ạ?

**Comment by dinhan92** [comment]
var myWidgetHTML = MyWidgetHTML();
  dom.Document document = parser.parse(data);
  BuildMetadata meta = BuildMetadata(element: document.documentElement);
  
A ơi, làm sao có được BuildMetadata nhy? E làm như thế này cứ bị lỗi Abstract class can not be initiated

**Comment by daohoangson** [comment]
Tự parse ở ngoài chắc không được nha bạn. Nó cần nhiều internal implementation.

**Comment by daohoangson** [comment]
Bạn implement cái `WidgetFactory` như trên rồi kêu `HtmlWidget` nó xài kiểu này nhé.

```dart
                  HtmlWidget(
                    html,
                    factoryBuilder: () => MyWidgetFactory(),
                  ),
```

**Comment by dinhan92** [comment]
Oạch, vậy ạ, hix cám ơn a nhé, e hỏi ChatGpt nó ra cái gì ko à hix. Cám ơn a nhiều nhé :D

**Comment by daohoangson** [comment]
Hỏi ChatGPT lun hả, ghê vại 🤣

**Comment by dinhan92** [comment]
Kém phải hỏi chứ a, có mấy cái cơ sở nó vẫn trả lời được :))
