### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### ISSUE THREAD

**Issue by Anoopjhn** [daohoangson/flutter_widget_from_html#926]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by daohoangson** [comment]
What is your Flutter version? Looks like an issue with chewie / wakelock?

**Comment by Anoopjhn** [comment]
> What is your Flutter version? Looks like an issue with chewie / wakelock?

3.10.1, yes both have issues

**Comment by daohoangson** [comment]
Your `pub get` probably picked an old chewie version. You can add `chewie: ^1.5.0` in your pubspec to request the latest one. It should work if there is no conflict with other dependencies in your app.

**Comment by varunlohade** [comment]
got the same issue 



FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by daohoangson** [comment]
Have you tried adding `chewie: ^1.5.0` to your app's pubspec file?

**Comment by varunlohade** [comment]
Hey @daohoangson I have fixed the issue and raised a pull request for the same

link to the pull request for the same. 
for anyone facing the same issue just add 

```
dependency_overrides:
  win32: 3.1.4
```
 
 to your pubspec.yaml
 the issue is caused by wakelock dependency and this seems to work

**Comment by daohoangson** [comment]
I think you can choose to use ***@***.*** or override win32. Both fixes are
valid.
