### ISSUE TITLE
Snippet not working in newest version

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [daohoangson/flutter_widget_from_html#93]

**Comment by daohoangson** [comment]
In recent versions, the `buildImageFromUrl` method signature have changed. The sample code must be updated to something like this:

```dart
  @override
  ImageProvider buildImageFromUrl(String url) =>
      url?.isNotEmpty == true ? NetworkImage(url) : null;
```

Sorry for the inconvenience. This plugin is still under active development and its API may change quite a bit, should be more stable when it reaches `v1.0.0`.

**Comment by aleksandar-radivojevic** [comment]
It's working, your plugin is great, keep up the good work.. :D

**Comment by daohoangson** [comment]
Thank you for the kind words 😁

Since the issue has been resolved, I'm closing it now.
