### ISSUE TITLE
Error: Type 'ChewieFactory' not found.

### ISSUE THREAD

**Issue by khuhro-majid** [daohoangson/flutter_widget_from_html#932]
flutter_widget_from_html: ^0.10.1

CODE:
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

HtmlWidget('''
                        <iframe type="text/html" width="640" height="360"
                        src="https://www.youtube.com/embed/$videoId?autoplay=1"
                        frameborder="0"></iframe>
                    ''');

### Error: Error when reading '../../../../.pub-cache/hosted/pub.dev/fwfh_chewie-0.7.1+2/lib/fwfh_chewie.dart': No such file or directory
flutter_widget_from_html-0.10.1/lib/src/widget_factory.dart:14:9: Error: Type 'ChewieFactory' not found. ChewieFactory 

<img width="1328" alt="Screenshot 2023-06-05 at 1 13 44 AM" src="https://github.com/daohoangson/flutter_widget_from_html/assets/82215384/f7a411eb-9b87-43a8-88b7-0ec91b38bee4">

I am facing this issue, Need to sort out urgent basis. Can anyone please guide/help me to resolve this. using flutter_widget_from_html: ^0.10.1

Details:
**Flutter 3.10.3 • channel stable**
**Tools • Dart 3.0.3 • DevTools 2.23.1**
**Android Studio IDE** Macbook with m1
**flutter_widget_from_html: ^0.10.1**

@daohoangson @renovate-bot @DFelten

**Comment by daohoangson** [comment]
Try `flutter clean` and `flutter pub get` again. For some reason the dependency directory is missing?

**Comment by khuhro-majid** [comment]
> dependency directory

Yes. Already did many times still no luck.

**Comment by daohoangson** [comment]
Have you tried deleting the `pubspec.lock` file?

**Comment by khuhro-majid** [comment]
> Have you tried deleting the `pubspec.lock` file?

Not yet. is it required?

**Comment by daohoangson** [comment]
It's worth trying.
