### ISSUE TITLE
Style white-space: nowrap not working

### ISSUE THREAD

**Issue by sonuPrasas010** [daohoangson/flutter_widget_from_html#939]
## Steps to Reproduce

<details>

```
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

**Comment by daohoangson** [comment]
Can you provide some details?

**Comment by sonuPrasas010** [comment]
the widget is :<p style="line-height: 1.2;">For any two real numbers x and y, prove that: <span style="white-space:nowrap">|x + y| ≤ |x| + |y|.</span></p>

it behaves fine in a browser like, when the elelment does not fit in on line it automatically goes to  a new line:
Web screenshot ![image](https://github.com/daohoangson/flutter_widget_from_html/assets/64410209/535c03b4-d575-4b73-bcd9-7e33567e1d8a)
but it mobile it does not work 
mobile screenshot: ![image](https://github.com/daohoangson/flutter_widget_from_html/assets/64410209/0b2ab2ca-947a-4b6b-9963-b4d19da1756f)

**Comment by daohoangson** [comment]
Which version of this package are you using?

**Comment by sonuPrasas010** [comment]
flutter_widget_from_html: ^0.10.1

**Comment by daohoangson** [comment]
This is expected, v0.10 only supports `white-space: normal/pre`.

**Comment by daohoangson** [comment]
FYI, the latest stable (`v0.14.2`) has been released with the fix for no wrap `white-space`.

**Comment by sonuPrasas010** [comment]
Thanks
