### ISSUE TITLE
Loading this html will crash

### ISSUE THREAD

**Issue by YinRenjie1993** [daohoangson/flutter_widget_from_html#94]
url is https://www.cnblogs.com/haha12/p/11652038.html
Use http to request the html of this address, loading with HtmlWidget will crash
![image](https://user-images.githubusercontent.com/11569655/66628705-2bde0000-ec32-11e9-922a-7e44b14f08b3.png)

**Comment by daohoangson** [comment]
A new patch version has been released (`v0.2.3+4`), please upgrade and try again. It contains a fix for your issue.

**Comment by YinRenjie1993** [comment]
thanks
