### ISSUE TITLE
`chewie-1.0.0` causes a crush during launch on Flutter 3.10.x

### ISSUE THREAD

**Issue by muknta** [daohoangson/flutter_widget_from_html#945]
## Steps to Reproduce

- upgrade Flutter to 3.10.x
- try to launch with the last version of `flutter_widget_from_html` dependency (0.13.0-alpha.1)

Need to upgrade `chewie` dependency in the package (`1.5.0` version supports Dart 3.0.x).

## Expected results

App with the dependency successfully launched within Flutter 3.10.x

## Actual results

During attempt to launch an app the error appears caused by `chewie-1.0.0`
```
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.

Could not build the application for the simulator.
```

**Comment by daohoangson** [comment]
Have you tried adding `chewie: ^1.5.0` to your pubspec?

**Comment by daohoangson** [comment]
No I meant trying to add that into your app's. This package aims to support the widest range of dependency so it supports Flutter 3.7 & chewie 1.0. Some people are still stuck in older Flutter version and that's OK.

If you app targets Flutter 3.10 and you want to use chewie 1.5, this package doesn't prevent you from doing that. It supports all versions from 1.1 to 1.999. Just add `chewie: ^1.5.0` directly to your app's pubspec.

**Comment by muknta** [comment]
I have checked, `chewie: ^1.5.0` also works for `flutter 3.7`, but `chewie: ^1.0.0` doesn't work for `flutter 3.10`.

Your suggestion about explicitly set `chewie: ^1.5.0` in my package for `flutter 3.10` works also. But I don't think this is the solution

**Comment by muknta** [comment]
@daohoangson, please, take a look at the previous comment. 
`chewie: ^1.5.0` version works for `flutter 3.7+`

**Comment by daohoangson** [comment]
My point is: you can specify any chewie version in your app pubspec (1.0 or 1.5 or the latest 1.7). This package accepts anything in the 1.x range so it won't prevent you from doing that.
