### ISSUE TITLE
Not loading the External css & Jquery Libraries 

### ISSUE THREAD

**Issue by govindh163** [daohoangson/flutter_widget_from_html#946]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

  var kHtml=r"""
 <!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>PayWeb :: Some CompanyPty Ltd</title>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="css/core.css">
	<link rel="stylesheet" type="text/css" href="css/fontawesome-all.min.css">
    <link type="text/css" rel="stylesheet" href="css/lottie-loader.css">
	<script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/jquery.maskedinput-1.4.min.js"></script>
	<script type="text/javascript" src="js/lang/en.js" charset="UTF-8"></script>
	<script type="text/javascript" src="js/confirmOnClose.js" charset="UTF-8"></script>
	<script type="text/javascript" src="js/trans.min.js" charset="UTF-8"></script>
	<script type="text/javascript" src="js/Attachable_Components.min.js"></script>
    <script type="text/javascript" src="js/applepay.min.js" charset="UTF-8"></script>
    <script type="text/javascript" src="js/lottie-player.js"></script>
	<style type="text/css">
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 14px !important;
        color: #333 !important;
        font-weight: normal !important;
	</style>
    <style type="text/css">
        body{font-family:Verdana,Arial,sans-serif !important;font-size:12px !important;color:#000000 !important;font-weight:normal !important;}
.Container{min-width:200px !important;}
.Label{font-weight:bold !important;}
input{font-weight:normal !important;}
select{font-weight:normal !important;}
.Button{font-weight:normal;}
.Button:hover{font-weight:normal;}
.Button:active{font-weight:normal;}
.Top{display: none !important;}
.Bottom{display: none !important;}
option{}
    </style>
	<script type="text/javascript">
        $(document).ready(function () {
            $(".lottie-wrapper").fadeOut();
                        $('#fTrans').css({'visibility': 'visible'});        });
    </script>
</head>
<body>
<div class="lottie-wrapper">
    <div class="lottie-loader">
        <lottie-player src="misc/lootie.json" background="transparent"  speed="1" loop autoplay></lottie-player>
        <div class="lottie-message">
            Loading...
        </div>
    </div>
</div>
<div align="center" class="noIframeWarning container" id="loaderCenter"  style="padding-top: 15px; display: none">
    <p align="center"><i class="fa fa-2x fa-spinner fa-spin"></i></p>
    <p align="center">Processing, please wait.</p>
    <p><strong>Warning:</strong> <span>Do not click the refresh or back button or this transaction may be interrupted or terminated.</span></p>
</div>
<div align="center" class="noscript"><noscript><div class="scriptError">Please note : this page requires that JavaScript is enabled.<br />Please enable JavaScript before proceeding with your payment.</div></noscript></div>
<div class="container-fluid">
    <div class="Top"></div>
    <div class="row">
        <div class="col-md-3 Left"></div>
        <div class="col-md-6">
            <div class="Main">
            <form role="form" style="visibility: hidden" class="form-horizontal text-left" name="fTrans" id="fTrans" action="process.trans" method="post" novalidate>
                <div id="header">
                          <div class="header row">
                        <div class="col-xs-6 text-right text-nowrap">
                            <span class="Label">Merchant</span>
                        </div>
                        <div class="col-xs-6 text-left text-nowrap" >
                            <span>Some COmpany Pty Ltd</span>
                        </div>
                    </div>
                    <div class="header row">
                        <div class="col-xs-6 text-right text-nowrap">
                            <span class="Label">Reference</span>
                        </div>
                        <div class="col-xs-6 text-left text-nowrap" >
                            <span>1256920_1S8_LZQ7G73ZO2FRRRFF</span>
                        </div>
                    </div>
                    <div class="header row ">
                        <div class="col-xs-6 text-right text-nowrap">
                            <span class="Label">Transaction Date</span>
                        </div>
                        <div class="col-xs-6 text-left text-nowrap" >
                            <span>Thu, 15 Jun 2023</span><span class="hidden-xs hidden-sm"> 13:17:25 +0200</span>
                        </div>
                    </div>
                    <div class="header row">
                        <div class="col-xs-6 text-right text-nowrap">
                            <span class="Label">Amount</span>
                        </div>
                        <div class="col-xs-6 text-left text-nowrap" >
                            <span style="font-weight:bold;">R&nbsp;4.00&nbsp;(ZAR)</span>
                        </div>
                    </div>
                    <div id="ChType" align="center" style="display: none;">
                        <button type="button" id="changePMBtn" class="Button" onclick="ShowPM('ChangePM','2');" >Change Payment Type</button>
                        <br>
                        <br>
                    </div>
                </div>
                				<div class="row text-center" id="paymethodButtons">
                    <p style="padding-top: 8px">
                        <strong>Please select a payment type</strong>
                    </p>
                    <p style="margin-bottom: 15px;">
                        <button id="pmCreditcardBtn" type="button" class="Button btn-custom creditcard-btn " style="background: url(https://assets.paygate.co.za/payweb3/buttons/creditcard.png) no-repeat 50% 50% !important;" onclick="ShowPM('creditcard','2', 'test@test.com');" disabled>Card</button>
                    </p>                    <p style="margin-bottom: 15px;">
                        <button id="pmSidBtn" type="button" class="Button btn-custom sid-btn " style="background: url(https://assets.paygate.co.za/payweb3/buttons/sid.png) no-repeat 50% 50% !important;" onclick="ShowPM('sid','2', 'test@test.com');" disabled>SiD Secure EFT</button>
                    </p>				</div>
                <div id="paymethods">
                    					<div class="form-group initialHide" id="creditcard1">
                        <label for="ccName" class="control-label Label">Card Holder</label>
                        <div class="text-left has-feedback">
                            <input style="white-space: nowrap;" id="ccName" class="form-control Input" type="text" name="ccName" value="" placeholder="Enter your name" />
                            <span class="glyphicon form-control-feedback"></span>
                        </div>
                    </div>					<div class="form-group initialHide" id="creditcard2">
                        <label for="ccNumber" class="control-label Label">Card Number</label>
                        <div class="text-left has-feedback">                            <div class="input-group">
                                <input id="ccNumber" 
                                       class="form-control Input" 
                                       type="number" 
                                       name="ccNumber" 
                                       value="" 
                                       autocomplete="off" 
                                       placeholder="Enter Card number" 
                                       style="min-height: 34px;" />
								<span class="input-group-addon" style="padding: 0; min-width: 52px;">
									<div class="collapse card-type" id="card_visa">
										<img alt="Card Type" src="images/creditcards/visa.png">
									</div>
									<div class="collapse card-type" id="card_mastercard">
										<img alt="Card Type" src="images/creditcards/mastercard.png">
									</div>
									<div class="collapse card-type" id="card_amex">
										<img alt="Card Type" src="images/creditcards/amex.png">
									</div>
									<div class="collapse card-type" id="card_diners_club_international">
										<img alt="Card Type" src="images/creditcards/diners_club_international.png">
									</div>
									<div class="collapse card-type" id="card_diners_club_carte_blanche">
										<img alt="Card Type" src="images/creditcards/diners_club_carte_blanche.png">
									</div>
									<div class="collapse card-type" id="card_jcb">
										<img alt="Card Type" src="images/creditcards/jcb.png">
									</div>
									<div class="collapse card-type" id="card_astropay">
										<img alt="Card Type" src="images/creditcards/astropay.png">
									</div>
								</span>
							</div>
							<span class="glyphicon form-control-feedback" 
							      style="line-height: 34px; right: 67px; top: 3px">
							</span>
							<div class="collapse" id="acceptedMessage">
								<p class="help-block"><span class="text-danger" id="cardsAccepted"></span></p>
							</div>                        </div>
                    </div>					<div class="form-group initialHide" id="creditcard3">
                        <label for="ccExpDate" 
                               class="control-label Label"
                               style="width: 100%; text-align: left;">
                            Expiry Date
                        </label>
                        <div class="col-xs-6 col-sm-6 text-left has-feedback">							<select class="form-control Input" name="ccOpMonth" id="ccOpMonth">								<option value="01" >01</option>								<option value="02" >02</option>								<option value="03" >03</option>								<option value="04" >04</option>								<option value="05" >05</option>								<option value="06" >06</option>								<option value="07" >07</option>								<option value="08" >08</option>								<option value="09" >09</option>								<option value="10" >10</option>								<option value="11" >11</option>								<option value="12" >12</option>							</select>
                            <span class="glyphicon form-control-feedback"></span>
                        </div>
                        <div class="col-xs-6 col-sm-6 text-left has-feedback no-padding-right">
                            <select class="form-control Input" name="ccOpYear" id="ccOpYear">								<option value="2023" >2023</option>								<option value="2024" >2024</option>								<option value="2025" >2025</option>								<option value="2026" >2026</option>								<option value="2027" >2027</option>								<option value="2028" >2028</option>								<option value="2029" >2029</option>								<option value="2030" >2030</option>								<option value="2031" >2031</option>								<option value="2032" >2032</option>								<option value="2033" >2033</option>								<option value="2034" >2034</option>								<option value="2035" >2035</option>								<option value="2036" >2036</option>								<option value="2037" >2037</option>								<option value="2038" >2038</option>								<option value="2039" >2039</option>								<option value="2040" >2040</option>								<option value="2041" >2041</option>								<option value="2042" >2042</option>                            </select>
                            <span class="glyphicon form-control-feedback"></span>						</div>
                    </div>					<div class="form-group initialHide" id="creditcard4">
                        <label class="control-label Label" 
                               for="ccCvv"
                               style="width: 100%; text-align: left;">
                            CVV Digits
                        </label>
                        <div class="col-xs-10 col-sm-6 text-left has-feedback" style="white-space: nowrap;">
                            <input id="ccCvv" class="form-control Input" type="number" name="ccCvv" value="" autocomplete="off" />
                            <span class="glyphicon form-control-feedback"></span>
                        </div>
                        <div class="col-xs-1 col-sm-6 text-left">
                            <span class="help-block"><a href="#" title="Click here for more information on what CVV Digits are." data-toggle="modal" data-target="#CreditCardCvvInfo"><span style="font-size: 16px;" class="glyphicon glyphicon-question-sign"></span></a></span>
                        </div>
                    </div>					<div class="modal fade" id="CreditCardCvvInfo" tabindex="-1" role="dialog" aria-labelledby="Credit Card CVV Info" aria-hidden="true" style="z-index: 1080;">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                    <h4 class="modal-title" id="myModalLabel">What is the CVV Number ? </h4>
                                    <span class="text-info">(Also known as CVC2, CVV2 and CID number.)</span>
                                </div>
                                <div class="modal-body">
                                    <p>This is the three(or four) digit code printed on the back panel of your credit card.</p>
                                    <p>The code is a security feature - it adds an extra level of protection to your credit card transaction.</p>
                                    <p>This number is not stored electronically anywhere on your credit card - and payment gateways are not allowed to store this number.</p>
                                    <p>PayGate passes this number directly to the bank together with your credit card details and details of the transaction.The bank checks to make sure that the CVV number is valid for this credit card number.If its not - then the transaction is declined.</p>
                                    <p>Fraudsters often generate credit card numbers - or steal lists of 'unprotected' card numbers.If this is the case -then they will not have access to the CVV number, and the transaction(using your stolen card number) will fail when the fraudster attempts to process it through PayGate.</p>
                                    <br>
                                    <div class="text-center">
                                        <span><img src="./images/cvv2_small.jpg" alt="CVV Number on the back of a Credit Card" title="CVV Number on the back of a Credit Card" /></span>
                                        <span style="padding-left: 20px;"><img src="./images/amex_small.gif" alt="CID Number on the front of an AMEX Card" title="CID Number on the front of an AMEX Card" /></span>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div><script type="application/javascript" src="js/jquery.creditCardValidator.js"></script>
<script type="application/javascript">
var acceptedCards = ["visa","mastercard","amex","diners_club_international", "diners_club_carte_blanche","discover"];

$(document).ready(function(){
	$('#ccNumber').validateCreditCard(handleCCValidation);
});
</script> 			<div class="form-group logo initialHide" id="sid1">
                <div class="col-md-12 text-center">
                    <a href="http://www.sidpayment.com/" target="sidwindow" title="SID Instant EFT"><img src="https://assets.paygate.co.za/payweb3/paymethods/sid_logo2.png" alt="SID Instant EFT" title="SID Instant EFT" border="0" width="150" /></a>
                </div>
            </div>
            <input style="display: none" type="text" id="sidCUSTOMER_COUNTRY_NAME" name="sidCUSTOMER_COUNTRY_NAME" minlength="4" maxlength="50" class="form-control Input sid required" value="ZA">
<input style="display: none" type="text" id="sidCUSTOMER_EMAIL" name="sidCUSTOMER_EMAIL" minlength="4" maxlength="50" class="form-control Input sid required" value="">
					<input style="display: none" type="text" id="sidREDIRECT" name="sidREDIRECT" minlength="4" maxlength="50" class="form-control Input sid required" value="false"><div class="form-group initialHide" id="sid2"><label for="sidCUSTOMER_NAME_INPUT" class="control-label Label text-left">First & Last Name</label><div class="text-left has-feedback"><input placeholder="Enter your First & Last name" id="sidCUSTOMER_NAME_INPUT" name="sidCUSTOMER_NAME_INPUT" type="text"  maxLength=50 validators="{&quot;validatorType&quot;:&quot;&quot;,&quot;maxLength&quot;:50,&quot;minLength&quot;:0,&quot;required&quot;:false}" class="form-control Input sid" value="" /><span class="glyphicon form-control-feedback"></span></div></div><div class="form-group initialHide" id="sid3"></div>                </div>
                				<div class="row alert-gdpr-row" style="    width: 75%;
    margin-left: 12.5%;
    margin-right: 12.5%;">
				   <div id="gdprAlert" class="col-md-12 alert alert-info text-center alert-gdpr">
                            <p>
		    By continuing I hereby give permission for DPO Group and any Third Party commissioned by DPO
		    Group to use Personal Information
		    provided for the sole purpose of processing the requested
		    transaction and conducting necessary fraud and risk screening.</p>
                    </div>
                </div>
                <div class="row button-row" style="width: 75%;
                                                       margin-left: 12.5%;
                                                       margin-right: 12.5%;">
                    <div class="col-md-12" style="padding: 0">
                        <div class="pull-right col-xs-6 col-md-6">
                            <i style="display:none; position: absolute;right: 60px;top: 5px;" 
                               id="loader" 
                               class="fa fa-2x fa-spinner fa-spin">
                            </i>
                            <button id="nextBtn" 
                                    type="submit" 
                                    class="Button initialHide btn-block" 
                                    name="paywebPay" 
                                    value="Next">
                                Next
                            </button>
                        </div>
                        <div class="pull-left col-xs-6 col-md-6">
                            <button id="backBtn" 
                                    type="submit" 
                                    class="Button btn-back-link" 
                                    name="payhostPay"
                                    value="Back">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                Back
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
				<div class="row text-center">
                    <div class="col-md-12"  style="margin-top: 24px">
                       <i style="vertical-align: middle" id="lock" class="fa fa-2x fa-lock"></i><span class="hidden-xs" style="vertical-align: middle; font-weight: bold; line-height: 12px"> Powered by</span>&nbsp;<span><a style="border: none; text-decoration:none; color:#000; vertical-align: middle;" href="https://www.paygate.co.za" title="Click here for Secure Credit Card Processing on your website" target="_blank"><br><img style="border: none; padding-right: 5px; text-decoration:none; vertical-align: text-top;" src="images/pglogo_mini.png" height="28px" /></a></span>
                    </div>
                </div>
                <input id="paywebDate" type="hidden" name="paywebDate" value="1686827877" />
                <input id="PAY_REQUEST_ID" type="hidden" name="PAY_REQUEST_ID" value="E9A73FDD-7D7F-DBF6-DD7D-F7DD8918712A" />
                <input id="paywebSource" type="hidden" name="paywebSource" value="2022313063" />
                <input id="paywebSubmit" type="hidden" name="paywebSubmit" />
                <input id="paywebMethod" type="hidden" name="paywebMethod" />
                <input id="CHECKSUM" type="hidden" name="CHECKSUM" value="daaed5d604f0a9d43ad46a46ffa89a8f" />
                <input id="GOODS_DESCRIPTION" type="hidden" name="GOODS_DESCRIPTION" value="" />
            </form>
        </div>
        </div>
        <div class="col-md-3 Right"></div>
    </div>
    <div class="Bottom"></div>
</div>
    <div class="modal bs-example-modal-sm fade" tabindex="-1" role="dialog" id="testAlert" aria-labelledby="Test Account Alert" aria-hidden="true" style="z-index: 1080;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content alert-danger">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="testAlertLabel"><strong>Warning</strong></h4>
                </div>
                <div class="modal-body">
                    Please note that this is a test transaction.                    <br>
                    This alert does not appear when a LIVE PayGate ID is used.                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal bs-example-modal-sm fade" tabindex="-1" role="dialog" id="cancelAlert" aria-labelledby="Cancel Transaction Alert" aria-hidden="true" style="z-index: 1080;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content alert-danger">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="cancelAlertLabel"><strong>Warning</strong></h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to cancel this transaction?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="doCancel();">Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.Button').each(function(){
               $(this).attr('disabled', false);
            });
        })
    </script>
</body>
</html>
 """;

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```  
 SizedBox(
              height: 30.h,
              width: 400,
              child: HtmlWidget(
                kHtml,
                buildAsync: true,
                factoryBuilder: () => _WidgetFactory(
                  webView: true,
                  webViewJs: true,
                ),
                rebuildTriggers: RebuildTriggers([true, true]),
                onErrorBuilder: (context, element, error) => Text('$element error: $error'),
                renderMode: RenderMode.listView,
              ),
            ),
```
</details>

<details>
  <summary>Tesing environment</summary>

```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.10.2 on channel stable at /Users/mtpc-419/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1
```

</details>

## Expected results

 ![Screenshot 2023-06-16 at 4 44 29 PM](https://github.com/daohoangson/flutter_widget_from_html/assets/52994786/d7446732-e812-41f9-97d7-9ba3c7875c0d)

## Actual results
![Screenshot 2023-06-16 at 4 41 51 PM](https://github.com/daohoangson/flutter_widget_from_html/assets/52994786/a4cbbf49-c927-49f4-80a4-c2b6f9a987c4)

**Comment by daohoangson** [comment]
This package doesn't handle external CSS file and JavaScript execution. You will need a full webview for that.

**Comment by govindh163** [comment]
> webview
@daohoangson 
can you please suggest how can I achieve this?
Thanks in Advance!

**Comment by daohoangson** [comment]
I would suggest using this package https://pub.dev/packages/webview_flutter to view the web page.

**Comment by slimpotatoboy** [comment]
> I would suggest using this package https://pub.dev/packages/webview_flutter to view the web page.

But that package doesn't support for flutter_web

**Comment by daohoangson** [comment]
Unfortunately, that's true.
