### ISSUE TITLE
says platform web?

### ISSUE THREAD

**Issue by sgehrman** [daohoangson/flutter_widget_from_html#954]
: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
chewie_player.dart:144
    SystemChrome.setEnabledSystemUIOverlays(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
chewie_player.dart:157
      SystemChrome.setEnabledSystemUIOverlays(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
chewie_player.dart:161
      SystemChrome.setEnabledSystemUIOverlays([]);
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
material_controls.dart:441
- 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../../development/flutter/packages/flutter/lib/src/material/theme_data.dart').
theme_data.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
                  playedColor: Theme.of(context).accentColor,
                                                 ^^^^^^^^^^^

: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
material_controls.dart:442
- 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../../development/flutter/packages/flutter/lib/src/material/theme_data.dart').
theme_data.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
                  handleColor: Theme.of(context).accentColor,
                                                 ^^^^^^^^^^^

Failed to compile application.

**Comment by daohoangson** [comment]
Looks like your app is using an old chewie version, try specifying `chewie: ^1.5.0` in your pubspec if possible.

Alternatively, if you don't plan to use VIDEO tags in your HTML, consider switching to `flutter_widget_from_html_core` instead of using `flutter_widget_from_html`. The core package doesn't include multimedia support and it has less overhead.
