### ISSUE TITLE
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:' error on ios

### ISSUE THREAD

**Issue by nilun132** [daohoangson/flutter_widget_from_html#957]
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the
selector 'setInspectable:'

I saw this error after flutter run but if you remove  dependency and add after run it's ok

**Comment by daohoangson** [comment]
You should be able to fix this by adding `webview_flutter_wkwebview: 3.6.0` into your pubspec. The latest version (3.6.0) requires iOS 16.4. For more information, see https://github.com/flutter/flutter/issues/129587
