### ISSUE TITLE
Border radius is ignored when border is used.

### ISSUE THREAD

**Issue by Manty-K** [daohoangson/flutter_widget_from_html#959]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<div style="display: inline-block; padding: 5px 10px; background-color: #e0e0e0; border-radius: 20px; border: 2px solid #ff0000;">
  <span style="color: #333; font-size: 14px;">Your Text Here</span>
</div>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
const HtmlWidget(html)
```
</details>

<details>
  <summary>Tesitng environment</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-US) • Flutter version 3.10.5 on channel stable at /Users/manthan/Documents/Development/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700 • Engine revision 45f6e00911 • Dart version 3.0.5 • DevTools version 2.23.1
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Users/manthan/Library/Android/sdk
• Platform android-33, build-tools 31.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14E300c
• CocoaPods version 1.12.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.68.0

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-arm64 • macOS 13.4.1 22F82 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
• All expected network resources are available.

• No issues found!
```
</details>

## Expected results

Widget rendered with border and border radius.
![Expected Result](https://i.ibb.co/pwty0jF/Screenshot-2023-07-06-at-12-09-41-PM.png)

## Actual results
Widget rendered with border but _without_ border radius.
![Actual Result](https://i.ibb.co/XLx5yk6/Screenshot-2023-07-06-at-12-15-00-PM.png)

**Comment by daohoangson** [comment]
That's weird. Which version of this package are you using?

**Comment by Manty-K** [comment]
``flutter_widget_from_html: ^0.10.2``

**Comment by Uhtredtb** [comment]
Same issue here

**Comment by daohoangson** [comment]
Yes, I have identified the bug. New version is being released soon.

**Comment by daohoangson** [comment]
`v0.10.3` has been released with the fix for this. Please try upgrading and see whether it works for you.

**Comment by Manty-K** [comment]
Yes, It is working now 👍🏻

**Comment by daohoangson** [comment]
That's great to hear. I'm closing this issue now.

**Comment by hoangphuc1103** [comment]
Hi anh @daohoangson, này có support border-radius cho hình khong anh - https://tppr.me/6EGLZ
`<div style="display: inline-block; padding: 5px 10px; background-color: #e0e0e0; border-radius: 20px; border: 2px solid #ff0000;">
  <span style="color: #333; font-size: 14px;">Your Text Here</span>
  <img src="https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png" alt="Girl in a jacket" style="width: 50px; height: 50px;border-radius: 20px;">
</div>`

**Comment by daohoangson** [comment]
v0.10 hiện không bo góc của ảnh nha bạn @hoangphuc1103. Next major thì đã hỗ trợ (#903), bạn có thể xài v0.13 alpha để thử.

**Comment by hoangphuc1103** [comment]
> v0.10 hiện không bo góc của ảnh nha bạn @hoangphuc1103. Next major thì đã hỗ trợ (#903), bạn có thể xài v0.13 alpha để thử.

Dạ cảm ơn anh
