### ISSUE TITLE
Plugin does not compile for Android with new AGP versions

### ISSUE THREAD

**Issue by bdmendes** [daohoangson/flutter_widget_from_html#968]
## Steps to Reproduce

1. Depend on `flutter_widget_from_html` 0.10.3
2. Setup `Android Gradle Plugin` 7.4.0 in `android/build.gradle`
3. Run an application in debug mode

## Error message

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

**Comment by daohoangson** [comment]
It appears you are using some older version of `chewie`, a dependency of this package. To use the latest version, try `flutter pub upgrade`. If that doesn't work, try adding `chewie: ^1.7.0` in your pubspec.

If your app doesn't plan to use VIDEO tag, switch to `flutter_widget_from_html_core` for better app size.

**Comment by bdmendes** [comment]
That did the trick. Thank you!
