### ISSUE TITLE
Add support for data URI schemes

### ISSUE THREAD

**Issue by jithware** [daohoangson/flutter_widget_from_html#976]
## Use case

Allow data to be displayed using data URI schemes: ```data:content/type;base64```

## Proposal

To embed an [image](https://en.wikipedia.org/wiki/Data_URI_scheme#HTML) of a small red dot, you would use the following html:

```
<img src="data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot" />
```
<img src="data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" />

For more info see https://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by daohoangson** [comment]
It is already supported. Do you have some HTML that doesn't work?

**Comment by jithware** [comment]
For some reason in my app when I use red dot code above in my app it does not render. But when I use the demo flutter [image](https://github.com/daohoangson/flutter_widget_from_html/blob/9bb95c249c6c146d4ea9bc1cf350505d644ff35e/demo_app/lib/screens/img.dart#L74), it does work in my app. I then added the reddot image above to the [demo](https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/lib/screens/img.dart) and it works fine. So looks like this is a user error on my part. I'll have to figure out why the reddot does not work in my app. Thanks!

**Comment by jithware** [comment]
Ok, so figured it out. It's the```alt=``` attribute that causes the issue. Without it, it works fine:

```
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
```

So not sure if you think this is a bug or not, but as long as users don't use ```alt=```, it works fine.

**Comment by daohoangson** [comment]
I'm testing with this HTML

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

And it seemed to be working fine?

<img width="912" alt="Screen Shot 2023-07-29 at 22 58 17" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/45d33278-5394-4531-ba5d-43655e0b8a84">

**Comment by jithware** [comment]
Must just be an issue in my app. Thanks for taking a look at this!
