### ISSUE TITLE
Add support for facebook video embed

### ISSUE THREAD

**Issue by theneshofficial** [daohoangson/flutter_widget_from_html#98]
Currently if we embed facebook video iframe it's keep on opening url_launcher whenever I route to that page.

**Comment by daohoangson** [comment]
That bug has been fixed a while ago. What is your plugin version? Also, can you share the full html?

**Comment by theneshofficial** [comment]
Hi @daohoangson I'm using version 0.2.3+4 which is the latest version. Below is my complete HTML code for your reference. 

<figure id="attachment_1254545" style="width: 800px" class="wp-caption alignnone"><img class="wp-image-1254545 size-full" src="https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1.jpg" alt="" width="800" height="500" srcset="https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1.jpg 800w, https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1-300x188.jpg 300w, https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1-768x480.jpg 768w, https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1-696x435.jpg 696w, https://s3media.freemalaysiatoday.com/wp-content/uploads/2019/10/curi-roti-video-fb-1-672x420.jpg 672w" sizes="(max-width: 800px) 100vw, 800px" /><figcaption class="wp-caption-text">The boy punching the bread vendor who chased after him.</figcaption></figure> <p>PETALING JAYA: A video of a teen punching a bread seller after being caught red-handed trying to steal several pieces of bread has riled many social media users.</p> <p>In the 54-second clip, which has been viewed nearly 520,000 times on Facebook, a teenage boy in a red T-shirt is seen casually walking away with several pieces of bread.</p> <p>The bread vendor notices this and chases after him and tries to take back the bread, but the teen is reluctant to give them back.</p> <p><iframe style="border: none; overflow: hidden;" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fkader.ibrahimz%2Fvideos%2F1411177839056948%2F&amp;show_text=0" width="560" height="308" frameborder="0" scrolling="no" allowfullscreen="allowfullscreen"><span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span></iframe></p> <p>Eventually, the boy lets go of the bread but punches the bread seller in the stomach, causing the man to stumble backwards in pain.</p> <p>The boy then walks towards a motorcycle that&#8217;s waiting for him and flees, as other customers look on.</p> <p>The post has drawn more than 4,000 angry reactions, with some hurling profanities at the boy.</p> <p>One social media user, Esther Ong, questioned why no one helped the man, while Nadiatul Erma Kassim called on the police to arrest the teenager.</p>

Thank you.

**Comment by daohoangson** [comment]
Hmm, 

I have created a new app with this `main.dart`: https://gist.github.com/daohoangson/2bcb9bd5a4ee8d8ba6974a806e274cd9, it runs fine on iOS simulator.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-20 at 21 54 32](https://user-images.githubusercontent.com/239336/67161393-3b70ed80-f384-11e9-9deb-a2f48d2bd105.png)

Are you testing with Simulator/emulator or real device? Also, what is your Flutter version? Output of `flutter doctor -v` would be useful.

**Comment by theneshofficial** [comment]
@theneshofficial my bad I was using older version of this plugin. Once upgrade all looks good.
