### ISSUE TITLE
When quitting audio in the DemoApp after playing an audio widget goes to error

### ISSUE THREAD

**Issue by securexperts** [daohoangson/flutter_widget_from_html#981]
## Steps to Reproduce

In the Audio Tab when I play an audio and like to gob back to the mein menu. It shows me the Following error: 

Failed assertion: line 5518 pos 14 "_dependents.isEmpty" is not true

## Expected results

No Error Shown in Widget

## Actual results

Error as described above

## Roman

**Comment by securexperts** [comment]
Hello, 

I download the whole package and compiled the following DemoApp for iOS
https://github.com/daohoangson/flutter_widget_from_html/tree/master/demo_app

Roman

**Comment by daohoangson** [comment]
This seems to be closely related to #980.
