### ISSUE TITLE
Support textScale directly and/or document solid workaround

### ISSUE THREAD

**Issue by neiljaywarner** [daohoangson/flutter_widget_from_html#984]
## Use case

Working on 507/ally/wcag etc.
User has increased display size https://support.google.com/accessibility/android/answer/11183305?hl=en

## Proposal
For example if MediaQuery.of(context).textScaleFactor = 1.5, then increase all/most items by 1.5
Ideally with a calculation/autosize, and/or a maxFont so that things don't get cutofff.
similar to https://github.com/daohoangson/flutter_widget_from_html/blob/master/demo_app/lib/screens/font_size.dart
except a little more automagically tied to the OS display settings.
also see

and perhaps taking into accoutnt
` boolean addBodyStart = !html.toLowerCase().contains("<body>");
    boolean addBodyEnd = !html.toLowerCase().contains("</body");
// if addBodyStart then start Wrapper with body, else don't
// if addBodyENd then end Wrapper with body, else don't`

(your example shows wrapping in span, is it "better" to make the entire body increase by 1.5 em etc?  not a web dev so not sure.
and then h1 would be too large, so it could have max height...

Maybe this could be in stages ;)

**Comment by daohoangson** [comment]
This package already takes into account text scale factor when it calculates font size. Did something appear incorrectly in your app or something?

**Comment by neiljaywarner** [comment]
With no change the font appeared very small relative to others

Your font scale example requires wrapping in span which is okay but of
course what about H1 etc

....sent from my phone

**Comment by daohoangson** [comment]
It should not require SPAN tag. What is your HTML?

**Comment by daohoangson** [comment]
If you want to specify a `font-size` you you need to wrap it in some tag. Otherwise the text will inherit the default size. Both the default size and specific size should be multiplied with the text scale factor. If it doesn't do that in your app then it's a bug. Some sample HTML + Dart code will be helpful to troubleshoot and fix.

**Comment by neiljaywarner** [comment]
my apologies, this appears to be correct thank you so much.

Is it ok if we modify this ticket to account for H1 somehow, with a maxfontSize like autotext? Of courese, that might not be easy...

**Comment by neiljaywarner** [comment]
![image](https://github.com/daohoangson/flutter_widget_from_html/assets/3019617/47360658-aafa-4c44-893b-c76273afea21)
  AutoSizeText(
                  displayString,
                  maxLines: 1,
                  style: Theme.of(context).textTheme.displayLarge,
                ),
                HtmlWidget(displayString),
                HtmlWidget('<h1>$displayString<h1>'),

**Comment by daohoangson** [comment]
You should be able to customize the factory to replace `RichText` with any other widget you want. It's best to open another issue for it though.

**Comment by neiljaywarner** [comment]
Thank you sorry about that

**Comment by daohoangson** [comment]
Since the original issue has been resolved. I'm closing this now.
