### ISSUE TITLE
Data from HTML Rendered , But Selectable Text Widget not working as expected ...  

### ISSUE THREAD

**Issue by Debdaru07** [daohoangson/flutter_widget_from_html#985]
I was using this Package to render data which comes as a string format into CustomStylesBuilder ... 
using the customWidgetBuilder , it is not allowing us to select the Data which is formatted and styled properly ... 
So it is not serving my purpose ,.,,, please look into it ...

Package used : flutter_widget_from_html_core

If there is any alternate packages that allows us to use SelectableText and customStyles Builder at the same time , please suggest ....

**Comment by daohoangson** [comment]
Which data do you want to select? Some sample HTML and Dart code would be helpful here.
