### ISSUE TITLE
i have a problem with flutter_widget_from_html 

### ISSUE THREAD

**Issue by axroromonov** [daohoangson/flutter_widget_from_html#987]
This problem has been happening lately, who or what is the problem? how to fix it ?

<img width="1702" alt="Screenshot 2023-08-08 at 09 49 18" src="https://github.com/daohoangson/flutter_widget_from_html/assets/76530966/e36020eb-5ced-478a-858a-3b811fa11948">

**Comment by daohoangson** [comment]
Looks like you have upgraded Flutter version but didn't upgrade packages. Try running this command `flutter pub upgrade fwfh_text_style` maybe?

**Comment by axroromonov** [comment]
Neither I nor pub dev have such a package

**Comment by daohoangson** [comment]
It is a valid pub.dev package, available at https://pub.dev/packages/fwfh_text_style

Have you tried running the pub upgrade command? What is the output?

**Comment by axroromonov** [comment]
yes , I did but the error doesn't change 
<img width="1640" alt="Screenshot 2023-08-10 at 16 08 38" src="https://github.com/daohoangson/flutter_widget_from_html/assets/76530966/b7553d4f-36b4-4c66-976e-8fe80d7ace42">

**Comment by daohoangson** [comment]
What is your Flutter version?

**Comment by jamesDockal** [comment]
I'm getting same problem 

environment:
  sdk: ">=2.16.1 <3.7.1"

**Comment by axroromonov** [comment]
> What is your Flutter version?

I solved it with another package, I have the latest version of flutter, I think it doesn't work with the latest version

**Comment by axroromonov** [comment]
> I'm getting same problem
> 
> environment: sdk: ">=2.16.1 <3.7.1"

I solved it with another package

**Comment by jamesDockal** [comment]
what package did you use? @axroromonov

**Comment by daohoangson** [comment]
That's weird, I'm glad you have got something else working though. I'm closing this issue for now.

**Comment by axroromonov** [comment]
> what package did you use? @axroromonov

https://pub.dev/packages/flutter_super_html_viewer but the above package is much better, I will use it again after a while

**Comment by axroromonov** [comment]
> That's weird, I'm glad you have got something else working though. I'm closing this issue for now.

try this if you also have the latest version of flutter , thanks bro

**Comment by axroromonov** [comment]
> > That's weird, I'm glad you have got something else working though. I'm closing this issue for now.
> 
> try this if you also have the latest version of flutter , thanks bro

Do you own both flutter_widget_from_html and flutter_widget_from_html_core ? both are great

**Comment by jamesDockal** [comment]
> > That's weird, I'm glad you have got something else working though. I'm closing this issue for now.
> 
> try this if you also have the latest version of flutter , thanks bro

Thanks, this library works too,
but I'm getting a weird behaviour on that, if you know a solution for that will help me a lot,
I can not put something over it, like a modal, even though its in front of the component I can't hover over it to click a button in the modal
