### ISSUE TITLE
引用后编译报错Error: Method not found: 'MouseRegion'.

### ISSUE THREAD

**Issue by 952055647** [daohoangson/flutter_widget_from_html#99]
Compiler message:
file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/cupertino_controls.dart:68:12: Error: Method not found: 'MouseRegion'.
    return MouseRegion(
           ^^^^^^^^^^^
file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/cupertino_controls.dart:68:12: Error: The method 'MouseRegion' isn't defined for the class '_CupertinoControlsState'.
 - '_CupertinoControlsState' is from 'package:chewie/src/cupertino_controls.dart' ('file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/cupertino_controls.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MouseRegion'.
    return MouseRegion(
           ^^^^^^^^^^^
file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/material_controls.dart:52:12: Error: Method not found: 'MouseRegion'.
    return MouseRegion(
           ^^^^^^^^^^^
file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/material_controls.dart:52:12: Error: The method 'MouseRegion' isn't defined for the class '_MaterialControlsState'.
 - '_MaterialControlsState' is from 'package:chewie/src/material_controls.dart' ('file:///sdk-ndk-ant/flutter/.pub-cache/hosted/pub.flutter-io.cn/chewie-0.9.8/lib/src/material_controls.dart').

**Comment by daohoangson** [comment]
What is your `flutter doctor -v` output? Also, can you share the html which is causing error?

**Comment by 952055647** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G8030, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[!] Android Studio (version 2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.39.0)
[✓] Connected device (1 available)


html用的是例子中的

**Comment by daohoangson** [comment]
`v1.7.8` is pretty old. I'm not sure `chewie` (one of this plugin dependencies) is compatible with it. Can you upgrade Flutter to latest stable (`v1.9.1`)?

**Comment by daohoangson** [comment]
See https://github.com/brianegan/chewie/issues/200
