### ISSUE TITLE
Question; image with surrounded a-tag

### ISSUE THREAD

**Issue by gerritwitkamp** [daohoangson/flutter_widget_from_html#993]
Hi all,

I want to following behaviour, don't know how to achieve.

`<img src="..." />`
On tap: open the image in full-screen.

`<a href="..."><img src="..." /></a>`
On tap; open the url

In both cases the onTapImage is fired, but in this method I cannot access the parent-node to see if the image is wrapped with an a-tag.

I did some try outs with WidgetFactory, without success. Furthermore is it possible to retrieve the context in buildImage, so I can pull the Navigator widget?

```
class _WidgetFactory extends WidgetFactory {
  @override
  Widget? buildImage(BuildMetadata meta, ImageMetadata data) {
    final widget = super.buildImage(meta, data);

    if (meta.element.parent?.localName != 'a') {
      return widget;
    }
        
    // Special case, it's surrounded with an a-tag!
    return widget;        
  }
}
```
Thanks

**Comment by gerritwitkamp** [comment]
I managed by extending the WidgetFactory but don't know if it's the right way:

`class _WidgetFactory extends WidgetFactory {
  Widget? Function(BuildMetadata meta, ImageMetadata data, Widget? widget) imageBuilder;

  _WidgetFactory({required this.imageBuilder});

  @override
  Widget? buildImage(BuildMetadata meta, ImageMetadata data) {
    final widget = super.buildImage(meta, data);
    return imageBuilder(meta, data, widget);      
  } 
}`


`  @override
  Widget build(BuildContext context) {
    return HtmlWidget(
      html,
      factoryBuilder: () => _WidgetFactory(imageBuilder: (BuildMetadata meta, ImageMetadata data, Widget? widget) {
        if (widget is! Widget) {
          return null;
        } else if (meta.element.parent?.localName != 'a') {
          return GestureDetector(child: widget, onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (context) => Foo(image: widget))));
        } else {
          return widget;
        }
      }),`

**Comment by daohoangson** [comment]
Your solution looks great! If you just need the `BuildContext`, it's probably easier to use a `Builder` inside `buildImage` instead of passing the callback `imageBuilder` around. Something like this:

```dart
  @override
  Widget? buildImage(BuildMetadata meta, ImageMetadata data) {
    Widget? built = super.buildImage(meta, data);

    if (meta.element.parent?.localName != 'a' && built != null) {
      final image = built;
      built = Builder(
        builder: (context) {
          return GestureDetector(
            child: image,
            onTap: () => Navigator.of(context).push(
              MaterialPageRoute(builder: (_) => Foo(image: image)),
            ),
        },
      );
    }

    return built;
  } 
```

**Comment by gerritwitkamp** [comment]
awesome thnx!
